lib/db.js

Right now index error string gives unhelpful "MongoError: n/a". With this change you get a more helpful error message.

Handle index creation failure in a manner consistent with inserts

---

lib/server.js
test/functional/connection_tests.js

Standalone wasn't properly removing listeners when connection timed out - was causing one of the failures in mongoose's driver upgrade branch.

Properly remove listeners on timeout

---

lib/collection.js

Right now `{ w: 0 }` doesn't work when you specify it in arguments to insert, for instance `coll.insert({ x: 1 }, { w: 0}, callback)` because 0 is falsy. Thanks to some language quirks, however, `0 != null`, so if you use the same check you use in L1994 this works as expected.
Also, for posterity's sake, much to my surprise, using `==` is actually the [right choice here](http://www.ecma-international.org/ecma-262/5.1/#sec-11.9.3). My knee-jerk reaction was "fix to use `===`" but the ECMAScript spec clarifies that this gives the correct behavior, `x == null` iff x is null or undefined.

Enable setting w:0 in .insert()

---

lib/mongo_client.js

Right now you can't set `connectTimeoutMS` in URI passed to MongoClient.connect(). For instance, [this connect-mongodb-session](https://github.com/vkarpov15/connect-mongodb-session/blob/master/test/examples.test.js#L153-162) test currently fails, because I'd expect connecting to `mongodb://bad.host:27000/connect_mongodb_session_test?connectTimeoutMS=10` to time out after 10ms rather than 30s.
With this patch, that test succeeds against 2.4, 2.6, and 2.8.

Enable setting connectTimeoutMS and socketTimeoutMS in URI

---

lib/mongodb/connection/connection.js

The previous logic would always evaluate as true since process.platform will always be either not `sunos` or `win32`.

Fix check of process.platfom for default socketOptions.keepAlive

---

lib/collection.js

Not sure if the correct behavior is to throw an exception if no selector is specified (I seem to remember this being part of some spec that was floating around in early 2.6, but this behavior isn't really specified in the CRUD spec atm) or to accept it. Unfortunately, the current behavior is to silently accept it but never call the callback, which is definitely not right.

Fix LearnBoost/mongoose#2627: don't hang callback when no selector specified

---

lib/mongodb/db.js

See LearnBoost/mongoose#2619. Basically if you reuse `.authenticate()`, your options object gets authMechanism set to "DEFAULT" and subsequent authenticate() calls with the same options incorrectly throw an error.

Make shallow clone of options to auth() before modifying

---

lib/mongodb/connection/server.js

Re: some of the work for https://jira.mongodb.org/browse/NODE-244 and LearnBoost/mongoose#2229. Right now the close event only gets bubbled up to the server instance, rather than the actual connection. IMO makes sense to emit on the connection if its a standalone.

LearnBoost/mongoose#2229: emit close on parseError on db for single servers

---

lib/mongodb/connection/connection_pool.js
test/functional/db_tests.js

Hi Christian,
Re: LearnBoost/mongoose#2682, looks like when you specify a non-numeric pool size the driver will hang forever because of the [=== check here](https://github.com/mongodb/node-mongodb-native/blob/0b9644bc89fe988c5cde04801dbac34d5b1ef9ec/lib/mongodb/connection/connection_pool.js#L117). I think we can improve how we handle that case.

Gracefully handle non-numeric pool sizes

---

lib/mongodb/cursor.js
lib/mongodb/utils.js
test/functional/cursor_tests.js

When query commands (specifically, nextObject) return an error as a
result document of the form {$err: "message", code: 1234}, we should
allow the application to see the code (and any other fields on the
error).  This is consistent with what we do if the error is returned in
the "errmsg" field on the next line.
Note: `node test/runner.js -t functional -f cursor` passes with the change (and fails with my test change only) but `node test/runner.js -t functional` fails for me on current master:
```
/Users/glasser/Projects/Meteor/node-mongodb-native/lib/mongodb/connection/base.js:246
throw message;      
^
AssertionError: {} == null
at equal (/Users/glasser/Projects/Meteor/node-mongodb-native/node_modules/integra/lib/schedulers/test_runner.js:62:14)
at …
```

Keep numeric error code in query errors

---

lib/cursor.js
test/functional/cursor_tests.js

Fixes bug in `cursor.count()` that causes the result to always be zero when called against a collection with a dot ('.') in the collection name (e.g. "fs.files").
This bug occurs in v2.0.x (I haven't investigated v3.0, it may happen there as well...)
This fixes the bug I reported here:  https://jira.mongodb.org/browse/NODE-379

[NODE-379][2.0] Fixes bug in cursor.count() that causes the result to always be zero for dotted collection names.

---

lib/bulk/common.js
lib/bulk/unordered.js

There were few issues with in the unordered bulk operation implementation in addToOperationsList: 1) currentBatchSize is updated twice in the function so the batch size will be half of maxWriteBatchSize. 2) currentBatchSize and currentBatchSizeBytes are not reset when switching batches for batch types. As a result it's incorrectly creating a new batch because it thinks it's reached maxWriteBatchSize when it has not. This can result in an empty batch and an "insert must contain at least one document" error. 3) There is some redundant code in the addToOperation function.
This pull request fixes the above issues.

NODE-376 Fixes issue - Unordered batch incorrectly tracks batch size when switching batch types

---

index.js

This is useful when promisifying the API and trying to catch operational errors like:
```js
var Promise = require('bluebird');
var mongodb = Promise.promisifyAll(require('mongodb'));
var db = mongodb.connectAsync(mongoUri)
.catch(mongodb.MongoError, function( e ){
throw new Error('Unable to connect to database: "' + mongoUri + '"');
});
```

Expose MongoError from mongodb-core

---

lib/db.js
test/functional/connection_tests.js

Currently won't re-emit 'reconnect' event on db after one reconnect because of `.once()`, see LearnBoost/mongoose#2656.
FWIW I think we should change the entire L163-L169 block to use `on()` instead of `once()` as well as 'reconnect'. Functional tests succeed with both on() and once() on my mint box

Don't only emit reconnect event on db once

---

lib/gridfs/grid_store.js
test/functional/gridfs_tests.js

fixes stream.pipe compatibility for writable GridStoreStream objects

NODE-426 handle writes to GridStoreStream instances properly

---

lib/mongodb/connection/repl_set/repl_set.js

The mongo connect response does not include passive hosts in the hosts array.  Instead, these hosts are included in the passives array.  The (BSON) response might look like:
```
{ setName: 'rs0',
setVersion: 31,
ismaster: true,
secondary: false,
hosts: 
[ '10.72.100.80:8000',
'10.72.229.66:8000',
'10.72.102.196:8000',
'10.72.101.200:8000' ],
passives: [ '10.72.230.249:8000' ],
primary: '10.72.100.80:8000',
tags: { dc: 'west' },
me: '10.72.100.80:8000',
maxBsonObjectSize: 16777216,
maxMessageSizeBytes: 48000000,
maxWriteBatchSize: 1000,
localTime: Wed Jun 24 2015 19:19:42 GMT+0000 (UTC),
maxWireVersion: 2,
minWireVersion: 0,
ok: 1 }
```
We want to be able to read from these passive hosts.
I have manually verified all existing unit tests pass.
I am looking into adding a unit test …

Fix mongo driver to use passive nodes

---

lib/bulk/ordered.js
lib/bulk/unordered.js
test/functional/bulk_tests.js

Previously writeErrors returned by ordered and unordered bulk operations were mongodb WriteErrors, this runs them through the toError pathway that way it plays nicer in user land where a lot of code depends on err instanceof Error.
JIRA: https://jira.mongodb.org/browse/NODE-506

Ensures that errors from bulk unordered and ordered are instanceof Error

---

lib/collection.js

I noticed when calling the `find(selector, fields)` method on a collection with fields set to `undefined`, I get a `TypeError: Object.keys called on non-object`. When checking out the problem, I found that the `collection.js` module checks if `argument.length >= 2` which evaluates to `true` even if `argument[1]` is not explicitly set. I.e. the code is trying to use the `fields` argument as if it's set, throwing the error eventually.
Fixed it by comparing `fields !== undefined` instead of using the argument count.
In our application, we basically do something like this:
```js
// fields is optional
function getRecords(arg1, arg2, fields) {
// validate arg1, arg2 etc...
// build the query with arg1, arg2
var query = {};
return collection.find(query, fields);
}
```
I changed `fields` to …

Ignore undefined fields in Collection.find()

---

lib/gridfs/grid_store.js

JIRA issue [NODE-557](https://jira.mongodb.org/browse/NODE-557)

GridStore doesn't share readPreference setting from connection string

---

lib/mongo_client.js

If the library is not properly passed, the underlying function attempts to use es-6 promises instead.
As I am not using that particular package, it crashes my app.

Pass promise library through to DB function

---

lib/cursor.js

Fix problem: run hasNext more than once will make cursor point move and miss document.
I don't find a way to report an issue. And this is a simple change. I hope you will take it.

add currentDoc condition in hasNext function

---

lib/cursor.js

Right now, if the result is a single document with error, the application callback is called directly. This means that if the application code throws an exception, it gets propagated to the driver code causing unexpected behavior (server topology being destroyed in my case).
Using `handleCallback` ensures that in this scenario, the exception does not get propagated to the driver code.

Use handleCallback if result is an error for count queries

---

lib/gridfs-stream/download.js
lib/gridfs-stream/index.js
test/functional/gridfs_stream_tests.js

As specified in https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst#id24. Includes:
* `openDownloadStreamByName()`
* start/end options (partial file retrieval) for `openDownloadStream()` and `openDownloadStreamByName()`
* `rename()`
* `drop()`
Also https://github.com/mongodb/node-mongodb-native/commit/fa10f88888e168e31975911bc51da6d931cae042 addresses a minor clarification added in between the original implementation.
This should put us in full conformance with the streaming gridfs spec's basic and advanced API sections.

Advanced part of GridFS spec

---

lib/mongo_client.js

MongoClient didn't use the domain_socket property for MongoS connections, so this couldn't connect through Unix Sockets.
Maybe this is because MongoS expects a port. I have included a dummy 27017 port in the new Server invocation for the domain_socket version.

MongoClient support for MongoS through Unix Socket

---

lib/gridfs/grid_store.js

Make an unique index files_id_1_n_1 on chunk collection for compatiblity with [mongo-cxx-driver:legacy](https://github.com/mongodb/mongo-cxx-driver/blob/legacy/src%2Fmongo%2Fclient%2Fgridfs.cpp)
fragment of mongo/client/gridfs.cpp:65
```cpp
GridFS::GridFS(DBClientBase& client, const string& dbName, const string& prefix)
: _client(client), _dbName(dbName), _prefix(prefix) {
_filesNS = dbName + "." + prefix + ".files";
_chunksNS = dbName + "." + prefix + ".chunks";
_chunkSize = DEFAULT_CHUNK_SIZE;
client.createIndex(_filesNS, BSON("filename" << 1));
client.createIndex(_chunksNS, IndexSpec().addKeys(BSON("files_id" << 1 << "n" << 1)).unique());
}
```
during the execution of the last line throw an exception "Index with name: files_id_1_n_1 already exists with different options"

Make an unique index files_id_1_n_1 on chunk collection

---

lib/url_parser.js

`read_preference` is not a valid dbOption, but `readPreference` is: http://mongodb.github.io/node-mongodb-native/2.0/api/Db.html, https://github.com/mongodb/node-mongodb-native/blob/2.0/lib/db.js

fix(url_parser): readPreference option

---

test/functional/operation_example_tests.js

ObjectID.createFromHexString already creates a new ObjectID.

Remove superfluous new.

---

docs/reference/content/reference/connecting/connection-settings.md

The description of the `ssl` option in Individual Server Level Options was a copy of the description of `poolSize`. Changed to the description found on the api reference in the class Server.

Wrong ssl option description

---

test/functional/operation_example_tests.js

Hey Christian,
The EdX course still uses an older version of the driver (and still will because otherwise we're gonna have to re-record) that doesn't support the `[['a', 1]]` syntax for sorting, so students are getting confused when we link to the docs. Can the examples highlight both syntaxes and explain why you might want to use the array syntax?
Thanks,
Val

docs; still show .sort({a: 1}) syntax in docs

---

README.md

Hi Christian,
The current description uses "MongoDB driver" to refer to 2 distinct concepts, which is a little confusing. IMO this does a better job of conveying the purpose of the driver.

fix awkward description in README.md

---

lib/url_parser.js
test/functional/connection-string/invalid-uris.json
test/functional/connection-string/invalid-uris.yml

Throw an error if more than database name provided with backslash separating
them, also throw an error if a trailing backslash found after the database
name.
link to ticket: https://jira.mongodb.org/browse/NODE-636

NODE-636: Multiple database names ignored without a warning

---

lib/db.js

Couple small tweaks to the docs in db.js: improved the `createCollection()` description, and made the one for `dropDatabase()` more in line with the one for `dropCollection()`.

Improve some unclear descriptions in the docs

---

lib/gridfs-stream/upload.js

Using the second script from JIRA. After fix:
```
---> { rss: 188477440, heapTotal: 46725152, heapUsed: 11759800 }
Completed 10000
```
Before:
```
---> { rss: 2214129664, heapTotal: 109673248, heapUsed: 65545536 }
Completed 10000
```
The issue is that, because I missed the return statement, every new GridFSBucketWriteStream registers a listener for the GridFSBucket's 'index' event, and so the GridFSBucketWriteStream never gets GC-ed until the whole GridFSBucket is.

NODE-643 fix memory leak in GridFSBucketWriteStream

---

lib/cursor.js
test/functional/cursorstream_tests.js

When using standard source.pipe(dest) source will not be destroyed if dest emits close or an error. You are also not able to provide a callback to tell when then pipe has finished.
[https://www.npmjs.com/package/pump](pump) does these two things for you, so you don't need to listen all the error events from all streams
So for handling all the errors correctly with pump it make sense to emit error first before closing stream. Example of code can be found here: https://github.com/mafintosh/pump/pull/2
Also, should it be PR to the 2.2 or 2.1?

Emit error before closing stream

---

lib/gridfs-stream/download.js
lib/gridfs-stream/upload.js
test/functional/gridfs_stream_tests.js

Re: https://jira.mongodb.org/browse/NODE-655 .
* `GridFSBucketUploadStream` now has an `abort()` method as described in [the GridFS stream spec](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst#file-upload)
* `GridFSBucketDownloadStream` now has a `destroy()` method that is analogous to [node fs read stream's implementation](https://github.com/nodejs/node/blob/1124de2d76ad7118267d91a08485aa928a5f0865/lib/fs.js#L1849-L1854)

GridFS stream support for cancelling upload streams and download streams

---

lib/gridfs-stream/index.js

GridFS always returns the oldest version due to incorrect field name in lib/gridfs-stream/index.js
uploadedDate -> uploadDate

Fix: GridFS always returns the oldest version due to incorrect field name

---

lib/db.js
test/functional/index_tests.js

Re: Automattic/mongoose#3864, if you try to use an invalid partial index filter, the `createIndex()` function falls back to trying to create the index using an insert, which then gives you a BSON serialization error because of query operators in the partial index filter: `Error: key $exists must not start with '$'`.
I added a test case to repro this error condition in a separate commit below, as well as a possible solution: if the mongodb server gives you an invalid partial index filter error, don't fall back to using insert. I'm not thrilled about this solution, you may be able to think of a better one, so I put it as a separate commit to make it easier.

Confusing error with invalid partial index filter

---

lib/url_parser.js

Fixes test for a double-colon in line 44 of url_parser.js from one colon to two colons :-)

fixed typo in double-colon test

---

lib/collection.js

When an error is thrown from `OrderedBulkOperation#raw` or `UnorderedBulkOperation#raw` (such as the document greater than maximum size error), it was not caught properly, and therefore not propagated correctly through callbacks.
Test case:
```js
var MongoClient = require('mongodb').MongoClient;
// Connection URL
var url = 'mongodb://localhost/test';
// Use connect method to connect to the Server
MongoClient.connect(url, function(err, db) {
console.log("Connected correctly to server");
var col = db.collection('testcol');
col.insert({
blob: new Buffer(20 * 1024 * 1024)
}, function (err) {
console.log('callback');
console.log(err);
db.close();
});
});
```
Before:
```
$ node test
Connected correctly to server
node_modules/mongodb/lib/mongo_client.js:465
throw err
^
MongoError: document is …
```

Added error catching in bulkWrite function for bulk.raw

---

lib/gridfs-stream/download.js

This addition makes it much easier to handle file not found errors the users applications.

gridfs: add code attribute to file not found error

---

lib/collection.js

Currently when you set `verbose:true` you wont get the stats of the mapReduce operation unless you specify inline results - this is when using Promises. In callback mode stats are returned regardless of the output settings.
cc: @christkv

Fixing issue that prevented mapReduce stats from being resolved

---

lib/db.js

If the `authMechanism` is omitted, it will be populated with `DEFAULT`. However, if the user has explicitly set `authMechanism` to `DEFAULT`, an error will be thrown because the code does not include `DEFAULT` in its sanity check of the `authMechanism` field. This is [contrary to the documented behaviour](https://mongodb.github.io/node-mongodb-native/2.1/reference/connecting/authenticating/).

fix DEFAULT authMechanism; don't throw error if explicitly set by user

---

docs/reference/content/reference/ecmascript6/connecting.md

I noticed the "exiting" typo when reading the docs and thought I'd make a quick PR.

Fixes small typos in docs

---

lib/server.js

Last time, we forgot to forward the unref request to the mongodb-core server class.

Forward unref to mongodb-core server class

---

package.json

This doesn't look legacy to me.

replaced 'legacy' package keyword with 'official'

---

2.1/api/ObjectID.html

Hi,
I've noticed what appears to be a small mistake in the documentation for `ObjectID.isValid()`.
The method is a static, but the documentation omits (unlike the other statics before) to specify that an `ObjectId` should be passed as a parameter.
PS: I did not find any guidelines on how to contribute to the documentation, so I hope this is the right way.

Improve documentation for ObjectID.isValid()

---

lib/collection.js
lib/db.js
lib/utils.js

Same fix as in mongodb-core.  The Db.dropCollection(), Db.dropDatabase(), and Collection.rename() were using Object.assign() directly.

polyfill for Object.assign()

---

lib/collection.js
lib/db.js

The `Collection.findAndModify` and `Collection.findOneAnd*` methods take an optional `maxTimeMS` parameter, but do not actually apply it when present. Fix by adding `options.maxTimeMS` to the command object in `findAndModify`, which all the `findOneAnd*` methods resolve to. Also apply the specified `maxTimeMS` in `Collection.count` and `Collection.distinct`, which previously ignored it.

Enable maxTimeMS in count, distinct, findAndModify

---

lib/read_preference.js

This should be the last fix necessary for mongoose to work with 2.2.x (https://github.com/Automattic/mongoose/pull/4363), all tests pass with 2.2.5 and this patch.
General problem is that `typeof [] === 'object'` and the `tags` param is an array, so the read preference constructor thinks that tags are never passed.

fix: allow passing in an array of tags to ReadPreference constructor

---

lib/collection.js

Hi Christian,
Still having some test failures on mongoose with 2.2.x, [this strange mapReduce issue showed up on node 0.10 and 0.12](https://travis-ci.org/Automattic/mongoose/jobs/155174111) . Not sure the exact reason why this started happening, but one fix for this issue would be to make it so that the `processScope` function treats ObjectIds as standalone values rather than cloning them into POJOs (which seems like the right behavior anyway).

Don't treat ObjectId as object for mapReduce scope

---

lib/db.js

Hi Christian,
Automattic/mongoose#4459 pointed out another potential condition where `createIndex` incorrectly falls back to using inserts. This PR fixes that particular problem, but I think it might be better to explicitly check for the server returning a 'bad cmd' key (1) or error code 61 (2) rather than falling back to insert by default, because this is the second time we've had this bug.
(1)
```
{ MongoError: no such cmd: createIndexes
at Function.MongoError.create (/home/val/Workspace/10gen/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
at commandCallback (/home/val/Workspace/10gen/mongoose/node_modules/mongodb-core/lib/topologies/server.js:1187:66)
at Callbacks.emit (/home/val/Workspace/10gen/mongoose/node_modules/mongodb-core/lib/topologies/server.js:119:3)
at …
```

Don't fall back to insert if 'IndexOptionsConflict' error

---

docs/reference/content/tutorials/create-indexes.md

Ascending Index is created for the `dateOfBirth` field in the source example, not the `quantity` field as the explanation text says.
Fixes #NODE-814

Fix the explanation text.

---

lib/mongos.js
lib/replset.js
lib/server.js

Fix a typo in the name of the serverHeartbeatFailed event. This should only be merged after https://github.com/christkv/mongodb-core/pull/143 is released.

fix typo in serverHeartbeatFailed event name

---

docs/gridfs.md

There is no db.GridStore.unlink. Its a call on a GridStore instance like all the rest.

correcting unlink

---

lib/cursor.js

The `Cursor.prototype.map` function is annotated with a `null` return type, while it actually returns a `Cursor` instance (or, more precisely, `this`).

Fix Cursor.prototype.map return annotation

---

lib/collection.js

The documentation even states "doc" to be the parameter name. I think this happened due to copy & paste from the updateOne function.

Changed misleading parameter name

---

lib/db.js

It seems like this property has been eliminated in 3.0 but it is definitely documented in 2.2:
http://mongodb.github.io/node-mongodb-native/2.2/api/Db.html
and is used in `logout`(): https://github.com/mongodb/node-mongodb-native/blob/2.2/lib/db.js#L1579
furthermore, an `authSource` as an option to `authenticate()` is **NOT** documented:
http://mongodb.github.io/node-mongodb-native/2.2/api/Db.html#authenticate

Don't ignore Db-level authSource on log-in

---

lib/bulk/unordered.js

The `UnorderedBulkOperation.length` property annotation was missing. This pr adds it

Added UnorderedBulkOperation.length property annotation

---

docs/reference/content/reference/ecmascript6/index.md

This is a simple fix, changing "ECMASdcript" to "ECMAScript"

Fix documentation typo

---

test/benchmarks/parallel_ldjson_export_child.js
test/functional/collection_tests.js
test/functional/cursorstream_tests.js
test/functional/find_tests.js
test/functional/gridfs_tests.js
test/functional/mapreduce_tests.js
test/functional/operation_example_tests.js
test/functional/operation_generators_example_tests.js
test/functional/operation_promises_example_tests.js
test/functional/readconcern_tests.js
test/functional/readpreference_tests.js

Was reading through the docs and found some inconsistencies in the spelling of 'Perform'.

Corrects spelling in unit tests and examples

---

lib/mongos.js
lib/replset.js

Fixes [NODE-728](https://jira.mongodb.org/browse/NODE-728) (`this.s.topology.unref is not a function` when calling `db.unref()`)

Add missing unref implementations for replset, mongos

---

test/functional/url_parser_tests.js

`uri_decode_auth` was removed in this commit https://github.com/mongodb/node-mongodb-native/commit/044063097dc4dd5e6cf3a3574c555fec7559d38b

remove obsolete option uri_decode_auth

---

lib/collection.js
test/functional/aggregation_tests.js

fix(collection): pass batchSize to AggregationCursor

---

lib/utils.js

Re: tmpvar/jsdom#1752, Automattic/mongoose#5033
The origin of this issue was that using Facebook's "jest" testing library bugs out with mongoose indexes (Automattic/mongoose#5033). The issue traces down to jsdom overwriting `global.toString()`, which confuses the index `isObject` check and leaves us with an empty index getting sent to mongodb. `Object.prototype.toString` works though

fix: don't rely on global toString() for checking if object

---

test/functional/operation_example_tests.js
test/functional/operation_generators_example_tests.js
test/functional/operation_promises_example_tests.js

Many of the tests of (and consequently the documentation for)
collections.updateMany(...) included the "multi" option, which was
used by collections.update(...), but is not a valid option for
updateMany.  These have been removed.
modified:   test/functional/operation_example_tests.js
modified:   test/functional/operation_generators_example_tests.js
modified:   test/functional/operation_promises_example_tests.js

Remove multi option from updateMany tests/docs

---

lib/apm.js

Only 'find' and 'getmore' had the cursor in their reply. But aggregate can also return a cursor. Unfortunately the reply field used to be null in that case.

Add cursor to reply of aggregate command

---

lib/mongo_client.js
test/functional/readconcern_tests.js

The documentation says that the connect function of MongoClient accepts a readConcern option, but the object was being flattened and passed to the db as `level` instead of `readConcern`. This change excludes the readConcern option from being merged which results in it being handled correctly.
I confirmed that the test fails on MongoDB 3.4 when run with the replicaset topology before the change, and passes after it has been applied.
This PR also includes a documentation fix for the type of the `readConcern.level` property.

Fix passing the readConcern option to MongoClient.connect

---

lib/collection.js

AFAIK saving a doc with null `_id` is perfectly valid, but this code makes that impossible. Re: Automattic/mongoose#5236

allow saving doc with null `_id`

---

lib/gridfs-stream/download.js

Currently skip function does not use the index, replace it with $gte over "n" field

Fix for NODE-1026

---

lib/cursor.js
test/functional/cursor_tests.js

before, calling map multiple times on a cursor resulted in only the last map transform to be applied.

Allow multiple map calls

---

CHANGES_3.0.0.md
lib/cursor.js
test/functional/crud_api_tests.js
test/functional/cursor_tests.js
test/functional/error_tests.js
test/functional/operation_example_tests.js
test/functional/operation_generators_example_tests.js
test/functional/operation_promises_example_tests.js

The `Cursor.nextObject()` method was deprecated with the release of v2.0 of the driver. This PR entirely removes support for it and updates the documentation.

NODE-1072 Remove Cursor.nextObject and document changes

---

lib/gridfs/grid_store.js

This PR brings forward @christkv's commit 1298820dedaebc27fa0440b0da038441208dfa1f on the 2.2 branch. This commit fixed [NODE-1034](https://jira.mongodb.org/browse/NODE-1034), which fixed a GridStore on Node 8. This commit seems to have been made after the 3.0.0 branch was split off. This fix allows our tests to pass on Node 8.

NODE-1034 Fix GridStore issue caused by Node 8.0.0 breaking backward compatible fs.read API

---

lib/mongo_client.js
lib/url_parser.js
test/functional/connection_tests.js

Based on my reading of `url_parser.js` looks like there's no reason why `auth` isn't a supported option. Having support for this option would be very helpful for issues like https://github.com/Automattic/mongoose/issues/5419, otherwise we'd have to mutate the user-provided URI or ask users to not use those options anymore.

allow auth option

---

lib/collection.js

[The porcelain layer cursor already supports `noCursorTimeout` as an option](https://github.com/mongodb/node-mongodb-native/blob/129d5400e46340f929eba32d5fb10b63145448e7/lib/cursor.js#L152-L154) and we got bit by this internally recently where `.find({}, { noCursorTimeout: true })` gets treated as a projection.

fix(collection): allow passing `noCursorTimeout` as an option to `find()`

---

lib/bulk/common.js

`index` wasn't documented before, I've added in the @param comment to the docs

Add param to documentation for BulkWriteResult.getWriteError

---

lib/db.js

Server has a 'reconnectFailed' event, but that doesn't end up getting emitted by the 'db'

fix(db): bubble up `reconnectFailed` event from Server topology

---

docs/reference/content/tutorials/gridfs/streaming.md

It's **s** , not **6** in `Node.js`

Fixed spelling error

---

CHANGES_3.0.0.md
lib/bulk/common.js
lib/collection.js
test/functional/insert_tests.js
test/functional/operation_example_tests.js
test/functional/operation_promises_example_tests.js

Bulk operation failures used to be presented to users in a non
idiomatic fashion, calling the async callback with (Error,
BulkWriteResult), assuming the user remembered to check the second
value.  Instead we now create a new BulkWriteError type which wraps
the result, and only callback with a single value in the error
case
NODE-1088

refactor(bulk-write): standarize how we treat bulk operation errors

---

lib/gridfs/grid_store.js

This adds the missing callback to `fs.close` in `grid_store.js` 🍕 
Fixes [NODE-1154](https://jira.mongodb.org/browse/NODE-1154)

NODE-1154 - Calling an asynchronous function without callback

---

lib/bulk/ordered.js
lib/bulk/unordered.js
test/functional/bulk_tests.js

This adds the check into unordered bulk operations to see if the `ignoreUndefined` option has been set to `true`. 
Tests added for both ordered and unordered bulk operations. 
Fixes [NODE-1155](https://jira.mongodb.org/browse/NODE-1155) ✨

NODE 1155 - ignoreUndefined is not working in unordered bulkWrite

---

lib/topologies/mongos.js
lib/topologies/replset.js
lib/topologies/server.js
lib/topologies/topology_base.js

All three topology types were duplicating code across three files
needlessly.  This reduces duplication, while also making it easier
to maintain and modify in the future by providing a common
TopologyBase class that they all extend.

refactor(topologies): extract common code into TopologyBase

---

lib/url_parser.js
test/functional/url_parser_tests.js

This changes the url parser so that unsupported connection string options don't throw an error and prevent the connection, instead they're ignored and a warning is issued 🍍 
Fixes [NODE-913](https://jira.mongodb.org/browse/NODE-913)

NODE-913 Don't throw error with unsupported connection string options

---

.travis.yml
lib/collection.js
lib/cursor.js
lib/db.js
lib/gridfs-stream/index.js
lib/gridfs/grid_store.js
lib/utils.js
test/functional/db_tests.js
test/functional/gridfs_tests.js
yarn.lock

Running the test suite against 3.6.0-rc2 resulted in a slew of new and interesting errors, mostly around cursors but also related to the need to "unset" sessions when they are implicitly created.  I apologize for the large size of this PR, but you should be able to review the piecewise commits (they are generally small except for the first one where I added error checks to all the gridfs tests).

Fix cursor issues with driver sessions

---

lib/authenticate.js

Backpatching this to 2.2, to fix NODE-1173

fix(import): adds missing import to lib/authenticate.js

---

lib/gridfs-stream/download.js

BUG: https://jira.mongodb.org/browse/NODE-1168
When using the promoteBuffers connect option, `doc.data` is already a node.js Buffer.
So trying to call `length()` like for `BSON.Binary` fails.
Fixed simply by checking `Buffer.isBuffer(doc.data)` type.
Would love to get your review, and fix whatever is needed.
Thanks

NODE-1168 promoteBuffers + GridFS = TypeError: doc.data.length is not a function

---

lib/mongo_client.js

Fixing jsdoc to have proper type for `keepAliveInitialDelay`

docs(MongoClient): keepAliveInitialDelay should be a number

---

lib/collection.js
test/functional/aggregation_tests.js

Adds a "comment" field to the aggregation command
Fixes NODE-1149

feat(aggregation): adds support for comment in aggregation command

---

lib/gridfs-stream/download.js

This is a port of #1555 to 3.0.0 branch.
When using the promoteBuffers connect option, `doc.data` is already a node.js Buffer.
So trying to call `length()` like for `BSON.Binary` fails.
Fixed simply by checking `Buffer.isBuffer(doc.data)` type.

fix(GridFS):  fix TypeError: doc.data.length is not a function

---

lib/collection.js
package.json
test/functional/causal_consistency_tests.js
test/mock/index.js
test/unit/sessions/collection_tests.js

Version 3.6 of the server introduces support for [causal consistency of reads](https://github.com/mongodb/specifications/blob/master/source/causal-consistency/causal-consistency.rst), this pull request adds support for this feature to the porcelain layer of the driver.

feat(causal-consistency): add support for causally consistent reads

---

lib/mongo_client.js
lib/topologies/topology_base.js
package.json
test/functional/causal_consistency_tests.js
test/functional/sessions_tests.js
yarn.lock

As initially implemented, sessions must be explicitly ended by the
user.  This is likely to lead to cases where users forget to do
this, and therefore leak sessions.  Instead, MongoClient now tracks
all sessions created on the client, and explicitly cleans them up
upon client close.
NODE-1105

feat(sessions): MongoClient will now track sessions and release

---

test/functional/examples_tests.js

I got here from the tutorial, and the reference of this test in tutorial is 'https://docs.mongodb.com/manual/tutorial/update-documents/#replace-a-document' .
updateOne should contain atomic operators, while replaceOne needn't.
Thus according to the context, I infer the original purpose in that doc shall refers to 'replaceOne' instead of 'updateOne'

Change 'updateOne' into 'replaceOne' in e.g 54

---

lib/url_parser.js
test/functional/url_parser_tests.js

If a user enters a non-socket hostname with more than one "/" in it (such as `mongodb://invalid/127.0.0.1:27017/db`), the error message would previously state "double colon in host identifier" which was incorrect.

Better error message for slash in hostname

---

docs/reference/content/tutorials/connect/authenticating.md

This ports a change to documentation (to be more clear) from `2.2` to `3.3`.
Original change in #1560 🌟 
NODE-1181

[Port] Update server domain for GSSAPI auth 

---

lib/url_parser.js
test/functional/url_parser_tests.js

This ports #1559 from the `2.2` branch to `3.0`.
Notes:
- There were changes between `2.2` and `3.0` in the test set up so it's not a direct transfer there.
- I had to add the check `&& r.path.indexOf('::') === -1` to line `203` because without it both test URIs end up with the slash error because they each contain 3 items in their array after the split:
```bash
path split [ '', '::host', 'db' ]
path split [ '', 'host:27017', 'db' ]
```
I'm not quite sure why the tests passed without this in `2.2` cc @mbroadst for thoughts 💭

[Port] Better error message for slash in hostname

---

lib/change_stream.js

`require('util').inherits(ctor, super)` blows away the original prototype
of ctor. If we wish to use it, we need to move the inherits call to
directly after the constructor creation. In the future, we should
switch to using classes.

fix(changeStreams): fixing node4 issue with util.inherits

---

lib/cursor.js
test/functional/change_stream_tests.js
test/mock/index.js

This makes all of the currently active unit tests for change streams work with the replicaset topology. In most cases, we just needed to ensure that `.hasNext` was called on a cursor before we actually changed anything in the DB.

test(changeStream): fixing all broken replset changestream tests

---

lib/collection.js

Re: Automattic/mongoose#5839
This is a very rough edge in the API where `findAndModify()` treats `upsert: 1` as `upsert: true`, but `findOneAndUpdate()` and `updateX()` treat `upsert: 1` as `upsert: false`. [CRUD spec does say `upsert` is a boolean](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst) but we've had `upsert: 1` in shell examples for a while so it may be worthwhile to support both, especially since truthiness is so common in JS.

fix(collection): allow { upsert: 1 } for findOneAndUpdate() and update()

---

lib/collection.js
test/functional/collations_tests.js
test/functional/command_write_concern_tests.js
test/functional/crud_api_tests.js
test/functional/cursor_tests.js
test/functional/db_tests.js
test/functional/decimal128_tests.js
test/functional/find_tests.js
test/functional/insert_tests.js
test/functional/mapreduce_tests.js
test/functional/promote_buffers_tests.js
test/functional/promote_values_tests.js
test/functional/raw_tests.js
test/functional/sharding_read_preference_tests.js
test/functional/unicode_tests.js
test/mock/lib/request.js
test/unit/sessions/collection_tests.js

Find api is now updated and clarified. You can no longer pass in
fields, and you cannot pass in individual options as parameters.
BREAKING CHANGE:
`find` and `findOne` no longer support the `fields` parameter.
You can achieve the same results as the `fields` parameter by
using `Cursor.prototype.project` or by passing the `projection`
property in on the `options` object . Additionally, `find` does not
support individual options like `skip` and `limit` as positional
parameters. You must pass in these parameters in the `options` object

feat(collection): updating find API

---

lib/mongo_client.js
lib/mongos.js
lib/server.js
test/runner.js

Hi, this is related with [this](https://github.com/mongodb-js/mongodb-core/issues/245) and [this](https://github.com/mongodb-js/mongodb-core/issues/242).
In short, is it currently impossible to do ssl handshake with mongos/mongod if it is used certificate with ECDH curve. This is due to recently added `ecdhCurve` ssl option to nodejs. Here we are passing this option and `cipher` option to `mongodb-core`
Also, I was faced with Promise error about missed `return` statement while runned tests.

Added missed ssl options for `ciphers` and `ecdhCurve`

---

lib/collection.js
test/functional/causal_consistency_tests.js

`Collection.prototype.findOne` needs to use the new explicit
parameters for `find` (since it internally delegates). In the
process it made sense to clean up the methods own parameter
handling code as well

fix(collection): make the parameters of findOne very explicit

---

lib/topologies/mongos.js
lib/topologies/replset.js
lib/topologies/server.js

Adds missing ssl options that are required for mongodb-core to establish
ssl handshake with mongo server which is used certificate with ECDH curve
Ports #1579 to 3.0.0

feat(ssl): adds missing ssl options ssl options for `ciphers` and `ecdhCurve`

---

lib/db.js

Updated the documentation of the `listCollections` in the `Db` class. The `filter` argument is optional

[doc] Filter is optional in Dd.listCollections

---

lib/url_parser.js
test/functional/connection_string_spec_tests.js
test/functional/url_parser_tests.js

The existing url parser spec tests were using `var` judiciously
and because of hoisting were never actually testing anything but
a single uri. This change switches to let/const where appropriate
and ensures we're running the tests we intend to be running.

test(url-parser): lexically scope all the things

---

lib/db.js

This ports a documentation fix from #1549 to `3.0.0`.
The `filter` parameter in `Db.listCollections` should me shown as optional 📖

docs(db): filter param is optional in Db.listCollections

---

docs/reference/content/upgrade-migration/main.md

Instead of recreating the entire 3.0.0 guide in the docs, I'm just linking to them here.

docs(upgrading): Update upgrade documentation to include info for 3.0

---

docs/reference/content/quick-start/quick-start.md
docs/reference/content/tutorials/aggregation.md
docs/reference/content/tutorials/collations.md
docs/reference/content/tutorials/collections.md
docs/reference/content/tutorials/commands.md
docs/reference/content/tutorials/connect/authenticating.md
docs/reference/content/tutorials/connect/index.md
docs/reference/content/tutorials/connect/ssl.md
docs/reference/content/tutorials/create-indexes.md
docs/reference/content/tutorials/crud.md
docs/reference/content/tutorials/geospatial-search.md
docs/reference/content/tutorials/gridfs/gridstore.md
docs/reference/content/tutorials/gridfs/streaming.md
docs/reference/content/tutorials/projections.md
docs/reference/content/tutorials/text-search.md
docs/reference/layouts/shortcodes/basic-connection.html
docs/reference/layouts/shortcodes/connect-to-replicaset.html
docs/reference/layouts/shortcodes/connect-to-sharded-cluster.html
docs/reference/layouts/shortcodes/create-2dsphere-index.html
docs/reference/layouts/shortcodes/create-text-index.html
docs/reference/layouts/shortcodes/find-documents.html
docs/reference/layouts/shortcodes/index-collection.html
docs/reference/layouts/shortcodes/js6-connect.html
docs/reference/layouts/shortcodes/myproject-connect.html

Updating the quickstart guide for 3.0.0

Updating docs for 3.0.0

---

lib/mongo_client.js
lib/topologies/topology_base.js
lib/utils.js

The test for whether a deployment supports sessions is to check if
`logicalSessionTimeoutMinutes` is set. For more complicated
deployments (e.g. not single) this value is not determined by a
single ismaster. As a result I've changed this to no longer be a
part of our `ServerCapabilities` detection, but read right off
the topology.
NODE-1188

refactor(sessions): modify how we check for sessions support

---

CHANGES_3.0.0.md
lib/topologies/mongos.js
lib/topologies/replset.js
lib/topologies/server.js
test/functional/mongo_client_tests.js
test/functional/reconnect_tests.js
test/functional/replset_connection_tests.js

keepAlive options are now consistent with socket / node api.
keepAlive is a boolean that enables / disables keepAlive,
and keepAliveInitialDelay is the number of milliseconds to wait
before initiating keepAlive.
BREAKING CHANGE:
option `keepAlive` is now split into boolean `keepAlive` and
number `keepAliveInitialDelay`
Fixes NODE-998

feat(keepAlive): make keepAlive options consistent

---

lib/topologies/mongos.js
lib/topologies/replset.js

UPDATE: Eliminates the DB parameter from the `connect` call in replset
and mongos to unify the api with server
Would like some discussion on this, as some fix is needed for NODE-1089

fix(connect): unifying topology connect options

---

lib/collection.js
lib/db.js
lib/mongo_client.js
lib/topologies/mongos.js
lib/topologies/replset.js
lib/topologies/server.js
lib/utils.js
test/functional/buffering_proxy_tests.js
test/functional/change_stream_tests.js
test/functional/collations_tests.js
test/functional/command_write_concern_tests.js
test/functional/crud_spec_tests.js
test/functional/ignore_undefined_tests.js
test/functional/max_staleness_tests.js
test/functional/replicaset_mock_tests.js
test/functional/view_tests.js
test/unit/sessions/client_tests.js

chore(assign): replace assign with native Object.assign

---

lib/admin.js
lib/aggregation_cursor.js
lib/collection.js
lib/command_cursor.js
lib/cursor.js
lib/db.js
lib/gridfs/grid_store.js
lib/mongo_client.js
lib/topologies/mongos.js
lib/topologies/replset.js
lib/topologies/server.js

Fix all the examples in the API documentation. Part of NODE-1218

docs(api): fixing all examples in API documentation

---

lib/bulk/unordered.js

Updating the return types of some functions to be
FindOperatorsUnordered instead of UnorderedBulkOperation
Fixes NODE-1225

docs(FindOperatorsUnordered): updating return types to self

---

lib/collection.js

Per DRIVERS-350, All aggregation commands must either include
the 'cursor' option or 'explain':true.
Note that this is the simplest fix for this issue. Depending on what gets removed for NODE-1122, there are more items that might get cleaned up.

fix(aggregate): remove support for inline results for aggregate

---

docs/reference/content/tutorials/crud.md

It stated bulkWrite supported insertMany instead of replaceOne.

Update list of operations that bulkWrite supports

---

README.md

Not sure if the 2.2 link is by design but it's caused me some confusion so I figured I'd point it out.

docs: link to 3.0.0 API in README

---

docs/reference/content/quick-start/quick-start.md

Updated the installation instruction in the Quick Start guide to refer specifically to version 2.2. 
Otherwise it will install the recently released `mongodb` npm module version 3.0.0 which is not compatible with rest of the Quick Start tutorial.

Updated npm install to install specifically v2.2 of the mongodb module.

---

lib/collection.js

This is a fix for issue https://github.com/webpack/webpack/issues/6191
Needed to surround the require statement with parenthesis to make its priority higher.

Surrounded require('./db') with ()

---

lib/mongo_client.js

Updating documentation of IP family field to indicate new default
behavior of attempting IPv6, followed by IPv4.
Fixes NODE-1260

docs(MongoClient): updating documentation of IP family field

---

docs/reference/themes/mongodb/theme.toml

Update the root path for the versions dropdown to point to
node-mongodb-native
Deals with NODE-1235, but also requires a change to
learn-mongodb-docs

docs(reference): update version dropdown root path

---

lib/collection.js

Updates the aggregation documentation to show that the callback
should receive a cursor, not an object.
Fixes NODE-1283

docs(aggregate): updating docs to indicate callback returns cursor

---

lib/collection.js

This fixes linting errors from https://github.com/mongodb/node-mongodb-native/pull/1637 that are breaking the tests.
I'll rebase https://github.com/mongodb/node-mongodb-native/pull/1640 and https://github.com/mongodb/node-mongodb-native/pull/1641 after this goes in 👍

chore(collection): lint errors

---

lib/topologies/topology_base.js

Fixes [NODE-1270](https://jira.mongodb.org/browse/NODE-1270)

fix(topology base): allow more than 10 event listeners

---

CHANGES_3.0.0.md

We now consolidate all notes on aggregation in to a single location
in the upgrade guide. We also add a note about how `aggregate` no
longer accepts variadic arguments.
Fixes NODE-1285

docs(aggregate): add more info on aggregation changes to upgrade guide

---

lib/change_stream.js
lib/collection.js

This documentation change updates the docs for what the `fullDocument` option in `collection.watch()` takes: either `default` or `updateLookup`. These are the correct strings and match our [ChangeStreams examples](https://github.com/mongodb/node-mongodb-native/blob/3.0.0/test/functional/operation_changestream_example_tests.js#L128). 
Fixes [NODE-1272](https://jira.mongodb.org/browse/NODE-1272)

docs(watch): update docs to the correct param strings

---

test/functional/operation_changestream_example_tests.js

This adds the missing `mongodb` version requirement to the changestream example specs.

test(changestreams): add mongodb version requirement

---

test/functional/mongodb_srv_tests.js
test/functional/spec/dns-txt-records/README.rst
test/functional/spec/dns-txt-records/uri-with-auth.json
test/functional/spec/dns-txt-records/uri-with-auth.yml

Two new test files went into the specifications for DNS Seedlist discovery in: https://github.com/mongodb/specifications/pull/262. This PR updates our specs to match these new files (which check that auth is preserved).
Related to https://github.com/mongodb/node-mongodb-native/pull/1640.

Update SRV tests with latest from specifications

---

test/functional/mongodb_srv_tests.js
test/functional/specs/dns-txt-records/README.rst
test/functional/specs/dns-txt-records/uri-with-auth.json
test/functional/specs/dns-txt-records/uri-with-auth.yml

_This backports the update of srv files to `2.2`. The sibling PR is #1649._
Two new test files went into the specifications for DNS Seedlist discovery in: https://github.com/mongodb/specifications/pull/262. This PR updates our specs to match these new files (which check that auth is preserved).
Related to https://github.com/mongodb/node-mongodb-native/pull/1641.

Update SRV tests with latest from specifications (backport)

---

lib/collection.js

The current syntax does not play well with Webpack in Electron 1.7.11, basically breaking all our plugins in standalone modes on the latest driver. The combination of `new` + `require` seems to be throwing it for a loop.
Example plugin before this change:
Example plugin after this change:
The syntax recently got updated in this commit: https://github.com/mongodb/node-mongodb-native/commit/efa78f0f72388e567a96c6427527dacfae3fa9c1 but that actually does not resolve the issue in this specific case. Here's a SS with that fix in, still the same error:
This is because the generated code, *even with the parens* is this:
```
collection = new !(function webpackMissingModule() { var e = new Error(\"Cannot find module \\\".\\\"\"); e.code = 'MODULE_NOT_FOUND'; throw e; }())('./db')(\n …
```

Change db instantiation in Collection#mapReduce:

---

lib/db.js
test/functional/db_tests.js
test/functional/index_tests.js

If an error occurs within the users callback the callback is called twice. This checks and only returns the callback with an error if it is a `MongoError` from the server.
Fixes NODE-1293

fix(db): only callback with MongoError NODE-1293

---

lib/collection.js
test/functional/remove_tests.js

Calling remove with no arguments resulted in an error b/c
of the lack of options.
Fixes NODE-1287
@mbroadst @jlord I'm wondering if we should instead fix this in `executeOperation`?

fix(collection): fix error when calling remove with no args

---

test/functional/examples_tests.js

Fixes NODE-1262
NOTE: the version filter means the test isn't currently being run :(

test(causalConsistency): adding an example test for causal consistency

---

test/functional/apm_tests.js

If one of these tests fails, it frequently causes false negatives
for following tests. This change properly cleans up after ourselves.

test(apm): making tests clean up after themselves

---

lib/url_parser.js
test/functional/spec/connection-string/invalid-uris.json
test/functional/spec/connection-string/invalid-uris.yml

Update to the latest tests from the connection string spec and fix our url parser so that it handles errors that come from Node's `url.parse` when given a bad uri.
The error message uses 'malformed' because this is how the original Node error describes it.
Fixes [NODE-1292](https://jira.mongodb.org/browse/NODE-1292)

Resync Connection String Spec Tests

---

lib/db.js

Hello!
As stated in [JSDoc](https://github.com/mongodb/node-mongodb-native/blob/077b876ab8d90ea4938926b33c6ebdff3ae7d5eb/lib/db.js#L397) to [Db.prototype.collection](https://github.com/mongodb/node-mongodb-native/blob/077b876ab8d90ea4938926b33c6ebdff3ae7d5eb/lib/db.js#L415) function, 
```text
If the application does not use strict mode you can use it without a
callback in the following way: `var collection = db.collection('mycollection');`
```
This pull request fixes JSDoc, which removes this IDE warning:
Additionally, it fixes a typo in the function description (duplicated word `can`).
Thank you for a great project and keep up the good work! 😃

fix(jsdoc): mark db.collection callback as optional + typo fix

---

lib/collection.js

[`arrayFilters` is necessary for the filtered positional operator](https://docs.mongodb.com/manual/reference/operator/update/positional-filtered/) but it looks like it isn't in the docs yet

docs(collection): add `arrayFilters` option to docs

---

lib/utils.js
test/unit/sessions/collection_tests.js

When the topology believes it has session support, options passed to
commands were getting mutated with the session added to them. It is our
expectation that the driver will never be mutating arguments passed to
it via the public facing API.
This commit creates a new object and copies into it, then replaces in
the args array.

Don't mutate options passed to commands:

---

lib/mongo_client.js

`MongoClient.prototype.startSession` doesn't take a second argument, or return a Promise. It returns the ClientSession from the mongodb-core:
https://github.com/mongodb-js/mongodb-core/blob/2d3fa98db1d1430558979af092fd033315551406/lib/sessions.js#L12

Update documentation for startSession

---

lib/utils.js
test/functional/operation_example_tests.js
test/functional/operation_generators_example_tests.js
test/functional/operation_promises_example_tests.js
test/unit/execute_operation_tests.js

Makes sure that, if an error is thrown before the async part
of executeOperation, the implicit session is cleaned up
Fixes NODE-1335
~~WIP waiting for unit tests~~ Unit tests done

fix(utils): fixes executeOperation to clean up sessions

---

lib/mongo_client.js

Use the authentication database form the URI if no parameter is provided to `MongoClient.db()`

NODE-1258 - Use database from URI

---

lib/admin.js
lib/bulk/common.js
lib/bulk/ordered.js
lib/bulk/unordered.js
lib/collection.js
lib/db.js
lib/utils.js

We presently have many similar methods laying around the codebase to deal with applying a write concern to some command. This has become a problem during transactions development because we need to make some decisions about whether to apply based on transaction status - and requiring changing this logic in seven locations is error-prone, and outright annoying.

Refactor multiple `writeConcern` helpers into a single `applyWriteConcern' method

---

lib/collection.js
test/functional/apm_tests.js

We should use the `batchSize` that users provide for calls to `aggregate`

NODE-1415 honor user provided batchSize in aggregate

---

lib/mongo_client.js
lib/topologies/topology_base.js
lib/utils.js
package.json
test/functional/sessions_tests.js

`withSession` allows users to ignore resource management while
using sessions. A provided method/operation will be provided with
an implicitly created session, which will be cleaned up for them
automatically once the operation is complete.
NODE-1418

feat(withSession): add top level helper for session lifetime

---

lib/collection.js
lib/db.js
test/functional/collection_mapping_tests.js

This is a WIP to add mapping / unmapping on a collection level.
This can give document-mapper libraries a quicker way to map documents so that they don't have to wrap every collection's methods. (i.e. [type-mongo-mapper](https://github.com/j/type-mongo-mapper))
Features to be implemented:
- Mapping: Allow all collection methods that return plain documents (ignoring aggregations) to be "mapped" (i.e. converting a document to a class).
- Unmapping: Allow all collection methods that insert or update plain documents (without update modifiers) to be unmapped (i.e. converting a class to a document).
Basic Example:
```javascript
class User {
public _id;
public firstName;
public lastName;
public createdAt;
constructor(doc) {
this._id = doc._id || new ObjectID();
this.firstName = doc.firstName; …
```

feat(collection): add colleciton level document mapping/unmapping

---

lib/change_stream.js

Fixes NODE-1462
WIP b/c we need to figure out a way to determine if an error is coming from a `getMore`, and do separate processing in that case.

feat(changeStream): expanding changeStream resumable errors

---

lib/mongo_client.js

The `isConnected` method does not take a `name` parameter before `options`, its code is:
```javascript
MongoClient.prototype.isConnected = function(options) {
options = options || {};
if (!this.topology) return false;
return this.topology.isConnected(options);
};
```
Perhaps this parameter existed once, but was removed at some point without updating the JSDoc.

Removed extraneous parameter from JSDoc

---

lib/topologies/mongos.js
test/functional/sharding_connection_tests.js

Fix Automattic/mongoose#6249
In addition to the changes in #1685, I put together a test that fails when `mongos.js` is unchanged. Should make it clear why this change is necessary.
As far as mongoose is concerned, the 'close' event is what matters, so I'd be open to leaving the 'timeout' and 'error' events as `once()` if that helps address any concerns.

fix(mongos): bubble up close events after the first one

---

package.json

Normally would not do this, but 3.5.4 does not lock version of
babylon, leading to the install not having compatible engines

chore(jsdoc): updating version of jsdoc

---

lib/change_stream.js
lib/error.js
lib/error_codes.js
test/unit/change_stream_resume_tests.js

Fixes [NODE-1494](https://jira.mongodb.org/browse/NODE-1494)

fix(change_stream): do not check isGetMore if error[mongoErrorContextSymbol] is undefined

---

lib/change_stream.js

If a change stream resume occurred, and the user was using the
Promise-based version of .next, the promise would resolve before
waiting for the change stream to resume, resulting in bad behavior.
Fixes NODE-1493
There is no test for this, but #1697 will incorporate tests.

fix(change-stream): fix change stream resuming with promises

---

lib/cursor.js
test/functional/cursor_tests.js

When a callback function is not specified by the user,
the forEach method returns a Promise.
Fixes NODE-1231

feat(cursor-forEach): cursor forEach return Promise

---

lib/cursor.js
test/functional/cursor_tests.js

Instead of throwing an error when the cursor is exhausted, the
hasNext method returns false.
Fixes NODE-1197

fix(cursor-hasNext): cursor hasNext returns false when exhausted

---

lib/collection.js

We documented session as being a valid option for
parallelCollectionScan, but it is not a valid option,
and we do not support it.
Fixes NODE-1490

docs(parallelCollectionScan): remove session option

---

lib/cursor.js

Corrected the type and description for parameter 'value' in
cursor.addQueryModifier
Fixes NODE-1126

docs(cursor): fix documentation for cursor.addQueryModifier

---

docs/reference/content/tutorials/gridfs/streaming.md

Corrected the documentation to have users listen for
'end' events (for readable streams) rather than 'finish'
(for writable streams) when using openDownloadStreamByName.
Fixes NODE-1376

docs(GridFS): incorrect end event in GridFS docs

---

lib/cursor.js

It was unclear what type the 'returnKey' parameter
for cursor.returnKey should be and what it meant.
Fixes NODE-1182

docs(cursor): incorrect returnKey documentation

---

lib/collection.js

findAndModify and findOneAndUpdate were missing
documentation for the optional options.arrayFilters
parameter.
Fixes NODE-1422

docs(collection): Add arrayFilters option for methods

---

lib/change_stream.js
lib/collection.js
lib/cursor.js
lib/db.js
lib/mongo_client.js
package.json
test/functional/change_stream_spec_tests.js
test/functional/change_stream_tests.js
test/functional/spec/change-stream/README.rst
test/functional/spec/change-stream/change-streams-errors.json
test/functional/spec/change-stream/change-streams-errors.yml
test/functional/spec/change-stream/change-streams.json
test/functional/spec/change-stream/change-streams.yml

Adds new ChangeStream features for 4.0 as per SPEC-1057
- Db.watch() method
- MongoClient.watch() method
- startAtClusterTime option
This is no longer WIP, though the killCursor test cannot be enabled until we finish #1705 
+ [x] Test for [killing cursors](https://github.com/mongodb/specifications/pull/311/files#diff-bc08254b22b485d29a830c0d98eebaaeR604)
+ [x] Proper test for [change streams resuming with `startAtClusterTime`](https://github.com/mongodb/specifications/pull/311/files#diff-bc08254b22b485d29a830c0d98eebaaeR590)

feat(changeStream): Adding new 4.0 ChangeStream features

---

lib/cursor.js
test/functional/cursor_tests.js

Created a new method, cursor.transformStream, which
returns a readable stream with the transformation
applied. Does not mutate the cursor.
Fixes NODE-1208

WIP: feat(cursor): new cursor.transformStream method

---

lib/db.js

My least favorite bug strikes again: `createIndex()` falls back to inserting an index doc and swallows the original error. Below is a minimal repro script with `mongodb@3.0.9`:
```javascript
const { MongoClient } = require('mongodb');
run().catch(error => console.error(error.stack));
async function run() {
const client = await MongoClient.connect('mongodb://localhost:27017/test');
const db = client.db();
await db.collection('Test2').ensureIndex({ _id: 1 }, { background: true });
console.log('Done');
}
```
This throws a very unhelpful error:
```
$ node gh-6109.js 
Error: cyclic dependency detected
at serializeObject (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/bson/lib/bson/parser/serializer.js:333:34)
at serializeInto …
```

fix(db): throw readable error when creating `_id` with background: true

---

lib/apm.js
lib/bulk/ordered.js
lib/bulk/unordered.js
lib/collection.js
test/unit/bypass_validation_tests.js

The bypassDocumentValidation key will only be set if it explicitly
receives a true, otherwise it remains undefined.
Fixes NODE-1492

fix(collection): only send bypassDocumentValidation if true

---

lib/collection.js
lib/db.js
lib/operations/collection_ops.js
lib/operations/db_ops.js
lib/utils.js

feat(read-preference): unify means of read preference resolution

---

lib/change_stream.js
test/functional/change_stream_tests.js
test/functional/spec/change-stream/change-streams.json
test/functional/spec/change-stream/change-streams.yml

Updates the setting of a default startAtOperationTime to be spec-compliant.
Fixes NODE-1520
Depends on mongodb-js/mongodb-core#320

feat(ChangeStream): update default startAtOperationTime

---

lib/cursor.js
lib/operations/collection_ops.js
test/functional/find_tests.js

When we removed the session use from parallelCollectionScan,
we introduced an error where parallelCollectionScan cursors would
attempt to use implicit sessions on their cursors.
Looking for feedback on the name of the field :)

fix(parallelCollectionScan): do not use implicit sessions on cursors

---

lib/mongo_client.js
lib/operations/cursor_ops.js
test/functional/cursor_tests.js

Fix wrong placement and typo in options argument in
cursor.s.topology.command, and test that specified readPreference
is passed in to that call.
Fixes NODE-1511

fix(cursor): cursor.count not respecting parent readPreference

---

lib/operations/collection_ops.js
lib/operations/db_ops.js

Undeprecates ensureIndex for collection and db.
Fixes NODE-1354

docs(ensureIndex): undeprecate ensureIndex

---

lib/db.js

Found another issue re: https://github.com/Automattic/mongoose/issues/6109#issuecomment-398403430 . Looks like index builds always fail if `retryWrites` is turned on, for example:
```javascript
run2.catch(error => console.error(error.stack));
async function run() {
const { MongoClient } = require('mongodb');
const client = await MongoClient.connect('mongodb://localhost:27017/test?retryWrites=true');
await client.db('test').collection('test').createIndex({ email: 1 }, {
unique: true
});
console.log('done');
}
```
Gives you a very unhelpful "Error: cyclic dependency detected" error. This will make it so that `session` doesn't make it into the return value from `createCreateIndexesCommand()`

fix(db): don't send session down to createIndex command

---

lib/collection.js

The `query` parameter is optional and will default to `{}` if omitted.

Fixed JSDoc for Collection.count

---

lib/db.js

Creating a user normally does not specify an auth mechanism, leaving
it to the server to select a default mechanism. 4.0 server introduced
default of SCRAM-SHA-256, which is not supported by the driver.
For server versions >= 4.0, we will enforce SCRAM-SHA-1.

fix(createUser): allow creating a user against 4.0 server

---

lib/collection.js

There are different ways of building aggregation pipelines, you can put the whole pipeline in the first parameter:
```javascript
db.collection('Foo').aggregate([{ $match: { bar: 1 } }, { $limit: 10 }])
```
or add them via separate method calls later:
```javascript
db.collection('Foo').aggregate([]).match({ bar: 1 }).limit(10)
```
In the second case, passing the empty array to `aggregate()` seems redundant and even though the `pipelines` parameter is currently documented as required, this also works:
```javascript
db.collection('Foo').aggregate().match({ bar: 1 }).limit(10)
```
But I'm not fully sure if this is supposed to work or perhaps just an unintended side effect of a deprecated version of the function.
Either way, I find it clearer and would prefer it to be supported.

docs: updated Collection.aggregate()

---

lib/collection.js
test/functional/collection_tests.js

bulk updates and deletes cannot retry writes.
Fixes NODE-1534
Backports #1760 to 3.0.x

fix(retryWrites): fixes more bulk ops to not use retryWrites

---

lib/topologies/server.js

This `console.log()` has been causing me some grief and I think it's just something that was added for debugging and then left there.

fix(server): remove unnecessary print statement

---

README.md

Bit of a gotcha, found myself wondering why the docs for `countDocuments()` weren't there

docs(README): link to 3.1 docs in readme

---

lib/operations/mongo_client_ops.js
test/functional/uri_tests.js

During the refactor of MongoClient operations a mapping variable
was mistaken to be a function expression, and we silently broke
using the new url parser. This corrects that, renames the mapping
variable to make it very clearly that, and adds a test to prove
that the new url parser is working again.
NODE-1542

fix(client-ops): return transform map to map rather than function

---

lib/operations/collection_ops.js
test/functional/collection_tests.js

The countDocuments method was not properly checking that documents were
returned from the query. Added tests on top of astanciu's bug fix.
Fixes NODE-1543

fix(collection): countDocuments throws error when query doesn't match docs

---

lib/operations/collection_ops.js

otherwise the scucess handler is called, which results into further missleading errors (e.g. length is not defined)

return on handleCallback

---

lib/operations/collection_ops.js
test/functional/find_and_modify_tests.js

Fixes [NODE-1541](https://jira.mongodb.org/browse/NODE-1541)

fix(collection): ensure findAndModify always uses readPreference primary

---

lib/operations/collection_ops.js
test/functional/collection_tests.js

The collection method isCapped was returning undefined
when the capped option was either unspecified or specified
as false.
Fixes NODE-1380

fix(collection): isCapped returns undefined

---

index.js

My use case is to be able to do `foo instanceof AggregationCursor` just as one could do with `Cursor` and I don't see any reason why `AggregationCursor` should not be exposed.

refactor(export): expose AggregationCursor

---

docs/reference/content/quick-start/quick-start.md
docs/reference/content/reference/connecting/connection-settings.md
docs/reference/content/reference/ecmascriptnext/connecting.md
docs/reference/content/reference/ecmascriptnext/crud.md
docs/reference/content/reference/faq/index.md
docs/reference/content/reference/management/logging.md
docs/reference/content/tutorials/connect/authenticating.md
docs/reference/content/tutorials/connect/index.md
docs/reference/content/tutorials/connect/ssl.md
docs/reference/content/tutorials/gridfs/streaming.md
docs/reference/layouts/shortcodes/basic-connection.html
docs/reference/layouts/shortcodes/connect-to-replicaset.html
docs/reference/layouts/shortcodes/connect-to-sharded-cluster.html
docs/reference/layouts/shortcodes/find-documents.html
docs/reference/layouts/shortcodes/js6-connect.html
docs/reference/layouts/shortcodes/myproject-connect.html

We want to encourage people to manually create a new MongoClient,
and then call connect, instead of using the static method MongoClient.connect
Fixes NODE-1585

docs(connect): remove references to MongoClient.connect

---

lib/operations/mongo_client_ops.js

if topology.connect has an error, topology is "overwritten" which leads to an error like:
```
Uncaught TypeError: Cannot read property 'close' of undefined
at topology.connect (node_modules/mongodb/lib/operations/mongo_client_ops.js:412:16)
at ReplSet.<anonymous> (node_modules/mongodb/lib/topologies/replset.js:364:11)
at node_modules/mongodb-core/lib/topologies/replset.js:634:14
at Server.<anonymous> (node_modules/mongodb-core/lib/topologies/replset.js:357:9)
at node_modules/mongodb-core/lib/topologies/server.js:508:16
at node_modules/mongodb-core/lib/connection/pool.js:531:18
at process._tickCallback (internal/process/next_tick.js:61:11)
```
changing the function parameter to a new name, let's "force close" the old instance.

Fix error handler in topology.connect

---

CHANGES_3.0.0.md

The links to change streams specification and change streams examples were broken.

Fixed change streams spec and example links

---

lib/change_stream.js

every time we call changestream.on('change',callback), the changestream will call this.cursor.on('data'...) , which is not correct.  
change event was add to changestream,  not changestream.cursor, so `this.cursor.listenerCount('change') === 0` will always be `true`.
[bug demo](https://github.com/huangciyin/mongodb-change-streams-bug-demo)

fix bug: 'change' event callback was called multi times.

---

lib/cursor.js

Also, sort of unrelated, but the docs show that AggregationCursor's base is "Readable" and the `@types/mongodb` package reflects that and is missing a lot of methods for the AggregationCursor.

fix(cursor): remove deprecated notice on forEach

---

lib/collection.js

These docs should be valid only for `countDocuments`
`estimatedDocumentCount` doesn't have `query` parameter so no need to add these migration guide.
It seems this is a copy & paste docs from `countDocuments` issue.

Remove unnecessary information for estimatedDocumentCount

---

lib/cursor.js

You may pass an object with a `$meta` key in place of the order parameter to `sort`.  The previous code would incorrectly reject this input as illegal.  See https://docs.mongodb.com/manual/reference/method/cursor.sort/#sort-metadata for documentation.

Allow `$meta` based sort when passing an array to `Cursor.sort()`

---

test/examples/transactions.js

Fixes transaction examples on how to retry transactions
Fixes NODE-1668

docs(transactions): fixing transaction examples

---

package-lock.json
test/config.js
test/functional/scram_sha_256_tests.js

The existing SCRAM-SHA-256 tests were not correctly applying the
`replicaSet` option to the URL/options used for initial connect.
This change provides access to the environment through the
configuration, and appropriately applies these values when it
detects replset environments.
NODE-1685

test(scram-sha-256): ensure tests are respecting environment

---

lib/authenticate.js
lib/db.js
lib/operations/mongo_client_ops.js
lib/topologies/mongos.js
lib/topologies/replset.js
lib/topologies/server.js
lib/topologies/topology_base.js
test/functional/scram_sha_256_tests.js

This is the companion to https://github.com/mongodb-js/mongodb-core/pull/361, effectively moving all authentication to the core driver. The majority of the changes here relate to making sure that credentials that are passed in the options to the topology proxy classes are not filtered out when instantiating the mongodb-core versions of the topologies. 
As mentioned in the companion PR, this is more work than we ever intended to put into these types we soon hope to get rid of, but it is a crucial step towards making that transition much smoother. 
**NOTE:** This builds on the previous PR related to running SCRAM-SHA-256 tests against replica sets, so the change set will look bigger until that is merged.

refactor(auth): remove `authenticate`, push authentication to core

---

lib/gridfs-stream/upload.js

Fixes deprecation warning:  `DeprecationWarning: collection.insert is deprecated. Use insertOne, insertMany or bulkWrite instead.`

Fixed deprecation warning.

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-atlas-tests.sh
package-lock.json
package.json
test/atlas_connectivity_tests.js

These tests were originally in core, but they actually make more
sense in the native driver, as it becomes a full e2e test

chore(evergreen): port atlas connectivity tests to native

---

lib/collection.js

* document what findAnd* promises resolve to
* fix run-on sentences
* replace "on MongoDB" with "in/from a collection"
* be specific re. update vs. replace
* consistent @param descriptions

Doc what promises resolve to. Consistent params. Fix English.

---

lib/collection.js
lib/options_validator.js
test/unit/options_validator_tests.js

Fixes [NODE-1670](https://jira.mongodb.org/browse/NODE-1670)
This PR depends on the `assertArity` implementation [PR](https://github.com/mongodb/node-mongodb-native/pull/1837).
This is the implementation of `OperationBuilder`, which is responsible for building a function that checks the arity of an operation, validates its options, and calls the original function.

feat(options_validator): implement OperationBuilder

---

lib/options_validator.js
test/unit/options_validator_tests.js

While working on [NODE-1671](https://jira.mongodb.org/browse/NODE-1671), I realized that I was not handling the case where an operation is called without any options.
If `insertOne(doc, callback)` is called before this fix, the `doc` will be treated as `options` in `build()`. This fix ensures that a new options object is created if one is not passed in.

fix(options_validator): add options if they do not exist

---

docs/reference/content/quick-start/quick-start.md
docs/reference/content/reference/faq/index.md
docs/reference/content/reference/management/sdam-monitoring.md
docs/reference/layouts/shortcodes/js6-connect.html
docs/reference/layouts/shortcodes/myproject-connect.html

We were incorrectly stating that client.connect took a url
parameter.
Fixes NODE-1716

docs(connect): fixing errors in client.connect documentation

---

lib/collection.js
lib/db.js
lib/mongo_client.js
lib/operations/mongo_client_ops.js
lib/options_validator.js
test/functional/aggregation_tests.js
test/functional/collection_tests.js
test/functional/db_tests.js
test/functional/insert_tests.js
test/unit/options_validator_tests.js

Fixes [NODE-1733](https://jira.mongodb.org/browse/NODE-1733)
I also changed `validationLevel` to `optionsValidationLevel` because `validationLevel` is a Mongo option for `createCollection`.

 feat(mongo_client): add validationLevel as an option to MongoClient

---

lib/collection.js

This option is supported by the code, but not documented for some reason.
It accepts the same input as documented here: https://docs.mongodb.com/manual/reference/command/aggregate/

Document options.hint in collection.aggregate

---

lib/collection.js
lib/operations/collection_ops.js
lib/utils.js
test/functional/readconcern_tests.js

Fixes [NODE-1532](https://jira.mongodb.org/browse/NODE-1532)

fix(collection): add support for `readConcern` on every eligible operation

---

lib/bulk/common.js
lib/bulk/ordered.js
lib/bulk/unordered.js
test/functional/bulk_tests.js

Bulk Writes were failing to account for the size of the array
index key when calculating the batch size in a bulk write.
We now calculate the size of the key based off of the max batch
size, and incorporate that number in to the byte size calculations.
Fixes NODE-1778

fix(bulk): properly calculate batch size for bulk writes

---

lib/mongo_client.js

This PR adds options that I unintentionally left out of the original MongoClient connect PR. I found these forgotten options after adding #1891 and seeing warnings for unknown options.

fix(mongo_client): add connection options

---

lib/bulk/unordered.js
test/unit/bulk_write_tests.js

Previously, errors that were not the last returned during
a bulk write would be swallowed. Now, we return them.
Fixes NODE-1702

fix(bulk): make sure that any error in bulk write is propagated

---

lib/mongo_client.js
lib/options_validator.js
test/unit/options_validator_tests.js

This PR fixes the magic boolean I added to `validate()` in [this commit](https://github.com/mongodb/node-mongodb-native/commit/18e187a1b140fa6f888bbbef1135fb898b628bd3).

fix(options_validator): use validationOptions instead of magic boolean

---

lib/collection.js

All write operations (insertOne,update,updateMany etc...). honor the ignoreUndefined flag defined in the collection scope. Apparently UnorderedBulkOp was left out. This fixes it, makes UnorderedBulkOp honor the flag.

initializeUnorderedBulkOp to honor ignoreUndefined

---

lib/change_stream.js
test/functional/change_stream_tests.js

If a changeStream gets an event while it is in the middle of closing,
a race condition can occur where the event is still processed after
the stream has closed. This commit adds handling for this edge
case by returning an error to callbacks, rejecting promises,
and simply ignoring it in emitter mode.
Fixes NODE-1831

fix(changeStream): properly handle changeStream event mid-close

---

lib/collection.js
lib/db.js
lib/gridfs/grid_store.js
lib/mongo_client.js
lib/operations/collection_ops.js
lib/operations/cursor_ops.js
lib/operations/db_ops.js
lib/operations/mongo_client_ops.js
lib/options_validator.js
lib/schemas/collection_schemas.js
lib/schemas/db_schemas.js
lib/schemas/mongo_client_schemas.js
lib/utils.js
package-lock.json

This PR is an update to #1876 since `applyDefaults` is now merged to `next`.

fix(lib): refactor db and collection to prevent multiple rounds of options validation

---

test/functional/spec/transactions/convenient-api/README.rst
test/functional/spec/transactions/convenient-api/callback-aborts.json
test/functional/spec/transactions/convenient-api/callback-aborts.yml
test/functional/spec/transactions/convenient-api/callback-commits.json
test/functional/spec/transactions/convenient-api/callback-commits.yml
test/functional/spec/transactions/convenient-api/callback-retry.json
test/functional/spec/transactions/convenient-api/callback-retry.yml
test/functional/spec/transactions/convenient-api/commit-retry.json
test/functional/spec/transactions/convenient-api/commit-retry.yml
test/functional/spec/transactions/convenient-api/commit-transienttransactionerror-4.2.json
test/functional/spec/transactions/convenient-api/commit-transienttransactionerror-4.2.yml
test/functional/spec/transactions/convenient-api/commit-transienttransactionerror.json
test/functional/spec/transactions/convenient-api/commit-transienttransactionerror.yml
test/functional/spec/transactions/convenient-api/commit-writeconcernerror.json
test/functional/spec/transactions/convenient-api/commit-writeconcernerror.yml
test/functional/spec/transactions/convenient-api/commit.json
test/functional/spec/transactions/convenient-api/commit.yml
test/functional/spec/transactions/convenient-api/transaction-options.json
test/functional/spec/transactions/convenient-api/transaction-options.yml
test/functional/transactions_tests.js

This is the native component to NODE-1741. Considering the helper is hung off a `ClientSession`, this PR is mostly concerned with importing and syncing the YAML tests and providing a test runner for said tests.

NODE-1741: implement convenient transaction api (native)

---

test/functional/transactions_tests.js

Ensure the find remains causally consistent with previous operations by using a "local" read concern level while reading the latest data on the primary.
NODE-1793

test(txns): ensure `local` read concern used for outcome testing

---

lib/schemas/mongo_client_schemas.js

The default value for `validateOptions` was causing a lot of annoying deprecation notices. This removes the unnecessary default and the annoying deprecation notices.

fix(mongo_client_schemas): remove default for deprecated option validateOptions

---

lib/operations/mongo_client_ops.js
test/functional/uri_tests.js

This slightly modifies @kvwalker 's work from last week to support x509 without any username/password provided in a URI. We need to be careful not to always create an `auth` object, because that will result in `MongoCredentials` being created in cases where no auth is desired. This also includes a unit test to validate the behavior in the future.

refactor(connect): modify the rules for determining auth from uri

---

test/functional/session_leak_test.js

Clear all of the session tracking if a test fails, b/c otherwise
those can cause every subsequent test to fail

test: stop session leak tests from cascading

---

test/functional/promises_collection_tests.js

Won't change the actual result of the test, but makes sure errors
cause a quick error rather than an uncaught error causing a stall

test: make sure bulk tests catch all errors

---

lib/operations/aggregate.js
test/functional/aggregation_tests.js

Sending a batchSize of 0 will break the cursor, and in general we
should not be sending batchSize for aggregation pipelines
that contain a $out stage.
Fixes NODE-1850

fix(aggregate): do not send batchSize for aggregation with $out

---

package-lock.json
test/functional/mongo_client_tests.js

Fixes NODE-1658
These are just the tests. The PR for the fix in core is [#400](https://github.com/mongodb-js/mongodb-core/pull/400)

test(mongo_client): add tests to show how uri parsers handle duplicate options

---

lib/bulk/ordered.js
lib/bulk/unordered.js

Bulk Writes use bson.calculateObjectSize to determine the size of
batches. However, it was not respecting user or default option
values like ignoreUndefined, which lead to bulkWrite errors in
some edge cases. To be safe, it now always sets ignoreUndefined to
false.
Fixes NODE-1898

fix(bulkWrite): always count undefined values in bson size for bulk

---

lib/aggregation_cursor.js
lib/command_cursor.js
lib/cursor.js
lib/utils.js

Adds a stronger spot check against importing the async iterator
for cursors. Handles case where other project pollute the known
symbols of the environment.
CC @majorhayes

fix(asyncIterator): stronger guard against importing async generator

---

docs/reference/content/reference/connecting/connection-settings.md
docs/reference/content/tutorials/connect/ssl.md
lib/mongo_client.js
lib/topologies/mongos.js
lib/topologies/replset.js
lib/topologies/server.js

fix(docs): correctly document that default for `sslValidate` is false

---

lib/topologies/native_topology.js

I know the ticket says something about session leaks, but that's because I was forcing a constant pool size of 5, where most of our tests actually set it to 1.

fix(unified-topology): only clone pool size if provided

---

lib/bulk/ordered.js
lib/bulk/unordered.js

Documents the two errors that can be thrown by a bulkWrite execution:
- throws if the bulk object has already been executed
- throws if the bulk object does not have any operations
Fixes NODE-1914
CC @dandv

docs(BulkWrite): document when errors are thrown

---

lib/mongo_client.js

The `client.close()` calls at http://mongodb.github.io/node-mongodb-native/3.1/api/index.html don't pass a `force` parameter. The parameter not being documented as optional triggers linting errors:

The MongoClient.close `force` param is optional

---

lib/collection.js

Mongoose has [some trouble with the findAndModify deprecation](https://mongoosejs.com/docs/deprecations.html#-findandmodify-) because Mongoose's [`findOneAndUpdate()` function](https://mongoosejs.com/docs/api.html#model_Model.findOneAndUpdate) pre-dates the driver's `findOneAndUpdate()`, so we still use `findAndModify()` by default to maintain backwards compatibility. Unfortunately, this means if you use `findOneAndUpdate()` with Mongoose, you'll get a very confusing deprecation warning:
```
collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.
```
I'd like to suppress this warning and add a Mongoose-specific one instead, but there's no good way to suppress one deprecation warning in Node. I hate to suggest this change, and I'm open …

refactor: add private `_findAndModify()` function that bypasses deprecation warning for Mongoose

---

lib/core/connection/connect.js

Connect error handler was attempting to read properties off
of an error that had a chance of being null. Removed that,
and replaced the error generation to be more explicit.
Fixes NODE-1960
Fixes NODE-1968

fix(connect): fixed syntax issue in connect error handler

---

test/unit/change_stream_resume_tests.js

These tests take way too long, so let's disable them outside
of unified topologies.

test: disable change stream resume tests for non-unified topology

---

lib/core/sessions.js

Fixes NODE-1557
`clientOptions` was not initialized in the `ClientSession` constructor. The `clusterTime` initialization was cleaned up.

fix(ClientSessions): initialize clientOptions and cluster time

---

lib/core/sessions.js
test/functional/transactions_tests.js

Fixes NODE-1931
According to the 4.0 transaction spec, startTransaction SHOULD report an error if the driver can detect that transactions are not supported by the deployment. A deployment does not support transactions when the deployment does not support sessions, or maxWireVersion < 7, or the topology type is Sharded. This PR throws a new `MongoError` for sharded topologies and topologies with `maxWireVersion < 7`.
`ClientSession.startTransaction` will throw a new `MongoError` when it is called on a sharded topology or on a topology where `maxWireVersion` is less than 7.
The test in `transactions_tests.js` shows that the error is thrown for a sharded topology.

fix(sessions): ensure an error is thrown when attempting sharded transactions

---

lib/core/topologies/server.js

Same thing as https://github.com/mongodb-js/mongodb-core/pull/438, but for the `next` branch as per https://github.com/mongodb-js/mongodb-core/pull/438#issuecomment-499844609

fix(server): emit "first connect" error if initial connect fails due to ECONNREFUSED

---

lib/bulk/common.js
test/functional/bulk_tests.js

Fixes NODE-1965
An unspecific `BulkWriteError: write operation failed` message was changed to the first item from `writeErrors`. 
A user requested to make the error more specific and suggested to use the first item from `writeErrors`. A change was made to the `MongoError` message field to reflect this error message.

fix(Bulk): change BulkWriteError message to first item from writeErrors

---

lib/collection.js

fixes Node-1981
This comment navigates developers from countDocument to estimateDocumentCount, since estimatedDocumentCount is not easily discoverable by developers in their IDE.
Added a comment line to the collections documentation for countDocuments, that refers people to estimatedDocumentCount

fix(documentation): Documentation for countDocuments mentions estimatedDocumentCount

---

lib/collection.js
test/functional/collection_tests.js

Fixes NODE-1920
This provides extended functionality for the `update` command by allowing the specification of a pipeline. `update` can now take in an object or an array.
To allow the user to pass in an array to `update` in addition to preserving the functionality of providing an object, the corresponding argument in the `updateOne` function was modified to check for atomic operators on each element in the array, if passed in as such.

feat(Update): add the ability to specify a pipeline to an update command

---

lib/change_stream.js
test/functional/change_stream_tests.js

Fixes Node-1727
Closes the 'data', 'close', 'end', and 'error' listeners when the ChangeStream's cursor is closed.
This change closes event listeners when the cursor is closed. Before, when `ChangeStream.prototype.close` was called, the event listeners would remain, which led to memory leaks and made bugs hard to understand.

fix(changestream): removes all event listeners on close

---

lib/core/cursor.js

Port of mongodb-js/mongodb-core#441 to native.
Fixes a cursor issue where a cursor id could get truncated if it was larger than `Number.MAX_SAFE_INT`.
Minor change to `lib/core/cursor.js`
nope

fix(cursor): do not truncate an existing Long

---

lib/operations/aggregate.js
test/functional/readconcern_tests.js

Adds support for adding a ReadConcern to aggregates with $out against
4.2 servers. Some ReadConcerns (like linearizable) are still
not supported by the server, but will still be added on to
the outbound request.
Fixes NODE-1880
- Small change to `lib/operations/aggregate.js` to properly attach ReadConcern against 4.2 servers.
- Adds test in `test/functional/readconcern_tests.js` to verify changes
None
**Note:** there are spec tests in `test/functional/spec/crud/v2` that will give full coverage to the proper results, but since the `v2` test runner is not implemented they are not being run atm.

feat(Aggregate): support ReadConcern in aggregate with $out

---

docs/reference/content/upgrade-migration/main.md

Fixes NODE-1632
Adds a `What's new in 3.1` section to the upgrade guide.
Added documentation to `docs/reference/content/upgrade-migration/main.md`
nope
**Anything else?**
Needs to be ported to `master` and `next`

docs(changes): add Whats new in 3.1 to upgrade guide

---

docs/reference/content/reference/ecmascriptnext/connecting.md

Fixes NODE-1849
By way of: https://twitter.com/mikemaccana/status/1090328293243527168
Previous demo code was returning an error. By adding this useNewURLParser argument, the demo code works. 
Added correct argument to MongoClient()

doc(connect): 'Connecting' example code returns a deprecation warning

---

test/functional/bulk_tests.js

NODE-1994
The test originally had a `test.ok(...)` that checked if any WriteErrors were generated, but left extraneous code and asserts that would never be checked.
Updated 'should correctly handle multiple unordered batch API' to adhere to current testing specifications and generate 1 `WriteError` consistently.

test(bulk_tests): fix 'should correctly handle multiple unordered batch API'

---

lib/core/wireprotocol/command.js
lib/mongo_client.js
lib/operations/mongo_client_ops.js
package.json

This is the client component to Client Encryption. Primarily we are allowing users to specify a new option `autoEncryption` to the `MongoClient` constructor to enable auto encryption. The actual work is implemented in the `command` wire protocol method. **NOTE:** This feature only works with the unified topology.
The big change is that the `command` wire protocol method now conditionally autoencrypts if the feature was requested. It's supported in a non-ideal way, because our wire protocol methods are not easily decorated. If, instead, they were defined on a `Connection`, then we could potentially provide a `CryptoConnection` - alas it's not possible with the current design. 
No

Node 1854/enable client encryption in client

---

lib/bulk/common.js
lib/collection.js
test/functional/bulk_tests.js

Fixes NODE-1911
Made an arrayFilters method for FindOperators which matches the documentation of the method here: https://docs.mongodb.com/manual/reference/method/Bulk.find.arrayFilters/
Created two tests for ordered and unordered operations with arrayFilters.
Made a 'Should be able to use array filters in unordered operation' and  'Should be able to use array filters in ordered operation' test. Created an arrayFilters method in the FindOperators class which calls the find method on each filter in the filter array.

test(arrayFilter): Ability to use array filters with bulk operations

---

lib/operations/mongo_client_ops.js

This pull request fixes the unnecessary `the options [x] is not supported` warnings when extending the `Object.prototype` object for custom functions. For example, using the following code:
```js
Object.prototype.custom = function () { return true; };
```
... would report this to console when you try to create a new Mongo client:
`the options [custom] is not supported`
On line 593 of the file that validates config files, it checks to make sure that the key it is checking is an actual property within the object, instead of prototype function.
Nope

Ignore prototype methods in config validation

---

lib/collection.js
lib/operations/aggregate.js
lib/operations/collection_ops.js
test/functional/crud_spec_tests.js
test/functional/runner/index.js
test/functional/spec/crud/v2/aggregate-merge.json
test/functional/spec/crud/v2/aggregate-merge.yml
test/functional/spec/crud/v2/db-aggregate.json
test/functional/spec/crud/v2/db-aggregate.yml
test/functional/spec/crud/v2/updateWithPipelines.json
test/functional/spec/crud/v2/updateWithPipelines.yml

The main work here was that `$merge` is accepted as a final aggregation pipeline stage similar to `$out`. We needed to ensure that when this is provided, that the operation is considered a write operation, and therefore things like write concern apply.
The tests are expressed in YAML in the CRUDv2 format, so I've also included updates to support running those tests. The commits are unit, and should have detailed descriptions where appropriate.
No.

NODE-2004: Finer Grained Updates from Aggregation via `$merge`

---

lib/collection.js
lib/db.js

Fixes NODE-1631
Adds documentation for write concern options to `Collection.prototype.drop` and `Db.prototype.dropCollection`
jsdoc comments on the methods mentioned above
No

docs(drop): document writeConcern usage for drop methods

---

lib/change_stream.js

This is basically a duplicate of [JAVA-2987](https://jira.mongodb.org/browse/JAVA-2987) but in the node driver.  When the cursor tries to reconnect, it has an internal resumeToken value that it has acquired while iterating over earlier changes.  If a startAtOperationTime was set when the cursor was originally created, it will also be sent and the server will respond with "Only one type of resume option is allowed, but multiple were found"
No

Don't set startAtOperationTime if resumeToken is available

---

docs/reference/content/tutorials/crud.md

This fixes some misleading code comments in the docs where it says the code is inserting one document when it seems to be inserting multiple.

Fix doc code comments

---

lib/operations/mongo_client_ops.js

Fixes NODE-2023
Enables the sharded recovery token by default.
An alternative option is to remove the option `useRecoveryToken`
Enables the sharded recovery token by default
No

chore(transactions): enable recovery token by default

---

docs/reference/content/upgrade-migration/main.md

Ports the `What's new in 3.1` guide to `master`, and adds `What's new in 3.2` as well.
`docs/reference/content/upgrade-migration/main.md` update to include changes in 3.1 and 3.2
nope

Whats new 3.2

---

lib/core/sdam/server.js
lib/core/wireprotocol/command.js
lib/topologies/server.js

Fixes NODE-2013
`AutoEncrypter` is now accessible as a server property. Improves readability.
Make access of autoEncrypter easier, by defining a server property. Changed variables assigned as autoEncrypter accordingly, thus making commands more readable.

style(autoEncrypter): make autoEncrypter more easily accessible

---

lib/core/connection/pool.js
lib/core/sdam/server.js
lib/core/utils.js

This change implements reset functionality for the connection pool, which is required for the "connections survive primary stepdown" as well as prose tests for SDAM. 
The `Pool.prototype.reset` was implemented, which essentially destroys the pool, transitions it to a `DISCONNECTED` state, and then reconnects it. The only questionable change is in the pool's `_execute` method, where we now attempt to create more connections if none are available rather than flushing monitoring operations. As noted in the code, it's unclear why this was implemented this way, but there aren't broken tests, and the fallback behavior is to use the old code path.
No.

NODE-1682: implement connection pool reset

---

test/functional/readconcern_tests.js
test/functional/shared.js

Fixes NODE-1811
`readconcern_tests.js` previously included a lot of repeated tests and logic, which is now extracted out into a more templated form.
The tests have become more streamlined, and similar aspects have been extracted out and put into an array that can be passed into a templated test format. This includes command monitoring.
None.

refactor(readconcern_tests): refactor readconcern tests to be more DRY

---

lib/operations/collection_ops.js
test/functional/collection_tests.js

Fixes NODE-1986
Removed duplication in collection_tests.js and modernized the code, using `const` and `let` instead of `var` as well as arrow functions when possible.
The tests in collection_tests.js have been refactored and certain configuration and client statements have been moved to beforeEach() hooks to reduce redundancy.

test(collection tests): Clean up collection_tests and make them DRY

---

lib/mongo_client.js
lib/operations/mongo_client_ops.js

Fixes NODE-2012
Previously, cryptd's connectionString was not configurable. Now, the user has the option of setting connectionString by passing it in as an option for MongoClient.
cryptdConnectionString is now a valid option for MongoClient

feat(cryptdConnectionString): makes mongocryptd uri configurable

---

test/functional/change_stream_tests.js

Quick PR to address @kvwalker's comment [here](https://github.com/mongodb/node-mongodb-native/pull/2043#discussion_r300080031)
Switched from using `var` to `const` in a test
Nope

test(ChangeStream): rewrite with const

---

lib/aggregation_cursor.js
lib/change_stream.js
lib/command_cursor.js
lib/core/cursor.js
lib/core/sdam/topology.js
lib/core/topologies/mongos.js
lib/core/topologies/replset.js
lib/core/topologies/server.js
lib/cursor.js

The current constructor is hard to reason about, in particular
during refactoring. This change reduces the duplication of the
passed in values.
NODE-2063

refactor(cursor): simplify `Cursor` constructor

---

lib/core/cursor.js
lib/core/sdam/server.js
lib/core/topologies/server.js

The primitive wire protocol methods are not meant to be used
directly outside of the `Server` class(es). The fact that the
cursors are doing so makes it difficult to provide consistent
error handling behavior required by SDAM/sessions/etc. This patch
moves these methods to the `Server`, with an eye towards
eventually moving them to `Connection`.
NODE-2066

refactor(cursor): move all wire protocol calls to `Server`

---

lib/operations/connect.js

Fixes NODE-2054
Used the flag `useNewUrlParser` when creating the client for mongocryptd.

fix(autoEncryption): use new url parser for autoEncryption client

---

lib/operations/close.js
lib/operations/connect.js

Fixes NODE-2051
Made sure to store off mongocryptd client as `client.s.mongocryptdClient`. In close operation, added logic to ensure that `client.s.mongocryptdClient` is clused as well.
This has the tricky issue of multiple optionally async callbacks nested within each other.

fix(AutoEncryption): tear down mongocryptd client when main client closes

---

lib/command_cursor.js
lib/core/cursor.js
lib/core/sdam/server_description.js
lib/core/sdam/topology.js
lib/core/sdam/topology_description.js
lib/core/utils.js
lib/cursor.js
lib/operations/execute_operation.js
lib/operations/explain.js

In accordance with the [drivers-sessions](https://github.com/mongodb/specifications/blob/master/source/sessions/driver-sessions.rst#how-to-check-whether-a-deployment-supports-sessions) and [SDAM](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#data-bearing-server-type) specs, we must perform server selection under certain circumstances in order to ensure we have accurate information about sessions support.
- ability to filter by "data-bearing" and "known" servers was added to `TopologyDescription` and `ServerDescription`.
- `executeOperation` gains the ability to execute server selection prior to operation execution if `shouldCheckForSessionSupport` is true …

NODE-2068: perform server selection to determine session support, if needed

---

lib/core/cursor.js
lib/core/sdam/server.js
lib/core/sessions.js
lib/core/wireprotocol/get_more.js
lib/core/wireprotocol/query.js
test/functional/runner/context.js
test/functional/runner/index.js
test/functional/sessions_tests.js
test/functional/spec/sessions/README.rst
test/functional/spec/sessions/dirty-session-errors.json
test/functional/spec/sessions/dirty-session-errors.yml

**NOTE:** this depends on #2072, so there is duplicate code in here. Please review that PR first, and re-review once it has been merged.
On the surface this PR does what the ticket asks: marks sessions as dirty on a network error, and evicts them from the `ServerSessionPool` upon operation execution. More importantly, this introduces YAML tests around session behavior and reintroduces support for `lsid` on read operations. We stopped sending sessions data on read operations during the wire protocol refactor, and this corrects that.
I made _very_ incremental commits on this one, so you should be able to clearly follow the changes through individual commits. Mostly what's happening here is:
- each of the command handlers for wire protocol methods has gained an ability to …

NODE-1977: discard session on network error

---

lib/mongo_client.js
lib/operations/close.js
test/functional/mongo_client_tests.js

Switched the internal dbCache from a plain object to
a Map.
Fixes NODE-2060
Replaced `MongoClient.s.dbCache` with a Map, allowing for cached db's with names like `constructor`

fix(MongoClient): allow Object.prototype items as db names

---

lib/collection.js
lib/db.js
lib/mongo_client.js

* it was changed during alpha, beta testing from  to  but JSDocs keeps old option name
* related to api ref docs: https://mongodb.github.io/mongo-java-driver/3.8/javadoc/com/mongodb/client/ChangeStreamIterable.html
* related to specs: https://github.com/mongodb/specifications/blob/master/source/change-streams/change-streams.rst

Fix name of stream changes watch option startAtOperationTime

---

lib/core/connection/msg.js

Since OpMsg uses buffer write methods, these methods can throw if the buffer
attempts to write a number to large for the space. We now cap the requestId
at 0x7fffffff and loop back around to 0
Fixes NODE-2067
We now mask the OP_MSG `_requestId` with `0x7fffffff` to prevent it from exceeding signed int32 size.

fix(OpMsg): cap requestIds at 0x7fffffff

---

lib/change_stream.js

Re: https://github.com/Automattic/mongoose/issues/7930, if the underlying replica set dies and the driver gives up reconnecting, the change stream doesn't emit a 'close' event. Based on my reading of [the stream 'close' event](https://nodejs.org/api/stream.html#stream_event_close_1), closing the underlying topology should result in a 'close' event.
Added `emit('close')` it `waitForTopologyConnected()` returned an error. It looks like the only way `waitForTopologyConnected()` can return an error is if it times out.

fix(change_stream): emit 'close' event if reconnecting failed

---

lib/collection.js
lib/command_cursor.js
lib/core/sdam/topology.js
lib/core/topologies/mongos.js
lib/core/topologies/replset.js
lib/operations/command_v2.js
lib/operations/list_indexes.js
test/functional/apm_tests.js
test/functional/retryable_reads_tests.js
test/functional/runner/index.js

Enables retryability for the `listIndexes` operation
- `ListIndexesOperation` was refactored to exclude notions of cursors
- The `Collection.listIndexes` now return a cursor constructed with an operation
- The unified `Topology` and legacy `ReplSet` topology classes gained an ability to respect a passed in read preference to `selectServer`
No

NODE-1744: retryable listIndexes

---

lib/admin.js
lib/operations/list_databases.js
test/functional/retryable_reads_tests.js
test/functional/runner/index.js

Add retryable read support for `listDatabases`
Added a `ListDatabasesOperation`, used it in the `Amin.listDatabases` method. This operation should prove useful if we choose to move this method to the top level of the `MongoClient` (which would be consistent with other drivers)

refactor(list-databases): support retryable reads

---

lib/collection.js
lib/core/sessions.js
lib/operations/aggregate.js
lib/operations/collection_ops.js
lib/operations/command_v2.js
lib/operations/estimated_document_count.js
lib/operations/rename.js
test/functional/retryable_reads_tests.js

Add support for retryable reads to all of our count commands
- `EstimatedDocumentCount` is now an operation subclassing `CommandOperationV2`, supporting execution by selection and retryability
- `Collection.count` now reuses the `EstimatedDocumentCountOperation`
- `commandSupportsReadConcern` has been reused from the command wire protocol temporarily
- The test runner now checks command names against a list of known cursor operations, and calls `toArray` on them (used to only be `aggregate` and `find`)

NODE-1744: retryable count commands

---

lib/core/topologies/replset.js

We were calculating lastUpdateTime using nanoseconds instead of
milliseconds, despite calculating maxStaleness with a millisecond
lastWriteDate

fix(replset): correct legacy max staleness calculation

---

lib/operations/connect.js

Fixes NODE-2078
Our handling for missing `mongodb-client-encryption` was covering up other errors.
We now explicitly check for `mongodb-client-encryption` existence with `require.resolve`, and emit the error if the package is not found. Any other errors stemming from pulling in the package are directly propagated to the user.
No

feat(AutoEncryption): improve error message for missing mongodb-client-encryption

---

lib/change_stream.js
test/functional/change_stream_tests.js

Fixes NODE-2075
When `cursor.close()` was called, all event listeners were removed before the cursor actually closed. Because of this, a `close` event was not emitted.
This PR removes event listeners after the cursor is closed, handling both callbacks and promises.
No.

fix(change_stream): emit close event after cursor is closed during error

---

index.js
lib/operations/close.js
lib/operations/connect.js

Delegates most autoEncryption resource management to autoEncryptor. autoEncryptor now spawns `mongocryptd` as well as a client to connect to it, and handles teardown.
The driver portion of https://github.com/mongodb/libmongocrypt/pull/33
- setup and teardown logic in `lib/operations/connect` and `lib/operations/close`
- Exposes `MongoTimeoutError` for injection into `mongodb-client-encryption`

Node 2070/auto spawn mongocryptd

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Update evergreen config generator to generate a matrix that tests 4.2, as well as omits some out of date oses
the generator file `.evergreen/generate_evergreen_tasks.js`
`.evergreen/config.yml` is auto-generated, and can be ignored

chore(ci): update evergreen config

---

lib/core/sessions.js
lib/core/utils.js
lib/operations/execute_operation.js
test/environments.js
test/functional/runner/index.js
test/functional/sessions_tests.js
test/functional/sharding_read_preference_tests.js
test/functional/transactions_tests.js

A few things:
- Fixed a bug where session was not getting passed to serverSelection, which broke mongos-pinning for transactions
- Fixed the error that is thrown for invalid sharded transaction sessions. Now that we support
sharded transactions, it should not throw on sharded unless wire version is low enough
- Fixed a bunch of test runner issues that were causing test failures
- Temporarily disabled some tests that could not be worked around in the current state of the unified test runner.
No

fixing transaction tests

---

lib/core/sessions.js
lib/core/transactions.js
test/functional/spec/transactions/convenient-api/commit-retry.json
test/functional/spec/transactions/convenient-api/commit-retry.yml
test/functional/spec/transactions/convenient-api/commit-writeconcernerror.json
test/functional/spec/transactions/convenient-api/commit-writeconcernerror.yml
test/functional/spec/transactions/error-labels.json
test/functional/spec/transactions/error-labels.yml
test/functional/spec/transactions/transaction-options.json
test/functional/spec/transactions/transaction-options.yml

This PR adds the spec tests for NODE-1978 and the code needed to pass those tests. This includes adding `maxTimeMS` to the transaction options, as well as checking for `maxTimeMSExpired` errors before retrying.
Any test files are just syncing spec tests.

feat(transaction): allow applications to set maxTimeMS for commitTransaction

---

lib/collection.js
lib/core/cursor.js
lib/cursor.js
lib/operations/find.js
test/functional/cursor_tests.js
test/functional/find_tests.js
test/functional/retryable_reads_tests.js

This changeset introduces support for using an operation for find operations. Unlike other operations, this one is still in progress in terms of becoming a proper subclass of `CommandOperationV2`. Since we must maintain support for legacy versions of the server, we cannot simply reuse the command operation.

refactor(find): use `FindOperation` for finds

---

lib/change_stream.js
lib/cursor.js
lib/mongo_client.js
lib/operations/aggregate.js
lib/operations/command_v2.js
lib/operations/list_collections.js
lib/operations/list_indexes.js

Implements change streams through an `AggregateOperation` providing retryability for the `ChangeStreamCursor` through `executeOperation`. We cannot presently implement the retryable reads tests because we don't provide a `tryNext`, the tests depend on `next` returning in a reasonable about of time.

NODE-1744: retryable change streams

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Fixes NODE-2095
This updates Evergreen to test MongoDB >= 4.2 on Ubuntu 18.04 and to only test MongoDB < 4.2 on Ubuntu 16.04 ARM.
I made changes to `generate_evergreen_tasks.js` and ran the script to generate `config.yml`. This is my first time updating the Evergreen config so I'd appreciate a double-check that the `config.yml` is correct.
No.

chore(ci): update evergreen config to test Ubuntu 18.04 on mongodb >= 4.2

---

lib/core/sdam/topology.js
lib/core/topologies/mongos.js
lib/core/topologies/replset.js
lib/core/topologies/shared.js

Fixes NODE-2098
This adds a new error message for `retryWrites` failures on MMAPv1.
No.

fix(topology): add new error for retryWrites on MMAPv1

---

test/functional/change_stream_spec_tests.js
test/functional/connections_stepdown_tests.js

Follow-up with this in NODE-2112 and NODE-2113
Disabled the connection survive primary stepdown tests, and added a force-close to the change stream tests. Created tickets to follow up investigation.

test: disable some failing tests for later investigation

---

lib/operations/find.js
test/functional/find_tests.js

Fixes a regression introduced in v3.3.0 that ignores a user provided read preference at the client level.
NODE-2124

fix(find): respect client-level provided read preference

---

lib/aggregation_cursor.js

Update AggregationCursor documentation to show `.each` usage as deprecated and promote usage of proper `.forEach` method on the aggregation cursor
Documentation definition in **lib/aggregation_cursor.js** changed
No

Aggregation cursor doc fix

---

lib/core/error.js
lib/core/sdam/server.js
lib/core/sdam/topology.js
test/functional/connections_stepdown_tests.js

Does three things to fix connectionSurvivePrimaryStepdown tests
1. Increase the serverSelectionTimeout to 30s to align with SDAM
2. make sure we close the cursor from the first test
3. Alter SDAM to make sure we do not clear the pool for certain
errors.
Part of NODE-2112.
**There are still some periodic errors that occur in `Not Master - Keep Connection Pool` where, despite not creating a connection anywhere on our end, a connection is still created on the server. I am not sure where it is coming from, but my best guess is that it is the replSet members creating connections between each other. I am not sure how to go about fixing this.**
- Fix to SDAM to implement this:
> If the client is connected to server version 4.2 or higher, and the client receives a "not master" …

test(connections): fix connectionSurvivePrimaryStepdown tests

---

.travis.yml
package-lock.json
package.json
test-runner-poc/LICENSE.md
test-runner-poc/config.js
test-runner-poc/environments.js
test-runner-poc/lib/filters/mongodb_topology_filter.js
test-runner-poc/lib/runner.js
test-runner-poc/package-lock.json
test-runner-poc/package.json
test-runner-poc/test/tools/deprecate_warning_test_program.js
test-runner-poc/test/tools/utils.js
test/check_mongo_orchestration_tests.js

Fixes NODE-2046
Part of the overall goal to replace mongodb-topology-manager with mongo-orchestration.
There are new environments.js and config.js files in the test-runner-poc folder, and the file paths are updated to route to the locations of these new files. Furthermore, environments.js and no longer requires mongodb-topology-manager.
Note: Another PR for this issue was previously opened. https://github.com/mongodb/node-mongodb-native/pull/2096

refactor(test-runner-poc): removes dependencies on topologyManager

---

lib/collection.js

Adds documentation around the createIndex command that links
to docs.mongodb.com entry for an index definition. Also adds an
example showing multiple index definitions to createIndexes,
and adds some examples to createIndex. Makes explicit that
createIndexes uses different syntax from createIndex.
Fixes NODE-2024
jsdoc in `collection.js`
No

docs(createIndex): better document createIndex(es) method and add examples

---

lib/core/uri_parser.js
lib/mongo_client.js
lib/operations/connect.js
test/functional/mongo_client_tests.js

Defaults useNewUrlParser to true, and patches any bugs that result from that
A few things:
- We were previously expecting some parsed options to come back in lowercase, when they were actually coming back in camelCase. So in `lib/operations/connect.js` we now check for the camelCase fields
- we set a default readPreference of `primary` if no readPreference is parsed out.
- We always return a `defaultDatabase` from the url parser. If we do not get it from the auth object, we set the value to `test`. **Appreciate Scrutiny here**
- We change the rules for parsing auth fields like `username` and `password`. **Appreciate Scrutiny here**
- `lib/mongo_client.js`: doc changes
- `test/functional/mongo_client_tests.js`: minor test output change …

default useNewUrlParser to true

---

docs/reference/content/reference/cursors.md

Adds a guide that reviews the basic usage of cursors. Includes two
important warning messages about how not to use cursors.
Fixes NODE-2000
Nope

docs(cursors): Add guide for cursors

---

lib/core/connection/pool.js

We're actually using "passphrase" and not "passPhrase", so we are
updating the docs and default value to reflect this.
Fixes NODE-1762
No

chore(pool): s/passPhrase/passphrase/

---

lib/aggregation_cursor.js
lib/change_stream.js
lib/collection.js
lib/command_cursor.js
lib/core/cursor.js
lib/cursor.js
lib/db.js
lib/gridfs-stream/index.js
lib/mongo_client.js

Add links to our documentation on batchSize in locations where
batchSize can be specified.
Fixes NODE-1967
Fixes NODE-1987
No

docs(batchSize): add documentation links for batchSize

---

docs/reference/README.md
docs/reference/static/js/java.js
docs/reference/themes/mongodb/README.md
docs/reference/themes/mongodb/theme.toml

docs(links): do not link to java docs

---

conf.json
docs/lib/jsdoc/merge_params.js

Adds custom tags to jsdoc that allow merging parameter and property
definitions:
`@merge-params`: used in place of a @param whose type is defined
elsewhere. Will expand out all of the properties of the type.
`@merge-props`: used in a typedef that inherits from another typedef.
Will inherit all properties of that typedef.
Example of `ChangeStream` now:
Example of `ChangeStream` using `@merge-params` for its options object:
- adds the plugin to `conf.json`
nope.

docs(merge-params): adds custom merge-params and merge-prop jsdoc

---

lib/bulk/common.js
lib/bulk/ordered.js
lib/bulk/unordered.js

Adds documentation for multiple methods and properties
associated with bulk writes. Also marks certain methods as
internal.
Fixes NODE-1800
Fixes NODE-1938
Added more documentation to the BulkOperationBase. Includes, but is not limited to:
- Updating language
- Adding examples for how to add various operations to the bulk op
- Correcting the jsdoc for getters such that the description and type actually show up
- Marking certain methods as internal by adding an `@ignore` tag
- `lib/bulk/ordered.js` and `lib/bulk/unordered.js` have trivial changes.

docs(BulkWrite): adds documentation to BulkWrite

---

lib/collection.js

Adds explicit docs that count is deprecated, with instructions
to use estimatedDocumentCount or countDocuments instead.
Fixes NODE-2224
What it looks like:
If this is approved, it needs to be backported to the documentation for `3.2` and `3.1`
Documentation for `Collection#count`
No

docs(count): more explicit documentation that count is deprecated

---

lib/core/connection/pool.js
lib/core/error.js
lib/core/sdam/monitoring.js
lib/core/sdam/server.js
lib/core/sdam/topology.js
test/core/functional/server_tests.js
test/functional/connection_tests.js
test/functional/db_tests.js
test/functional/mongo_client_tests.js
test/functional/operation_example_tests.js
test/functional/operation_generators_example_tests.js
test/functional/operation_promises_example_tests.js
test/functional/scram_sha_256_tests.js

Our FLE implementation of autospawning ran into an issue with the fact that the unified topology did not respect the `serverSelectionTimeoutMS` on initial connect to a topology. This was for two reasons:
- The unified topology implementation incorrectly reported errors encountered during the server selection loop immediately, rather than when the loop was completed.
- The driver _always_ erroneously reported error on connect immediately, even if `auto_reconnect` was specified. We now respect these settings, an in the process much of the code to create connections in the pool has been cleaned up, deduplicated and consolidated.
The server selection loop will now save the error on the topology description, and report the error _after_ the server selection loop has timed …

NODE-2121: respect selection timeout ms on connect

---

lib/core/topologies/mongos.js

We were leaving servers in an open, leaked state if they were determined not to be mongos instances on connect.
NODE-2232

fix(mongos): disconnect proxies which are not mongos instances

---

lib/core/connection/msg.js

Addresses https://github.com/mongodb-js/mongodb-core/issues/456
The `new Buffer(size)` syntax is deprecated in favor of `Buffer.alloc(size)` by node.

fix(connect): Switch new Buffer(size) -> Buffer.alloc(size)

---

docs/guide/management/apm.txt

Fixes NODE-2190
- Deleted all references to the old instrumentation API
- Deleted references to "operationId"

docs(guide): convert /reference/management/apm to rst

---

docs/guide/whats-new.txt

Fixes NODE-2211
Removed references to 2.x upgrade guide and a few other outdated items.

docs(guide): converting upgrade-migration/main.md to rst

---

lib/bulk/common.js
lib/collection.js
lib/operations/common_functions.js
test/functional/spec/crud/v2/bulkWrite-update-hint.json
test/functional/spec/crud/v2/bulkWrite-update-hint.yml
test/functional/spec/crud/v2/replaceOne-hint.json
test/functional/spec/crud/v2/replaceOne-hint.yml
test/functional/spec/crud/v2/updateMany-hint.json
test/functional/spec/crud/v2/updateMany-hint.yml
test/functional/spec/crud/v2/updateOne-hint.json
test/functional/spec/crud/v2/updateOne-hint.yml

This is effectively a POC for the changes added in https://github.com/mongodb/specifications/pull/596.
`hint` is now supported on all update related commands. CRUDv2 spec tests have been added, and everything passes

SPEC-1334: support hint for update commands

---

lib/core/sdam/server_description.js
lib/core/sdam/topology.js
lib/core/sdam/topology_description.js
lib/core/utils.js
test/core/spec/server-discovery-and-monitoring/monitoring/standalone_debounce_description_updates.json
test/core/spec/server-discovery-and-monitoring/monitoring/standalone_debounce_description_updates.yml
test/tools/sdam_viz

`ServerDescription` gains an `equals` method, which allows us to compare against another description for equality. The new operator is used in the `Topology` update path in order to debounce topology update events when nothing of note has actually changed.
Additionally, a tool is introduced with this PR called `sdam_viz` which allows us see changes to a cluster in realtime. It's in a very nascent state, but it's very useful for watching topology changes
**NOTE:** I'd prefer not get into review of the `sdam_viz` tool, we can improve that incrementally.

NODE-2257: add server description equality checks

---

lib/collection.js

As can be seen in the function body, the `query` parameter is optional and will default to an empty object if not provided.
https://github.com/mongodb/node-mongodb-native/blob/0463f7838dbfc0740f6fa52174b96241eb0c3980/lib/collection.js#L1516
The JSDoc was updated to reflect the optionalness of the parameter.
No

docs: mark query as optional in JSDocs

---

docs/guide/tutorials/connect/tls.txt

Fixes NODE-2201
The SSL options are mostly copied from [`connection-settings.txt`](https://github.com/mongodb/node-mongodb-native/pull/2165).

docs(guide): convert tutorials/connect/ssl.md to rst

---

docs/guide/tutorials/connect/authentication.txt

Fixes NODE-2199
* Added `SCRAM-SHA-256`
* Removed links to `mongocr` b/c those just redirect to SCRAM on docs.mongodb.com
* Added notifications about `SCRAM-SHA-1` and `SCRAM-SHA-256` being defaults, and `MONGO-CR` being deprecated.

docs(guide): convert /tutorials/connect/authenticating.md to rst

---

docs/guide/connection-settings.txt

Fixes NODE-2183
* I added `useNewUrlParser` and `useUnifiedTopology` to the top
* Where possible, I removed items that were made redundant by docs.mongodb.com
* I moved any options that specifically applied to the legacy topologies to a separate table at the bottom.

docs(guide): convert /reference/connection-settings/ to rst

---

docs/guide/management/sdam-monitoring.txt

Fixes NODE-2193
I tried to update the structure of the SDAM notifications as best as possible. The problem is that `JSON.stringify` will not stringify `Map` and `Set`, so those show up as `{}`. If this is still adequate, then it's fine, but we might want to switch to something like ts interfaces?

docs(guide): convert reference/management/sdam-monitoring to rst

---

docs/guide/tutorials/gridfs.txt

Fixes NODE-2206
Fixes NODE-2207
Drops the documentation for the deprecated GridFS API, and consolidates remaining GridFS documentation into 1 page. Basically a combo of [the root page](http://mongodb.github.io/node-mongodb-native/3.3/tutorials/gridfs/) and [the streaming api](http://mongodb.github.io/node-mongodb-native/3.3/tutorials/gridfs/streaming/)
**NOTE**: I feel a little weird about how we are pointing users to download a specific song from an external website in this tutorial. We should probably change that to another file that is owned by us.

docs(guide): convert /tutorias/gridfs/* to rst

---

lib/core/topologies/replset.js
package-lock.json
package.json
test/tools/sdam_viz

A change introduced during the massive effort to clean up leaked connections in testing broke the SDAM flow for the legacy `ReplSet` topology type. Connecting servers are now being tracked as "unknownServers", and so needed to be spliced out of the list if they failed connection. Additionally, this PR introduces support for the legacy topology to the `sdam_viz` tool, which was invaluable in visually determining the issues at hand.

NODE-2270: replset leaking unknown servers

---

docs/guide/installation-guide.txt

Fixes NODE-2180
I modified and updated up to the `Kerberos` section. Everything after the `Kerberos` heading I left mostly as is. I'm not sure we should actually include the section on `Kerberos`. We might be better off writing a separate guide on native extensions, how to install them, etc. What do y'all think?

docs(guide): converting installation-guide to rst

---

lib/core/connection/pool.js
lib/core/sdam/server.js
lib/core/sdam/topology.js
lib/core/utils.js

This patch ensures that we use the same method for building state
machines across all modern (read: unified topology) classes.
NODE-1517
**NOTE:** this is built on top of #2195

refactor: introduce `makeStateMachine`, reuse for all fsms

---

lib/core/connection/pool.js
lib/core/sdam/monitoring.js
lib/core/sdam/server.js
lib/core/sdam/topology.js
lib/core/sdam/topology_description.js
lib/operations/close.js
test/core/functional/pool_tests.js
test/core/functional/server_tests.js
test/functional/spec/transactions/convenient-api/transaction-options.json
test/functional/spec/transactions/convenient-api/transaction-options.yml
test/functional/spec/transactions/transaction-options.json
test/functional/spec/transactions/transaction-options.yml
test/mocha.opts
test/runner/config.js
test/runner/filters/unified_filter.js
test/tools/run_each_test.sh

The fundamental issue here is that when using the unified topology, if a node is "lost" (due to some network error, etc) it is never regained. This was due to some complicated error handling, primarily around the events propagated from the connection pool. I'll try to summarize in the next section what changed (or needed to be changed)
- State machines for the `Pool`, `Server` and `Topology` types were formalized, now using the same method to generate the machines. The `Pool` gained a new state `DRAINING` which is used to distinguish whether new commands can be written to the pool or not, in particular during a scenario when fire-and-forget messages are sent right before pool destruction
- The `Topology` no longer listens for `error` or `close` events from the `Pool`. …

NODE-2274: unified failover server loss

---

lib/core/sdam/topology.js

We relay topology events on the `Db` class for legacy compat, so
we need to remove limitations on max listeners in case users are
operating across many instances.
NODE-2123

fix(topology): set max listeners to infinity for db event relay

---

lib/core/connection/connect.js
test/core/unit/connect_tests.js

We treat `close`/`timeout`/`parseError`/`error` as error cases
during initial handshake, but some of these do not generate errors.
Additionally, in some cases multiple of these events may be emitted
which leaves us in a bad state if a subsequent `error` message is
emitted, since that will crash the node process.
NODE-2277

fix(connect): prevent multiple callbacks in error scenarios

---

lib/core/sdam/topology.js
lib/core/topologies/shared.js
test/core/unit/connect_tests.js
test/runner/config.js
test/runner/filters/unified_filter.js

The unified topology has been incorrectly reporting itself as `nodejs-core` in client metadata. This correct that to report just `nodejs`, but to include the unified or legacy type in the platform data.
NODE-2316

NODE-2316: fix client metadata for unified topology

---

lib/core/cmap/connection.js
lib/core/cmap/message_stream.js
lib/core/connection/apm.js
lib/core/connection/connect.js
lib/core/connection/msg.js
lib/core/connection/pool.js
lib/core/wireprotocol/compression.js
package-lock.json
package.json
test/functional/cmap/connection_tests.js
test/runner/index.js
test/runner/plugins/deferred.js
test/unit/cmap/message_stream_tests.js

This changeset introduces a new `Connection` type for use with the forthcoming CMAP implementation. It is strictly callback-based, which is in line with expectations of CMAP and SDAM. It is still an `EventEmitter`, but strictly for command monitoring events and coordinating events such as the receipt of the cluster time.
Nothing changed per se, since this is a new class, but I will describe some of the design choices here. 
All code related to serializing wire protocol messages, and concerns like compression, have been relegated to the newly introduced `MessageStream` class. It's a `Duplex` stream that parses incoming messages, and marshalls outgoing commands. I think there is potential for further refactorings here (we could move _all_ the `OP_QUERY` and `OP_MSG` code …

NODE-2310: introduce modern connection type

---

conf.json
lib/mongo_client.js
package-lock.json
package.json

Pull in the documentation from mongodb-client-encryption and
use that instead of duplicating it across.
Fixes NODE-2298
NOTE: will not really work until we cut a new version of `mongodb-client-encryption` that has the updated jsdoc.

docs(encryption): leverage mongodb-client-encryption docs

---

lib/collection.js

Adds a more detailed example to `coll.find({}, { projection: { a: 0, b: 0 } })` to have both an include and exclude versions. Hopefully it clarifies a bit more that you can't have both.
JSDoc documentation in `collection.js`. 
Thanks!

docs: add example for find's projection exclude + include options

---

lib/bulk/common.js
test/functional/bulk_tests.js

The bulk spec requires that the driver report the index of a failed
operation according to it's input to the unordered bulk operation.
NODE-2308

fix(bulk): use operation index from input to report operation error

---

lib/core/uri_parser.js
test/core/unit/mongodb_srv_tests.js

See: https://jira.mongodb.org/browse/NODE-2335
This PR fixes Fixes non-compliant DNS Seedlist Discovery parsing.
Currently the TXT record values override the querystring values, spec states the opposite must be true, so the uri parser was fixed.
The spec test was also not being performed properly so that was fixed as well to add coverage.

Fixes NODE-2335 (non-compliant DNS Seedlist Discovery parsing.)

---

lib/core/connection/connect.js

This is a fix for a hard-to-reproduce bug that occurs in
certain network setups on Windows 10. In  those cases,
attempting an IPv6 lookup with a shortname will somehow cause the
subsequent IPv4 lookup to also fail, even though it can succeed
independently. For some reason, this does NOT happen with family: 0.
This really should be fixed in either Node or in Windows itself,
but since we cannot create a stable reproducer, we will use this
fix short-term while we come up with a more stable solution.
Fixes NODE-1747
Fixes NODE-2143

fix(connect): connect with family 0 instead of family 4

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/generate_evergreen_tasks.js
.evergreen/run-tests.sh
package-lock.json
package.json
test/runner/filters/client_encryption_filter.js

We only want to test client-side encryption where we actively
provide prebuilds, and where the server is testing it. This reduces
the test matrix to those variants
NODE-2100

test: only test client-side encryption in certain build variants

---

lib/core/auth/scram.js

If username or password isn't a string, it's a little tricky to debug what actually the parameter actually was. This will make it a little easier to debug issues like Automattic/mongoose#8176

fix(auth): throw more readable error if username or password isn't a string

---

lib/core/sdam/topology.js
lib/core/sdam/topology_description.js
test/unit/sdam/topology_tests.js

The logic for checking for sessions support was flawed, in that if
it was connect to a single server it would check the conditions for
single server session support and, failing that, would back off to
the generalized support check. These cases have been split up, and
unit tests were added.
NODE-2342

fix(topology): correct logic for checking for sessions support

---

lib/core/connection/pool.js
lib/core/cursor.js
lib/core/error.js
lib/core/sdam/server.js
lib/core/sdam/server_selection.js
lib/core/sdam/topology.js
test/functional/spec-runner/index.js
test/tools/sdam_viz

Until we integrate the new connection pool conforming to the CMAP specification, any type of error/close/timeout coming from a pool signals pool invalidation. If the pool is configured for unified then it should invalidate the server by emitting a `drain` event which is translated to an `error in the `Server` instance, causing the topology to cycle the server.
The `Pool` gains a new event `drain` which is emitted when some connection error occurs. This causes an `error` event and cycles the server for rechecking (and subsequent server selection). A superfluous timer queue was removed for `monitorIntervals`, which turns out to be a needless timed action. 
Extra small changes:
- `sdam_viz` now has a nicely formatted message for `workload` events
**Are there any files to …

NODE-2332: introduce drain mode for connection pool in unified mode

---

docs/reference/content/reference/unified-topology/index.md
lib/core/sdam/topology.js
lib/operations/connect.js
lib/utils.js

When using the unified topology, a number of options and events are now deprecated. This will notify users of that, and point them to our documentation, which now contains information about deprecations.

NODE-2348: warn on deprecated event and options

---

docs/lib/jsdoc/merge_params.js
lib/collection.js
lib/core/connection/logger.js
lib/core/error.js
lib/core/sessions.js
lib/db.js
lib/gridfs-stream/download.js
lib/gridfs-stream/index.js
lib/gridfs-stream/upload.js

Does a couple of things:
1. Changes the names of `@merge-props` and `@merge-params` to `@mergeProps` and `@mergeParams` respectively. This is mostly to help with syntax highlighting
2. Does a little bit of cleanup on the jsdoc in `Logger`, `Session`, `Error`, `GridFS`, and `Collection`
3. Does a more in-depth dive into `Collection` to try to properly align with CRUD spec. In general, this resulted in:
- Verifying that parameters defined in crud spec were properly documented in `Collection`
- Adding as many known BSON options as possible to write operations (helps with NODE-1652)
- Rearranging some options so that cross-cutting fields (`session`, `WriteConcern`, bson options, etc) were at the bottom, and spec defined fields were at the top.
The following fields were not added for a variety …

Node 2217/normalize api

---

lib/core/connection/connection.js
lib/core/connection/pool.js
test/unit/sdam/topology_tests.js

In the event that a timeout occurs and a server instance is drained, the work items were cleared before the server could signal it needed to be cycled. By waiting until the next tick, we can ensure the event makes it to the `Topology`, and the server is removed from consideration for server selection.

fix(pool): flush workItems after next tick to avoid dupe selection

---

lib/core/connection/connect.js
lib/core/connection/pool.js
test/unit/core/connect.test.js

Sometimes connections are inflight during pool destruction. Introducing a cancellation token to the `connect` method allows us to proactive terminate connections which are being established during these destroy events

NODE-2363: allow connect cancellation

---

lib/core/sdam/monitoring.js
test/unit/sdam/monitoring.test.js

Round trip time was calculated and reported for servers in the
unified topology, but not marked for consideration during server
selection.
NODE-2356

fix: add calculated duration to server as `roundTripTime`

---

lib/bulk/common.js
test/functional/bulk.test.js

The fix for bulk introduced in v3.4.0 did not take into account
the index of the operation result when referring to the original
stored index map.
NODE-2383

fix(bulk): use original indexes as map for current op index

---

index.js
lib/core/error.js
lib/core/index.js
lib/core/sdam/server_description.js
lib/core/sdam/server_selection.js
lib/core/sdam/topology_description.js
lib/core/utils.js
test/functional/core/server.test.js
test/functional/scram_sha_256.test.js
test/unit/sdam/server_description.test.js
test/unit/sdam/server_selection/select_servers.test.js
test/unit/sdam/server_selection/spec.test.js

There are a lot of reasons a server selection timeout error might occur, and even though we include the reason in an attached field, most people only see `Server selection timed out after 30000ms`. We will now surface the first encountered error in the set of known server descriptions as the primary error message for a timeout error. The `reason` field for server selection errors will now include the `TopologyDescription` for better traceability

NODE-2397: improve selection timeout errors

---

docs/reference/content/reference/unified-topology/index.md

Fixes typo in docs: ~psuedocode~ pseudocode

docs(reference): fix typo in unified-topology

---

lib/cmap/connection_pool.js

`setTimeout`s have a non-trivial overhead in node.  Adding one every 10ms that will ultimately result in nothing but another `setTimeout` is an unnecessary operation and takes up vital time that the event loop could otherwise use for something else.
Short circuits the `ensureMinPoolSize` function if the `minPoolSize` option is set to `0` (the default).
No

fix(connection): Do not add setTimeouts if minPoolSize is not set

---

lib/cursor.js
test/functional/cursor.test.js
test/functional/spec-runner/index.js

A recent change to allow use of `hasNext` with a cursor that is piped as a stream introduced a regression when a cursor with a limit is iterated. Until the cursor is rewritten, we will manually decrement the local `currentLimit` on calls to `hasNext`.
https://jira.mongodb.org/browse/NODE-2483

NODE-2483: cursor limit regression

---

lib/connection_string.js
test/unit/core/connection_string.test.js

We observed errors thrown from `assertTlsOptionsAreEqual()` when using a badly formed connection string, but the error message did not convey the name of the option (either `tls` or `ssl`).
A Template Literal should have been used to declare the error message, to interpolate the value of `${optionName}`.
This has been observed using mongodb@3.4.1, but the issue appears to still be present on `master`. It is a very minor issue, but figured it could be valuable to fix this nonetheless.

fix: missing optionName in MongoParseError message

---

lib/core/sdam/topology.js
test/functional/core/replset_state.test.js
test/spec/server-discovery-and-monitoring/rs/repeated.json
test/spec/server-discovery-and-monitoring/rs/repeated.yml

[NODE-2474](https://jira.mongodb.org/browse/NODE-2474) - Server_Description update with lastUpdateTime / lastWriteDate fields is ignored in topology
The SDAM spec says:
> Each time the client checks a server, it MUST replace its description of that server with a new one. This replacement MUST happen even if the new server description compares equal to the previous one, in order to keep client-tracked attributes like last update time and round trip time up to date.
This PR ensures the server description is updated even when equal.

NODE-2474: update equal server description

---

docs/reference/content/tutorials/aggregation.md
docs/reference/content/tutorials/collations.md
lib/collection.js
lib/db.js
lib/gridfs/grid_store.js
test/functional/aggregation.test.js
test/functional/cursor.test.js
test/functional/document_validation.test.js
test/functional/find.test.js
test/functional/operation_example.test.js
test/functional/raw.test.js
test/functional/readpreference.test.js

Functions returning `cursor` should not return them within callback.
* Removes callback for `collection.aggregate`
* Removes callback for `db.aggregate`
* Removes callback fro `collection.find`
No
Jira Ticket https://jira.mongodb.org/browse/NODE-2074

Node 2074/aggregate callback

---

lib/core/sdam/topology.js
test/unit/cmap/connection.test.js
test/unit/sdam/topology.test.js

In certain failover events, multiple entities may signal that the
server selection queue should be processed. This is problematic
because the queue is processed serially per invocation, even though
the queue may grow during processing. Likely a more robust solution
is required in the future, but for now we can prevent issues by
ensuring the loop breaks if no more wait queue members are present.
NODE-2472

NODE-2472: double wait queue drain regression

---

lib/collection.js

NODE-2322
Previously, would console.warn if callback to findOne was a bad type, now it will throw a TypeError.
~~**Are there any files to ignore?**~~

refactor: throw if 3rd arg to findOne passed but not callback

---

lib/core/cursor.js
lib/cursor.js
test/functional/cursor.test.js

A regression in merging the core cursor into the native codebase
resultied in a document transform (set with the `.map` helper) to
be applied to incoming documents twice.
NODE-2503

fix(cursor): transforms should only be applied once to documents

---

package-lock.json
test/examples/update_documents.js
test/functional/document_validation.test.js

https://jira.mongodb.org/browse/NODE-2502
Removed update operators from usages of replaceOne

NODE-2502/replaceOne example uses update Operators

---

lib/collection.js

https://jira.mongodb.org/browse/NODE-2416
Fix an error in the docs for the aggregate op on a collection. Specifically the collation options did not have the correct text.

NODE-2416/Confusing documentation for collection.aggregate collation option

---

lib/read_preference.js
test/functional/readpreference.test.js

lib/core/topologies/read_preference.js: TODO(major): tags MUST be an array of tagsets
NODE-2323
Previously if a non-array was passed in, it would implicitly be converted into a 1-element array containing that value.
Now it will throw a TypeError.
~~**Are there any files to ignore?**~~

refactor: read pref tags must be array

---

package-lock.json
package.json
test/functional/client_side_encryption/corpus.test.js
test/functional/client_side_encryption/driver.test.js
test/functional/client_side_encryption/prose.test.js
test/functional/client_side_encryption/spec.test.js

Most notably we are now skipping `symbol` tests because BSONv4
promotes them to string when `promoteValues: true` (the default).
Since this is a deprecated type, there is less concern that this
will be an issue for users.
NODE-2517

test: correct CSFLE tests to work with BSONv4 changes

---

lib/core/sessions.js
test/functional/transactions.test.js

See: Automattic/mongoose#8637 . The issue is that if you do session.withTransaction(() => Promise.reject()), you get a TypeError: Cannot read property 'code' of undefined error.
Re: #2252, just against 3.5 branch so it can land in 3.5.6.
One liner checking for null
Nope

fix(sessions): don't throw if `withTransaction()` callback rejects with a null reason

---

lib/operations/create_collection.js
test/examples/change_streams.js
test/functional/collection.test.js
test/functional/cursor.test.js
test/functional/find.test.js
test/functional/mapreduce.test.js
test/functional/multiple_db.test.js
test/functional/operation_promises_example.test.js
test/functional/readconcern.test.js
test/unit/db_list_collections.test.js

Our `createCollection` helper attempts to be too helpful. It will
run a `listCollections` before attempting to send the `create`
command to the server, and if a collection with the same name is
present it will skip creating the collection and return a local
reference to the collection. This is dangerous because there is
no way to strictly verify that the remote collection has all the
same options a user is passing into the helper
NODE-2537

fix: createCollection only uses listCollections in strict mode

---

lib/core/uri_parser.js
test/spec/uri-options/read-preference-options.json
test/spec/uri-options/read-preference-options.yml

ReadPreference tags must be an array in order for matching to
succeed during server selection. If a single value is entered for
the `readPreferenceTags` uri option, it should be parsed as an
array of size one.
NODE-2541

fix: single `readPreferenceTags` should be parsed as an array

---

lib/collection.js

Just fixing a minor typo I noticed while browsing the docs.
http://mongodb.github.io/node-mongodb-native/3.5//api/Collection.html#find shows the existing typo. This PR should remove it :smile: 
Nope!
This PR matches #2288 but is targeting the `3.5` branch instead of `master`.

docs: Fix typo in Collection#find param

---

test/functional/db.test.js
test/functional/operation_example.test.js

`reIndex` commands should only be run against standalone servers.
Remove `replicaset` topology from tests running the `reIndex` command.

test: remove replicaset reIndex tests

---

test/functional/db.test.js
test/functional/operation_example.test.js

`reIndex` commands should only be run against standalone servers.
Remove `replicaset` topology from tests running the `reIndex` command.

test: remove replicaset topology from reIndex tests

---

test/unit/core/write_concern_error.test.js

[NODE-2506](https://jira.mongodb.org/browse/NODE-2506)
Added test to see if entire `writeConcernError` is propagated in the mocks.

Node 2506/3.6/write concern error propagate

---

lib/core/cursor.js
lib/core/error.js
lib/core/index.js
lib/error.js
test/functional/change_stream.test.js

The `isResumableError` function should not check for the
`NonResumableChangeStreamError` label. Per the change streams spec,
resumability is determined by the `ResumableChangeStreamError` label
for servers >= 4.4 and the manually maintained whitelist for
servers < 4.4.
[NODE-2565](https://jira.mongodb.org/browse/NODE-2565)

fix: remove check for NonResumableChangeStreamError label

---

test/functional/gridfs.test.js

I created a test to ensure driver doesn't fail when creating an index with:
```js
db.collection('fs.files').createIndex({ filename: 1, uploadDate: 1 })
```
* https://jira.mongodb.org/browse/NODE-2429
* https://jira.mongodb.org/browse/DRIVERS-789

Node 2429/3.6/gridfs support indexes

---

lib/core/sessions.js

Server sessions are no longer acquired at `ClientSession` instantiation, but rather lazily created at the first access of the `serverSession` property. This has the effect of deferring the acquisition to command construction, after a connection has been checked out during operation execution.
NODE-2552

fix: limit growth of server sessions through lazy acquisition

---

lib/core/sdam/server.js
lib/core/sdam/server_description.js
lib/core/sdam/topology.js
test/functional/core/replset_state.test.js
test/spec/server-discovery-and-monitoring/README.rst
test/spec/server-discovery-and-monitoring/rs/topology_version_equal.json
test/spec/server-discovery-and-monitoring/rs/topology_version_equal.yml
test/spec/server-discovery-and-monitoring/rs/topology_version_greater.json
test/spec/server-discovery-and-monitoring/rs/topology_version_greater.yml
test/spec/server-discovery-and-monitoring/rs/topology_version_less.json
test/spec/server-discovery-and-monitoring/rs/topology_version_less.yml

This change introduces support for a `topologyVersion` field on monitoring responses. If this field is present, it will be used to determine if incoming monitoring responses are out of date, in which case the driver will not use the response to update the local topology information.
NODE-2559

feat(sdam): ignore stale topology updates

---

lib/collection.js

[NODE-2546](https://jira.mongodb.org/browse/NODE-2546)
`Collection.geoHaystackSearch` was deprecated.

feat(geoHaystackSearch): deprecate geoHaystackSearch

---

package.json

`prebuild-install`, which no longer supports node v4, updated major versions on several dependencies in a patch release that were breaking for node v4. This PR updates `snappy` to a version that corrects this issue by pinning to the version of `prebuild-install` before the compatibility issue.

chore: update snappy version to fix issue with node v4

---

docs/reference/content/tutorials/gridfs/streaming.md

fix: event names in gridFS tutorial

fix event names in gridFS tutorial

---

docs/guide/installation-guide.txt
lib/cmap/auth/scram.js
lib/cmap/commands.js
lib/gridfs-stream/upload.js
package.json
test/disabled/server.test.js
test/functional/cursorstream.test.js
test/functional/find.test.js
test/functional/gridfs_stream.test.js
test/functional/insert.test.js
test/functional/promote_buffers.test.js
test/unit/core/common.js
test/unit/core/scram_iterations.test.js

`safe-buffer` [does nothing](https://github.com/feross/safe-buffer/blob/7d544741d5a360613abb0d47926e107722fae723/index.js#L11) when native `Buffer.from` API is available and it's available since Nodes.JS 5.10 (https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_array), so, there is no sense to bring it as production dependency (one of four) when your declared minimum supported Node.JS version is 10.x (in `master`).

chore: remove safe-buffer dependency

---

lib/core/auth/auth_provider.js
lib/core/auth/gssapi.js
lib/core/auth/mongocr.js
lib/core/auth/mongodb_aws.js
lib/core/auth/plain.js
lib/core/auth/scram.js
lib/core/auth/x509.js
lib/core/connection/connect.js
test/functional/scram_sha_256.test.js

MongoDB 4.4+ supports speculative authentication for the SCRAM-SHA and X509 auth mechanisms, which means that these mechanisms can include the first part of their auth 
conversation in the initial ismaster, potentially reducing one round trip.
The majority of the work here can be summed up in the following points:
- A `prepare` step was added to `AuthProvider` which allows a provider to manipulate the handshake document before the initial handshake
- An `AuthContext` was introduced to carry methods like `connection`, `credentials` and optionally information a mechanism might need to share between steps of an auth conversation. Currently the only piece of context tracked is the `nonce` generated for SCRAM-SHA. 
None

NODE-2487: introduce speculative authentication

---

test/unit/core/write_concern_error.test.js

Adds test to check if "errInfo" writeConcernError values are being propagated values like w, wtimeout, and provenance.
NODE-2506

test: add writeConcernError propagate

---

lib/change_stream.js
test/functional/change_stream.test.js
test/functional/shared.js

[NODE-2598](https://jira.mongodb.org/browse/NODE-2598)
- Refactor `close` to use `maybePromise` helper
- Ensure explicitly closed change streams don't process further changes
- Fix broken `mid-close` tests by delaying the final write
- Add `waitForStarted` helper to tests where appropriate to reduce flakiness

refactor(ChangeStream): use maybePromise for close, improve tests

---

lib/operations/connect.js
test/functional/shared.js
test/functional/write_concern.test.js

Ensure the journal option returned by parseQueryString is converted
into j during the connect operation. This fixes the issue of the
write concern not being set on commands where journal is only
specified in the connection string.
NODE-2422

fix: honor journal=true in connection string

---

.evergreen/install-dependencies.sh
package.json
test/functional/change_stream.test.js
test/functional/index.test.js
test/functional/logger.test.js
test/functional/shared.js
test/functional/shared.test.js

[NODE-2605](https://jira.mongodb.org/browse/NODE-2605)
- remove `withTempDb`
- make `client` argument of `withClient` optional
- move unexported top-level function `makeCleanupFn` into `withClient`
- remove `connectToDb` helper
-  add filter function to `filterForCommands`/`filterOutCommands`/`withMonitoredClient`
- alphabetize helpers in `shared.js`
Also introduced some CI-related cleanup:
- output `eslint` version before linting
- upgrade `nvm` and use `--no-progress` option to clean up log output

test: improve shared helpers

---

lib/collection.js
lib/core/sdam/common.js
lib/operations/re_index.js

The `collection.reIndex` helper has been deprecated, and will be removed
in the next major version. It is also now only supported on standalone 
servers.
[NODE-2560](https://jira.mongodb.org/browse/NODE-2560)

feat(reIndex): deprecate and make standalone-only command

---

lib/change_stream.js
test/functional/change_stream.test.js
test/functional/shared.js

Introduced `getCursor` method to safely provide a change stream cursor
for `next`/`hasNext` across recoveries from resumable errors.
[NODE-2548](https://jira.mongodb.org/browse/NODE-2548)
- `next` and `hasNext` now use `getCursor`
- `processError` was extracted from `processNewChange`
- added `withCursor` shared test helper

fix(ChangeStream): should resume from errors when iterating

---

lib/core/sdam/server_selection.js
test/spec/max-staleness/Unknown/SmallMaxStaleness.json
test/spec/max-staleness/Unknown/SmallMaxStaleness.yml
test/spec/server-selection/server_selection/ReplicaSetWithPrimary/read/Nearest.json
test/spec/server-selection/server_selection/ReplicaSetWithPrimary/read/Nearest.yml
test/spec/server-selection/server_selection/ReplicaSetWithPrimary/read/Secondary.json
test/spec/server-selection/server_selection/ReplicaSetWithPrimary/read/Secondary.yml

In order to accurately reduce the set of viable servers for server selection, we need to filter the set by the read preference BEFORE we reduce by max staleness, tagSet and latency window.
NODE-2407

fix: filter servers before applying reducers

---

lib/bulk/unordered.js
test/functional/bulk.test.js

When an unordered bulk operation is executed, it should attempt to
execute all batches and only return errors after all batches have
been attempted
NODE-2619

fix: unordered bulk write should attempt to execute all batches

---

test/examples/transactions.js

[NODE-2516](https://jira.mongodb.org/browse/NODE-2516)
```
docs: update comment in transactions 
Removes "CRUD operations in transactions must be on existing collections." part of comment.
NODE-2516
```

[NODE-2516] docs: update comment in transactions (3.6)

---

lib/cmap/wire_protocol/command.js
lib/collection.js
lib/db.js
lib/operations/collection_ops.js
lib/operations/command.js
lib/operations/command_v2.js
lib/operations/db_ops.js
lib/operations/find.js
lib/operations/map_reduce.js
lib/read_preference.js
lib/sdam/topology.js
lib/topologies/topology_base.js
lib/utils.js

Wondering what people's thoughts are about being more DRY and centralizing the readPreference creation to the ReadPreference class.
```
refactor: consolidate read-preference creation
Centralizes `ReadPreference` "translation" and "resolution" to `ReadPreference` class. Removes duplicate code from `utils` and `topology`.
NODE-2566
```
[Reasoning in ticket here.](https://jira.mongodb.org/browse/NODE-2566?focusedCommentId=3092955&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3092955)

[NODE-2566] refactor: consolidate read-preference creation (master)

---

test/unit/sdam/spec.test.js

Commit Message:
```
test: sdam spec test typo property "compatible"
Fixes sdam spec test typo property "compatible"
NODE-2616
```
[NODE-2616](https://jira.mongodb.org/browse/NODE-2616)

[NODE-2616] test: sdam spec test typo property "compatible" (3.6)

---

test/examples/transactions.js

[NODE-2516](https://jira.mongodb.org/browse/NODE-2516)
```
docs: update comment in transactions 
Removes "CRUD operations in transactions must be on existing collections." part of comment.
NODE-2516
```

[NODE-2516] docs: update comment in transactions (master)

---

lib/change_stream.js
test/functional/shared.js
test/unit/sdam/spec.test.js

Commit Message:
```
test: sdam spec test typo property "compatible"
Fixes sdam spec test typo property "compatible"
NODE-2616
```
[NODE-2616](https://jira.mongodb.org/browse/NODE-2616)

[NODE-2616] test: sdam spec test typo property "compatible" (master) 

---

lib/bulk/common.js
lib/core/error.js
test/functional/bulk.test.js

We special case situations where there is only one error returned from a bulk operation, but that can be quite confusing for users of the bulk API. Promoting the single error to the top-level error message is reasonable, but in all cases we should use a consistent shape, and return `writeErrors` as a field on the object
NODE-2625

fix: always include `writeErrors` on a `BulkWriteError` instance

---

lib/cmap/connection_pool.js
test/unit/cmap/connection_pool.test.js

Each time the wait queue in the connection pool is processed it is currently gated by having available connections. This can result in a memory leak where many wait queue members are cancelled, but the pool is unable to clear them out before all connections are used for new operations.
NODE-2413

fix: always clear cancelled wait queue members during processing

---

lib/core/cursor.js
lib/cursor.js
lib/operations/cursor_ops.js

This is a fix and a refator, which ensures that implicit sessions are ended as soon as possible when cursor commands are executed. The current code path calls `_endSessions` in a confusing number of locations, and in some cases can accidentally call the method twice in a row. Reducing the number of calls to the method, and ensuring its called only after server command responses and the `close` method should prevent these errors
NODE-2630

fix: ensure implicit sessions are ended consistently

---

lib/sdam/server_description.js
lib/sdam/topology_description.js
test/spec/server-discovery-and-monitoring/README.rst
test/spec/server-discovery-and-monitoring/single/direct_connection_wrong_set_name.json
test/spec/server-discovery-and-monitoring/single/direct_connection_wrong_set_name.yml

[NODE-2564](https://jira.mongodb.org/browse/NODE-2564)
```
fix: clarify handle wrong set name single topology
Adds check to see if topologyDescription setName matches the serverDescription setName. In instances where they don't match, sets serverDescription type to Unknown. Incorporates spec tests from SPEC-1656 (bc864e6f9ccbdd162658cfbc08bfb1cb713143c5).
NODE-2564
```

[NODE-2564] fix: clarify handle wrong set name single topology (master)

---

lib/operations/find.js
test/spec/crud/README.rst
test/spec/crud/v2/find-allowdiskuse-clientError.json
test/spec/crud/v2/find-allowdiskuse-clientError.yml
test/spec/crud/v2/find-allowdiskuse-serverError.json
test/spec/crud/v2/find-allowdiskuse-serverError.yml

fix: throw an error if `allowDiskUse` is used on MongoDB < 3.2

---

lib/core/sdam/server.js
test/functional/core/operations.test.js
test/spec/transactions/README.rst
test/spec/transactions/error-labels.json
test/spec/transactions/error-labels.yml

Unless a write command is `commitTransaction` or `abortTransaction` it should not receive a `RetryableWriteError` label on command failure.
NODE-2594

fix: writes within transactions are not retryable

---

lib/change_stream.js
lib/cmap/connection.js
lib/core/connection/apm.js
lib/core/connection/pool.js
lib/core/sdam/monitor.js
lib/core/sdam/server_description.js
lib/core/sessions.js
lib/core/topologies/replset.js
lib/core/utils.js
lib/utils.js
test/unit/core/sessions.test.js

We use `process.hrtime` a lot throughout the codebase to track durations for certain operations, often storing the result of it on an object and using it later for duration calculation. This patch changes that to depend on numbers rather than hrtime, which would make it easy in the future to use something like `performance.now` or even degrade into `Date.now` in environments which don't support hi-res timers.
NODE-2651

refactor: use common methods for duration calculations

---

lib/gridfs-stream/download.js
test/functional/gridfs_stream.test.js

Errors related to handling the start/end options for `createDownloadStream`
did not propagate correctly.
[NODE-2623](https://jira.mongodb.org/browse/NODE-2623)

fix(GridFS): emit error on bad options

---

lib/operations/create_indexes.js

Added `bucketSize` to the list of valid options for indexes, because geoHaystack indexes require `bucketSize`: https://docs.mongodb.com/manual/tutorial/build-a-geohaystack-index/#geospatial-indexes-haystack-index
Nope

fix(create_indexes): add missing `bucketSize` option to list of valid options

---

lib/change_stream.js
lib/core/cursor.js
test/functional/change_stream.test.js

A notified cursor triggers a `null` change, which caused an exception
to be thrown. This PR implements graceful handling of such `null`
changes.
[NODE-2626](https://jira.mongodb.org/browse/NODE-2626)

fix(ChangeStream): handle null changes

---

package-lock.json
package.json
tsconfig.json

The `typescript-cached-transpile` module implements the type of caching that will soon be reintroduced to `ts-node`. It caches the result of transpilation, significantly improving test runs after the initial transpilation.
NODE-2690

test: add caching for our TypeScript transpiling

---

lib/core/sdam/monitor.js

When a failure occurs while streaming topology updates, we need to wait some time before restarting the monitoring protocol. It's
likely that if some error closed the connection, an immediate attempt to reconnect will also fail, leading to tight failure loops.
NODE-2711

fix: don't immediately schedule monitoring after streaming failure

---

package.json

This is required for the `drivers-atlas-testing` integration , and should prove useful generally (e.g. when users are attempting to `npm link` the module).

chore: change prepublishOnly package.json script to prepare

---

src/sdam/monitor.ts
src/sdam/server.ts
src/sdam/server_description.ts
test/unit/sdam/monitoring.test.js
test/unit/sdam/server_description.test.js

https://jira.mongodb.org/browse/NODE-2671
Both server class and monitoring class split the address string on `:` and assumed it would return address and port tuple. To handle IPv6 addresses we need to use the number at the end of the address and keep the ipv6 address from being split. I consolidated the logic into ServerDescription getters.

NODE-2671: IPv6 is not supported when using dns service discovering

---

docs/reference/content/tutorials/crud.md

Update link about `Cursor API documentation` in
https://github.com/mongodb/node-mongodb-native/edit/master/docs/reference/content/tutorials/crud.md
From:
[Cursor API documentation](/node-mongodb-native/2.0/api/Cursor.html)
To:
[Cursor API documentation](/node-mongodb-native/3.4/api/Cursor.html)
In:
https://github.com/mongodb/node-mongodb-native/edit/master/docs/reference/content/tutorials/crud.md
No

Update doc link version

---

docs/reference/config.toml
docs/reference/layouts/partials/header.html
docs/reference/layouts/partials/new_version.html

DOCSP-9667: add link to new reference docs 3.6

---

docs/reference/config.toml
docs/reference/layouts/partials/header.html
docs/reference/layouts/partials/new_version.html

DOCSP-9667: add link to new reference docs 2.2

---

docs/reference/config.toml
docs/reference/layouts/partials/header.html
docs/reference/layouts/partials/new_version.html

DOCSP-9667: add link to new reference docs 3.0

---

docs/reference/config.toml
docs/reference/layouts/partials/header.html
docs/reference/layouts/partials/new_version.html

DOCSP-9667: add link to new reference docs 3.1

---

docs/reference/config.toml
docs/reference/layouts/partials/header.html
docs/reference/layouts/partials/new_version.html

DOCSP-9667: add link to new reference docs 3.2

---

docs/reference/config.toml
docs/reference/layouts/partials/header.html
docs/reference/layouts/partials/new_version.html

DOCSP-9667: add link to new reference docs 3.3

---

docs/reference/config.toml
docs/reference/layouts/partials/header.html
docs/reference/layouts/partials/new_version.html

DOCSP-9667: add link to new reference docs 3.4

---

docs/reference/config.toml
docs/reference/layouts/partials/header.html
docs/reference/layouts/partials/new_version.html

DOCSP-9667: add link to new reference docs 3.5

---

test/spec/server-discovery-and-monitoring/integration/connectTimeoutMS.json
test/spec/server-discovery-and-monitoring/integration/connectTimeoutMS.yml

[NODE-2661](https://jira.mongodb.org/browse/NODE-2661)
Note: the new spec test passes without any code change. From [net.Socket documentation](https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback):
> If timeout is `0`, then the existing idle timeout is disabled.
Since `connectTimeoutMS` is used for the timeout when attempting initial establishment (without addition of `maxAwaitTimeMS`), this behavior is already correct.

chore: sync connectTimeoutMS SDAM spec test

---

test/functional/connections_stepdown.test.js
test/functional/spec-runner/context.js
test/spec/server-discovery-and-monitoring/integration/rediscover-quickly-after-step-down.json
test/spec/server-discovery-and-monitoring/integration/rediscover-quickly-after-step-down.yml

[NODE-2659](https://jira.mongodb.org/browse/NODE-2659)

test: avoid unable to acquire lock errors on primary stepdown

---

README.md

Now that the driver doesn't use mongodb-core anymore under the hood, I think it's worth removing it from the README.
Quick change to readme
No

docs(README): remove link to mongodb-core

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/generate_evergreen_tasks.js
.evergreen/run-tests.sh
.evergreen/run-tls-tests.sh
package.json
test/manual/tls_support.test.js
test/spec/apm/updateOne.json

[NODE-877](https://jira.mongodb.org/browse/NODE-877)
port to `3.6`

chore(ci): add tls support test to evergreen

---

src/collection.ts
src/cursor/command_cursor.ts
src/cursor/core_cursor.ts
src/cursor/cursor.ts
src/operations/command.ts
src/operations/operation.ts
src/operations/run_command.ts
src/sdam/topology.ts
test/functional/core/cursor.test.js
test/functional/core/extend_cursor.test.js
test/functional/core/tailable_cursor.test.js
test/functional/core/undefined.test.js

We no longer need to support construction of cursors without an operation, so we can remove the logic in the constructor to check for whether one was passed in or not.
NODE-2763

refactor: remove legacy cursor construction

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/generate_evergreen_tasks.js
lib/cmap/connection.js
package.json
test/manual/kerberos.test.js

Also runs the `auth-kerberos` evergreen tests on `legacy` and `unified` topologies.
[NODE-2731](https://jira.mongodb.org/browse/NODE-2731)

fix: add host/port to cmap connection

---

package.json
src/bulk/common.ts
src/bulk/ordered.ts
src/bulk/unordered.ts
src/collection.ts
src/index.ts
src/operations/bulk_write.ts
src/operations/delete.ts
src/operations/insert.ts
src/operations/insert_many.ts
src/operations/update.ts

This work reduces some of the complexity of typing the bulk API by removing tricky patterns, reducing the number of helper methods and refactoring to improve readability:
- `addToOperationsList` is now an abstract method on the base `BulkOperationBase` class
- `finalOptionsHandler` is removed, improving readability of the `executeCommands` function
- typedoc errors were resolved
- `BulkWriteOptions` were introduced and reused throughout the rest of the public API
NODE-2786
**NOTE:** This does not touch the public api for bulk at all, and as a result a number of `any` types are left in. That will be completed in a subsequent PR

refactor: clean up bulk operations for easier typing

---

src/bulk/common.ts
src/bulk/ordered.ts
src/bulk/unordered.ts
src/collection.ts
src/index.ts
src/operations/bulk_write.ts
src/operations/insert_many.ts
test/functional/collations.test.js
test/functional/crud_api.test.js

The primary focus of this patch is to provide correct types for the top-level API for the Bulk API. Specifically, type information for write models, as well as bulk write operations were added as well as formal models for "update" and "delete" statements as defined and supported by the "update" and "delete" commands.
NODE-2786

refactor: add complete type information to the bulk API

---

lib/core/auth/gssapi.js

refactor(kerberos): move MongoAuthProcess into driver

---

package-lock.json
package.json

According to this [CVE](https://github.com/advisories/GHSA-pp7h-53gx-mx7r) there is buffer over-read vulnerability in bl < 2.2.1.
updated bl to version 2.2.1

updated bl version because of CVE-2020-8244

---

lib/cmap/connection_pool.js
lib/core/cursor.js
lib/core/sessions.js
test/functional/spec-runner/index.js
test/unit/cmap/connection_pool.test.js

Running `processWaitQueue` on the next tick allows the event loop to process while the connection pool is processing large numbers of wait queue members.
NODE-2803

fix: allow event loop to process during wait queue processing

---

CONTRIBUTING.md

Describe how to get the driver dev environment up and running

docs: Adds developer setup to contributor guide

---

src/cmap/wire_protocol/command.ts
src/operations/command.ts
src/operations/execute_operation.ts
src/operations/operation.ts
src/operations/run_command.ts
src/sdam/topology.ts
src/sessions.ts
test/functional/core/cursor.test.js
test/functional/core/shared.js
test/functional/core/tailable_cursor.test.js
test/unit/core/write_concern_error.test.js
test/unit/sdam/topology.test.js

This is a minor refactoring that ensures that wire protocol primitives are only available on the `Server` type. The primary benefit here is that we no longer hide any server selection behind `Topology` API, all commands issued are always the result of server selection and a command being executed against a specific server.
NODE-2801

refactor: remove Topology#command method

---

src/bson.ts
src/cmap/wire_protocol/get_more.ts
src/cmap/wire_protocol/query.ts
src/cmap/wire_protocol/shared.ts
src/collection.ts
src/cursor/core_cursor.ts
src/cursor/cursor.ts
src/operations/create_collection.ts
src/operations/find.ts
src/operations/operation.ts
src/utils.ts
test/functional/collations.test.js
test/functional/collection.test.js
test/functional/find.test.js

The primary work of this ticket was to make the `Collection#find` method behave like other read operations by moving the command construction to the `FindOperation` itself. Along the way a number of improvements were made:
- cursors now know they are tailable and/or awaitData upon construction, rather than observing the internal `cmd` they are built around. As much as possible the cursor implementation now no longer alters behavior after initialization based on what is in the internal `cmd` document
- a number of supported, but undocumented options were added to the `find` method itself
- `bsonOptions` were introduced to the `OperationBase` class as a first step towards improving our story around overriding these values and passing them to wire protocol methods
NODE-2830

refactor: move find command building to FindOperation

---

src/utils.ts
test/unit/utils.test.js

The logic for waking the AsyncInterruptibleInterval sooner than its interval is dependent on an ability to reliably mark the last call made to the wrapped function. In environments like AWS Lambda where instances can be frozen and later thawed, it's possible for the last call to be in a distant past even though the internal timer has not completed yet. This change ensures that we immediately reschedule in these situations.
NODE-2829

fix: permit waking async interval with unreliable clocks

---

src/change_stream.ts
src/cmap/connection.ts
src/cmap/wire_protocol/get_more.ts
src/cmap/wire_protocol/kill_cursors.ts
src/cmap/wire_protocol/query.ts
src/cmap/wire_protocol/shared.ts
src/cursor/core_cursor.ts
src/cursor/cursor.ts
src/index.ts
src/operations/find.ts
src/operations/indexes.ts
src/operations/list_collections.ts
src/operations/operation.ts
src/sdam/server.ts
src/sessions.ts
test/functional/aggregation.test.js
test/functional/cursor.test.js
test/functional/find.test.js
test/functional/generator_based.test.js
test/functional/operation_example.test.js
test/functional/operation_generators_example.test.js
test/functional/operation_promises_example.test.js
test/node-next/es2018/cursor_async_iterator.test.js

Cursors presently have an internal state tracking object called `cursorState` which has a high degree of coupling with multiple components in the system, and is source of great confusion and bugs. This patch removes the `cursorState` completely, mounting its relevant properties directly on the `CoreCursor` type and removing it from the signature of the `query`, `killCursors`, and `getMore` wire protocol methods.
Many changes were required as part of this refactoring, but most notable is cleanup around cursor `close`. The internal call to kill the cursor raced with the `_endsession` method, which uncovered a number of failures in our test suite when fixed.
NODE-2810
**NOTE:** this is based on #2546 , so it will appear to have the same changes until that PR is merged and this one is …

refactor: remove cursorState from Cursor and wire protcol methods

---

etc/update-spec-tests.sh
test/spec/connection-monitoring-and-pooling/pool-checkout-connection.json
test/spec/connection-monitoring-and-pooling/pool-checkout-connection.yml
test/spec/connection-monitoring-and-pooling/pool-create-min-size.json
test/spec/connection-monitoring-and-pooling/pool-create-min-size.yml
test/spec/connection-monitoring-and-pooling/wait-queue-timeout.json
test/spec/connection-monitoring-and-pooling/wait-queue-timeout.yml

Update connection-monitoring-and-pooling tests
ensuring ConnectionCreated proceed ConnectionReady events
NODE-2804
I have a spec sync script I suggest we bring in here, if anyone has a hesitation we can drop that.
There were a few formatting issues that made it to 3.6, the fixes are in here.

test: Update connection-monitoring-and-pooling specs

---

etc/update-spec-tests.sh
test/spec/connection-monitoring-and-pooling/pool-checkout-connection.json
test/spec/connection-monitoring-and-pooling/pool-checkout-connection.yml
test/spec/connection-monitoring-and-pooling/pool-create-min-size.json
test/spec/connection-monitoring-and-pooling/pool-create-min-size.yml
test/spec/connection-monitoring-and-pooling/wait-queue-timeout.json
test/spec/connection-monitoring-and-pooling/wait-queue-timeout.yml

Update connection-monitoring-and-pooling tests
ensuring ConnectionCreated proceed ConnectionReady events
Add a script for spec fetching convenience
Port of #2555 to 4.0

test: Update connection-monitoring-and-pooling specs (port to 4.0)

---

src/cmap/connect.ts
src/cmap/connection.ts
src/operations/connect.ts

Socket timeout by default should be infinity.
Removed 6min defaults.
NODE-2835

fix: Change socket timeout default to 0

---

src/mongo_client.ts
src/operations/connect.ts
test/functional/connection.test.js
test/functional/sessions.test.js

`connect` doesn't work again after `close` has been called once on a `MongoClient`.
Cleaning up some state beforehand fixes the issue.
NODE-2544

fix: allow client connect after close

---

test/functional/sharding_connection.test.js

NODE-2827
bringing in test from https://github.com/mongodb/node-mongodb-native/pull/2557

test: ensure connection with sharded topology

---

lib/change_stream.js
test/functional/change_stream.test.js

NODE-2172
I tried pretty hard to recreate this locally, and I ran into issues, I was also considering stubbing out the `#pipe` here and testing the `createChangeStreamCursor` function directly but that would mean exporting it which would make it public. I can't get this code to fire and it does not exist in master anymore. 
It does seem verifiably wrong.
```js
const x = ['pipe1', 'pipe2', 'pipe3']
> for (let pipe in x) { console.log(pipe) }
0
1
2
> for (let pipe of x) { console.log(pipe) }
pipe1
pipe2
pipe3
```

fix: correctly re-establishes pipe destinations

---

src/mongo_client.ts
src/operations/connect.ts
test/functional/connection.test.js
test/functional/sessions.test.js

This reverts commit 1aecf964d79344acea4ff4387d2faf51b78cfe78. 
This approach for allowing a client to reconnect after being closed can cause session leaks, because old topologies (and sessions) may be stored on `Db`s/`Collection`s. This ticket can be revisited after NODE-2850.

fix: revert "fix: allow client connect after close (#2581)"

---

.eslintrc.json
package-lock.json
package.json
test/functional/readpreference.test.js
test/node-next/es2018/cursor_async_iterator.test.js

NODE-2851
Removes destructuring allowing Node 4 tests. Adds lint check to prevent this from happening in the future.

test: removes destructuring and spread for Node 4 and adds lint rules

---

src/bson.ts
src/collection.ts
src/db.ts
src/mongo_client.ts
src/operations/bulk_write.ts
src/operations/command.ts
src/operations/common_functions.ts
src/operations/delete.ts
src/operations/find.ts
src/operations/find_and_modify.ts
src/operations/find_one.ts
src/operations/insert.ts
src/operations/insert_many.ts
src/operations/operation.ts
src/operations/replace_one.ts
src/operations/update.ts
src/utils.ts
test/functional/ignore_undefined.test.js
test/functional/insert.test.js
test/functional/mongo_client.test.js

Previously, each operation in `collection.ts` needed to do the necessary logic to figure out which `BSONSerializationOptions` values to include in the options. Some operations omitted this logic completely, while others did it incorrectly. This change stores the `BSONSerializationOptions` as a new inheritable property on `MongoClient`, `Db`, `Collection`, and `OperationBase`, and makes it accessible via a new `bsonOptions` getter for each class. 
NODE-1561

refactor: unify means of applying `ignoreUndefined`

---

test/functional/change_stream.test.js

Updated test from 3.6
port of https://github.com/mongodb/node-mongodb-native/pull/2582

fix: correctly re-establishes pipe destinations (master)

---

src/admin.ts
src/bson.ts
src/change_stream.ts
src/cmap/connection_pool.ts
src/collection.ts
src/cursor/cursor.ts
src/index.ts
src/operations/distinct.ts
src/operations/map_reduce.ts
src/operations/stats.ts
src/sdam/common.ts
src/sdam/topology_description.ts
src/transactions.ts
src/utils.ts

Fixes API Extractor warnings, and splits out `@public` and `@internal` one-liners, because while it's valid syntax, it's not the intended functionality, providing a string after a `@tag` becomes the "attribute" of that tag, and in these cases it's a `@description` which is the first string in the comment-doc.

chore: fix symbols & public / internal one-liners

---

src/cmap/connection_pool.ts

cmap/connection_pool
connection may be leak if waitque cancelled

fix: connection leak if waitque cancelled

---

src/operations/find_one.ts

This PR changes `FindOneOperation` so it extends `CommandOperation` instead of `OperationBase`. 
Recently, `FindOperation` was modified to extend `CommandOperation` as well, so this change is partially for symmetry and partially because it may help simplify the work required for implementing explain functionality on both operations.
NODE-2852/NODE-2853

refactor: have FindOneOperation extend CommandOperation

---

package.json

It appears that `aws4` was being required without being listed as a dependency. This results in errors when using strict package managers such as Yarn 2 (berry) and pnpm.
~~Additionally, it seems a non-standard way of requiring optional modules was being used.~~
All recent package managers support optional peer dependencies using the `peerDependenciesMeta` field:
npm as of: https://github.com/npm/cli/pull/224
Yarn 1: https://classic.yarnpkg.com/en/docs/package-json#toc-peerdependenciesmeta
Yarn 2: https://yarnpkg.com/configuration/manifest/#peerDependenciesMeta
pnpm: https://pnpm.js.org/en/package_json#peerdependenciesmeta
~~Removed `require_optional` dependency and used standard optional peer dependency definitions.~~
Added `aws4` as an optional peer dependency. See: …

fix: add optional peer dependencies (yarn2/pnpm)

---

src/bulk/common.ts
src/collection.ts
test/functional/bulk.test.js

This change extends the work from #2589 to bulk operations. The changes involved for `BulkOperationBase` parallel those for `OperationBase`: a new `bsonOptions` field was added (in `s`, so it's at the same level as `options`) with values inherited from the collection parent, it is exposed with a `bsonOptions` getter, and it is included in the options before any `executeOperation` is called.
NODE-1561

fix: apply bson options for bulk operations

---

test/functional/operation_example.test.js
test/functional/operation_generators_example.test.js
test/functional/operation_promises_example.test.js
test/functional/readconcern.test.js

This PR restricts `geoHaystack`/`geoSearch` tests to mongodb `<=4.4`, which was overlooked in NODE-2546.

test: restrict geoSearch tests to mongodb <= 4.4

---

lib/core/auth/gssapi.js

This PR fixes a bug in Kerberos authentication by moving the Kerberos
client initialization from the `AuthProvider.prepare` override into a
local `getClient` function.
NODE-2859

fix: move kerberos client setup from prepare to auth

---

lib/cmap/connection_pool.js

A performance regression was identified in switching the connection pool to using setImmediate instead of process.nextTick for wait
queue processing. This patch reverts that change.
NODE-2861

fix: revert use of setImmediate to process.nextTick

---

lib/core/auth/x509.js

I believe there should be `Object.assign` and not `Object.apply` otherwise `user` isn't added to the `command` object and authentication that requires this field fails.

fix: correctly extend the "command" object with "user"

---

src/collection.ts
src/db.ts
src/operations/command.ts
src/operations/create_collection.ts
src/operations/find.ts
src/operations/map_reduce.ts
src/operations/operation.ts
src/operations/run_command.ts
src/read_preference.ts
src/utils.ts

This PR introduces a new helper `resolveOptions` which includes the logic for inheriting some options from a parent. NOTE: It only merges in inherited properties (read/write concern, read preference, and bson options) from the parent, and does not add to or modify any other properties of options. 
Options are resolved before a command is constructed. This means the options passed to `CommandOperation` are already properly inherited, and inheritance is no longer needed in the `CommandOperation` constructor. So, we can get rid of the `NO_INHERIT_OPTIONS` aspect and simply not call `resolveOptions` before those commands. Similarly, the `ReadPreference.resolve()` function is no longer needed.
There is also a change to `ReadPreference.fromOptions()`, where if the options don't have a …

refactor: consolidate options inheritance logic 

---

test/functional/spec-runner/index.js

This fixes a regression introduced in the ADL testing patch set, where the spec test runner always skips the first `ping` command sent by a client. The `ping` should only be skipped if credentials were provided to the client, since that's when the driver actually sends the command.
NODE-2885

test: only skip initial ping command if credentials provided

---

src/bulk/common.ts
src/cmap/wire_protocol/write_command.ts
src/collection.ts
src/operations/bulk_write.ts
src/operations/command.ts
src/operations/common_functions.ts
src/operations/find_and_modify.ts
src/operations/insert.ts
src/operations/insert_many.ts
src/operations/operation.ts

This PR extends the work from #2614 to bulk operations. Now, bulk ops use `resolveOptions` to inherit options from the parent. Also, since no bson options or read preference resolving needs to be done in subclasses of `OperationBase`, assigning the `bsonOptions` and `readPreference` properties now occurs in the `OperationBase` constructor.
The changes to `find_and_modify.ts`, `insert.ts`, and `common_functions.ts` should have been done in the last PR :(
NODE-2870

refactor: consolidate options inheritance for bulk ops

---

test/tools/runner/plugins/session_leak_checker.js

Since we migrated to acquiring a server session lazily the stack traces for the sesson leak checker haven't been very helpful. This patch records the trace from the call to `Topology#startSession` in order to provide a more high quality trace.
NODE-2880

chore: capture more informative stack trace in session leak checker

---

src/cmap/wire_protocol/query.ts
src/cursor/cursor.ts
src/explain.ts
src/index.ts
src/operations/aggregate.ts
src/operations/command.ts
src/operations/find.ts
src/operations/find_one.ts
test/functional/aggregation.test.js
test/functional/explain.test.js

This PR implements explain functionality for `findOne`, `find`, and `aggregate`. 
These operations can be explained via the `explain` option introduced in #2599 or with the `explain` method on cursors, which now takes an optional `verbosity` parameter (defaults to `true` for backwards compatibility).

feat: add explain support for cursor commands 

---

src/bulk/common.ts
src/index.ts
test/functional/crud_spec.test.js

This PR makes `BulkWriteError` conform to the CRUD spec by adding the necessary fields required by the spec tests to the class and renames `BulkWriteError` to `MongoBulkWriteError`.
NODE-1989, NODE-2331

fix: make MongoBulkWriteError conform to CRUD spec

---

test/.eslintrc.json
test/functional/sharding_connection.test.js

One of our tests was using lib which stops the tests from running if you have a clean repo, this little fix changes the import and adds a linter rule to catch this for us going forward.

fix: tests using lib prohibited

---

docs/reference/content/tutorials/crud.md
docs/reference/static/js/toggle-switch.js

This PR makes ES2017 usages displayed by default.
It's 2020. `await` is [supported since Node.js v7.6.0](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await), which is released [over 3.5 years ago](https://nodejs.org/en/blog/release/v7.6.0/) (2017/02/22). Also, [93% of the browsers support `await` already](https://caniuse.com/mdn-javascript_operators_await). As a result, developers no longer need to be buried under the callback hell.

docs: Display ES2017 usage by default

---

lib/core/topologies/replset.js
lib/core/topologies/server.js
test/functional/core/rs_mocks/connection.test.js

When the legacy ReplSet and Server topology types are destroyed they transition their internal state after a potentially long async close process has completed. With the recently introduced infinite default socket timeout, we are hitting this race condition more consistently. This patch ensures the types transition their state immediately, reducing the chance that such race conditions can occur.
NODE-2916

fix: transition topology state before async calls

---

src/cursor/abstract_cursor.ts
test/functional/abstract_cursor.test.js

The default cursor iteration behavior is to block until either a cursor is dead (has a cursor id of 0), or a non-empty batch is returned from the server for a `getMore` command. `tryNext` allows users to iterate a cursor optionally returning `null` if the `getMore` returns an empty batch (likely on a tailable + awaitData cursor).
NODE-2917

feat: add an internal `tryNext` method

---

lib/admin.js
lib/bulk/common.js
lib/collection.js
lib/db.js
lib/gridfs-stream/upload.js
lib/gridfs/grid_store.js
lib/mongo_client.js
lib/operations/connect.js
lib/write_concern.js
test/functional/bulk.test.js
test/functional/write_concern.test.js
test/tools/runner/config.js

This PR is mostly documentation changes to indicate that keys `w`, `j`, `wtimeout` and `fsync` are deprecated. 
Code changes include:
- `WriteConcern.fromOptions` now warns when the options contain the top-level keys and _not_ the `writeConcern` key.
- During client creation, when creating options from a URL, the write concern options are moved under the `writeConcern` key, so that warnings are not logged later. Options passed directly to the client are also moved under the `writeConcern` key, but only after `WriteConcern.fromOptions` is called, ensuring at least one warning is logged.
- GridFS now includes `options.writeConcern`, if it exists, when getting the write concern. 
Tests now spit out a _ton_ of warns because the vast majority of tests which pass write concern options to …

feat: Deprecate top-level write concern option keys 

---

lib/aggregation_cursor.js
lib/collection.js
lib/core/sdam/topology.js
lib/core/topologies/mongos.js
lib/core/topologies/replset.js
lib/core/wireprotocol/query.js
lib/core/wireprotocol/write_command.js
lib/cursor.js
lib/db.js
lib/explain.js
lib/operations/aggregate.js
lib/operations/command_v2.js
lib/operations/common_functions.js
lib/operations/delete_many.js
lib/operations/delete_one.js
lib/operations/distinct.js
lib/operations/find.js
lib/operations/find_and_modify.js
lib/operations/find_one.js
lib/operations/map_reduce.js
lib/operations/operation.js
lib/operations/update_many.js
lib/operations/update_one.js
lib/utils.js
test/functional/aggregation.test.js
test/functional/crud_api.test.js
test/functional/explain.test.js

Port explain support to 3.6.
The logical changes are the same, but some things had to occur in different places: Since `OperationBase` is the only shared class between all of the explainable ops, the `explain` property is on `OperationBase`, and `decorateWithExplain` is used in a few more places.

feat: add explain support

---

.evergreen/config.yml
.evergreen/config.yml.in
.gitignore
README.md
lib/operations/command_v2.js
lib/operations/list_collections.js
package-lock.json
package.json
test/functional/operation_example.test.js
test/functional/operation_generators_example.test.js
test/functional/operation_promises_example.test.js
test/functional/readconcern.test.js
test/mocha.opts

Backports of #2596 and #2612 for `3.5`
Note: also fixes a failing test on the latest server to get CI passing, related to setting collation on `listCollections`.
It seems we set collation a bit too aggressively and rely on the server ignoring it where it's not supported. However, the latest server version is returning an error:
<pre><code>FAILURE: BSON field &#x27;listCollections.collation&#x27; is an unknown field. ()
MongoError: BSON field &#x27;listCollections.collation&#x27; is an unknown field.
at Connection.&#x3C;anonymous&#x3E; (lib/core/connection/pool.js:451:61)
at processMessage (lib/core/connection/connection.js:384:10)
at Socket.&#x3C;anonymous&#x3E; (lib/core/connection/connection.js:553:15)
at addChunk (_stream_readable.js:288:12)
at readableAddChunk …

chore(ci): xunit integration [3.5]

---

etc/prepare.js

This should fix the script failing to run on windows.
I had added this flag in earlier work when we wanted a more complex prepare script but we abandoned that, however we should still keep this flag to fix windows use cases.

chore: add shell flag to prepare script

---

src/sdam/monitor.ts
test/functional/mongo_client_options.test.js

This PR ensures that awaitable isMaster handshakes respect an unlimited timeout (`connectionTimeoutMS=0`) as per the [SDAM specification section on socket timeouts](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-monitoring.rst#socket-timeout):
> Clients MUST use connectTimeoutMS as the timeout for the connection handshake. When connectTimeoutMS=0, the timeout is unlimited and MUST remain unlimited for awaitable isMaster replies. Otherwise, connectTimeoutMS is non-zero and clients MUST use connectTimeoutMS + heartbeatFrequencyMS as the timeout for awaitable isMaster replies.
NODE-2874
(port of #2627 for `4.0`)

fix: awaitable isMaster timeout must respect connectTimeoutMS

---

docs/reference/content/tutorials/crud.md
src/cursor/abstract_cursor.ts
src/gridfs-stream/download.ts
src/operations/find.ts
src/read_concern.ts
test/functional/apm.test.js
test/functional/buffering_proxy.test.js
test/functional/cursor.test.js
test/functional/max_staleness.test.js
test/functional/readpreference.test.js

This patch adds a builder method to add a read concern to a cursor similar to the existing method to build with a ReadPreference. It also changes `setReadPreference` to `withReadPreference` so the two follow a common convention.
NODE-2806

feat: add `withReadConcern` builder to AbstractCursor

---

src/bulk/common.ts
test/functional/abstract_cursor.test.js
test/functional/bulk.test.js
test/functional/shared.js

An inverted boolean expression accidentally always forced the driver to force the server to generate document ids.
NODE-2923

fix: only force server id generation if requested

---

src/cmap/connection.ts
src/cmap/wire_protocol/query.ts
src/index.ts
src/operations/find.ts
src/operations/indexes.ts
src/operations/list_collections.ts
src/sdam/server.ts
test/functional/max_staleness.test.js

One of the changes made in merging the core and native drivers was to merge the wire protocol methods for executing find operations. A vestigial piece of this was that the find command was being built in the wire protocol layer, rather than the operation layer. This patch teases these two apart, so that the `query` wire protocol method only creates and executes an `OP_QUERY` message, and the modern and legacy find commands are built in the find operation's definition itself.
NODE-2900

refactor: move find command building all into the find operation

---

src/change_stream.ts
src/cursor/abstract_cursor.ts
src/cursor/aggregation_cursor.ts
src/cursor/find_cursor.ts
src/operations/indexes.ts
src/operations/list_collections.ts
test/functional/abstract_cursor.test.js
test/functional/operation_example.test.js

These two commits add back support for cloning and rewinding cursors.
The changes should be fairly straightforward, but I wanted to call out a few design decisions:
~- I had originally intended `clone` to be an abstract method on `AbstractCursor`, forcing us to implement it for all possible cursor subclasses. This would have unfortunately required us to make `AbstractCursor` generic over the subclass types, since the following signature results in type ambiguity at the point of implementation in the subclass: `abstract clone(): this`~
- Therefore, `clone` is implemented by hand in `AbstractCursor` subclasses. I only implemented it for `FindCursor` and `AggregateCursor` because it's likely that's where legacy users have actually used this feature.
- There is a correction …

feat: reintroduce clone and rewind for cursors

---

src/utils.ts

This is the solution mongosh is currently using in my fork of the driver. I don't know if you want to use this directly or some other solution. For more details see NODE-2937

fix: use require instead of readFileSync for driver.version (#2937)

---

src/bulk/common.ts
test/functional/bulk.test.js

This spec compliant behavior was lost through refactoring in recent years. We now prevent users from calling execute multiple times on a bulk operation.
NODE-2926

fix: prevent bulk operations from being executed multiple times

---

src/bulk/common.ts
src/gridfs-stream/index.ts
src/operations/common_functions.ts
src/operations/delete.ts
src/operations/insert.ts
src/operations/insert_many.ts
src/operations/replace_one.ts
src/operations/update.ts
test/functional/aggregation.test.js
test/functional/apm.test.js
test/functional/collection.test.js
test/functional/crud_api.test.js
test/functional/crud_spec.test.js
test/functional/find.test.js
test/functional/insert.test.js
test/functional/object_id.test.js
test/functional/operation_example.test.js
test/functional/operation_generators_example.test.js
test/functional/operation_promises_example.test.js
test/functional/promises_collection.test.js
test/functional/retryable_writes.test.js
test/functional/spec-runner/index.js
test/functional/uri.test.js

Our CRUD result types have been out-of-sync with the official drivers CRUD specification for some time. This patch brings them in line, and updates our tests accordingly
NODE-2936

refactor!: conform CRUD result types to specification

---

src/mongo_client.ts

Updated the Auth interface to include 'password' instead of 'pass'. I could not find any tests that depended on this, but let me know if anything else should be changed.

chore: change pass to password in Auth interface #2921

---

src/cmap/auth/scram.ts

`payload.value()` already returns a string, so calling on it `toString('base64')`
implies the signature consists of a base64 representation, but the plain string is required.
The first argument ('base64') of String.toString is dropped, so although the code works
as expected (by accident) it implies that it was desired to have a base64 there, which is wrong.
Dropped the toString() call to not confuse driver authors when they want to get inspiration
from this JS driver.

fix: SASL's signature consists of the string representation of the payload, not base64

---

src/mongo_client.ts

Caching has been removed from `MongoClient.db`.
`returnNonCachedInstance` is now the default behavior and is
no longer a supported option.
NODE-2931

refactor: remove db cache

---

package.json
src/cmap/message_stream.ts
src/index.ts
src/sdam/monitor.ts
src/utils.ts
test/unit/utils.test.js

BufferList really helped simplify a lot of code in our message stream processing, but ultimately is more powerful than we need it to be. Additionally, depending on this package makes maintenance of the driver more difficult over time. This introduces a new type called BufferList which is tailored to our particular use case.
NODE-2930

feat: introduce BufferPool to replace BufferList

---

src/bulk/common.ts
src/collection.ts
src/db.ts
src/operations/indexes.ts
test/functional/index.test.js

`CreateIndexesOperation` was returning the name of the created index
instead of the result from the server because of the logic ensuring
`CreateIndexOperation` has that behavior.
This PR makes `CreateIndexesOperation` return an *array of index names*
(breaking change), while `CreateIndexOperation` continues to return a
single index name string. This makes the behavior consistent with other
official drivers.
Users in need of the raw result from the server should use `db.command`.
NODE-2602

refactor!: CreateIndexOp returns string, CreateIndexesOp returns array

---

lib/aggregation_cursor.js

Related Issue [NODE-2895](https://jira.mongodb.org/browse/NODE-2895)
param change from number to string or object

docs: aggregation cursor wrong param for unwind

---

lib/collection.js
test/functional/find_and_modify.test.js

Honors the `ignoreUndefined` option for find-and-modify commands.
Note: this option doesn't seem to have any effect for `findOneAndDelete`
operations, but support was added because it is listed as a valid option.
NODE-2945

fix: honor ignoreUndefined on findAndModify commands

---

package.json
src/bulk/common.ts
src/change_stream.ts
src/cursor/abstract_cursor.ts
test/functional/change_stream.test.js

Exposes the `tryNext` iteration helper on cursors and change streams.
NODE-2952

fix: make tryNext and Batch public

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/generate_evergreen_tasks.js
.evergreen/install-dependencies.sh
.evergreen/run-tests.sh
test/functional/change_stream.test.js

The Continuous Matrix Testing project requires a number of changes to our test infrastructure.
This PR:
- prevents testing node versions after carbon on vs2013, which they don't support 
- fixes a flaky change stream test which could sometimes produce invalid JSON and then attempt to parse it 
- adds `SKIP_DEPS` flag to `run-tests.sh` 
- if this flag is missing, automatically run `install-dependencies.sh` (for matrix tests)
- adds `SKIP_DEPS=1` to `run tests` Evergreen function, preserving old behavior
- adds `NO_EXIT` flag to `run-tests.sh`
- if this flag is missing, automatically exit early from test runs that leak resources (for matrix tests)
- adds `NO_EXIT=1` to `run tests` Evergreen function, preserving old behavior
NODE-2914

chore(ci): continuous matrix integration [3.6]

---

src/cmap/connect.ts

This made it passed testing because if maxWireVersion is a number then so is min and the actual 'less than' comparison is correct.

fix: correct typeof check in checkSupportedServer

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/install-dependencies.sh
.evergreen/run-tests.sh
.gitignore
COMPATIBILITY.md
README.md
package-lock.json
package.json
test/core/functional/rs_mocks/add_remove_tests.js
test/core/functional/rs_mocks/connection_tests.js
test/functional/collations_tests.js
test/functional/connection_tests.js
test/functional/cursor_tests.js
test/functional/db_tests.js
test/functional/find_tests.js
test/functional/gridfs_tests.js
test/functional/index_tests.js
test/functional/mapreduce_tests.js
test/functional/mongo_client_tests.js
test/functional/operation_example_tests.js
test/functional/operation_generators_example_tests.js
test/functional/operation_promises_example_tests.js
test/functional/readconcern_tests.js
test/mocha.opts

The Continuous Matrix Testing project requires updates to some driver versions which are no longer maintained.
This PR for the `3.3` branch allows testing the Node driver released to support MongoDB 4.2.
port of #2667
[patch build](https://spruce.mongodb.com/version/5fe10b073066155bd25aa86e/tasks?page=0&taskName=4.2-era-driver)
- enables xunit reporting
- fixes testing on windows
- adds `COMPATIBILITY.md` and skips incompatible tests
NODE-2914

chore(ci): continuous matrix integration [3.3]

---

src/bulk/common.ts
test/functional/bulk.test.js

Update tests to assert TypeError is used for this API misuse
NODE-2961

refactor!: Clarify empty BulkOperation error message

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/generate_evergreen_tasks.js
.evergreen/run-mongosh-integration-tests.sh

This is part of NODE-2940 (it doesn’t address Compass integration, because I don’t know what that would even look like given the many, many packages that make up Compass).
--- 
Add a mongosh integration test task to evergreen. This currently passes CI, but could fail if more breaking changes are being added. I’m doing my best to keep up with all driver changes, but we still have to adjust our code on a regular basis to changes being made to the master branch here – if you want to avoid this task failing occasionally, you can of course wait until the actual 4.0 release (or until all planned breaking changes are done).

feat(ci): add mongosh integration testing

---

test/functional/bulk.test.js

This adds tests to ensure ordered and unordered bulk operations respect the max bson size and split into batches. The previous tests were only testing splitting in to batches based on the number of documents in the batch.
Added 2 tests in `bulk.test.js`.

HELP-21340: Adding Tests For Max BSON Size Batching

---

src/connection_string.ts
src/mongo_client.ts
test/functional/write_concern.test.js

This reverts a change that now makes it possible to pass a
writeConcern option that maps directly to 'majority'
or a number for the w value
NODE-2836

fix: ingest WC as a simple object or number for w value

---

src/index.ts

Good news! Our mongosh early warning system works!
Looks like I dropped the Map export from BSON by mistake, here's the fix.

fix: revert BSON Map export removal

---

lib/utils.js
test/functional/bulk.test.js
test/unit/utils.test.js

Certain documents cannot contain atomic operators
i.e. keys with a leading dollar sign, documents can contain
toBSON transformation functions that would modify such keys the check
now respect the transformation
NODE-2741

fix: hasAtomicOperator check respects toBSON transformation

---

src/deps.ts

This updates the type definition of the `AutoEncryptionOptions` to support GCP and Azure KMS providers. This is in line with https://github.com/mongodb/libmongocrypt/pull/154.
_None_

chore: update AutoEncryptionOptions with GCP and Azure MONGOSH-527

---

lib/collection.js
test/functional/find.test.js

The find command's `timeout` option was incorrectly being translated
into `noCursorTimeout`, this has been corrected to be `!timeout`.
NODE-2828

fix(find): correctly translate timeout option into noCursorTimeout

---

.evergreen/config.yml
.evergreen/config.yml.in

After https://github.com/mongodb-js/mongosh/commit/be303719f53726ed3cb55fe0087d3a49645e6488
we are temporarily relying on the `DISTRO_ID` evergreen expansion to
figure out which mongod server package to download.
Sorry for causing trouble!

chore(ci): fix mongosh integration

---

src/connection_string.ts
src/operations/connect.ts

See the ticket description in NODE-3042 for details.

fix: restore `createAutoEncrypter()` functionality

---

lib/operations/connect.js
test/functional/readpreference.test.js
test/functional/write_concern.test.js

fix: respect readPreference and writeConcern from connection string

---

test/functional/readpreference.test.js
test/functional/write_concern.test.js

Note: this bug was already fixed by the options work in 4.0, so I'm just adding the new tests from #2711 for consistency.
NODE-2965

test: ensure readPreference and writeConcern are honored in uri

---

src/collection.ts
src/connection_string.ts
src/operations/connect.ts
test/tools/runner/config.js

Permits legacy options being used by mongodb-client-encryption's
use of the MongoClient constructor. Permits legacy WC option style in
insertOne.
NODE-3006
[CSFLE Tests Patch](https://spruce.mongodb.com/task/mongo_node_driver_ubuntu_18.04_erbium_test_4.2_replica_set_patch_25ef87026bca935b00d30ad943ddd28784f801e8_600b33953627e07e4a808b81_21_01_22_20_20_38/tests?execution=0&page=0&testname=Client_Side_Encryption)

fix: Compatibility with mongodb-client-encryption

---

package-lock.json
test/functional/change_stream.test.js
test/functional/unified-spec-runner/entities.ts
test/functional/unified-spec-runner/match.ts
test/functional/unified-spec-runner/operations.ts
test/functional/unified-spec-runner/schema.ts
test/functional/unified-spec-runner/unified-utils.ts
test/functional/unified-spec-runner/unified.test.ts
test/tools/runner/config.js
test/tools/utils.js

Adds special operations support i.e. $$unsetOrMatches for testing
nested schema equality of results and events. Adds Recursive
equality test that tracks the path into the object it is testing
for ease of error tracing. Enable Change Stream tests with the
repurposed EventsCollector class to iterate change events. Adds
find, insertMany, iterateUntilDocumentOrError, and failPoint operations.
NODE-2287

test: Complete all matching operations

---

src/bulk/common.ts
test/functional/insert.test.js

Adds getters so that mergeBatchResults changes are reflected in wrapper
classes.
NODE-3055
Came across this bug while working on unified tests, these properties are new in 4.0 so this doesn't need a backport.

fix: Use getters to sync BulkWriteResult wrappers

---

lib/core/cursor.js

Fixes NODE-3008.
Please refer to NODE-3008 for more details.
I can try to write a test for this bug if someone give me a hint on an example of such tests.
Also we should check if this should be ported to v4.x

fix(cursor): don't use other operation's session for cloned cursor operation (NODE-3008)

---

src/sdam/topology.ts
test/unit/legacy_compat.test.js

This addresses an incompatibility with the existing versions of
mongodb-client-encryption which falls back on the bson library
being attached to the topology class.
NODE-3041

fix: Support bson property on Topology class

---

src/write_concern.ts

If you call `createCollection()` with `null` for options, you get a "Cannot read property 'writeConcern' of null" error. Not a problem in TypeScript because technically this function doesn't accept `null` as a parameter, but might be worth fixing in case JS developers run into it.

fix(write_concern): avoid throwing error when `options` is null

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-tls-tests.sh
test/manual/tls_support.test.js

Port of #2718, the bug was already fixed so this PR only includes CI updates and the new test.
NODE-2977

chore(ci): enable tls testing on windows

---

package-lock.json
test/functional/unified-spec-runner/match.ts
test/functional/unified-spec-runner/operations.ts
test/functional/unified-spec-runner/schema.ts

Operations needed for Versioned API.

test: Operations needed for versioned API tests

---

lib/core/uri_parser.js
test/functional/bulk.test.js
test/functional/mongo_client_options.test.js
test/functional/sharding_connection.test.js

We removed automatic direct connection for the unified topology in the `3.6.3` release of the driver. This change was preparatory for the `4.0` version of the driver, where we'll always perform automatic discovery. This PR restores automatic direct connection when connecting to a single host without a specified `replicaSet` and without `directConnection: false`. 
In #2557 this was justified because `useUnifiedTopology: true` is an opt-in feature, but we've had a number of users file tickets about this change, and it's probably more appropriate to delay it until the major release of the driver, along with a call-out/explanation in the migration guide, rather than putting it in a patch release. That said, I'm open to closing this PR if we decide the original reasoning was appropriate. …

fix: restore auto direct connection behavior

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/generate_evergreen_tasks.js
.evergreen/run-mongodb-aws-ecs-test.sh

Upgrades the `boto3` python dependency used in the AWS auth tests by means of the newly added `activate_venv.sh` script.
NODE-3056

chore(ci): fix aws auth tests

---

test/functional/cursor.test.js

Adds a test to ensure that cloning a cursor removes the session from the new cursor.

NODE-3008: Adding test for cursor cloning removing session

---

src/operations/command.ts

Came up when working on https://github.com/Automattic/mongoose/pull/9855: according to the [server collation docs](https://docs.mongodb.com/manual/reference/collation/), every collation property except `locale` is optional.
Nope

fix(operations): make every CollationOptions property optional except `locale`

---

src/operations/insert.ts
test/functional/collection.test.js

It looks like all insert operations hardcode `checkKeys: true`. I'm not sure if this change was intentional, I tracked the change to this commit: https://github.com/mongodb/node-mongodb-native/commit/07fd317afa91851cfa0065e664f1b5a88ec96fa9 . If this change was intentional, it would make sense to make a note in the changelog.
Nope

fix(operations): avoid hardcoding `checkKeys` for insert operations

---

src/cursor/aggregation_cursor.ts
src/cursor/find_cursor.ts
test/functional/cursor.test.js

Removes the session from the cloned cursor so it is not reused.

NODE-3008: Dont pass session to cloned cursor

---

test/functional/client_side_encryption/corpus.test.js
test/functional/client_side_encryption/driver.test.js
test/functional/spec-runner/index.js
test/functional/spec-runner/matcher.js
test/tools/cluster_setup.sh
test/tools/reporter/mongodb_reporter.js
test/tools/runner/index.js

Remove chai's stack traces and fix reporter on early exit.
Improve cluster script to permit multiple topologies.
I'll port the changes to 3.6 as well.

test: QoL improvements

---

README.md

Added a small note at the top of the readme about 4.0 beta, let me know if we want to make it more noticable somehow
(Also ran prettier on the readme which makes the code examples match our code style)

chore: format readme and add note about 4.0 beta

---

test/functional/gridfs_stream.test.js

Note: [writable.destroy](https://nodejs.org/api/stream.html#stream_writable_destroy_error) was added in node v8.0.0
NODE-3065

test: restrict destroy test to node v8 and up

---

test/functional/connection.test.js
test/functional/spec-runner/utils.js
test/functional/unified-spec-runner/entities.ts
test/functional/unified-spec-runner/match.ts
test/functional/unified-spec-runner/operations.ts
test/functional/unified-spec-runner/runner.ts
test/functional/unified-spec-runner/unified-runner.test.ts
test/functional/unified-spec-runner/unified-utils.ts
test/functional/unified-spec-runner/unified.test.ts
test/tools/runner/config.js

Adds a number of operations, makes use of chai expect instead of boolean
for assertions to track stack traces, adds session and bucket entity
types. Passes utilClient through to operation functions which are"
inlined into the operations map to get type checking to work.
Modifies url helper function to make multipleMongoses detection work.

test: more Unified runner operations

---

lib/core/sdam/topology_description.js
test/unit/core/common.js
test/unit/sessions/client.test.js

Discovered while working on a help ticket the reduce callback in the topology description
doesn't correctly return null if it's in the middle of the list of servers.

fix: session support detection spec compliance

---

lib/operations/operation.js
lib/operations/options_operation.js

Bugfix for: "Accessing non-existent property 'MongoError' of module exports inside circular dependency"
Related to https://developer.mongodb.com/community/forums/t/warning-accessing-non-existent-property-mongoerror-of-module-exports-inside-circular-dependency/15411

fix: MongoError circular dependency

---

.eslintrc.json
src/cmap/message_stream.ts
src/cmap/wire_protocol/compression.ts
src/connection_string.ts
src/db.ts
src/deps.ts
src/index.ts
src/logger.ts
src/mongo_client.ts
src/operations/set_profiling_level.ts
src/sdam/common.ts
src/sdam/server_description.ts
src/sdam/topology_description.ts
src/sessions.ts
src/transactions.ts
tsconfig.json

Changes remaining enums to const objects and exports all user relevant
"enums" from index.ts. Enums are frozen to ensure they remain static.
Added a lint rule to prevent further enums.
Corrected mistake in sourcemap emit settings.
NODE-2973

refactor: remove enums in favor of const objects

---

.eslintrc.json
lib/collection.js
lib/core/auth/scram.js
lib/core/connection/logger.js
lib/core/connection/msg.js
lib/core/sdam/topology.js
lib/core/tools/smoke_plugin.js
lib/core/topologies/read_preference.js
lib/core/uri_parser.js
lib/core/wireprotocol/kill_cursors.js
lib/db.js
lib/operations/add_user.js
lib/operations/connect.js
lib/utils.js
lib/write_concern.js
test/.eslintrc.json
test/functional/deprecate_warning.test.js
test/unit/sdam/server_selection/select_servers.test.js

Unify the way we print out messages relating to upcoming changes
or potential misuse of the driver. Using the emitWarning API allows
users to configure when and how messages are shown.
(code from #2740)
NODE-2317, NODE-3114

fix: backport emitWarning helper

---

lib/db.js
lib/utils.js
package-lock.json
test/functional/client_side_encryption/corpus.test.js
test/functional/client_side_encryption/driver.test.js
test/functional/deprecate_warning.test.js
test/functional/index.test.js
test/functional/spec-runner/index.js
test/functional/spec-runner/matcher.js
test/tools/runner/index.js

Some of the deprecation warnings are formatted a little different in node boron (v6), updated the tests to account for that.

fix: boron node version test failures

---

lib/mongo_client.js
lib/operations/execute_operation.js
test/functional/find.test.js
test/functional/insert.test.js
test/functional/operation_example.test.js
test/unit/sessions/client.test.js

Monitor checks run on a timer and network errors cause a reset
of the topology that would be corrected in the next cycle of the
monitor, we were checking a property that gets updated by this async
work. By moving the check to the operations layer we will allow users
to obtain a session regardless of support and then emit an error if
there is not support when the session is used in an operation.
NODE-3100

fix: move session support check to operation layer

---

package-lock.json
package.json
src/cmap/connect.ts
src/connection_string.ts
test/functional/index.test.js

Our validation for a nodejs option suggested that an option could be a boolean when it can actually only be false or a function. In addition this removes the catching of synchronous errors thrown from socket creation. 
NODE-3061

fix: remove catch for synchronous socket errors and remove validation on nodejs option

---

.evergreen/config.yml
lib/gridfs-stream/upload.js

Tests will hang on Node 14 so just updated Evergreen config with the fix.

NODE-3122: Always close gridfs upload stream on finish

---

lib/core/sdam/monitor.js

I couldn't get the driver into a state where this would occur, which is why there's no unit test here. But the 1 line of code change is the same as in the 4.0 branch and wouldn't have any potential negative impact.

NODE-3120: Ensure monitor has rtt pinger in when calculating rtt

---

.gitignore
src/cursor/abstract_cursor.ts
test/functional/cursor.test.js

The new autoDestroy option for streams in Node 14+ would emit an extra close event when the stream has ended.

NODE-2951: Don't auto destroy read stream on Node 14+

---

src/cursor/aggregation_cursor.ts
src/cursor/find_cursor.ts
test/functional/cursor.test.js

Port up to the 4.0 branch with added tests.

NODE-3008: Remove existing session from cloned cursors.

---

src/mongo_client.ts
src/operations/execute_operation.ts
src/operations/operation.ts
src/sessions.ts
test/functional/index.test.js
test/unit/sessions/client.test.js

Session support check is now performed after server selection
this ensures the monitor was able to update the topology description
NODE-3100

[PORT] fix: move session support check to operation layer

---

src/apm.ts
src/mongo_client.ts
src/sdam/topology.ts
src/sessions.ts
test/functional/unified-spec-runner/entities.ts
test/functional/unified-spec-runner/operations.ts
test/functional/unified-spec-runner/runner.ts
test/functional/unified-spec-runner/unified-runner.test.ts

Completes the unified runner by passing all the poc spec tests.
NODE-2287
There's some additional work in here that I'm happy to break out into its own ticket, but it came up in debugging:
- Sessions claimed to accept MongoClientOptions when they were instead receiving MongoOptions, guaranteed to have the well typed WC,RP,RC etc. 
- The issue blocking transactions from working was that my test provided an options object that had `{ writeConcern: undefined }` and that would overwrite the client options that were supposed to be inherited. I can go back and fix the test to not defined a key if the value is undefined but maybe this is unexpected enough to fix in driver, so here I used `??` and explicit fetching of the options to resolve the correct value
- APM overwrites the …

test: complete unified test runner

---

lib/core/connection/connect.js

servername should only ever be a hostname. Add a condition
to check if the host is an IP and skip auto setting the servername.

fix(NODE-3109): prevent servername from being IP

---

test/spec/server-discovery-and-monitoring/errors/write_errors_ignored.json
test/spec/server-discovery-and-monitoring/errors/write_errors_ignored.yml

test(NODE-3070): Ensure that SDAM should ignore the writeErrors field

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
test/functional/cursor.test.js

Somehow I dropped fermium testing, bringing it back here.

chore: reintroduce nodejs fermium testing

---

src/cmap/auth/mongo_credentials.ts

The AWS environment variables were not detected properly.
The checks for `username == null` and `password == null` would always return false as the static `merge(...)` method that is used to create an instance of `MongoCredentials` defaulted to an empty string as value for both.
Furthermore, the `AWS_SESSION_TOKEN` _must be applied_ if it is present in the environment variables and takes precedence over any other value. See https://github.com/mongodb/specifications/blob/master/source/auth/auth.rst#environment-variables:
> However, if AWS_SESSION_TOKEN is set Drivers MUST use its value as the session token.
The direct assignment of `AWS_SESSION_TOKEN` would also potentially fail as it happened that `this.mechanismProperties` was initialized with an already freezed object throwing an error. …

NODE-3152: ensure AWS environment variables are applied properly

---

src/cmap/connect.ts

PORT to 4.0
servername should only ever be a hostname. Add a condition
to check if the host is an IP and skip auto setting the servername.

fix(NODE-3109): prevent servername from being IP [PORT 4.0]

---

lib/operations/connect.js

When deprecating top-level writeConcern keys, some code was added to specifically skip them in `createUnifiedOptions`. You can see the change [here](https://github.com/mongodb/node-mongodb-native/pull/2624/files#diff-499ac669b51189e3130d91b7bf24cc7ca905950d199baea11c763981b231ff25R615)
This was ok for all keys except writeConcern, as the key being checked is cast to lowercase, but the original value is not. If given an input key of `writeConcern` it is converted to `writeconcern` and then always compared against `writeConcern` causing the check to always be false. This means that if you have connection options of:
```
writeConcern: {
w: 1
}
```
the createUnifiedOptions function will ultimately add w:1 to the final options object and result in deprecation errors being thrown, despite a …

fix: Invalid case on writeconcern makes skip check fail

---

lib/cmap/connection.js
test/unit/sdam/topology.test.js

If there's a socket that gets a large amount of data written to it our MessageStream will throw an error about exceeding the permitted BSON size, this error is now captured in SDAM.

fix(NODE-3176): handle errors from MessageStream

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/generate_evergreen_tasks.js
lib/core/auth/mongo_credentials.js
test/tools/runner/plugins/client_leak_checker.js

Some of the AWS functions were not running in CI, they are passing though, this makes sure we can see each scenario run as expected.

chore(NODE-3186): ensure all aws tests are run

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/generate_evergreen_tasks.js
.evergreen/run-mongodb-aws-ecs-test.sh
.evergreen/run-mongodb-aws-test.sh
src/cmap/auth/mongodb_aws.ts

In addition to the port from 3.6 there was a small fix to be made in the AWS auth that checks empty strings as falsey instead of just omitted values. #2776

chore(NODE-3186): ensure aws tests are run [PORT 4.0]

---

src/cmap/connection.ts
test/unit/sdam/topology.test.js

If there's a socket that gets a large amount of data written to it our MessageStream will throw an error about exceeding the permitted BSON size, this error is now captured in SDAM.
The code here is precisely the same as the fix in 3.6 so just asking for a sanity check here.

fix(NODE-3176): handle errors from MessageStream [PORT 4.0]

---

src/connection_string.ts
test/unit/mongo_client_options.test.js

The insecure TLS flags were not being correctly translated to the equivalent nodejs options.

fix(NODE-3166): allowInvalidHostnames and allowInvalidCertificates flags are ignored

---

lib/collection.js

This makes the docs match the behavior of the function since this does not accept a callback. 
There are no code changes, only deleted a line in the JSDoc comment referring to the callback parameter which does not exist
No

Remove callback from Collection.initializeOrderedBulkOp()

---

docs/CHANGES_4.0.0.md

Note: We'll probably want to have a shorter note about a versioned API in the CHANGES doc, and a link to the section in the official Node driver docs, once they have been updated with the versioned API usage examples here.

docs: document versioned api usage

---

src/sort.ts
test/functional/apm.test.js
test/functional/cursor.test.js
test/functional/spec-runner/index.js
test/functional/unified-spec-runner/match.ts

Updated internal representation of sort to use a map instead of a plain object in order to preserve correct ordering for multi-key sort queries; also enabled the use of a map type to specify input sort options

fix(NODE-3174): Preserve sort key order for numeric string keys

---

src/sdam/topology.ts

The topology was emitting both a "topologyClosed" and "close"
event which are bubbled up to the MongoClient. This was causing
two "close" events to be emitted from the MongoClient when the
client is closed.
NODE-3219
Note that there were no tests explicitly looking for that event, but there
are tests looking for the `topologyClosed` event, so I assume this just
slipped through.

fix(sdam): topology no longer causes close event

---

lib/utils.js
test/functional/spec-runner/index.js

Updated internal representation of sort to use a map instead of a plain object in order to preserve correct ordering for multi-key sort queries

fix(NODE-3173): Preserve sort key order for numeric string keys

---

package-lock.json
package.json

This PR upgrades `optional-require` to `1.0.3` for Yarn v2 PnP support. See https://jira.mongodb.org/browse/NODE-3198 for justification.

chore(NODE-3198): bump optional-require for yarn v2 pnp support

---

src/collection.ts
src/operations/distinct.ts

Fixes distinct() being erroneously typed as Document[] instead of any[] (NODE-3206)

fix(NODE-3206): Make distinct use any[] type instead of Document[]

---

src/bulk/common.ts
src/collection.ts
src/operations/insert.ts
test/functional/bulk.test.js
test/functional/crud_api.test.js
test/functional/operation_example.test.js
test/functional/operation_generators_example.test.js
test/functional/operation_promises_example.test.js

refactor!: remove deprecated bulk ops

---

src/collection.ts
src/index.ts
src/operations/find_and_modify.ts
src/sort.ts

BREAKING: Legacy `fields` option no longer supported, use `projection` instead.
NODE-3157 Updated public facing option interfaces for find and modify operations: `findOneAndDelete()`, `findOneAndReplace()`, `findOneAndUpdate()`. Standardized option parsing and internal representation of find and modify operations.

refactor(NODE-3157)!: update find and modify interfaces for 4.0

---

src/connection_string.ts
test/unit/mongo_client_options.test.js

Fix NODE-3194: MongoClient constructor should not try to parse undefined or null options

fix(NODE-3194): Ignore undefined and null options in MongoClient constructor

---

src/cmap/connection_pool.ts

A performance regression was identified in switching the connection pool to using setImmediate instead of process.nextTick for wait queue processing. This patch reverts that change.
NODE-3197

fix(NODE-3197): revert setImmediate in waitQueue

---

src/index.ts
src/operations/find_and_modify.ts
test/functional/crud_api.test.js
test/functional/crud_spec.test.js
test/functional/find.test.js
test/functional/insert.test.js
test/functional/multiple_db.test.js
test/functional/operation_example.test.js
test/functional/operation_generators_example.test.js
test/functional/operation_promises_example.test.js
test/functional/retryable_writes.test.js
test/functional/spec-runner/index.js
test/functional/unified-spec-runner/operations.ts
test/functional/unified-spec-runner/unified-utils.ts

NODE-1812
BREAKING: `returnOriginal` option no longer supported for `findOneAndReplace()` and `findOneAndUpdate()` collection methods, use the new `returnDocument` enum instead.
Replaced `returnOriginal` with `returnDocument` option in order to conform with shared drivers spec.

refactor(NODE-1812)!: replace returnOriginal with returnDocument option

---

docs/reference/content/reference/ecmascriptnext/crud.md
docs/reference/content/tutorials/crud.md
lib/collection.js
lib/operations/find_one_and_replace.js
lib/operations/find_one_and_update.js
test/functional/crud_api.test.js
test/functional/crud_spec.test.js
test/functional/operation_example.test.js
test/functional/operation_generators_example.test.js
test/functional/operation_promises_example.test.js
test/functional/retryable_writes.test.js
test/functional/spec-runner/index.js
test/unit/collection.test.js

NODE-1812
Deprecated `returnOriginal` in favor of `returnDocument` option in order to conform with shared drivers spec for `findOneAndReplace()` and `findOneAndUpdate()` collection methods.

refactor(NODE-1812): Deprecate returnOriginal in favor of returnDocument

---

lib/core/wireprotocol/command.js

The fix is really just making the if statement on line 53 check the correct properties before accessing them, but I also created some variables to help track which cluster time is being used where.

fix(NODE-3192): check clusterTime is defined before access

---

src/bulk/common.ts
src/bulk/ordered.ts
src/bulk/unordered.ts
src/cmap/auth/defaultAuthProviders.ts
src/cmap/auth/mongo_credentials.ts
src/cmap/message_stream.ts
src/cmap/wire_protocol/compression.ts
src/connection_string.ts
src/db.ts
src/deps.ts
src/explain.ts
src/index.ts
src/logger.ts
src/mongo_client.ts
src/operations/set_profiling_level.ts
src/read_concern.ts
src/read_preference.ts
src/sdam/common.ts
src/sdam/server_description.ts
src/sdam/topology_description.ts
src/sessions.ts
src/transactions.ts
test/functional/unified-spec-runner/schema.ts
test/unit/mongo_client_options.test.js

NODE-3275
Make type exports for enums use the same name as the enums themselves

fix(NODE-3275): Fix enum type export naming and serverApi validation

---

lib/cmap/connection.js
lib/core/error.js
test/unit/cmap/connection.test.js
test/unit/error.test.js

I ran into this issue when upgrading Mongoose to 3.6.7 (https://github.com/Automattic/mongoose/pull/10265). 3.6.7 did some refactoring with https://github.com/mongodb/node-mongodb-native/commit/f1afcc4efbc41ce436812a6bfa22843e939ab5cf that seems to have unintentionally flipped the `beforeHandshake` flag on timeout errors. This causes the topology to _always_ switch to 'Unknown' state when there's an operation timeout.
Undoing a change that I think may have been accidental.

fix(cmap): undo flipping of `beforeHandshake` flag for timeout errors

---

lib/bulk/common.js
lib/operations/bulk_write.js
test/benchmarks/driverBench/bulkWriteResult.js
test/unit/bulk_write.test.js

Add caching for getters that build the result object.
Add benchmarking script.
Add unit test for getter caching.
NODE-3309

fix(NODE-3309): remove redundant iteration of bulk write result

---

src/operations/insert.ts

[NODE-3311](https://jira.mongodb.org/projects/NODE/issues/NODE-3311)
`insertOne` is missing common options + session typings.

fix(NODE-3311): Fix "session" typescript typing for "insertOne" options.

---

src/bulk/common.ts
test/functional/bulk.test.js

feat(NODE-2751): add arrayFilters builder to bulk FindOperators

---

test/spec/initial-dns-seedlist-discovery/dbname-with-commas.json
test/spec/initial-dns-seedlist-discovery/dbname-with-commas.yml

Syncs the new tests to the 4.0 branch. No code changes required - they pass here.

test(NODE-3234): sync initial dns seedlist tests

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/generate_evergreen_tasks.js
.evergreen/run-bson-ext-test.sh
src/bson.ts
src/index.ts
test/benchmarks/driverBench/common.js
test/benchmarks/driverBench/index.js
test/functional/insert.test.js
test/types/bson.test-d.ts
test/unit/bson_import.test.js

- Update benchmark imports
- Add bson-ext test to CI
I've also updated the BSONSerializeOptions to use the options exported from our BSON library now, this pipes through the documentation from there so we don't have duplication. 
While I'm here, (and before the major release) how do we feel about renaming `BSONSerializeOptions` -> `BSONOptions`?
The truth is it is for both serialize and deserialize.

fix(NODE-2944): Reintroduce bson-ext support

---

src/sdam/srv_polling.ts
src/sdam/topology.ts
src/sessions.ts
test/functional/apm.test.js
test/functional/unified-spec-runner/unified-runner.test.ts
test/tools/utils.js
test/unit/sdam/topology.test.js

Corrects the event type emitted from the SRV polling listener on the Topology.
Also:
Skipped the cursor tests and marked them with the unskip ticket, and corrected the visibility on session properties.

fix(NODE-3272)!: emit correct event type when SRV Polling

---

src/operations/aggregate.ts
test/functional/unified-spec-runner/operations.ts
test/spec/crud/unified/aggregate-let.json
test/spec/crud/unified/aggregate-let.yml

Add support for `let` and cherry-pick the tests from https://github.com/mongodb/specifications/commit/3db387995bc0e64df862d621aaa31387afc1537c
(since actually updating the full test suite led to a bunch of failures).
Since the NODE ticket is scoped to only `aggregate`, nothing
else is done here.
Test files are cherry-picked from upstream.

feat(NODE-3325): support 'let' option for aggregate command

---

test/spec/uri-options/connection-pool-options.json
test/spec/uri-options/connection-pool-options.yml

Synced tests, all pass. Verified connection pool treats `maxPoolSize=0` as unlimited.

test(NODE-3284): add maxPoolSize=0 spec tests

---

src/operations/delete.ts
src/operations/find.ts
src/operations/find_and_modify.ts
src/operations/update.ts
test/functional/unified-spec-runner/operations.ts
test/spec/crud/unified/aggregate-let.json
test/spec/crud/unified/aggregate-let.yml
test/spec/crud/unified/crud-let.json
test/spec/crud/unified/crud-let.yml

Same as #2828.
The spec tests here are fake in the sense that no upstream spec tests
for this exist at this point. I’ve put them next to the other tests, more or less
just assuming that somebody would notice their existence when updating
the crud spec suite to upstream and make sure they aren’t deleted.
(They are just a temporary thing here anyway.)

feat(NODE-3333): support 'let' option for CRUD commands

---

src/cmap/command_monitoring_events.ts
src/cmap/connection.ts
test/functional/apm.test.js
test/functional/multiple_db.test.js
test/unit/cmap/command_monitoring_events.test.js

Changed events for Command monitoring to hold copies of the commands instead of the commands themselves to prevent changing state in event monitoring by modifying `extractCommand` function in src/cmap/command_monitoring_events.ts
- src/cmap/command_monitoring_events.ts
- test/functional/apm.test.js
- test/functional/multiple_db.test.js
- test/unit/cmap/command_monitoring_events.test.js

fix(NODE-1502): Command monitoring commands should be copies

---

src/cmap/command_monitoring_events.ts
test/functional/apm.test.js

fix(NODE-3356): update redaction logic for command monitoring events

---

src/cursor/abstract_cursor.ts
src/utils.ts
test/functional/cursor.test.js

Catch and propagate exceptions in awaited cursor.forEach
- src/cursor/abstract\_cursor.ts
- test/functional/cursor.js

fix(NODE-2035): exceptions thrown from awaited cursor forEach do not propagate

---

.evergreen/run-custom-csfle-tests.sh
package.json
src/error.ts
src/index.ts
test/functional/client_side_encryption/driver.test.js
test/functional/client_side_encryption/spec.test.js

The custom CSFLE test variant will now run the mocha tests defined in the libmongocrypt/bindings/node directory.
I also skipped the count documents test because the command monitoring exposed the fact that count is run with an aggregate and not a count operation.

test(NODE-3118): run CSFLE integration tests from libmongocrypt repo

---

lib/core/topologies/read_preference.js
test/functional/readpreference.test.js

Test verifying that transactions get their `readPreference` from `SessionOptions` passed at session instantiation
- lib/core/topologies/read_preference.js
- test/functional/readpreference.test.js

test(NODE-2856): Check that defaultTransactionOptions get used from session

---

src/cmap/connection.ts
src/error.ts
test/unit/cmap/connection.test.js
test/unit/errors.test.js

Forward port of https://github.com/mongodb/node-mongodb-native/pull/2813

fix(NODE-3305): beforeHandshake flag is always true

---

lib/command_utils.js
lib/core/connection/apm.js
lib/core/connection/connection.js
lib/core/connection/pool.js
lib/core/cursor.js
lib/core/sdam/server.js
lib/core/topologies/server.js
lib/operations/command.js
lib/operations/command_v2.js
lib/operations/db_ops.js

refactor(NODE-3356): Update command monitoring logging

---

src/bson.ts
src/cmap/auth/mongodb_aws.ts
src/cmap/commands.ts
src/cmap/connection.ts
src/cmap/wire_protocol/shared.ts
src/connection_string.ts
src/db.ts
src/operations/create_collection.ts
src/operations/map_reduce.ts
src/sdam/server.ts
test/types/bson.test-d.ts
test/unit/bson_regex.test.js

- Allowed retrieving PCRE-style RegExp by adding `bsonRegExp` option to commands, collections, and dbs
- Added unit tests for the `bsonRegExp` option

fix(NODE-3150): allow retrieving PCRE-style RegExp

---

package-lock.json
package.json
src/connection_string.ts
test/functional/mongo_client.test.js
test/tools/runner/config.js

As discussed earlier this year, this moves the connection string
parsing into a separate package for mongodb-connection-string-specific
URL parsing. The code in that package is based very closely on the
original code in the driver here.
No.

chore(NODE-2998): move connection-string parsing into separate package

---

src/cmap/auth/gssapi.ts
test/manual/README.md
test/manual/kerberos.test.js
test/unit/core/connection_string.test.js

This PR adds support for the `SERVICE_NAME` authentication mechanism property that replaces the old `gssapiServiceName` query string parameter.
It also includes a test case that would set the `SERVICE_NAME` to an invalid value and verifies the connection consequently fails.
_NOTE:_ I've also started a small README file for the manual tests as I was initially unsure on how to run them locally.
Let me know if there's anything I need to adapt 😊

fix(NODE-2905): support SERVICE_NAME authentication mechanism property

---

src/cursor/abstract_cursor.ts
src/cursor/aggregation_cursor.ts
src/cursor/find_cursor.ts
test/types/community/cursor.test-d.ts

This allows for users to override the resulting documents after a projection is applied.
A furhter improvement could be to use the projection to filter the keys out of the schema but that requires the projection to be a const type. I leave that up to a future feature request.

fix(NODE-3343): allow overriding result document after projection applied

---

lib/command_utils.js
lib/core/connection/apm.js
lib/utils.js
test/functional/apm.test.js
test/unit/cmap/apm_events.test.js

Modify extractCommand function used in apm event constructors to make deep copies of the command passed in
- lib/command_utils.js (cherry-picked from https://github.com/mongodb/node-mongodb-native/commit/299b9699c78a69d1b1219ef40604990ab36ef0ee)
- lib/core/connection/apm.js
- lib/utils.js
- test/functional/apm.test.js
- test/unit/cmap/apm_events.test.js

fix(NODE-3358): Command monitoring objects hold internal state references

---

test/functional/apm.test.js

Test clean-up
test/functional/apm.test.js

test(NODE-3358): Command monitoring objects hold internal state references

---

lib/cmap/connection.js
lib/collection.js
lib/core/connection/commands.js
lib/core/connection/connection.js
lib/core/connection/msg.js
lib/core/connection/pool.js
lib/core/cursor.js
lib/core/sdam/monitor.js
lib/core/sdam/server.js
lib/core/topologies/mongos.js
lib/core/topologies/replset.js
lib/core/topologies/server.js
lib/core/wireprotocol/shared.js
lib/db.js
lib/mongo_client.js
lib/operations/command.js
lib/operations/connect.js
lib/operations/db_ops.js
lib/topologies/mongos.js
lib/topologies/replset.js
lib/topologies/server.js
test/functional/unified-spec-runner/operations.ts
test/unit/bson_regex.test.js

- Allowed retrieving PCRE-style RegExp by adding bsonRegExp option to commands, collections, and dbs
- Added unit tests for the bsonRegExp option

fix(NODE-3150): added bsonRegExp option for v3.6

---

lib/core/sdam/server.js
lib/core/sdam/topology.js

The driver was incorrectly checking for a `Single` topology instead of
a `Standalone` server when determining the retryability of write
operations.
NODE-3380

fix(NODE-3380): perform retryable write checks against server

---

.evergreen/run-checks.sh
README.md
package-lock.json
package.json
src/index.ts
src/mongo_types.ts
src/operations/indexes.ts

Downlevel-dts is now run when ever defintions are generated and our package points typescript versions equal to 4.0.2 and older to these defintions. They target the lowest version downlevel-dts supports which is 3.4. I added a check to our CI to make sure that 4.0.2 will use and remain compatible with these types.

feat(NODE-3331): offer downleveled types for legacy typescript versions

---

src/cmap/auth/gssapi.ts
test/manual/kerberos.test.js

Introduces support for the `SERVICE_REALM` authentication mechanism property. It will be work as expected in Windows environments due to the underlying nature of the GSSAPI implementation on *nix.
The logic to compute the Service Principal Name (SPN) is as follows:
1. Combine service name and hostname (with a `/` in between for Windows and an `@` otherwise)
2. If present, attach the `SERVICE_REALM` with an `@` to the result of step 1.
The logic is taken from the C driver where you can find the steps mangled as follows:
1. "Join" the array of `[serviceName, hostName, serviceRealm]` with `@` (see https://github.com/mongodb/mongo-c-driver/blob/f1093ba1686b8bf876eed67e0c7f59918649ef15/src/libmongoc/src/mongoc/mongoc-cluster-sspi.c#L61-L71)
2. If there is no `/` in the SPN (which is not the …

fix(NODE-2026): support SERVICE_REALM authentication mechanism property

---

src/cmap/wire_protocol/constants.ts
test/unit/wire_version.test.js

Bumps the version and adds a test to capture the errors caused by out of range versions.

refactor(NODE-3324): bump max wire version to 13

---

lib/core/connection/connect.js

I haven't been able to repro this locally, but there's a user that ran into this case at Automattic/mongoose#10377. Figured this change is sufficiently straightforward that it's worthwhile to patch without digging into it much further.
Added a quick check for `null` or `undefined` before calling a method on an object

fix(NODE-3397): report more helpful error with unsupported authMechanism in initial handshake

---

test/functional/examples/versioned_api.js

Note: these are ingested for the official server doc examples and don't actually need to test anything.
NODE-3271

docs(NODE-3271): add versioned api examples

---

.evergreen/run-custom-csfle-tests.sh

fix(NODE-3063): fix custom csfle test script

---

src/change_stream.ts

In most places, the node driver defaults to using `Document` if no generic param is provided. `ChangeStream` looks to be an exception.
Added a default generic param to ChangeStream
Nope

fix(NODE-3416): make change stream generic default to Document

---

src/bulk/common.ts
test/functional/bulk.test.js

The BulkOperationBase class wasn't making use of the options provided at construction time during execution time.
NODE-1843

fix(NODE-1843): bulk operations ignoring provided sessions

---

src/change_stream.ts
test/functional/change_stream.test.js

Throw appropriate error when a ChangeStream object is used as both an iterator and an emitter
* src/change_stream.ts
* test/functional/change_stream.test.js

fix(NODE-1797): Error when ChangeStream used as iterator and emitter concurrently

---

src/error.ts

Added:
- MongoBatchReExecutionError
- MongoNotConnectedError
- MongoCursorError
- MongoCursorExhaustedError
- MongoTailableCursorError
- MongoCursorInUseError
- src/error.ts

feat(NODE-3403): define MongoRuntimeError children

---

src/collection.ts
src/db.ts
src/mongo_client.ts

fix(NODE-3430): watch method types on MongoClient and Db

---

src/error.ts

- Added class definitions of MongoRuntimeError children as seen in the second and third graph of [docs/errors.md](https://github.com/mongodb/node-mongodb-native/blob/4.0/docs/errors.md) and needed in [NODE-3404](https://jira.mongodb.org/browse/NODE-3404) and [NODE-3405](https://jira.mongodb.org/browse/NODE-3405).
Classes added:
- MongoURIError
- MongoCompressionError
- MongoDecompressionError
- MongoTransactionError
- MongoExpiredSessionError
- MongoKerberosError
- MongoStreamError
- MongoChangeStreamError
- MongoGridFSStreamError
- MongoGridFSChunkError
- MongoResourceClosedError
- MongoServerClosedError
- MongoStreamClosedError
- MongoTopologyClosedError

feat(NODE-3419): define MongoRuntimeError children

---

src/sessions.ts
test/functional/sessions.test.js
test/functional/unified-spec-runner/operations.ts

NODE-3393, NODE-3394
This PR started out as a fix to our spec runner which was selectively passing in sessions instead of applying them to all operations. Fixing the last test revealed a bug in the original snapshot session reads implementation: the `atClusterTime` from the server response was not applied to the session if the first operation executed against it was `distinct`. This PR includes the fix for that issue.

fix(NODE-3393): snapshot time not applied if distinct executed first

---

src/mongo_client.ts

Removed an error case that will make Automattic/mongoose#8702 much easier.
Removed a check that looks unnecessary because the `Db()` constructor no longer takes a `topology` param.

fix(NODE-3417): allow calling `db()` before MongoClient is connected

---

lib/core/auth/mongodb_aws.js
lib/core/auth/scram.js
lib/core/index.js
lib/core/utils.js
lib/encrypter.js
package-lock.json

Tested locally webpack only returns warnings with this change

fix(NODE-3199): unable to bundle driver due to uncaught require

---

src/operations/indexes.ts
test/types/index_options.test-d.ts
test/types/mongodb.test-d.ts

This isn't super clear from the index management specification, but it seems like `IndexDescription` needs to extend `CreateIndexesOptions`, since each index description may also contain options.

fix(NODE-3441): fix typings for createIndexes

---

package.json
src/cursor/abstract_cursor.ts
test/functional/cursor_async_iterator.test.js
test/types/community/cursor.test-d.ts
test/unit/execute_legacy_operation.test.js

The AsyncIterator had TSchema or null as its return type the truth is that the for await loop ends when the next function returns null so you never get null in your loop.

fix(NODE-3442): AsyncIterator has incorrect return type

---

test/functional/spec-runner/index.js
test/functional/spec-runner/utils.js

- Allow skipped tests to skip `beforeEach/afterEach` hooks, significantly speeding up test runs particularly against remote servers with higher latency.
- Fixes a bug in the URL returned by the legacy test runner when `isShardedEnvironment && !useMultipleMongoses`

test: legacy spec runner improvements

---

src/change_stream.ts
src/collection.ts
src/cursor/aggregation_cursor.ts
src/db.ts
src/operations/aggregate.ts
src/operations/count_documents.ts

Remove parent parameter from AggregateOperation and parent reference from AggregationCursor and change any instantiation of these internal classes to match their new signature
* src/change_stream.ts
* src/collection.ts
* src/cursor/aggregation_cursor.ts
* src/db.ts
* src/operations/aggregate.ts
* src/operations/count_documents.ts

fix(NODE-2883): Aggregate Operation should not require parent parameter

---

.eslintrc.json
src/cmap/auth/scram.ts
src/cmap/command_monitoring_events.ts
src/cmap/connection.ts
src/cmap/stream_description.ts
src/collection.ts
src/connection_string.ts
src/cursor/abstract_cursor.ts
src/cursor/aggregation_cursor.ts
src/cursor/find_cursor.ts
src/error.ts
src/explain.ts
src/operations/command.ts
src/operations/count.ts
src/operations/delete.ts
src/operations/find.ts
src/operations/insert.ts
src/operations/update.ts
src/read_preference.ts
src/sdam/topology_description.ts
src/sessions.ts
src/sort.ts
src/utils.ts

I added an ESLint rule to prevent us from mixing and matching our nullish checks, we should only be using double eq with a null literal now.

fix(NODE-3058): accept null or undefined anywhere we permit nullish values

---

src/bulk/common.ts
src/cursor/abstract_cursor.ts
src/cursor/find_cursor.ts
src/error.ts
src/mongo_client.ts
src/utils.ts
test/functional/bulk.test.js

Replace appropriate MongoDriverError instances with instances of the following classes
* MongoBatchReExecutionError
* MongoCursorError
* MongoCursorExhaustedError
* MongoTailableCursorError
* MongoCursorInUseError
* MongoNotConnectedError

refactor(NODE-3421): Replace MongoDriverError instances with MongoRuntimeError children

---

src/sdam/common.ts
src/sdam/topology.ts
src/sessions.ts
test/functional/sessions.test.js
test/unit/core/sessions.test.js

NODE-2843
Implemented the advanceClusterTime session method, refactored internal helper function for naming consistency

feat(NODE-2843): implement sessions advanceClusterTime method

---

src/collection.ts

One of the TS overloaded declarations for `rename()` had a `| void` which AFAIK is incorrect. If a method returns a `Promise`, it should never be typed `| void`.  The problem doesn't show up in any other overload declarations, so I assume this was just a bug, not a statement about weird behavior of this method.
I removed the `| void` for this overload's declaration. 
No.

fix(NODE-3510): omit incorrect `| void` in declaration of Promise overload of `rename()`

---

src/connection_string.ts
test/functional/causal_consistency.test.js
test/functional/cursor.test.js
test/functional/find_and_modify.test.js
test/functional/index.test.js
test/functional/insert.test.js
test/unit/mongo_client_options.test.js

Revert an accidental default enabling of command monitoring

fix(NODE-3513): default command monitoring to off

---

src/mongo_types.ts
src/utils.ts
test/types/community/collection/findX.test-d.ts
test/types/community/collection/insertX.test-d.ts
test/types/helper_types.test-d.ts

Under certain usages typescript will disallow readonly arrays, when overriding the results of a find is a notable usage, look to the tests for a more complete list. Additionally the result of find was resulting the in the schema unioned with filter operators, there's a test to confirm that no longer occurs.

fix(NODE-3452): readonly filters not permitted by typings

---

src/cursor/abstract_cursor.ts

Deprecate CloseCursorOptions
- src/cursor/abstract_cursor.ts

docs(NODE-3492): Deprecate CloseCursorOptions

---

.evergreen/config.yml
.evergreen/config.yml.in
package.json
src/db.ts
test/functional/load-balancer-spec.test.js
test/functional/unified-spec-runner/entities.ts
test/functional/unified-spec-runner/match.ts
test/functional/unified-spec-runner/schema.ts
test/functional/unified-spec-runner/unified-utils.ts
test/tools/runner/index.js

Removes the manual test and runs the entire test suite. The load balancer unified tests are moved into the `test/functional` directory and the test runner setup is changed to put the topology in the correct load balancer mode.

test(NODE-3461): refactor lb manual to full test run

---

src/db.ts
src/sdam/topology.ts
test/types/mongodb.test-d.ts

Unref is now deprecated and marked to be removed in the next major version.

docs(NODE-3481): deprecate unref in 4.1

---

test/types/community/collection/findX.test-d.ts

NODE-3468
The added tests ensure that users who re-use a single db object can define which collections are available on that Db, as well as the types those collections contain.

test(NODE-3468): Add tests for a strongly-typed Db

---

package-lock.json
package.json

NODE-3451
Updated lockfile version to 2 (for latest npm) and bumped the minimum bson version to 4.5.0 to ensure the deserialization performance fix is applied.

chore(NODE-3451): bump min bson version for performance fix

---

src/cmap/connection.ts
src/operations/command.ts
src/operations/distinct.ts
src/operations/find.ts
src/operations/operation.ts

NODE-3511
Removing the never properly implemented `fullResponse` option from the codebase, also marking `CommandOptions` internal, since they are, in fact, internal use only. Also, removing the ability to externally affect the `fullResult` option (TS compilation would break if `fullResult` is passed in as a command option, but nothing is stopping regular js users from setting it and overriding our internal settings - we should confirm with shell that they aren't using it for some niche functionality, but otherwise this should be safe to disable)

fix(NODE-3511): deprecate fullResponse and remove associated buggy code paths

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/generate_evergreen_tasks.js
.evergreen/run-snappy-version-test.sh
package-lock.json
package.json
src/cmap/wire_protocol/compression.ts
src/deps.ts
src/utils.ts
test/unit/snappy.test.js

Pulling this fix out of the larger deps upgrade PR.
Reworked the bson-ext and custom fle build variants to share the custom tasks. cleans up the EVG view a bit.
Test both snappy 6 and 7.
also upgrades our connection string dep

fix(NODE-3528): add support for snappy 7

---

src/collection.ts
src/cursor/abstract_cursor.ts
test/functional/crud_api.test.js
test/functional/sessions.test.js
test/types/community/collection/findX.test-d.ts
test/types/union_schema.test-d.ts

findOne will now return null
ModifyResult correctly types value to be null or TSchema

fix(NODE-3546): revert findOne not found result type to null

---

README.md

The current changelog link in the readme doesn't work because it links to `docs/HISTORY.md`, not `HISTORY.md`

chore(readme): fix broken link to changelog

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/generate_evergreen_tasks.js
.evergreen/init-nvm.sh
.evergreen/run-snappy-version-test.sh
HISTORY.md
lib/bulk/common.js
lib/core/auth/mongo_credentials.js
lib/core/auth/mongodb_aws.js
lib/core/auth/scram.js
lib/core/connection/connection.js
lib/core/connection/pool.js
lib/core/connection/utils.js
lib/core/index.js
lib/core/sdam/topology.js
lib/core/utils.js
lib/db.js
lib/encrypter.js
lib/utils.js
package-lock.json
package.json
test/functional/bulk.test.js
test/functional/mongodb_aws.test.js
test/unit/snappy.test.js

Syncs the following 3.6 changes to 3.7:
- fix(NODE-1843): bulk operations ignoring provided sessions [PORT] (#2898)
- fix(NODE-3199): unable to bundle driver due to uncaught require (#2903)
- chore(release): 3.6.11
- docs(NODE-3481): deprecate unref (#2936)
- fix(NODE-3528): add support for snappy v7 (#2947)
- fix(NODE-3487): check for nullish aws mechanism property (#2957)
- chore(NODE-3408): test against mongod 5.0 (#2958)
- chore(release): 3.6.12

chore: sync 3.6 changes to 3.7

---

lib/explain.js

NODE-3377, backport arbitrary explain level fix from 4.0 (#2834)

fix(NODE-3377): driver should allow arbitrary explain levels

---

test/functional/unified-spec-runner/operations.ts

NODE-3387 - fixed both `findOneAndReplace` and `findOneAndDelete`

test(NODE-3387): correctly extract findOneX values in unified operations

---

lib/core/index.js
lib/mongo_client.js
test/functional/unified-spec-runner/unified-utils.ts
test/functional/versioned-api.test.js

Updating versioned API not to use `Object.values` and unified runner not to use the node util for deep equality check.

fix: versioned api low node compat fix

---

src/cursor/aggregation_cursor.ts
test/types/mongodb.test-d.ts

Corrects an oversight in #2967

fix(NODE-3467): allow object type for aggregate out helper

---

package-lock.json
src/index.ts
test/types/mongodb.test-d.ts
test/unit/bson_import.test.js

Reintroduced the capitalized ObjectID export along with a deprecation tag.

fix(NODE-3574): reintroduce ObjectID export

---

src/connection_string.ts
src/mongo_client.ts
test/types/community/changes_from_36.test-d.ts
test/unit/mongo_client_options.test.js

compressors now accepts an array of strings in addition to the comma-delimited string as a way of setting the option, in accordance with the documentation; the TS type has also been updated to reflect the valid inputs

fix(NODE-3585): MongoClientOptions#compressors has incorrect type

---

src/bulk/common.ts
test/functional/bulk.test.js

`insertMany` now exposes the `errInfo` returned from the server on error the same way `insertOne` does

fix(NODE-3434): errInfo should be exposed on bulk write

---

src/connection_string.ts
src/mongo_client.ts
test/unit/core/connection_string.test.js
test/unit/mongo_client_options.test.js

Clarified wording in API docs around `tlsCertificateKeyFile` option, fixed the behavior to be as written; additionally added spec-compliant validation of multiple ssl/tls options set in the URI.

fix(NODE-3591): tlsCertificateKeyFile option does not default cert

---

src/collection.ts
src/operations/indexes.ts
test/types/indexes_test-d.ts

NODE-3599 `collection.indexes()` return type corrected to `Document[]`

fix(NODE-3599): incorrect indexes return type

---

src/gridfs/download.ts
src/gridfs/upload.ts
test/types/gridfs_types.test-d.ts

NODE-3559 Fix GridFS writeable stream type

fix(NODE-3559): incorrect GridFS stream type

---

src/operations/list_databases.ts
test/types/admin.test-d.ts

I took a look at the other listX() methods, we have strong type information for `listCollections()` that switches based on the nameOnly option, I figured we don't need the strict typing here but I'm open to changing that. `listIndexes()` has no type information, it returns an unannotated cursor so .toArray() will return `Promise<Document[]>`, which at least the array of objects part is correct.

fix(NODE-3609): correct listDatabases return type

---

package-lock.json
package.json

This PR upgrades optional-require to 1.1.8 for additional Yarn Berry PnP support. See https://jira.mongodb.org/browse/NODE-3622 for justification.

chore(NODE-3622): bump optional-require for additional yarn berry pnp support

---

docs/CHANGES_4.0.0.md

Calling out this change explicitly, since a user was surprised by it.

docs(NODE-3643): Discuss connection pool size options in 4.0 upgrade guide

---

.evergreen/config.yml
.evergreen/run-kerberos-tests.sh
.evergreen/run-tests.sh

3.x port
- we'll just switch fle versions based on nodejs version

test(NODE-3606): legacy and new versions of the CSFLE library

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/generate_evergreen_tasks.js
.evergreen/run-checks.sh
.evergreen/run-serverless-tests.sh
.gitignore
CONTRIBUTORS.md
package-lock.json
test/functional/core/tailable_cursor.test.js
test/functional/load-balancer-spec.test.js
test/spec/load-balancers/cursors.json
test/spec/load-balancers/cursors.yml
test/spec/load-balancers/sdam-error-handling.json
test/spec/load-balancers/sdam-error-handling.yml
test/spec/load-balancers/transactions.json
test/spec/load-balancers/transactions.yml
test/tools/runner/config.js
test/tools/unified-spec-runner/entities.ts
test/tools/unified-spec-runner/runner.ts
test/tools/utils.js

Adds the LOADBALANCED=ON setting to the create-instance.sh script usage. 
Syncs the load-balancers specs and runs them in our serverless testing
There's just a few more assertions a debug helpers that came up while figuring out the issues with these tests. No driver changes were needed. 
- I added the EJSON helper to the utils.js file, it came in real handy figuring out which clients were failing to connect
- I added a check to our run-checks.sh that will fail if you pushed changes without running generate_evergreen_tasks.js

chore(NODE-3552): test serverless behind a loadbalancer

---

src/mongo_types.ts

Typescript 4.5  is better at checking certain complicated types than before. Previously, it missed an error in mongo_types.ts in the use of SetFields and OptionalId.
SetFields passes an unconstrained type parameter, TSchema, to OptionalId, which does have a constraint:
```ts
export type OptionalId<TSchema extends { _id?: any }> = ...
```
Because the type was so complex, Typescript missed this before 4.5.
Looking at the comments for OptionalId, I believe the intent is to add `_id` to *any* type, not just ones that already have an `_id` field. So I moved the constraint into a conditional type instead.
Fixes https://jira.mongodb.org/browse/NODE-3668?jql=project%20%3D%20NODE%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22typescript%22%20ORDER%20BY%20priority%20DESC%2C%20updated%20 …

fix(NODE-3668): compile error with OptionalId on TS 4.5 beta

---

.evergreen/config.yml
.evergreen/config.yml.in

Fixes the error "The unauthenticated git protocol on port 9418 is no longer supported." when cloning drivers tools.
Uses https now to clone the repo on evergreen
No
Evergreen tasks would fail without this fix.

chore(NODE-3736): fix drivers tools cloning

---

src/db.ts
test/types/community/db/createCollection.test-d.ts

Add support for optional options in createColelction.
This adds support for calling createCollection with optional options.
This is useful if for example a wrapper function is used.
Overloads do not allow optional options.

fix(NODE-3726): add optional option overloads of Db's createCollection function

---

src/bulk/common.ts
test/types/community/bulk/bulk-operation-base.test-d.ts

Add overloads for BulkOperationBase's execute function.
This adds overloads to the execute function, to ensure void is returned if a callback is provided, 
and a promise is returned if no callback is specified.
Missing overloads.

fix(NODE-3727): add overloads for BulkOperationBase's execute function

---

src/cmap/connection.ts
src/operations/aggregate.ts
src/operations/command.ts
src/operations/execute_operation.ts
src/operations/operation.ts
src/sdam/server.ts
src/sdam/server_selection.ts
src/sdam/topology.ts
test/functional/crud_spec.test.js
test/spec/crud/unified/aggregate-write-readPreference.json
test/spec/crud/unified/aggregate-write-readPreference.yml
test/spec/crud/unified/db-aggregate-write-readPreference.json
test/spec/crud/unified/db-aggregate-write-readPreference.yml
test/unit/operations/aggregate.test.js
test/unit/sdam/server_selection.test.js

Allows $merge and $out aggregate operations to execute on secondaries. The logic here is:
1. If the server version is < 5.0, these operations always execute on the primary.
2. If the server version is >= 5.0, these operations operate using the provided read preference or the primary if none is provided.
The spec specifically avoids multi-version clusters, so we can handle this at server selection by implementing our own server selection function for this case that does not need to scan twice.
Includes NODE-3684 to skip $out/$merge tests on serverless
Operations can be flagged with `trySecondaryWrite` to use the new server selector function. This function looks at the read preference and common wire version of the topology to potentially change the read preference used to select the …

feat(NODE-3083): support aggregate writes on secondaries

---

src/utils.ts
test/unit/utils.test.js

Simplifying the logic so that we can reason more easily about the async scheduler.
The previous code was relying on the `NaN` `timeSinceLastWake` correctly falling through on first wake, this refactor makes it so we rely on a more straightforward boolean `cannotBeExpedited` instead. 
Updating tests to use synchronous assertions since sinon fake timers don't require async callbacks to execute.
No
Hopefully reduce chance of accidental bugs
- [N/A] PR title follows the correct format: `<type>(NODE-xxxx)<!>: <description>`

refactor: simplify async timer logic

---

src/utils.ts
test/unit/utils.test.js

When there is an unreliable clock we force async intervals to reschedule immediately.
The async interval check for negative clock times, like potentially AWS lambda, is moved to the first check so that we can potentially reschedule instead of just returning as was done previously.
No.

fix(NODE-3116): reschedule unreliable async interval first

---

src/operations/list_collections.ts
test/unit/operations/list_collections.test.js

This patch allows to pass `authorizedCollections` option when using `db.listCollections` method
`ListCollectionsOperation` class now has `authorizedCollections` defined and handled in a similar fashion to the `nameOnly` option
Not needed (I think)
This adds support for a `listCollections` command option that is helpful when you want to fetch a list of collections for the user that might not have enough privileges to list them otherwise. A full description can be found in [the `listCollections` command docs](https://docs.mongodb.com/manual/reference/command/listCollections/#listcollections)

feat(NODE-3728): Allow to pass `authorizedCollections` option to the `db.listCollections` method

---

src/transactions.ts
test/types/mongodb.test-d.ts
test/types/sessions.test-d.ts

Re: https://github.com/Automattic/mongoose/issues/10805
Right now, `startSession({ defaultTransactionOptions: { readConcern: { level: 'snapshot' } } })` fails to compile with a `Property 'toJSON' is missing in type '{ level: string; }' but required in type 'ReadConcern'.` error. This seems like something that should change.
`TransactionOptions.readConcern` is now a `ReadConcernLike`, which allows using strings or `{ level }` object.
Make `TransactionOptions` more user-friendly and line up with `Cursor#withReadConcern()` and `CollectionOptions`.

fix(NODE-3344): allow setting `defaultTransactionOptions` with POJO rather than ReadConcern instance

---

src/change_stream.ts
test/types/mongodb.test-d.ts

Added typescript generic typing to ChangeStreamEvents
The typing for `ChangeStreamEvents` was not generic, and did not contain `<TSchema>` so it was always assumed to be of type `Document`. This would affect code usage like this:
```typescript
interface MyDoc extends Document{
name: string
}
const client = new MongoClient('');
const coll = client.db('test').collection<MyDoc>('test');
coll.watch().on('change', c => c.fullDocument) 
// c.fullDocument above is typed as Document, but should be MyDoc
```
`ChangeStreamDocument` already had generic types, so I just passed through `<TSchema>`.
I tried it out locally and the typing showed correctly in my editor.
Could someone confirm that the `init` and `more` events do indeed return the same structure as `TSchema`, as I do not …

feat(NODE-3692): make change stream events typing more generic

---

src/collection.ts
test/types/mongodb.test-d.ts

[NODE-3446](https://jira.mongodb.org/browse/NODE-3446)
The mapReduce command is being deprecated.
No
This command predates our aggregation framework and have functionality which is superseded by the aggregate command. We do not intend to add it into the stable API and instead should deprecate it to preserve a smaller and more consistent API going forward.

feat(NODE-3446): deprecate mapReduce command

---

src/sdam/topology.ts
test/functional/connection.test.js

[NODE-3273](https://jira.mongodb.org/browse/NODE-3273) Remove undefined error parameter from topology "open" event
The error parameter is no longer being passed on the topology "open" event
No, this is an internal change
The error is always undefined based on the flow of the code, so there is no need to pass it.

refactor(NODE-3273): remove undefined error param from topology open event

---

docs/editor.md

Adding some helpful onboarding related to how we use VSCode to enable our tooling.
Helpful to new contributors!
- Ran `npm run check:lint` script
- Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)

chore: add our shared vscode settings

---

package-lock.json
package.json

Updates the `mongodb-connection-string-url` dependency to pull in a fix for electron 14+ users.

chore(NODE-3754): bump mongodb-connection-string-url to v2.2.0

---

src/collection.ts
test/types/community/collection/filterQuery.test-d.ts
test/types/community/collection/findX.test-d.ts
test/types/mongodb.test-d.ts
test/types/union_schema.test-d.ts

Adding a `WithId` wrapper to the return type of collection.findOne and collection.find
No, should be self documented by ts output and is otherwise (probably) expected behavior
Ran into a scenario similar to [NODE-3729](https://jira.mongodb.org/browse/NODE-3729) and after seeing [PR 3020](https://github.com/mongodb/node-mongodb-native/pull/3020) I wanted to suggest a more targeted solution that only impacts the find methods directly.
By changing only the return type of `.find()`; the `_id` property is correctly returned on all find operations. I limited the change to only instances where the return type for `.find()` isn't overridden because at that point the user is stating they want manual control over the resulting type and are responsible for their own `_id` definition (if one exists).

feat(NODE-3729): add withId to default return type for collection.find and collection.findOne

---

README.md
typedoc.json

typedoc no longer has the `toc` option. I've set the generator to remove internal symbols. And I've updated the link in our readme.
correctness!
- Ran `npm run check:lint` script

docs: remove toc option, update links
