lib/collection.js
I just noticed this in the docs and figured I'd send a PR rather than a bug report.
Feel free to kill this one and do your own change if you'd prefer different wording, I won't be offended ;)
=> Correcting findOne documentation

package.json
Analagous to 8a99da0d4a8a5c195f44e5b75d98c8230392f859
=> Fix a couple more incorrect URLs in package.json

README.md
`console.dir(docs) -> console.dir(docs);`
=> readme: add ";"

Makefile
`total` rule has alreay been deleted
=> delete unused .PHONY

lib/bulk/ordered.js, lib/bulk/unordered.js, lib/collection.js
I changed the files related to the following ticket on jira: https://jira.mongodb.org/browse/NODE-543
tests seem to work fine on my side.
=> fixed forceServerObjectId calls

README.md
Just some changes on README.
Did I forget anything to be changed ?
=> don't use insert, update, remove in README since they are deprecated

index.js
Would make life easier for mongoskin re: https://github.com/kissjs/node-mongoskin/commit/ab6247ca57391b340c71ca2dee8104b53b567ede :)
=> Export admin class

docs/reference/content/reference/gridfs/streaming.md
Consider this a draft, comments most welcome.
=> add GridFS streaming API article draft

lib/db.js, test/functional/index_tests.js
Suggested change base on the issue that was posted.
=> NODE-631 db.collection after db.close() > does not handle error

lib/mongodb/connection/repl_set/strategies/ping_strategy.js, lib/mongodb/connection/repl_set/strategies/statistics_strategy.js
ref https://github.com/mongodb/node-mongodb-native/pull/1322
=> fix strategy sort compare function

lib/db.js, test/functional/readpreference_tests.js
(also fixed typo in db.js on line 619: needed `options.`...)
This seems to fix my (easily testable) issues in Compass. Thanks! :)
=> Typo fix: 'readPeference', additional test

docs/reference/content/whats-new/upgrading.md
Additional note: I'm not sure why GitHub is showing 3 diffs in the file comparison, I only made two fixes and the third seems to be identical to the original.
=> Typo fixes

lib/collection.js, test/functional/readpreference_tests.js
Add the same fix from db.js to collection.js :)
=> convert custom readPreference objects in collection.js

docs/reference/content/getting-started/installation-guide.md
…ed the `--save` flag here as well.
Looks like a typo -- alternately we could remove "and add it to your package.json" on line 42.  Thanks!
=> [docs] small tweak to `kerberos` package install instructions

package.json
Hi Christian,
The package description right now is a little awkward, makes the driver seem like a legacy project rather than the official driver.
Also, what's the eta for 2.1.8?
=> Improve package.json description

test/functional/ssl_mongoclient_tests.js
See: https://github.com/christkv/mongodb-core/pull/85
=> Add tests for invalid SSL private key:

docs/reference/content/reference/ecmascript6/connecting.md
=> [docs] fix on ES6 connect documentation

docs/reference/content/installation-guide/index.md, docs/reference/content/tutorials/aggregation.md, docs/reference/content/tutorials/collections.md, docs/reference/content/tutorials/commands.md, docs/reference/content/tutorials/index.md, docs/reference/content/tutorials/projections.md
=> Phase2-2.1branch

docs/reference/layouts/shortcodes/basic-connection.html
Fixed small typo in ``basic-connection.html``.
=> Fixed small typo in 'basic-connection.html'

docs/reference/content/quick-start/index.md
=> Correction in index.md

docs/gridfs.md
Adding that the second parameter can also be an ObjectId
=> Adding _id

lib/collection.js
As specified in https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#basic
=> docs(collection): document ordered option for insertMany

lib/apm.js
Check needs to be != -1 and not truthy
=> Fix sensitive command check

docs/reference/content/quick-start/index.md
The comment for deleteOne was still "insert some documents"
=> Fix typo in node quickstart

lib/bulk/unordered.js, test/functional/insert_tests.js
=> fix(UnorderedBulkOperation): push correct index for INSERT ops

docs/reference/content/reference/ecmascript6/crud.md
ReferenceError: a is not defined
=> Update docs to avoid ReferenceError

lib/db.js, test/functional/db_tests.js
=> fix(db): don't remove database name if collectionName == dbName

lib/mongos.js, lib/replset.js, lib/server.js
The require function lookup algorithm already is relative to the file
you are requiring from.
Also see https://github.com/christkv/mongodb-core/pull/175
=> remove dynamic require

README.md
Noticed the issue when going through the project's readme, and I thought I'd fix it real quick.
=> Fix gitter badge link in README.md

lib/mongo_client.js, lib/replset.js, lib/server.js
This is continuation of https://github.com/christkv/mongodb-core/pull/183
=> 'family' was added to options to provide high priority for ipv6 addresses

lib/collection.js
=> clone insertMany options before mutating

lib/mongo_client.js
`promoteLongs` was listed twice
=> chore: remove duplicate option

lib/admin.js, test/functional/operation_example_tests.js
=> feat: add support for nameOnly option to listDatabases

lib/collection.js
Supports passing an index hint to the aggregate command
=> feat(aggregate): support hit field for aggregate command

test/functional/examples_tests.js
This ports a fix in #1556 to the 3.0 branch 🍕
=> [Port] Change 'updateOne' into 'replaceOne' in e.g 54

test/functional/apm_tests.js
APM tests are doing some instrumentation that is not undone
at the end of the test. This would prevent further tests from
completing. This change fixes one of the offending tests, while also
making it easy to do so for future tests.
=> test(apm): fix apm test teardown

README.md
This updates the documentation code comment to be correct and is cherry-picked from a 2.2 fix in #1574 to be in 3.0 🌴 
_sorry branch name should be just port lol_
=> Bring 2.2 documentation change to 3.0.0

CHANGES_3.0.0.md
=> docs(changes): adding 3.0 changes documentation for find changes

test/functional/operation_changestream_example_tests.js
This branch contains examples for using the new ChangeStream feature which will be used elsewhere in MongoDB in documentation 📖
=> ChangeStream Examples

lib/db.js
Backported from the 3.0.0 branch
NODE-1147
=> fix(list-collections): ensure default of primary ReadPreference

conf.json
Remove file lib/read_preferences.js from jsdoc config
=> docs(jsdoc): fixing jsdoc config

CHANGES_3.0.0.md
This is a guide on major changes to the driver in 3.0.0. 
WIP because I'm going through the changes and making sure nothing is missing.
=> Update Migration Guide for 3.0.0

test/functional/cursor_tests.js
Added a test to make sure we properly kill cursors
Fixes NODE-1214
=> test(cursor): ensure that we properly kill cursors

README.md
Putting a BIG BOLD NOTE at the top of the README that refers to
CHANGES_3.0.0.md, so people know about the breaking changes.
Fixes NODE-1229
=> docs(README): Updating readme to refer to CHANGES_3.0.0.md

test/environments.js
The sharded environment was previous broken due to the fact that the environment setup was not properly waiting for async events to occur in order (setup of `mongod`/`mongos` instances). This fixes all that.
=> NODE-1075 reenable sharded environment for testing (native)

lib/mongo_client.js
=> docs(client): updating api changes for 3.0.0

lib/collection.js, test/functional/collection_tests.js
=> feat(collection): expose `dbName` property of collection

docs/reference/README.md, docs/reference/static/js/java.js, docs/reference/themes/mongodb/README.md
Actually fix the version dropdown this time around
Fixes NODE-1235
=> docs(versions): fixing version dropdown

docs/reference/content/reference/ecmascriptnext/crud.md
missing declaring the col variable with collection name update
=> docs: update docs ECMAScript Next CRUD operations(update) missing collection name

README.md
The fixes are very few in quantity and only very minor issues can likely be ignored. 
> Missing comma after "However"
>Hyphen missing
=> Minor grammatical fixes to README

.eslintrc, lib/mongo_client.js, lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/server.js, lib/topologies/topology_base.js, package.json, test/functional/apm_tests.js, test/functional/crud_api_tests.js, test/functional/crud_spec_tests.js, test/functional/cursor_tests.js, test/functional/cursorstream_tests.js, test/functional/db_tests.js, test/functional/gridfs_stream_tests.js, test/functional/index_tests.js, test/functional/insert_tests.js, test/functional/operation_example_tests.js, test/functional/operation_generators_example_tests.js, test/functional/operation_promises_example_tests.js, test/functional/session_leak_test.js, test/functional/sharding_read_preference_tests.js, test/unit/sessions/client_tests.js, test/unit/sessions/collection_tests.js
Part of HELP-5834
Cannot be merged right now, as it needs a new release of mongodb-core
=> fix(sessions): move active session tracking to topology base

.eslintrc, lib/aggregation_cursor.js, lib/collection.js, lib/command_cursor.js, lib/cursor.js, lib/mongo_client.js, lib/topologies/topology_base.js, lib/utils.js, package.json, test/functional/aggregation_tests.js, test/functional/apm_tests.js, test/functional/causal_consistency_tests.js, test/functional/change_stream_tests.js, test/functional/cursor_tests.js, test/functional/examples_tests.js, test/functional/find_tests.js, test/functional/gridfs_stream_tests.js, test/functional/operation_changestream_example_tests.js, test/functional/operation_example_tests.js, test/functional/operation_generators_example_tests.js, test/functional/operation_promises_example_tests.js, test/functional/readpreference_tests.js, test/functional/session_leak_test.js, test/functional/sessions_tests.js
Fixes NODE-1326
WIP b/c it depends on https://github.com/mongodb-js/mongodb-core/pull/280
=> test(sessions): ensure cursors close sessions

lib/url_parser.js, test/functional/mongodb_srv_tests.js
=> fix(url_parser): support a default database on mongodb+srv uris

lib/db.js, test/unit/db_tests.js
=> fix(db): ensure `dropDatabase` always uses primary read preference

lib/db.js
Cleaned up this example a bit.
=> Clean up db example code

docs/reference/content/reference/management/apm.md, docs/reference/content/tutorials/crud.md, lib/collection.js, lib/cursor.js
=> chore(maxScan): deprecate maxScan query option

docs/reference/content/tutorials/crud.md, lib/collection.js, lib/cursor.js
=> chore(snapshot): deprecate snapshot option

lib/mongo_client.js
=> docs(minSize): document the minSize connection option

lib/mongo_client.js, test/functional/mongo_client_tests.js, test/functional/uri_tests.js
Adds the ability to opt-in to using the new spec-compliant url
parser.
Fixes NODE-1304
=> feat(urlParser): use core URL parser

lib/db.js, test/functional/index_tests.js
test(index): createIndex handles IndexKeySpecsConflict error
=> db(fix): createIndex handles IndexKeySpecsConflict

lib/authenticate.js, lib/db.js, lib/mongo_client.js, lib/url_parser.js, package.json, test/functional/saslprep_tests.js, test/functional/scram_sha_256_tests.js, test/functional/shared.js
Requires mongodb-js/mongodb-core#300
Fixes NODE-1311
Fixes NODE-1303
=> Implements SASLPrep and SCRAM-SHA-256

CHANGES_3.0.0.md
docs(changes_3.0.0): fix for a small typo
=> Fix for a small typo in CHANGES_3.0.0.md

lib/collection.js, test/functional/crud_api_tests.js
Fixes [NODE-1470](https://jira.mongodb.org/browse/NODE-1470)
=> fix(findOneAndUpdate): ensure that update documents contain atomic operators

lib/gridfs-stream/index.js, lib/gridfs-stream/upload.js, lib/gridfs/grid_store.js, test/functional/gridfs_stream_tests.js
=> feat(GridFS): add option to disable md5 in file upload

.travis.yml, test/functional/cursor_tests.js, test/functional/domain_tests.js, test/functional/error_tests.js
=>  test(Node10): updating travis to test against Node10 and Mongo 3.6

lib/db.js, test/unit/db_list_collections_tests.js
=> feat(listCollections): add support for nameOnly option

test/functional/aggregation_tests.js, test/functional/bulk_tests.js, test/functional/domain_tests.js, test/functional/error_tests.js, test/functional/mongo_client_tests.js, test/functional/operation_generators_example_tests.js, test/functional/operation_promises_example_tests.js, test/functional/promises_collection_tests.js, test/functional/promises_cursor_tests.js, test/functional/promises_db_tests.js, test/functional/promote_values_tests.js
Fixes [NODE-1431](https://jira.mongodb.org/browse/NODE-1431)
=> test(node): remove all node version filters less than 4.x

.npmignore
I don't think those files matter on npm
=> ignore other dotfiles on npm

lib/change_stream.js, lib/error_codes.js, test/unit/change_stream_resume_tests.js
Fixes NODE-1462
Requires mongodb-js/mongodb-core#309
=> feat(changeStream): allow resuming on getMore errors

lib/bulk/ordered.js, lib/bulk/unordered.js, test/functional/retryable_writes_tests.js, test/functional/spec/retryable-writes/README.rst, test/functional/spec/retryable-writes/bulkWrite.json, test/functional/spec/retryable-writes/bulkWrite.yml, test/functional/spec/retryable-writes/deleteOne.json, test/functional/spec/retryable-writes/deleteOne.yml, test/functional/spec/retryable-writes/findOneAndDelete.json, test/functional/spec/retryable-writes/findOneAndDelete.yml, test/functional/spec/retryable-writes/findOneAndReplace.json, test/functional/spec/retryable-writes/findOneAndReplace.yml, test/functional/spec/retryable-writes/findOneAndUpdate.json, test/functional/spec/retryable-writes/findOneAndUpdate.yml, test/functional/spec/retryable-writes/insertMany.json, test/functional/spec/retryable-writes/insertMany.yml, test/functional/spec/retryable-writes/insertOne.json, test/functional/spec/retryable-writes/insertOne.yml, test/functional/spec/retryable-writes/replaceOne.json, test/functional/spec/retryable-writes/replaceOne.yml, test/functional/spec/retryable-writes/retryableErrors.json, test/functional/spec/retryable-writes/retryableErrors.yml, test/functional/spec/retryable-writes/updateOne.json, test/functional/spec/retryable-writes/updateOne.yml
Fixes a retryable writes bug, and makes the retryable writes test runner up to date with latest config.
=> Node 1456/retryable writes more errors

conf.json
https://jira.mongodb.org/browse/NODE-1477
=> Add a title to Docs page

test/functional/retryable_writes_tests.js, test/functional/spec/retryable-writes/retryableErrors.json, test/functional/spec/retryable-writes/retryableErrors.yml
=> chore(retryableWrites): sync retryable writes tests

lib/collection.js, lib/cursor.js, lib/utils.js, test/functional/collations_tests.js, test/functional/cursor_tests.js
When a collation set is applied to a cursor,
the count method reflects this and returns
the correct value.
Fixes NODE-1369
=> fix(cursor): cursor count with collation fix

lib/collection.js, test/functional/crud_spec_tests.js, test/functional/spec/crud/read/count-collation.json, test/functional/spec/crud/read/count-collation.yml, test/functional/spec/crud/read/count.json, test/functional/spec/crud/read/count.yml
Deprecate count, implement and test countDocuments
and estimatedDocumentCount
Fixes NODE-1501
=> feat(collection): Implement new count API

lib/admin.js, lib/db.js, lib/operations/admin_ops.js
=> refactor(admin): move floating functions to admin_ops

lib/cursor.js, lib/operations/cursor_ops.js
=> refactor(cursor): move floating functions to cursor_ops

test/functional/operation_promises_example_tests.js
=>  docs(transactions): adding examples for transactions

lib/mongo_client.js, lib/operations/mongo_client_ops.js
=> refactor(mongo_client): move floating functions to mongo_client_ops

lib/bulk/common.js, lib/bulk/ordered.js, lib/bulk/unordered.js, test/functional/replset_operations_tests.js
=> fix(bulk): handle MongoWriteConcernErrors

lib/operations/collection_ops.js, test/functional/collection_tests.js
bulk updates and deletes cannot retry writes.
Fixes NODE-1534
=> fix(retryWrites): fixes more bulk ops to not use retryWrites

lib/collection.js
=> docs(count): document count api changes

lib/admin.js, lib/bulk/ordered.js, lib/bulk/unordered.js, lib/change_stream.js, lib/collection.js, lib/cursor.js, lib/db.js, lib/gridfs-stream/download.js, lib/gridfs-stream/index.js, lib/gridfs-stream/upload.js, lib/gridfs/grid_store.js, lib/mongo_client.js, lib/operations/collection_ops.js, lib/operations/cursor_ops.js, lib/operations/db_ops.js, lib/operations/mongo_client_ops.js, lib/topologies/mongos.js, lib/topologies/replset.js, lib/topologies/server.js
Change [param=null] to [param] to avoid
setting default value to null for optional
parameters.
Fixes NODE-1385
=> docs(options): options default to null

conf.json, docs/jsdoc-template/tmpl/container.tmpl, lib/mongo_client.js
Pulling in updated core docs for sessions
depends on mongodb-js/mongodb-core#328
=> docs(sessions): updating docs for sessions

lib/operations/mongo_client_ops.js
add missing legacy option name on warning message
=> add missing legacy option name on warning message

lib/operations/collection_ops.js, package.json, test/functional/collection_tests.js
Add tests that were node-specific or missing from spec tests.
Fixes NODE-1559
=> test(countDocuments): full test coverage for countDocuments

docs/reference/config.toml, docs/reference/content/upgrade-migration/main.md, docs/reference/data/mongodb.toml
=> docs(reference): fixing links in reference guide

lib/collection.js, lib/cursor.js, lib/db.js
Wraps deprecated functions with deprecatedOptions or util.deprecate.
Fixes Node-1430
=> feat(deprecation): wrap deprecated functions

lib/operations/collection_ops.js, lib/operations/cursor_ops.js, test/functional/cursor_tests.js
Fixes [NODE-1581](https://jira.mongodb.org/browse/NODE-1581)
=> fix(cursor): set readPreference for cursor.count

lib/mongo_client.js, lib/operations/mongo_client_ops.js
=> fix(teardown): properly destroy a topology when initial connect fails

lib/operations/mongo_client_ops.js
Fixes [NODE-1531](https://jira.mongodb.org/browse/NODE-1531)
=> fix(mongo_client): translate options for connectWithUrl

docs/reference/content/tutorials/connect/authenticating.md
=> Fix typo in Kerberos connection section

lib/bulk/common.js, lib/operations/collection_ops.js, lib/utils.js
=> fix(utils): only set retryWrites to true for valid operations

lib/collection.js, lib/options_validator.js, test/functional/insert_tests.js, test/unit/options_validator_tests.js
Fixes [NODE-1279](https://jira.mongodb.org/browse/NODE-1279)
=> feat(options_validator): implement schema validator for option types

package-lock.json, test/functional/gridfs_tests.js
Fixes test failure causes by combination of nodejs/node#22209 and an ambiguous test.
=> test(GridFS): fixes bug in node 10.10.x

lib/authenticate.js, lib/operations/mongo_client_ops.js, package-lock.json, package.json
Incorporates auth refactor into native. Uses MongoCredential
object in place of multiple auth options.
Part of NODE-1442
=> refactor(auth): incorporating auth refactor in to native

lib/collection.js, lib/options_validator.js, test/unit/options_validator_tests.js
Fixes [NODE-1673](https://jira.mongodb.org/browse/NODE-1673)
=> feat(options_validator): add overrideOptions functionality

test/functional/authentication_tests.js, test/functional/connection_tests.js, test/functional/operation_example_tests.js, test/functional/operation_generators_example_tests.js, test/functional/operation_promises_example_tests.js, test/functional/scram_sha_256_tests.js, test/functional/uri_tests.js
=> test(*): reenable all authentication tests for unified topology

lib/collection.js, lib/options_validator.js, test/unit/options_validator_tests.js
Fixes [NODE-1678](https://jira.mongodb.org/browse/NODE-1678)
=> feat(options_validator): implement assertArity

lib/collection.js, lib/operations/collection_ops.js, lib/operations/cursor_ops.js, lib/utils.js, test/functional/collations_tests.js
Ensure that collation is applied to all commands that support it, and additionally ensure that errors are caught and properly returned to users if they exist. 
**NOTE**: this supersedes #1789
=> refactor(collation): fix and improve collation support in native

lib/collection.js
I removed a number of defaults in the docs that were never applied in the
driver.
=> docs(collection): remove inaccurate defaults

lib/admin.js, lib/db.js, lib/mongo_client.js
=> Remove inaccurate defaults

test/functional/spec/retryable-writes/README.rst, test/functional/spec/retryable-writes/bulkWrite-serverErrors.json, test/functional/spec/retryable-writes/bulkWrite-serverErrors.yml, test/functional/spec/retryable-writes/bulkWrite.json, test/functional/spec/retryable-writes/bulkWrite.yml, test/functional/spec/retryable-writes/deleteMany.json, test/functional/spec/retryable-writes/deleteMany.yml, test/functional/spec/retryable-writes/updateMany.json, test/functional/spec/retryable-writes/updateMany.yml
Fixes NODE-1706
Fixes NODE-1714
=> test(retryableWrites): sync retryableWrites tests

.evergreen/config.yml, .evergreen/generate_evergreen_tasks.js
=> chore(ci): adding dubnium to evergreen config

lib/collection.js, lib/db.js, test/functional/cursor_tests.js
=>  feat(db): add options validation

lib/admin.js, lib/collection.js, lib/cursor.js, lib/db.js, lib/mongo_client.js, lib/operations/cursor_ops.js
=> feat(lib): add options validation to mongo_client, admin, and cursor

.travis.yml
=> chore: updating mongodb versions in travis

lib/collection.js, lib/operations/collection_ops.js
Fixes [NODE-1759](https://jira.mongodb.org/browse/NODE-1759)
=> feat(collection): add options validation to findAndModify and findAndRemove

lib/operations/mongo_client_ops.js, test/functional/authentication_tests.js
Fixes NODE-1765
(Currently working on Unit Tests)
=> fix(auth): remember to default to admin database

lib/gridfs-stream/index.js
Fixes [NODE-1705](https://jira.mongodb.org/browse/NODE-1705)
=> fix(gridfs-stream): add options validation

lib/gridfs-stream/index.js, lib/gridfs/grid_store.js
Fixes [NODE-1383](https://jira.mongodb.org/browse/NODE-1383)
=> fix(gridfs): remove shallowClone

lib/utils.js, package-lock.json, test/functional/spec/transactions/README.rst, test/functional/spec/transactions/bulk.json, test/functional/spec/transactions/bulk.yml, test/functional/spec/transactions/commit.json, test/functional/spec/transactions/commit.yml, test/functional/spec/transactions/error-labels.json, test/functional/spec/transactions/error-labels.yml, test/functional/spec/transactions/insert.json, test/functional/spec/transactions/insert.yml, test/functional/spec/transactions/pin-mongos.json, test/functional/spec/transactions/pin-mongos.yml, test/functional/spec/transactions/read-concern.json, test/functional/spec/transactions/read-concern.yml, test/functional/spec/transactions/retryable-abort.json, test/functional/spec/transactions/retryable-abort.yml, test/functional/spec/transactions/retryable-commit.json, test/functional/spec/transactions/retryable-commit.yml, test/functional/spec/transactions/run-command.json, test/functional/spec/transactions/transaction-options.json, test/functional/spec/transactions/transaction-options.yml, test/functional/transactions_tests.js
Fixes [NODE-1590](https://jira.mongodb.org/browse/NODE-1590)
=> test(transactions): sync transactions spec tests

lib/options_validator.js, test/functional/insert_tests.js, test/unit/options_validator_tests.js
Fixes NODE-1816
This PR includes the bug fixes from #1870.
=> fix(options_validator): use hasOwnProperty to check for presence of options

lib/operations/collection_ops.js, lib/operations/cursor_ops.js, lib/operations/db_ops.js, lib/operations/mongo_client_ops.js, lib/utils.js
=> fix(operations): do not call require in a hot path

lib/admin.js, lib/collection.js, lib/cursor.js, lib/db.js, lib/gridfs-stream/index.js, lib/mongo_client.js, lib/options_validator.js, test/unit/options_validator_tests.js
=> fix(options_validator): separate validate into type checking and application of defaults

lib/mongo_client.js, lib/operations/mongo_client_ops.js, lib/topologies/mongos.js, lib/topologies/native_topology.js, lib/topologies/replset.js, lib/topologies/server.js
=> fix(mongo_client): provide validation for MongoClient connect

lib/mongo_client.js, lib/options_validator.js, test/unit/options_validator_tests.js
=> fix(options_validator): warn on unknown options

test/examples/change_streams.js
Prefer use of streams to iterators, and document both approaches
DOCS-12248
=> doc(change-streams): update change streams examples to use streams

test/environments.js, test/functional/apm_tests.js, test/functional/find_tests.js, test/functional/insert_tests.js, test/functional/operation_example_tests.js, test/functional/sessions_tests.js, test/functional/sharding_connection_tests.js, test/functional/sharding_read_preference_tests.js
Fixes and/or removes any issues with our sharding tests, so that we can actually pass sharding tests in evergreen.
=> fix sharded tests

lib/utils.js, test/config.js, test/functional/collations_tests.js, test/functional/index_tests.js, test/functional/operation_example_tests.js, test/functional/operation_generators_example_tests.js, test/functional/operation_promises_example_tests.js
This is the native component to fixes for using the wire protocol refactor in `next`
=> NODE-1823: unified topology wire protocol port

test/examples/aggregate.js, test/examples/create_index.js, test/examples/run_command.js
=> docs: adding aggregation, createIndex, and runCommand examples

lib/operations/collection_ops.js, lib/operations/cursor_ops.js, lib/operations/db_ops.js, lib/operations/mongo_client_ops.js, lib/utils.js
Based on [this patch](https://gist.github.com/muradm/36e13bc2b51fa9edf4992a870c7dccac).
=> fix(lib): remove makeLazyLoader

lib/mongo_client.js, lib/operations/mongo_client_ops.js, lib/options_validator.js, test/functional/mongo_client_options_tests.js, test/functional/mongo_client_tests.js, test/unit/options_validator_tests.js
=> fix(mongo_client): remove validateOptions

lib/options_validator.js, test/unit/options_validator_tests.js
=> feat(options_validator): support deprecated aliases

test/functional/spec/transactions/commit.json, test/functional/spec/transactions/commit.yml, test/functional/spec/transactions/error-labels.json, test/functional/spec/transactions/error-labels.yml, test/functional/spec/transactions/retryable-commit.json, test/functional/spec/transactions/retryable-commit.yml, test/functional/transactions_tests.js
The native component of NODE-1848, which mostly involved syncing our transactions spec tests to verify that changes in core are functioning properly.
=> NODE-1848: majority write concern on txn retry (native)

lib/collection.js, lib/db.js
=> fix(lib): ensure bson options are honored

test/functional/change_stream_spec_tests.js, test/functional/spec/change-stream/change-streams.json, test/functional/spec/change-stream/change-streams.yml
=> test(change_stream): resync change stream tests to test all new notification types

test/examples/change_streams.js
=> docs(ChangeStream): updates resume token example

test/examples/transactions.js
=> docs(transactions): document using readPreference on transaction

.evergreen/config.yml, .evergreen/generate_evergreen_tasks.js, .evergreen/run-atlas-tests.sh, lib/authenticate.js, lib/operations/mongo_client_ops.js, package-lock.json, package.json, test/atlas_connectivity_tests.js
Please focus on correctness rather than suggestions for how to better write/format code here. This is just a backport of auth related work from `next` into `master` for the v3.2.0 release. The core component is forthcoming.
=> chore(auth): backport auth refactor to master

lib/collection.js
=> refactor(collection): deprecate parallelCollectionScan

lib/aggregation_cursor.js
=> refactor(aggregation): deprecate `$geoNear` agg stage helper

test/examples/aggregate.js
=> docs(aggregate): update docs to use cursors per docs request

lib/operations/mongo_client_ops.js
=> fix(mongo_client_ops): only skip authentication if no authMechanism is specified

lib/collection.js, lib/db.js, lib/operations/aggregate.js, test/functional/aggregation_tests.js, test/functional/crud_spec_tests.js, test/functional/spec/crud/README.rst, test/functional/spec/crud/db/db-aggregate.json, test/functional/spec/crud/db/db-aggregate.yml
=> feat(db): add database-level aggregation

.travis.yml, package-lock.json, test/functional/change_stream_tests.js, test/functional/replset_operations_tests.js, test/functional/session_leak_test.js, test/functional/transactions_tests.js
There were a few changes made recently which require minor changes to tests in native, primarily for `OP_MSG` support.
=> fix all replicaset tests

test/functional/crud_spec_tests.js
The recent introduction of db-level aggregation tests for CRUD
actually broke the tests on replsets (nobody's fault that the repl
set tests weren't enabled at the time). The gist of why it broke
is described in the "Extra Fields in Actual Documents" section of
the test runner definition, and is dealt with by using the
chai-subset plugin for chai. While I was here, I took the liberty
of also refactoring lots of duplicate code in the runner.
=> test(crud): fix broken CRUD replset tests, refactor and dedupe code

test/environments.js, test/functional/transactions_tests.js
Update test runner to pass tests for sharded transactions. Relies on https://github.com/mongodb-js/mongodb-core/pull/411
=> NODE-1743: pin sharded transactions

test/functional/transactions_tests.js
This modifies the test runner to run to spec by saving off the
session ids when they are created so that they can be used to check
expectations after cleanup. With the changes introduced in the core
component to this PR the id's are actually explicitly reset when
`endSession` is called, so the test was succeeding by side effect
previously.
=> test(transactions): ensure lsids are saved before cleanup

lib/operations/db_ops.js
=> fix(db_ops): rename db to add user on

test/functional/transactions_tests.js, test/match_transaction_spec.js
Creates a chai match function for running assertions on test expectations.
=> test: updating transaction test runner to use match function

lib/mongo_client.js, lib/operations/mongo_client_ops.js, lib/topologies/replset.js, lib/topologies/topology_base.js, package-lock.json, package.json, test/unit/sessions/collection_tests.js
The native component to https://github.com/mongodb-js/mongodb-core/pull/417
=> NODE-1828: cleanup async resources on close

test/functional/transactions_tests.js
Test runner was attempting to run sharded transaction tests
against 4.0.x servers. Modified the way tests are created
so that different topologies have different version requirements
Fixes NODE-1890
=> test(transactions): ensure test runner properly excludes sharded

lib/operations/mongo_client_ops.js
Here I provided a minor improvement for avoiding duplicated `_validOptions.indexOf(name) === -1` line processing
=> refactor: avoid duplication in invalid options notification processing

lib/collection.js, lib/operations/collection_ops.js, lib/utils.js
=> fix(collection): do not use resultMutator for insertMany

test/config.js, test/environments.js
SERVER-37631 requires that 3.6 servers have a command run on them
to report `logicalSessionsTimeoutMinutes` on connected proxies.
=> test: fix sessions tests on 3.6 sharded clusters

docs/reference/content/reference/management/sdam-monitoring.md
Hi!
I faced typo in docs:
– url param was missing in MongoClient constructor.
Thanks,
MongoDB fan, Maksym :)
=> docs: updating sdam-monitoring's code example

CHANGES_3.0.0.md
There was 404 links to Change Streams specs, so now the are proper.
=> Update links to Change Streams specs

package-lock.json, package.json, test/functional/mongo_client_tests.js, test/functional/spec/uri-options/README.rst, test/functional/spec/uri-options/auth-options.json, test/functional/spec/uri-options/auth-options.yml, test/functional/spec/uri-options/ca.pem, test/functional/spec/uri-options/cert.pem, test/functional/spec/uri-options/client.pem, test/functional/spec/uri-options/compression-options.json, test/functional/spec/uri-options/compression-options.yml, test/functional/spec/uri-options/concern-options.json, test/functional/spec/uri-options/concern-options.yml, test/functional/spec/uri-options/connection-options.json, test/functional/spec/uri-options/connection-options.yml, test/functional/spec/uri-options/connection-pool-options.json, test/functional/spec/uri-options/connection-pool-options.yml, test/functional/spec/uri-options/read-preference-options.json, test/functional/spec/uri-options/read-preference-options.yml, test/functional/spec/uri-options/single-threaded-options.json, test/functional/spec/uri-options/single-threaded-options.yml, test/functional/spec/uri-options/tls-options.json, test/functional/spec/uri-options/tls-options.yml, test/functional/uri_options_spec_tests.js
Fixes NODE-1740
Note: Travis will fail until [the core PR](https://github.com/mongodb-js/mongodb-core/pull/410) is merged.
=> test(uri_options): add URI Options spec tests

lib/db.js, lib/mongo_client.js
=> docs(readConcern): update all possible readConcern levels

docs/reference/README.md, docs/reference/content/reference/ecmascriptnext/crud.md, docs/reference/themes/mongodb/README.md, lib/aggregation_cursor.js, lib/bulk/common.js, lib/collection.js, lib/command_cursor.js, lib/cursor.js, lib/db.js, lib/gridfs/grid_store.js, lib/operations/collection_ops.js, lib/operations/db_ops.js, lib/operations/mongo_client_ops.js, lib/url_parser.js, lib/utils.js, test/functional/apm_tests.js, test/functional/cursor_tests.js, test/functional/gridfs_tests.js, test/functional/insert_tests.js, test/functional/operation_example_tests.js, test/functional/operation_generators_example_tests.js, test/functional/operation_promises_example_tests.js, test/functional/promises_db_tests.js, test/functional/url_parser_tests.js
Seems like the fixes from #1533 didn't make it into more recent versions, so I refixed the same typos in addition to a few new ones.
=> Fix various minor typos

lib/async/async_iterator.js
=> fix(async): rewrote asyncGenerator in node < 10 syntax

test/functional/transactions_tests.js
=> test(transactions): fix bug with sharded transaction tests

lib/gridfs-stream/download.js, test/functional/gridfs_stream_tests.js
=> fix(gridfs-stream): honor chunk size

lib/bulk/common.js, lib/bulk/ordered.js, lib/bulk/unordered.js, test/driverBench/common.js, test/functional/bulk_tests.js
Includes fixes for unordered bullk op executing in serial, and an update to driverBench
=> Node 1934/serialize unordered bulk op

lib/cursor.js, lib/dynamic_loaders.js, lib/operations/add_user.js, lib/operations/common_functions.js, lib/operations/count.js, lib/operations/create_collection.js, lib/operations/estimated_document_count.js, lib/operations/explain.js, lib/operations/has_next.js, lib/operations/map_reduce.js, lib/operations/next.js, lib/operations/operation.js, lib/operations/remove_user.js, lib/operations/rename.js, lib/operations/to_array.js
=> refactor(cursor): move operations to their own files

lib/operations/connect.js, lib/operations/mongo_client_ops.js, test/functional/spec/transactions/causal-consistency.json, test/functional/spec/transactions/causal-consistency.yml, test/functional/spec/transactions/commit.json, test/functional/spec/transactions/commit.yml, test/functional/spec/transactions/insert.json, test/functional/spec/transactions/insert.yml
=> feat(retryWrites): default retryWrites to true

lib/collection.js, lib/db.js, lib/mongo_client.js, lib/utils.js, lib/write_concern.js
=> refactor(utils): add WriteConcern type

lib/collection.js, lib/db.js, package-lock.json, package.json
Core PR: https://github.com/mongodb-js/mongodb-core/pull/427
=> refactor(lib): create ReadPreference.fromOptions

package-lock.json, package.json, test/functional/insert_tests.js
=> test(insert): check results returned by toJSON

lib/collection.js, lib/db.js, lib/operations/aggregate.js, lib/operations/collection_ops.js, lib/operations/command.js, lib/operations/db_ops.js, lib/operations/distinct.js, lib/operations/estimated_document_count.js, lib/operations/geo_haystack_search.js, lib/operations/list_indexes.js, lib/operations/map_reduce.js, lib/operations/stats.js, lib/utils.js
=> Embed inheritance of properties in Collection, Db, and MongoClient

lib/operations/find_and_modify.js, lib/operations/find_one_and_delete.js, lib/operations/find_one_and_replace.js, lib/operations/find_one_and_update.js
=> refactor(operations): findOneAnd* methods extend findAndModify

test/examples/change_streams.js, test/functional/change_stream_spec_tests.js
this should also be ported to #next
=> test(changeStream): fixes flakey changeStream tests

lib/core/topologies/read_preference.js, test/functional/readpreference_tests.js
=> fix(ReadPreference): only allow valid ReadPreference modes

lib/collection.js, test/functional/collection_tests.js, test/unit/collection_tests.js
=> fix(findOneAndReplace): throw error if atomic operators provided for findOneAndReplace

lib/admin.js, lib/bulk/common.js, lib/collection.js, lib/cursor.js, lib/db.js, lib/gridfs-stream/index.js, lib/gridfs/grid_store.js, lib/mongo_client.js, lib/operations/execute_operation.js, lib/utils.js, test/unit/db_tests.js, test/unit/execute_legacy_operation_tests.js
=> chore: rename executeOperation to executeLegacyOperation and executeOperationV2 to executeOperation

test/functional/error_tests.js
NODE-1480
Tests in `error_tests.js` were previously being skipped entirely. Now, the tests have been streamlined.
The `error_tests.js` file was modified to only contain meaningful tests and comply with current testing standards.
=> test(error_tests): streamline tests in error_tests.js

.travis.yml
We need to run Travis on our new test-runner branch.
The travis.yml file now includes the test-runner branch.
No.
=> chore(travis): add travis testing

test/functional/change_stream_spec_tests.js, test/functional/change_stream_tests.js, test/functional/spec/change-stream/README.rst, test/functional/spec/change-stream/change-streams-errors.json, test/functional/spec/change-stream/change-streams-errors.yml, test/functional/spec/change-stream/change-streams.json, test/functional/spec/change-stream/change-streams.yml
Updates ChangeStream tests.
- Synced tests
- minor changes to `test/functional/change_stream_spec_tests.js` to be spec compliant
Ignore all `test/functional/spec`, it is just syncing
=> update changeStream spec tests / test runner

lib/core/connection/connect.js
Porting https://github.com/mongodb-js/mongodb-core/pull/446 to the 'next' branch
=> fix(connect): don't treat 'connect' as an error event

docs/reference/content/tutorials/gridfs/streaming.md
=> docs(GridFS): fix typo

docs/reference/content/quick-start/quick-start.md
DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Connected successfully to server
=> Current URL string parser is deprecated

test/functional/connections_stepdown_tests.js
The required mongo versions have been updated in accordance with the spec.
No.
=> fix(connections_stepdown_tests): use correct version of mongo for tests

test/examples/change_streams.js
Attempt to remove client session leaks by encapsulating all
insert behavior into a class to manage the resource.
We continue to see the change stream examples fail to close an active session. this is an attempt to fix that. The theory is that it fails if you attempt to close the client in the middle of a write, as the client session will still have a checked-out server session. I wrapped all of the insert loops in a Looper class to ensure there is something to wait for so we do not do teardown until all writes are done.
=> test(ChangeStream): attempt to stabilize changeStream tests

.travis.yml
Added 4 more variants that test replicasets and mongoses against the 4.2 rc
nope
=> chore(travis): add 4.2 testing to travis

test/functional/collection_tests.js
=> test(collection): fixes test that failed to clean up client

.travis.yml, package-lock.json, package.json
=> add node v12 for travis tests

docs/reference/layouts/partials/header.html
=> docs(survey): remove link to survey

lib/collection.js
=> docs(findAndModify): link to official docs for lastErrorObject

test/examples/transactions.js
Adds an example tesst
Fixes NODE-2141
Added example test to `test/examples/transactions.js`
No
=> docs(withTransactions): add example usage of withTransaction

lib/core/connection/connection.js
=> docs(Connection): document internal connection

package-lock.json, package.json
Adds missing optionalDependency on `saslprep`
Fixes NODE-2225
=> fix(saslprep): add in missing saslprep dependency

docs/guide/tutorials/text-search.txt
=> docs(guide): convert /tutorials/text-search to rst

docs/guide/tutorials/projections.txt
Fixes NODE-2209
Added a big warning about trying to project with the second parameter of `find`.
=> docs(guide): converting /tutorials/projection.md to rst

docs/guide/tutorials/create-indexes.txt
Fixes NODE-2202
* Added a note about `createIndexes` at the bottom.
=> docs(guide): convert /tutorials/create-indexes.md to rst

docs/guide/tutorials/connect/connect.txt
=> docs(guide): convert /tutorials/connect/index.md to rst

docs/guide/tutorials/commands.txt
=> docs(guide): convert /tutorials/commands.md to rst

docs/guide/management/logging.txt
=> docs(guide): convert reference/management/logging to rst

lib/core/topologies/server.js
=> fix(replset): use correct `topologyId` for event emission

docs/guide/issues-help.txt
=> docs(guide): convert issue-help to rst

docs/guide/tutorials/geospatial-search.txt
Fixes NODE-2204
**NOTE**: Another file referencing the data-set at https://docs.mongodb.org/getting-started/node/import-data/
=> docs(guide): convert tutorials/geospatial-search to rst

docs/guide/tutorials/collections.txt
=> docs(guide): convert tutorials/collections to rst

lib/core/sdam/topology.js, test/functional/core/topology_tests.js, test/runner/filters/unified_filter.js
The `Topology` type gains a state machine for tracking its current
connection state.
NODE-2280
=> refactor(sdam): introduce a state machine for unified topology

.evergreen/config.yml, .evergreen/generate_evergreen_tasks.js
=> chore: remove evergreen targets that don't run newer node versions

docs/reference/content/reference/unified-topology/index.md
This begins the process of documenting the general design of the Unified Topology. Hopefully this should serve as a good resource to point confused users to, as well as guidance for our continued development of this piece of the driver.
=> doc: introduce documentation about the unified topology design

lib/core/error.js, lib/core/wireprotocol/command.js, test/functional/transactions_tests.js
Fixes NODE-2089
Reup of #2102 
=> fix(command): only add TransientTransactionError label when in a transaction

index.js
=> refactor: export all error types we use in the driver

lib/core/wireprotocol/command.js
=> fix(encryption): autoEncryption must error on mongodb < 4.2

lib/operations/connect.js, test/functional/client_side_encryption/spec_tests.js, test/runner/filters/client_encryption_filter.js
=> chore(encryption): use new API for loading encryption

docs/reference/content/reference/client-side-encryption.md
Fixes NODE-2265
Created https://jira.mongodb.org/browse/NODE-2336 to convert this to RST.
=> docs(encryption): add driver-specific guide to client-side encryption

lib/core/auth/scram.js, test/unit/core/scram_iterations.test.js
=> fix(scram): verify server digest after first `salsContinue`

1.4/driver-articles/mongoclient.html
change **readPrefrence** -> **readPreference**
=> docs(maintenance): correct typo in readPreference

docs/reference/content/reference/unified-topology/index.md
- Updated formatting in unified topology reference
- Fixed a type in the unified topology reference
No
=> docs: Fix type and formatting

README.md, docs/guide/issues-help.txt, docs/reference/content/issues-help.md
Links to MongoDB Community forums
=> updated community links to point to the new MongoDB Community forums

docs/reference/content/reference/ecmascriptnext/connecting.md
I think it isn't neccesary to import the assert module.
An imported module has removed
No, just a code line
=> Unused imported module assert

package-lock.json, package.json, test/unit/cmap/connection_pool.test.js
Pollyfill for `util.promisify` due to removal of `bluebird`.
=> Node 2498/polyfill promisify

package.json
Fixes bug introduced by changed npm scriopts
Removed globing in check:test
=> Node 2542/npm script bug

test/functional/uri_options_spec.test.js, test/spec/uri-options/README.rst, test/spec/uri-options/auth-options.json, test/spec/uri-options/auth-options.yml, test/spec/uri-options/tls-options.json, test/spec/uri-options/tls-options.yml
Ported spec tests & skip `tls` tests.
=> NODE-2528/3.6/tls-spec-skip

test/functional/change_stream.test.js
=> fix: linter issue

lib/operations/db_ops.js, test/benchmarks/driverBench/common.js
IGNORE version target in branch name
=> NODE-2536/3.5/node-circular-dependency-warnings

test/functional/shared.js
=> Rm use of object values

test/benchmarks/driverBench/common.js
=> test: fix benchmark import path

lib/change_stream.js, test/functional/change_stream.test.js
[NODE-2570](https://jira.mongodb.org/browse/NODE-2570)
=> refactor(ChangeStream): use maybePromise for next/hasNext

lib/cursor/cursor.js, lib/mongo_client.js, lib/utils.js, package-lock.json, package.json, test/functional/byo_promises.test.js, test/functional/promises_db.test.js, test/functional/spec-runner/index.js, test/unit/cmap/connection_pool.test.js
=> NODE-2490/master/port-maybe-promise-work

lib/cursor/core_cursor.js, test/node-next/es2018/cursor_async_iterator.test.js
=> fix: linting errors

lib/change_stream.js, test/functional/change_stream.test.js, test/functional/shared.js
merge to 3.6
[NODE-2598](https://jira.mongodb.org/browse/NODE-2598)
=> refactor(ChangeStream): use maybePromise for close, improve tests

lib/change_stream.js, test/functional/change_stream.test.js, test/functional/shared.js
merge to 4.0
NODE-2570
NODE-2598
=> refactor(ChangeStream): use maybePromise, improve tests

.evergreen/install-dependencies.sh, package.json, test/functional/change_stream.test.js, test/functional/logger.test.js, test/functional/shared.js, test/functional/shared.test.js
[NODE-2605](https://jira.mongodb.org/browse/NODE-2605)
- Merge into `3.6`
=> test: improve shared helpers

docs/reference/content/tutorials/text-search.md
https://jira.mongodb.org/browse/NODE-2592
```
docs: update to include atlas search
Add Atlas search to `$text` docs.
NODE-2592
```
=> [NODE-2592] docs: update to include atlas search (3.6)

docs/reference/content/tutorials/text-search.md
https://jira.mongodb.org/browse/NODE-2592
```
docs: update to include atlas search
Add Atlas search to `$text` docs.
NODE-2592
```
=> [NODE-2592] docs: update to include atlas search (master)

lib/change_stream.js, lib/core/cursor.js, test/functional/change_stream.test.js
[NODE-2626](https://jira.mongodb.org/browse/NODE-2626)
merge into 3.6
=> fix(ChangeStream): handle null changes

test/spec/retryable-reads/README.rst, test/spec/retryable-reads/aggregate-merge.json, test/spec/retryable-reads/aggregate-merge.yml, test/spec/retryable-reads/changeStreams-client.watch-serverErrors.json, test/spec/retryable-reads/changeStreams-client.watch-serverErrors.yml, test/spec/retryable-reads/changeStreams-client.watch.json, test/spec/retryable-reads/changeStreams-client.watch.yml, test/spec/retryable-reads/changeStreams-db.coll.watch-serverErrors.json, test/spec/retryable-reads/changeStreams-db.coll.watch-serverErrors.yml, test/spec/retryable-reads/changeStreams-db.coll.watch.json, test/spec/retryable-reads/changeStreams-db.coll.watch.yml, test/spec/retryable-reads/changeStreams-db.watch-serverErrors.json, test/spec/retryable-reads/changeStreams-db.watch-serverErrors.yml, test/spec/retryable-reads/changeStreams-db.watch.json, test/spec/retryable-reads/changeStreams-db.watch.yml, test/spec/retryable-reads/listIndexNames.json, test/spec/retryable-reads/listIndexNames.yml
=> chore: sync retryable reads tests for `listIndex` changes

test/unit/utils.test.js
Using sinon's ability to mock the system clock, we can make testing the interruptable async timer more deterministc across platforms.
NODE-2684
=> test: use sinon mock timers for determinstic timer testing

test/spec/auth/connection-string.json, test/spec/auth/connection-string.yml
Port of https://github.com/mongodb/node-mongodb-native/commit/e40b18e68a731e58e76c682b2f8791f9715dc79d
https://jira.mongodb.org/browse/NODE-2433
=> [PORT] NODE-2433/master/lift-restriction-auth-source

lib/error.js, test/spec/change-stream/README.rst, test/spec/change-stream/change-streams-errors.json, test/spec/change-stream/change-streams-errors.yml, test/spec/change-stream/change-streams-resume-whitelist.json, test/spec/change-stream/change-streams-resume-whitelist.yml
[NODE-2682](https://jira.mongodb.org/browse/NODE-2682)
=> fix(ChangeStream): make CursorNotFound error resumable

lib/core/sdam/monitor.js, lib/core/sdam/server.js, lib/core/sdam/server_description.js, test/unit/sdam/monitoring.test.js, test/unit/sdam/server_description.test.js
=> fix: IPv6 Address parsing in SDAM monitoring [3.5]

lib/core/sdam/monitor.js, lib/core/sdam/server.js, lib/core/sdam/server_description.js, test/unit/sdam/monitoring.test.js, test/unit/sdam/server_description.test.js
=> fix: IPv6 Address handling in SDAM monitoring [3.6]

test/functional/connections_stepdown.test.js, test/functional/spec-runner/context.js, test/spec/server-discovery-and-monitoring/integration/rediscover-quickly-after-step-down.json, test/spec/server-discovery-and-monitoring/integration/rediscover-quickly-after-step-down.yml
[NODE-2659](https://jira.mongodb.org/browse/NODE-2659)
port to master
=> test: avoid unable to acquire lock errors on primary stepdown

src/mongo_client.ts
docs: remove duplicated DriverInfoOptions typedef
=> docs: remove duplicated DriverInfoOptions typedef

test/spec/initial-dns-seedlist-discovery/direct-connection-false.json, test/spec/initial-dns-seedlist-discovery/direct-connection-false.yml
=> chore: adds test for SRV + directConnection

.evergreen/install-dependencies.sh, .evergreen/run-checks.sh, src/utils.ts
Adds our build script to our EVG's run-checks task.
=> chore: Check typescript compiles in CI

.evergreen/config.yml, .evergreen/generate_evergreen_tasks.js
https://jira.mongodb.org/browse/NODE-2634?filter=-1
=> NODE-2634/ocsp-4.4-latest-only

.eslintrc.json, src/cmap/auth/auth_provider.ts, src/cmap/connect.ts, src/cmap/connection.ts, src/cmap/connection_pool.ts, src/cmap/stream_description.ts, src/cmap/wire_protocol/command.ts, src/error.ts, src/operations/connect.ts, src/read_preference.ts, src/sdam/common.ts, src/sdam/events.ts, src/sdam/monitor.ts, src/sdam/server.ts, src/sdam/server_description.ts, src/sdam/server_selection.ts, src/sdam/srv_polling.ts, src/sdam/topology.ts, src/sdam/topology_description.ts, src/types.d.ts, src/utils.ts, test/unit/sdam/spec.test.js, test/unit/sessions/collection.test.js
Building upon the recently merged improved CMAP typings, this completes the SDAM typings so we can finish the rest of the project.
NODE-2726
=> refactor: complete typing for the sdam module

.evergreen/config.yml, .evergreen/config.yml.in, .evergreen/generate_evergreen_tasks.js, .evergreen/run-tests.sh, .evergreen/run-tls-tests.sh, package.json, test/manual/tls_support.test.js
=> chore(ci): add tls support test to evergreen

.evergreen/config.yml, .evergreen/generate_evergreen_tasks.js
Merger of:
* https://github.com/mongodb/node-mongodb-native/commit/dd7973bb9d47cdf110761a2cd3719f93b035d37c
* https://github.com/mongodb/node-mongodb-native/commit/edf429c25a40f54584709e583389a76d673bdf54
=> NODE-2634: MongoDB 4.4 / latest OCSP and AWS Auth testing

src/db.ts, src/operations/create_collection.ts, test/functional/collection.test.js, test/unit/db_list_collections.test.js
[NODE-2746](https://jira.mongodb.org/browse/NODE-2746)
=> feat(db): remove createCollection strict mode

lib/db.js
[NODE-2746](https://jira.mongodb.org/browse/NODE-2746)
=> feat(db): deprecate createCollection strict mode

.evergreen/config.yml, .evergreen/config.yml.in, .evergreen/generate_evergreen_tasks.js, lib/cmap/connection.js, package.json, test/manual/kerberos.test.js
=> fix: add host/port to cmap connection

lib/operations/create_indexes.js
https://jira.mongodb.org/browse/NODE-2755
=> fix: addeds text index options

README.md
Updated links in README to driver documentation and MongoDB.
=> DOCPS-11910: update links in README

CONTRIBUTING.md
Here's some literature on how to get up and running with the Node Driver Dev environment, as well as a section on some conventions we have. Hopefully this is a good start and can lead to a great resource for all contributors.
=> docs: Adds developer setup to contributor guide

lib/aggregation_cursor.js
=> fix: remove geoNear deprecation

src/mongo_client.ts, test/functional/mongo_client.test.js
NODE-2807
port of https://github.com/mongodb/node-mongodb-native/pull/2552
=> fix: readPreferenceTags type and client readPreference getter

lib/mongo_client.js, test/functional/mongo_client.test.js
=> fix: use options for readPreference in client

src/cursor/aggregation_cursor.ts
NODE-2834
port of https://github.com/mongodb/node-mongodb-native/pull/2561
=> fix: removed geoNear deprecation (master)

test/spec/server-discovery-and-monitoring/integration/isMaster-command-error.yml, test/spec/server-discovery-and-monitoring/integration/isMaster-network-error.yml, test/spec/server-discovery-and-monitoring/integration/isMaster-timeout.yml, test/spec/server-discovery-and-monitoring/monitoring/discovered_standalone.json, test/spec/server-discovery-and-monitoring/monitoring/discovered_standalone.yml, test/spec/server-discovery-and-monitoring/monitoring/standalone.yml, test/spec/server-discovery-and-monitoring/monitoring/standalone_suppress_equal_description_changes.json, test/spec/server-discovery-and-monitoring/rs/topology_version_greater.json, test/spec/server-discovery-and-monitoring/rs/topology_version_greater.yml
=> test: add directConnection spec tests

test/functional/deprecate_warning.test.js
NODE-2816
I accidentally deleted this test file in a previous PR.
=> test: reenable deprecation test

src/cursor/cursor.ts, test/functional/cursor.test.js
=> fix: remove Cursor#transformStream

.evergreen/config.yml, .evergreen/config.yml.in, .evergreen/generate_evergreen_tasks.js, .evergreen/run-data-lake-tests.sh, package.json, src/sdam/topology.ts, test/functional/spec-runner/context.js, test/functional/spec-runner/index.js, test/functional/spec-runner/utils.js, test/manual/data_lake.test.js, test/spec/atlas-data-lake-testing/aggregate.json, test/spec/atlas-data-lake-testing/aggregate.yml, test/spec/atlas-data-lake-testing/estimatedDocumentCount.json, test/spec/atlas-data-lake-testing/estimatedDocumentCount.yml, test/spec/atlas-data-lake-testing/find.json, test/spec/atlas-data-lake-testing/find.yml, test/spec/atlas-data-lake-testing/getMore.json, test/spec/atlas-data-lake-testing/getMore.yml, test/spec/atlas-data-lake-testing/listCollections.json, test/spec/atlas-data-lake-testing/listCollections.yml, test/spec/atlas-data-lake-testing/listDatabases.json, test/spec/atlas-data-lake-testing/listDatabases.yml, test/spec/atlas-data-lake-testing/runCommand.json, test/spec/atlas-data-lake-testing/runCommand.yml
=> test: adds tests for atlas data lake

README.md
Update the api-doc link to the version 3.6
=> fix: update api-doc link to version 3.6

src/collection.ts
=> feat: add types for the result of bulk initialize methods

src/cursor/find_cursor.ts, src/operations/find.ts
=> fix: min and max take Document parameters, not numbers

src/sessions.ts
=> fix: make the owner property of ClientSessionOptions optional

test/functional/command_write_concern.test.js
=> test: write concern command construction test cleanup

src/bulk/common.ts, test/functional/bulk.test.js
=> refactor: add batches accessor to BulkOperationBase

src/bulk/common.ts, src/bulk/ordered.ts, src/bulk/unordered.ts, src/index.ts, src/operations/delete.ts, src/operations/update.ts, test/functional/mongo_client_options.test.js
NODE-2957
**NOTE:** this is rebased on a few other PRs, it will translate to considerably less code once those are merged
=> refactor: move crud statements into respective operation files

package.json, src/cmap/events.ts, src/connection_string.ts, src/utils.ts
NODE-2120
**NOTE:** as the comment in the code says, this `deepCopy` is not meant to be comprehensive but instead just good enough for us to provide safe command monitoring. I'm also leaving more complex typing as an exercise for future maintainers.
=> refactor: introduce deepCopy, remove lodash dependency

src/sessions.ts
Just a tiny thing I happened to notice. :)
=> fix(ClientSession): correct toBSON TypeScript signature

package.json, test/functional/bulk.test.js
=> chore: add src directory to list of files included in package

src/cmap/connection.ts, src/operations/find.ts, test/functional/find.test.js
Port of  #2700 for `4.0`
NODE-2828
=> fix(find): correctly translate timeout option into noCursorTimeout

src/sdam/topology_description.ts, test/unit/core/common.js, test/unit/sessions/client.test.js
=> fix: session support detection spec compliance [PORT: 4.0]

src/deps.ts
See NODE-3107 / https://github.com/mongodb/libmongocrypt/pull/160
=> chore: add FLE AWS sessionToken TypeScript definitions

lib/core/sdam/monitor.js
=> fix(csfle): ensure monitoring connections are not encrypted

lib/core/connection/utils.js, lib/core/index.js, lib/core/utils.js, package-lock.json, package.json
This changes the dependency of require_optional to optional-require, which is currently maintained.
=> NODE-3050: Fix Infinite Loop with Optional Require on Windows

lib/operations/find.js
=> fix: ensure cursor readPreference is applied to find operations

test/spec/server-discovery-and-monitoring/errors/write_errors_ignored.json, test/spec/server-discovery-and-monitoring/errors/write_errors_ignored.yml
=> test(NODE-3070): Ensure that SDAM should ignore the writeErrors field

docs/reference/content/reference/management/apm.md
=> fix(docs): removing incorrect apm docs

lib/bulk/common.js, lib/operations/insert_many.js, test/functional/bulk.test.js, test/functional/crud_api.test.js, test/functional/operation_example.test.js, test/functional/operation_generators_example.test.js, test/functional/operation_promises_example.test.js
=> refactor: deprecate remove, removeOne, insertMany bulk operations

lib/core/topologies/replset.js
Change the state change to a legal transition
=> fix(NODE-3252): state transistion from DISCONNECTED

test/manual/atlas_connectivity.test.js
Made Atlas tests have a bit more patience.
=> test(NODE-3357): extend timeout for atlas connectivity

lib/core/connection/apm.js, test/functional/apm.test.js
=> fix(NODE-3356): update redaction logic for command monitoring events

test/spec/command-monitoring/unified/redacted-commands.json, test/spec/command-monitoring/unified/redacted-commands.yml, test/spec/unified-test-format/Makefile, test/spec/unified-test-format/invalid/entity-client-observeSensitiveCommands-type.json, test/spec/unified-test-format/invalid/entity-client-observeSensitiveCommands-type.yml
Syncs to latest command monitoring redaction tests in DRIVERS-1816
https://github.com/mongodb/specifications/pull/1026
=> test(NODE-3381): command monitoring redaction tests

package.json
Update package.json with author info and updated bug URL to point to NODE Jira project instead of the GitHub issues page. 
No
=> chore(NODE-3316): add author info and update bug url in package.json

src/error.ts
- Added `MongoRuntimeError` as per the proposed error class hierarchy
=> feat(NODE-3410): added MongoRuntimeError

lib/bulk/common.js, package-lock.json, package.json, test/functional/bulk.test.js
Same fix as in 4.0 the options provided at construction need to be joined with the options passed at execution.
NODE-1843
=> fix(NODE-1843): bulk operations ignoring provided sessions [PORT]

package-lock.json, package.json, src/bson.ts, src/deps.ts, src/encrypter.ts
Forward port of #2903, includes fix relating to https://github.com/mongodb-js/mongodb-connection-string-url/issues/2
=> fix(NODE-3199): unable to bundle driver due to uncaught require

package-lock.json, test/functional/write_concern.test.js, test/unit/core/write_concern_error.test.js
The new details property in 5.0 is already accesible we should just test to ensure it stays that way.
=> test(NODE-3082): details property from write errors is accessible

lib/core/connection/connection.js, lib/core/connection/pool.js, lib/core/sdam/topology.js, lib/db.js
Unref is now deprecated and marked to be removed in the next major version.
=> docs(NODE-3481): deprecate unref

src/change_stream.ts, src/cmap/auth/auth_provider.ts, src/cmap/auth/gssapi.ts, src/cmap/auth/mongo_credentials.ts, src/cmap/auth/mongodb_aws.ts, src/cmap/auth/scram.ts, src/cmap/commands.ts, src/cmap/connect.ts, src/cmap/connection.ts, src/cmap/connection_pool.ts, src/cursor/abstract_cursor.ts, src/db.ts, src/gridfs/download.ts, src/gridfs/index.ts, src/mongo_client.ts, src/operations/connect.ts, src/operations/execute_operation.ts, src/operations/is_capped.ts, src/operations/options_operation.ts, src/operations/profiling_level.ts, src/operations/set_profiling_level.ts, src/operations/validate_collection.ts, src/sdam/srv_polling.ts, src/sdam/topology.ts, src/sdam/topology_description.ts, src/sessions.ts, src/transactions.ts, src/utils.ts
Remove all instances of MongoDriverError and replace them with either MongoAPIError or MongoRuntimeError
=> refactor(NODE-3554): Prune MongoDriverError instances

README.md, package-lock.json, package.json
Documentation for errors, and BSON bump
=> docs(NODE-3569): describe the error API based on instanceof check

.evergreen/config.yml, .evergreen/config.yml.in, .evergreen/generate_evergreen_tasks.js, .evergreen/run-custom-csfle-tests.sh, .evergreen/run-tests.sh, test/functional/mongodb_aws.test.js, test/functional/spec-runner/index.js, test/spec/client-side-encryption/awsTemporary.json, test/spec/client-side-encryption/awsTemporary.yml
=> test(NODE-3409): support AWS temp credentials in CSFLE tests

test/examples/versioned_api.js
=> docs(NODE-3406): add versioned api examples

test/functional/change_stream.test.js
=> test(NODE-3293): clean up change stream tests setImmediate usage

package-lock.json, package.json
=> chore(NODE-3293): update semver

README.md
The current URLs were 404, this fixes that.
=> docs: fix compatibility urls

src/collection.ts, test/types/community/collection/aggregate.test-d.ts
An aggregation is the flexible Document type by default.
=> fix(NODE-3624): Incorrect default aggregation generic type

package-lock.json, package.json
=> chore: bump bson patch version

CONTRIBUTING.md
Clarified and cleaned the contributing guidelines.
CONTRIBUTING.md
No
Clarify what confused me as I joined the project so that others don't get stuck in the same ways
=> docs(NODE-3751): clarify contributing guidelines

etc/populate_spec_topics.sh
A helper script to assist with test clean up work.
I want the integration folder to remain closely in sync with the spec repo. A script to assist with that seems like a good way to keep with the practice. There are folders here which I believe may remain empty for sometime, but I think at somepoint we will either move in or have some case where it makes sense to put a test under a given topic.
-  Ran `npm run check:lint` script
=> chore: script populating integration spec topics

test/functional/connections_stepdown.test.js
NODE-3789
Tests with "Not Master" in their description have been updated to say "Not Primary"
No
Following the guidance documented in tools.ietf.org/id/draft-knodel-terminology-00.html, we will remove all oppressive and unnecessarily gendered language in driver documentation, code, tests, specs, and spec tests.
=> refactor(NODE-3789):Update tests with oppressive language in their description

package-lock.json, package.json
```
bson 4.6.1 -> 4.6.2
```
No.
=> chore: bump bson 4.6.1 -> 4.6.2

.evergreen/install-dependencies.sh
=> chore: fix windows file permission issue with npm version

.evergreen/config.yml, .evergreen/generate_evergreen_tasks.js
=> test(NODE-4216): add 6.0 server to CI matrix

test/integration/client-side-encryption/client_side_encryption.prose.test.js
=> chore(NODE-4162):  removed TODO

src/cmap/auth/scram.ts
No tests because the Node.js driver CI doesn’t have a FIPS setup.
MONGOSH-1232 will add integration tests for this message.
=> chore(NODE-4266): improve error message for SCRAM-SHA-1 in FIPS mode

src/operations/create_collection.ts, src/operations/drop.ts, test/spec/client-side-encryption/tests/fle2-CreateCollection.json, test/spec/client-side-encryption/tests/fle2-CreateCollection.yml
No new docs
See https://github.com/mongodb/specifications/pull/1215/files
=> refactor(NODE-4246): update FLE2 collection management

test/readme.md
Updates the setup documentation for testing csfle locally.
The test readme.
No
NODE-4382
=> test(NODE-4382): update fle setup in test readme

test/integration/change-streams/change_stream.test.ts, test/integration/change-streams/change_streams.spec.test.ts, test/readme.md, test/tools/unified-spec-runner/runner.ts, test/tools/unified-spec-runner/schema.ts, test/tools/unified-spec-runner/unified-utils.ts
https://jira.mongodb.org/browse/NODE-4431
[Evergreen patch with windows, linux & macos builds: https://spruce.mongodb.com/version/62d6be285623432d3942c9f8/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC](https://spruce.mongodb.com/version/62d6c30a3627e00541758146/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
=> chore(NODE-4431): fix failing change stream tests & csfle tests on windows

.evergreen/install-dependencies.sh
Clearing the cache fixes windows runs
green ci.
=> chore(NODE-4500): fix npm issue on windows

test/spec/client-side-encryption/tests/legacy/fle2-InsertFind-Unindexed.json, test/spec/client-side-encryption/tests/legacy/fle2-InsertFind-Unindexed.yml
Syncs a test fix for a new error message to fix a failing csfle test.
No.
Tests aren't supposed to fail.
=> test(NODE-4490): update expected error in fle2-InsertFind-Unindexed 

test/spec/change-streams/unified/change-streams-errors.json, test/spec/change-streams/unified/change-streams-errors.yml, test/spec/change-streams/unified/change-streams-pre_and_post_images.json, test/spec/change-streams/unified/change-streams-pre_and_post_images.yml, test/spec/change-streams/unified/change-streams-resume-allowlist.json, test/spec/change-streams/unified/change-streams-resume-allowlist.yml, test/spec/change-streams/unified/change-streams-resume-errorLabels.json, test/spec/change-streams/unified/change-streams-resume-errorLabels.yml, test/spec/change-streams/unified/change-streams.json, test/spec/change-streams/unified/change-streams.yml, test/spec/unified-test-format/valid-pass/poc-change-streams.json, test/spec/unified-test-format/valid-pass/poc-change-streams.yml
This syncs unified test changes from [DRIVERS-2288](https://jira.mongodb.org/browse/DRIVERS-2288).
No.
=> test(NODE-4200): sync serverless:forbid changes in change stream unified tests

.evergreen/config.yml, .evergreen/generate_evergreen_tasks.js, .evergreen/run-mongosh-integration-tests.sh
mongosh integration tests are now passing.
NODE-4593
=> chore(NODE-4593): fix mongosh integration tests

test/unit/index.test.ts
=> test(NODE-4607): add ConnectionPoolReadyEvent to exports unit test

.evergreen/config.yml, .evergreen/generate_evergreen_tasks.js, test/tools/cmap_spec_runner.ts, test/tools/runner/config.ts
=> test(NODE-4642): fix serverApi strict tests

etc/check-remote.sh, etc/docs/build.ts
Adds debug output to docs generation.
=> chore(no-story): add debug info to docs generation

.github/pull_request_template.md
=> chore: update PR template commit message example

README.md
=> docs(NODE-4909): update README.md quick links

.evergreen/run-mongosh-integration-tests.sh, test/integration/client-side-encryption/client_side_encryption.prose.test.js, test/tools/runner/hooks/configuration.js
=> test(NODE-4944): skip failing test on node19

src/cmap/auth/mongodb_aws.ts
Add a comment for a confusing bit of code
=> docs(NODE-4990): comment about serverNonce format

.evergreen/config.yml, .evergreen/generate_evergreen_tasks.js, .evergreen/run-tests.sh, test/integration/client-side-encryption/client_side_encryption.prose.21.automatic_data_encryption_keys.test.ts, test/integration/client-side-encryption/client_side_encryption.prose.22.range_explicit_encryption.test.ts
https://github.com/mongodb/node-mongodb-native/pull/3544
https://github.com/mongodb/libmongocrypt/pull/552
=> test(NODE-5015): clientEncryption createEncryptedCollection helper

.evergreen/ci_matrix_constants.js, .evergreen/config.in.yml, .evergreen/config.yml, .evergreen/generate_evergreen_tasks.js, .evergreen/generate_mongosh_tasks.js, .evergreen/run-mongosh-integration-tests.sh, .evergreen/run-mongosh-scope-test.sh, .evergreen/run-serverless-tests.sh, test/manual/mongosh_scopes.test.ts, test/readme.md
Applies changes from https://github.com/mongodb/node-mongodb-native/pull/3546 into main.
=> ci(NODE-5012): break apart mongosh integration tests (#3546)

test/integration/crud/insert.test.js
NODE-5059
SERVER-43894
Fixes failing tests on latest
=> test(NODE-5059): fix crud tests that assert result of drop

package-lock.json, package.json, test/integration/client-side-encryption/client_side_encryption.prose.test.js, test/integration/crud/insert.test.js, test/integration/node-specific/resource_clean_up.test.ts, test/integration/node-specific/resource_tracking_script_builder.ts, test/tools/fixtures/resource_script.in.js, test/tools/runner/config.ts
Backport of
https://github.com/mongodb/node-mongodb-native/pull/3553
=> test(NODE-5043): assert MongoClients are garbage collectable

.evergreen/config.yml, .evergreen/generate_evergreen_tasks.js
=> test(NODE-5035): skip oidc tests

test/spec/client-side-encryption/tests/legacy/fle2-CreateCollection.json, test/spec/client-side-encryption/tests/legacy/fle2-CreateCollection.yml, test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.json, test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.yml
…logger (#3532)### Description
=> test(NODE-5093): fix fle2 collection names in legacy fle2 tests

README.md
=> docs(NODE-5114): Update README.md

package-lock.json, package.json
=> deps(NODE-5282): bump bson to ^5.3.0

.evergreen/config.yml
Regenerates the config.yml
NODE-5315
=> test(NODE-5315): regenerate config.yml

.github/actions/setup.yml, .github/scripts/nightly.mjs, .github/workflows/build_docs.yml, .github/workflows/dependencies.yml, .github/workflows/release-alpha.yml, .github/workflows/release-nightly.yml
=> ci(NODE-5344): add alpha release automation

.github/workflows/release-4.x.yml
=> chore: update release 4x workflow name

.evergreen/config.in.yml, .evergreen/config.yml, .evergreen/generate_evergreen_tasks.js
=> ci(NODE-5654): remove vars from evergreen config

test/integration/client-side-encryption/client_side_encryption.prose.19.on_demand_azure.test.ts
Updates the Azure KMS endpoint and key name in addition to updating the evergreen environment variables to the new values.
Prose test and Evergreen environment variables.
None
NODE-5596
=> test(NODE-5694): update azure configuration

test/integration/client-side-encryption/client_side_encryption.prose.19.on_demand_azure.test.ts
Updates the Azure KMS endpoint and key name in addition to updating the evergreen environment variables to the new values.
Prose test and Evergreen environment variables.
None
NODE-5595
=> test(NODE-5695): update azure configuration

.github/workflows/release-nightly.yml
Uncommented the cron schedule
No
Folks can pull in the latest code for **test purposes only**.
=> chore: resume nightly releases

.evergreen/config.in.yml, .evergreen/config.yml, .evergreen/generate_evergreen_tasks.js, .evergreen/install-dependencies.sh
Update evergreen config to fix fle test setup
No
=> ci(NODE-5841): fix FLE test setup

.evergreen/config.yml, .evergreen/generate_evergreen_tasks.js
=> ci(NODE-5990): bump pinned commit for custom dependency tests

CONTRIBUTING.md
Update contribution README to have fork info.
See description.
This is a docs change.
To help users newer to open source have more context.
=> docs: Contribution README has fork info

package-lock.json, package.json
=> deps(NODE-6149): use bson 6.7.0

sbom.json
=> chore(NODE-6142): add sbom lite file to driver repo

.evergreen/ci_matrix_constants.js, .evergreen/config.yml, .evergreen/generate_evergreen_tasks.js
- add server 8.0 to evergreen
Compat table
- 8.0 coverage
=> ci(NODE-6163): add server 8.0 to evergreen

.github/scripts/highlights.mjs, .github/workflows/release.yml, .github/workflows/release_notes.yml, package-lock.json, package.json
- update release please owner
- make highlight use fetch and remove octokit
- new source for release please
- using fetch and "repository" variable makes copy pasting to other repos easier because there's now no owner/repo varaibles in the script that has to be changed.
=> chore(NODE-6170): update release please owner

src/collection.ts, src/index.ts, src/operations/count_documents.ts, test/integration/crud/abstract_operation.test.ts, test/integration/crud/crud_api.test.ts, test/mongodb.ts
Reverts mongodb/node-mongodb-native#4138
=> Revert "refactor: move CountDocument logic into collection API"

sbom.json
=> chore: add sbom-lite file to 5.x branch [skip-ci]

.github/workflows/release-5.x.yml, .github/workflows/release-6.8.yml
=> chore: specify branch when checking out GHA code

.evergreen/ci_matrix_constants.js, .evergreen/config.yml
Add Node.js 22 LTS to support matrix
No
=> ci(NODE-6557): Add Node.js 22 to support matrix

.evergreen/config.yml, .evergreen/generate_evergreen_tasks.js
=> ci(NODE-6748): unskip serverless tests

src/client-side-encryption/state_machine.ts
- Move KMS net socket creation into flagged path
No
The net socket was created unconditionally and in the finally block we destroy it which will reject the "willConnect" promise that is unhandled. Moving creation of the socket and the promise into a flagged path prevents this scenario. 
When using explicit encryption or automatic encryption, the driver makes requests to a Key Management System when to fetch key encryption keys.  The driver supports connecting to a KMS provider through a Socks5 proxy.  However, the socket used for the socks5 proxy was created in all circumstances, regardless of proxy configuration.  This leads to unhandled rejection errors when closing the socket the driver attempts to clean up the unused socket.
With the changes in this release, the socket is only created …
=> fix(NODE-6803): kms proxy socket creates unhandled rejection

test/integration/client-side-operations-timeout/client_side_operations_timeout.spec.test.ts
https://spruce.mongodb.com/version/mongo_node_driver_next_3d047ed19f6bf5c06e441fdf3a9c90b05ef9c15d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> ci: skip flaky test in CSOT test suite

README.md
=> docs(NODE-6819): remove mention of `yarn` from readme and update server compat matrix

test/tools/runner/flaky.ts
- add new test to the logging system
To get more information
=> chore: add logging for flaky tests

CONTRIBUTORS.md
Updating the contributors file
=> chore: add Neal Beeken to contributors list

release-please-config.json
=> chore(NODE-6967): remove skip-ci from release please config

README.md
Upgrade supports version, 4.0+  to 4.2+.
Support version on [README.md](https://github.com/mongodb/node-mongodb-native/blob/main/README.md)
no
Make README info correctly
=> chore(deps-dev): The driver currently supports 4.2+ servers.

README.md
=> chore: remove unintentional 4.2 server deprecation notice

.github/workflows/build_docs.yml
=> chore: fix missing hugo

.evergreen/install-mongodb-client-encryption.sh
=> ci: use python 3.7+ when building mongodb-client-encryption
