test/spec/atlas-data-lake-testing/estimatedDocumentCount.json
test/spec/atlas-data-lake-testing/estimatedDocumentCount.yml

ADL updated the reported wire version which changes which underlying command the driver uses for estimatedDocumentCount. Pulling in the test file changes corrects the test failure.

test(NODE-3778): sync ADL spec test files

---

src/connection_string.ts
test/unit/connection_string.test.js
test/unit/mongo_client.test.js

`dbName` option is not going to be deleted when `authSource` is present in the connection string.
I don't think there is unless this is intentional behaviour.
I have noticed that the `dbName` option is deleted when `authSource` is being passed in the connection string since version **4.2.0** (after [this commit](https://github.com/mongodb/node-mongodb-native/pull/3031#discussion_r748391108)) but I couldn't find any documentation for this neither the [MongoDB documentation](https://docs.mongodb.com/manual/reference/connection-string/#mongodb-urioption-urioption.authSource) nor in the [MongoDB driver documentation](https://mongodb.github.io/node-mongodb-native/4.2/classes/MongoClient.html#connect). I thought that this might be a bug since according to those documentations mentioned above, …

fix(NODE-3767): don't delete dbName if authSource is provided

---

test/unit/connection_string.test.js

For investigation of NODE-3763 added extra test cases to check the passed in options and not just the URI.
Additional tests added to verify some extra cases.
No
NODE-3763

test(NODE-3763): expand tls/ssl options parsing tests

---

src/change_stream.ts

`hasNext()` returns `Promise<boolean>` instead of `Promise<void>`. The type definition is wrong.
This initial pull request fixes one instance. There are more.

fix(NODE-2370): correct a return type of hasNext()

---

src/collection.ts
src/mongo_types.ts
test/types/community/collection/findX.test-d.ts
test/types/schema_helpers.test-d.ts
test/types/union_schema.test-d.ts

This is changing the internal definition of the `Filter` type to always apply `WithId` to the given `TSchema`.
FYI: I had to remove the old unused union schema unit tests, because it was throwing a TS error. I've reached out to @nbbeeken on another PR and he confirmed that we can remove those test assertions: https://github.com/mongodb/node-mongodb-native/pull/2972#issuecomment-964329383
No
Closes https://jira.mongodb.org/browse/NODE-3770
See discussion in https://github.com/mongodb/node-mongodb-native/pull/3044

fix(NODE-3770): Filter type uses WithId on the schema

---

CONTRIBUTING.md
test/readme.md

[NODE 3753](https://jira.mongodb.org/browse/NODE-3753)
Updating the Test readme to have more detailed information about the tests
No
The readme was lacking details that newbies need to understand the test infrastructure

docs(NODE-3753): Update testing readme file

---

src/error.ts
src/sessions.ts
test/functional/transactions.test.js
test/unit/error.test.js

The driver was retrying `commitTransaction` and `abortTransaction` but previously failing 4 spec tests that were tricking the driver to base retries on these commands on error code. The retryable writes spec defines the specific errors that are retryable, and the transactions spec states these 2 commands must adhere to that specification. The fact that an operation is retryable is stated as:
_When connected to a MongoDB instance that supports retryable writes (versions 3.6+), the driver MUST treat all errors with the RetryableWriteError label as retryable._
Note that the ticket was scoped to these two commands only, so the full gambit of retryable writes was not touched. There is a ticket to address that in NODE-3769.
This adds a new check for for if a transaction command can be retried, …

fix(NODE-3711): retry txn end on retryable write

---

.evergreen/run-serverless-tests.sh
test/integration/crud/bulk.test.js
test/integration/crud/crud.prose.test.js
test/integration/crud/crud.spec.test.js
test/integration/crud/crud_api.test.js
test/integration/load-balancers/load_balancers.spec.test.js
test/integration/max-staleness/max_staleness.test.js
test/integration/retryable-reads/retryable_reads.spec.test.js
test/integration/retryable-writes/retryable_writes.spec.test.js
test/integration/versioned-api/versioned_api.spec.test.js

NODE-3717
- crud and bulk tests were moved to `integration/crud`; one prose test was separated into a prose file from bulk
- max staleness test were moved to `integration/max-staleness` - they use a mock server but I think it's better to make them into proper integration tests than convert to a unit test (see my comment on this PR and new ticket)
- load balancer, retryable reads, and retryable writes tests have all been moved into a corresponding integration directory
NOTE: The changes in this PR affect the configuration for `run-serverless-tests.sh` we should double check to make sure all desired tests are still running (see my comment on that file).
N/A
Better test organization

refactor(NODE-3717): reorganize tests part 2

---

CONTRIBUTING.md

Update to the contributing guidelines to indicate that a feature deprecation is a "feat" commit type
No
I wasn't sure what commit type to use when I deprecated a feature

docs: Clarify that deprecation is a "feat" type commit

---

test/functional/explain.test.js

NODE-3801
Updated the currently failing tests to consistently check for indicator properties anywhere in the response object, regardless of nesting level. The property "queryPlanner" should be present in all cases. The property "executionStats" should only be present when additional verbosity is requested.
No
Latest server changed the shape of the explain output, so we need to update our tests to make our CI green again.

test(NODE-3801): fix explain tests to work with latest server

---

src/error.ts
test/functional/unit-sdam/topology.test.js
test/unit/error.test.js

NODE-3788
- Error codes with offensive names are being renamed
- Other offensive wording in error.ts is being renamed
The tests that reference these error codes are spec tests. Updates to those tests are covered in NODE-3791.
No
Following the guidance documented in https://tools.ietf.org/id/draft-knodel-terminology-00.html, we will remove all oppressive and unnecessarily gendered language in driver documentation, code, tests, specs, and spec tests.

refactor(NODE-3788): update names of offensive error codes

---

src/bulk/common.ts
src/collection.ts
test/types/community/collection/bulkWrite.test-d.ts
test/types/community/collection/replaceX.test-d.ts

`collection.replaceOne`, `collection.findOneAndReplace` and the `replaceOne` bulk operation now take a `WithoutId<TModel>` type for the replacement document.
I don’t think so. It should be self-documented from the tsdoc.
- The `_id` field is immutable, so it shouldn’t be required as it has to be the same value when passed.
- This makes `replaceOne` more in line with `insertOne`.

fix(NODE-3765): make replacement for replaceOne operations without _id

---

.eslintrc.json
src/cmap/stream_description.ts

Adds an eslint rule to catch my mistake. typeof x must be checked against one of the known string results.
A superficial bug where we might have been defining properties and setting them to undefined when we intented to filter them out. 
Since this bug has no virtually no impact, I decided against a ticket and even entering it into the changelog, happy to adjust.
- ~Changes are covered by tests~
- ~New TODOs have a related JIRA ticket~

chore: fix invalid use of typeof operator

---

package-lock.json
package.json

Updating the connection string url parser will disallow extraneous characters infront of the `mongodb://` or `mongodb+srv://` portion of a connection string.

fix: stricter protocol check in connection string

---

test/unit/imports.test.ts

Only import files that end in `.ts`
`.DS_Store` files make this test fail, so we should filter for .ts

chore: fix test importing non typescript files

---

src/mongo_client.ts

This method always returns the MongoClient on which it was called.

chore: stricten MongoClient.connect() return type

---

src/operations/find.ts

Fix a typo in `src/operations/find.ts`
Delete a redundant 'a'
No

docs: Fix a typo in FindOptions doc

---

.eslintrc.json
test/functional/change_stream_spec.test.js

Our linter will now error on (it/describe/context).only
This can just help us catch accidentally merging a .only usage
Peace of mind

chore: add lint rule to prevent .only usage

---

src/cmap/commands.ts
src/cmap/connection.ts
src/collection.ts
src/db.ts
src/read_preference.ts
test/functional/cursor.test.js
test/unit/db.test.ts
test/unit/read_preference.test.ts

NODE-3793
Remove and deprecate (when removal is not possible) all references to "slaveOk" in the source code and tests. Note that spec test updates are being tracked in NODE-3791
No
Following the guidance documented in tools.ietf.org/id/draft-knodel-terminology-00.html, we will remove all oppressive and unnecessarily gendered language in driver documentation, code, tests, specs, and spec tests.

feat(NODE-3793): Remove offensive language from code and tests

---

src/gridfs/upload.ts

Currently `GridFSBucketWriteStream.prototype.end()` returns `void`. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57473/files changed it so that `end()` now must return `this`, which means Mongoose and the Node driver are now incompatible with @types/node@17.0.6. First noticed this [here](https://github.com/Automattic/mongoose/runs/4686998575?check_suite_focus=true)
See above
No
Compilation fails with @types/node@17.0.6. I took a look and it looks like this change compiles fine with @types/node@16.x as well.

fix(NODE-3843): make `GridFSBucketWriteStream.prototype.end()` return `this` for compat with community nodejs types

---

src/gridfs/download.ts

Improving error message for when GridFS file `length` is less than the total length of the chunks' `data`. Below script triggers this error:
```javascript
'use strict';
const mongoose = require('mongoose');
const mongodb = mongoose.mongo;
run().catch(err => console.log(err));
async function run() {
await mongoose.connect('mongodb://localhost:27017/test');
const client = mongoose.connection.client;
await mongoose.connection.dropDatabase();
const _id = new mongoose.Types.ObjectId();
await client.db().collection('fs.files').insertOne({
_id,
length: 1, // <-- expecting that the file is only 1 byte...
uploadDate: new Date(),
chunkSize: 1
});
await client.db().collection('fs.chunks').insertOne({
files_id: _id,
n: 0,
data: Buffer.from('h')
});
await …
```

chore(gridfs): improve error message when overrunning file length

---

README.md

Updating the README api docs link to point to the api doc home page
This is docs :)
Until we get automation in place to ensure the api docs and the links to the docs are updated at the time of the release, we run the risk of publishing packages with README api links that incorrectly point to the previous version.

docs: update api link to point to home page instead of specific version

---

test/readme.md

Update the example command to run an Evergreen build using the Evergreen CLI
Example command in the Test readme
No
I got stuck when trying to use the current command in the readme

docs: update Evergreen CLI example command

---

src/bulk/common.ts
src/change_stream.ts
src/cmap/auth/mongo_credentials.ts
src/cmap/command_monitoring_events.ts
src/cmap/connect.ts
src/cmap/connection.ts
src/cmap/wire_protocol/compression.ts
src/constants.ts
src/deps.ts
src/operations/add_user.ts
src/sdam/events.ts
src/sdam/monitor.ts
src/sdam/server.ts
src/sdam/server_description.ts
src/sdam/topology.ts
src/sdam/topology_description.ts
src/utils.ts
test/functional/unit-sdam/server_selection/spec.test.js
test/functional/unit-sdam/topology.test.js
test/manual/socks5.test.ts
test/unit/_MISC_optional_require.test.js
test/unit/cmap/connection.test.js

Remove references to "master" throughout the codebase
- Any references to master that can be updated are updated or abstracted to a constant
- Any references to master that cannot be updated are deprecated
- Exceptions: 
- CSFLE references to masterKey are out of scope
- Historical documentation (e.g. history.md and changes_x.md) can remain as-is
- References to GitHub repos with master branches
- Spec tests are covered in NODE-3791
No
Following the guidance documented in tools.ietf.org/id/draft-knodel-terminology-00.html, we will remove all oppressive and unnecessarily gendered language in driver documentation, code, tests, specs, and spec tests.

fix(NODE-3792): remove offensive language throughout the codebase

---

test/spec/server-discovery-and-monitoring/errors/prefer-error-code.json
test/spec/server-discovery-and-monitoring/errors/prefer-error-code.yml

test(NODE-3787): sync preferring error codes over messages

---

src/connection_string.ts
test/unit/connection_string.test.ts

Adding test case and fix for a specified authSource but no further credentials provided.
The spec states that authSource can be ignored when no other credentials are given, we have a check that is throwing in this specific scenario because we still have an empty credentials object making it down to the connection creation layer.
This PR removes the credentials from the options object in this specific scenario and tests for it.

fix(NODE-3795): unexpected No auth provider for DEFAULT defined error

---

.evergreen/config.yml
.evergreen/config.yml.in
.evergreen/generate_evergreen_tasks.js
.evergreen/run-checks.sh
.evergreen/run-tests.sh
package.json

This PR adds code coverage generation for each build in Evergreen.
This PR does the following
- Adds a function to generate code coverage for each variant run in evergreen and upload it to s3 after each variant runs
- Adds a function (currently not used) to download all coverage reports for a patch, generate a combined coverage report and upload that to s3
- Adds a new build variant that depends on all other variants (currently commented out) to combine all coverage reports into one and upload it to s3 (calls the above function)
Nope

chore(NODE-3715): add code coverage generation to Evergreen tasks

---

src/change_stream.ts

This fixes the bug described in [Jira issue NODE-3621](https://jira.mongodb.org/browse/NODE-3621). The `documentKey` property on the `ChangeStreamDocument` type is currently typed incorrectly.
I have also checked the MongoDB Realm JS code and it appears the type is [implemented correctly](https://github.com/realm/realm-js/blob/6ba56fe83d3d36e3d07b90389e48f9e9aa98fc3f/types/services.d.ts#L264) in that codebase.

fix(NODE-3621): fixed type of documentKey property on ChangeStreamDocument

---

docs/CHANGES_4.0.0.md
src/cursor/find_cursor.ts
test/types/mongodb.test-d.ts

FindCursor.count will emit a warning once for the duration of the process, and the tsdoc states the deprecation and alternative APIs.
Our API docs will now flag this as deprecated
FindCursor.count executes a deprecated operation against MongoDB, countDocuments and estimatedDocumentCount are clearer APIs about what is being done database side.

feat(NODE-3867): deprecate cursor count and update v4 docs

---

test/spec/server-selection/server_selection/Unknown/read/ghost.json
test/spec/server-selection/server_selection/Unknown/read/ghost.yml
test/spec/server-selection/server_selection/Unknown/write/ghost.json
test/spec/server-selection/server_selection/Unknown/write/ghost.yml
test/unit/assorted/server_selection.spec.test.js

Spec test sync from here: https://github.com/mongodb/specifications/pull/1106/files
And some test code clean up.
Compliance!

test(NODE-3797): Ensure RSGhost servers are not selectable

---

test/integration/load-balancers/load_balancers.spec.test.js
test/tools/unified-spec-runner/entities.ts

NODE-3719, NODE-3543
Fixed the unified runner to not pass in URI options as an object, since that behavior is incorrect for URI-only options (like `loadBalanced`, and since they are already included in the generated URI string anyway.
N/A
Spec compliance review

test(NODE-3719,NODE-3543): fix unified runner to not pass uri opts in object and unskip lb tests

---

src/collection.ts
test/integration/client-side-encryption/client_side_encryption.spec.test.js
test/integration/command-monitoring/command_monitoring.spec.test.js
test/integration/retryable-reads/retryable_reads.spec.test.js
test/integration/transactions/transactions.spec.test.js

This PR updates `Collection.count` to use the legacy count operation.  It also unskips tests that were failing when `Collection.count` was modified to use the new count operation.

fix(NODE-3878): use legacy count operation on collection.count

---

src/cmap/auth/gssapi.ts
src/cmap/auth/mongo_credentials.ts
test/manual/kerberos.test.js

Sets the driver to use the proper `CANONICALIZE_HOST_NAME` option when using Kerberos.
Removes the old check of `gssapiCanonicalizeHostName` to use the proper option. This was dead code as it was not a public member of our `AuthMechanismProperties` and was not parsed by the URI.
No
NODE-3351

feat(NODE-3351): use hostname canonicalization 

---

test/spec/retryable-writes/insertOne-serverErrors.json
test/spec/retryable-writes/insertOne-serverErrors.yml
test/spec/transactions-convenient-api/commit-retry.json
test/spec/transactions-convenient-api/commit-retry.yml
test/spec/transactions/legacy/error-labels.json
test/spec/transactions/legacy/error-labels.yml
test/spec/transactions/legacy/mongos-recovery-token.json
test/spec/transactions/legacy/mongos-recovery-token.yml
test/spec/transactions/legacy/pin-mongos.json
test/spec/transactions/legacy/pin-mongos.yml
test/spec/transactions/legacy/retryable-abort.json
test/spec/transactions/legacy/retryable-abort.yml
test/spec/transactions/legacy/retryable-commit.json
test/spec/transactions/legacy/retryable-commit.yml

Removes the last of the legacy language (that isn't required for tests)
Wrap up the effort to remove the deprecated terms.

test(NODE-3885): update spec tests to remove legacy language

---

.evergreen/run-bson-ext-test.sh
.evergreen/run-tests.sh
test/integration/client-side-encryption/client_side_encryption.prose.deadlock.js
test/integration/client-side-encryption/client_side_encryption.prose.test.js

Updates mongodb-client-encryption to beta 4 and fixes shared imports in csfle tests.
Updates mongodb-client-encryption to beta 4 and fixes shared imports in csfle tests.
None
NODE-3777

chore: fix csfle imports and bump version

---

test/integration/causal-consistency/causal_consistency.prose.test.js
test/integration/change-streams/change_stream.test.js
test/integration/connection-monitoring-and-pooling/connection.test.js
test/integration/connections-survive-step-down/connections_survive_step_down.prose.test.js
test/integration/node-specific/operation_example.test.js
test/integration/node-specific/operation_promises_example.test.js
test/tools/reporter/mongodb_reporter.js
test/tools/runner/hooks/configuration.js
test/tools/utils.js

This PR cleans up the `skipReason` logic added in https://github.com/mongodb/node-mongodb-native/pull/3121.  By including the skipReason and the filter status `auth: disabled` in the metadata for tests that fail because `auth` was enabled, in cases where the test would not have run due to other requirements, we report the skip reason being that `auth` was enabled rather than the actual skip reason for the test.
This PR also fixes the broken AWS tests.
No.

test(NODE-3860): improve skipReason reporting for disabled 'auth' tests

---

.eslintrc.json
src/connection_string.ts
test/tools/uri_spec_runner.ts
test/unit/assorted/uri_options.spec.test.ts
test/unit/connection_string.test.ts

This PR does two things:
- fixes options parsing for arrays of options.
- refactors how we parse key-value pairs of options for a particular option.  In particular, it removes logic from parsing `readPreference` that was converting string values to native JS types, causing spec tests to fail
No.

fix(NODE-3813): unexpected type conversion of read preference tags

---

src/connection_string.ts
test/spec/uri-options/connection-options.json
test/spec/uri-options/connection-options.yml
test/unit/assorted/uri_options.spec.test.ts
test/unit/connection_string.test.ts

This PR updates the URI parsing logic to throw an error when the `directConnection` option is set with more than one host.
No, I don't think so.

fix(NODE-3917): Throw an error when directConnection is set with multiple hosts

---

docs/404.html
docs/index.html
docs/s/css/frontpage.css
docs/versions.json
etc/docs/build.ts
etc/docs/preview.ts
etc/docs/template/data/releases.toml
etc/docs/template/layouts/404.html
etc/docs/template/layouts/index.html
etc/docs/template/layouts/partials/banners/new_version.html
etc/docs/template/static/s/css/frontpage.css
etc/docs/template/static/versions.json
etc/docs/utils.ts

- Remove legacy 3x driver links
- Pin typedoc version
- Remove the version 3.6 banner from the index.html

docs: update build script to pin version of typedoc

---

test/integration/node-specific/examples/change_streams.test.js

NODE-4072
This PR updates usages of `.watch()` that were called with incorrect parameters (according to our Typescript) in the docs example change stream tests.
No.

docs(NODE-4072): update change stream example tests for the docs team

---

src/admin.ts
src/bulk/common.ts
src/change_stream.ts
src/collection.ts
src/cursor/abstract_cursor.ts
src/cursor/aggregation_cursor.ts
src/cursor/find_cursor.ts
src/db.ts
src/operations/add_user.ts
src/operations/common_functions.ts
src/operations/execute_operation.ts
src/operations/indexes.ts
src/operations/list_collections.ts
src/operations/map_reduce.ts
src/sessions.ts
src/utils.ts
test/integration/connection-monitoring-and-pooling/connection.test.js

This PR is a re-do of the work done by Daniel Lando (original PR: https://github.com/mongodb/node-mongodb-native/pull/3170).  I messed up the rebase and accidentally removed all changes.
All uses of `getTopology` that are used in an asynchronous manner now catch any errors thrown and pass the error along to the appropriate callback.
- All calls to `getTopology` that were used in conjunction with `executeOperation` were moved into `executeOperation`
- Tests were added to ensure we're handling the errors appropriately with both callbacks and promises
- Two other uses of `getTopology` (`indexInformation` and `AddUserOperation.execute`) were calling getTopology in an asynchronous context, so these two uses now handle the potential error thrown from `getTopology`.
- `getTopology` was enhanced …

fix(NODE-4074): ensure getTopology doesn't throw synchronously

---

src/deps.ts

Typings for (the current state of) https://github.com/mongodb/libmongocrypt/pull/265.

feat(NODE-4085): add typings for csfle shared library option support

---

test/tools/utils.ts

utils.js -> utils.ts
A FailPoint type interface makes a coder happy

chore: add failpoint interface

---

src/cmap/connection.ts
src/operations/operation.ts
src/sessions.ts
test/integration/sessions/sessions.spec.prose.test.ts
test/integration/sessions/sessions.test.ts
test/tools/cluster_setup.sh
test/tools/spec-runner/index.js
test/unit/sessions.test.js

- `incrementTransactionNumber` will no longer acquire a serverSession because it won't use the getter
With this change our driver will only acquire a serverSession when the getter is used which is in applySession, used inside the Connection class. This limits the number of serverSession allocated to be bounded by at least the number of concurrent operations running and at best by the max number of connection in our connectionPool.

feat(NODE-3697): reduce serverSession allocation

---

src/collection.ts
src/db.ts
src/mongo_client.ts

Constrain `watch` type parameter to same constraint as `ChangeStream`
Not
Starting with https://github.com/microsoft/TypeScript/pull/48366 we'll no longer be able to assign an unconstraint type parameter to a constraint one.
Constraining the type is required to pass https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59560

fix(NODE-4129): constrain `watch` type parameter to extend `ChangeStream` type parameter

---

src/mongo_types.ts
test/types/community/collection/filterQuery.test-d.ts

before:
after: 
not need
a tsc build error occurred for our specific requirements, after locating the cause several times, I think it is good for everyone, so fix it

fix(NODE-4133): array field NestedPaths return type

---

test/integration/sessions/sessions.spec.prose.test.ts

Fix up documentation on test
Sync with spec

test(NODE-4082): session spec prose test language clean up

---

test/integration/initial-dns-seedlist-discovery/initial_dns_seedlist_discovery.spec.test.ts
test/spec/initial-dns-seedlist-discovery/load-balanced/loadBalanced-directConnection.json
test/spec/initial-dns-seedlist-discovery/load-balanced/loadBalanced-directConnection.yml
test/spec/initial-dns-seedlist-discovery/load-balanced/loadBalanced-replicaSet-errors.json
test/spec/initial-dns-seedlist-discovery/load-balanced/loadBalanced-replicaSet-errors.yml
test/spec/initial-dns-seedlist-discovery/load-balanced/loadBalanced-true-txt.json
test/spec/initial-dns-seedlist-discovery/load-balanced/loadBalanced-true-txt.yml
test/spec/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-conflicts_with_loadBalanced-true-txt.json
test/spec/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-conflicts_with_loadBalanced-true-txt.yml
test/spec/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-zero-txt.json
test/spec/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-zero-txt.yml
test/spec/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-zero.json
test/spec/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-zero.yml

Updates the spec tests to verify DRIVERS-2224, which corrects the test cases for testing srv records in a load balancer environment.
None
DRIVERS-2224/NODE-4057

test(NODE-4057): update dns discovery tests

---

.github/workflows/build_docs.yml

Adds a github action to generate docs automatically off of commits to main and open a PR with the changes.
No.
Some notes
- If multiple changes come in before we merge the docs PR into main, the github action will automatically add the changes to the existing PR as to not create a duplicate PR.
- We don't pin a version of Hugo (our static site generator).  I don't think this is an issue because Hugo is widely used.  We've already been version hopping - the docs build in 4.5.0 used version 0.96 instead of 0.30 without issues.
- You can view the generated PR on my fork ([here](https://github.com/baileympearson/node-mongodb-native)).  It currently contains changes from two commits, including a change to a public interface (`ChangeStreamOptions`).

chore(NODE-4075): add docs generation workflow

---

test/spec/client-side-encryption/tests/badQueries.json
test/spec/client-side-encryption/tests/badQueries.yml
test/spec/client-side-encryption/tests/types.json
test/spec/client-side-encryption/tests/types.yml

A change in the error message in server 6.0 started causing issues with tests, this syncs a change where we test against a smaller subset of the error message that is unlikely to change. 
FLE tests passing.

test(NODE-4181): sync FLE test fixes for badQueries and types

---

.gitignore
test/integration/node-specific/bson-options/utf8_validation.test.ts

We accidentally left a sinon spy outstanding which accumulates memory for all the usages of the function. It started to cause an issue on my connect expirementation PR because failures seems to exagerrate the problem, with this change the memory usage of a test run remains constant.
Quick fix to help others that might hit this.

chore: fix sinon leak in tests

---

src/operations/command.ts
test/integration/enumerate_collections.test.ts
test/integration/enumerate_databases.test.ts
test/integration/enumerate_indexes.test.ts
test/tools/unified-spec-runner/match.ts

fix(NODE-4156): remove comment from commands pre-4.4

---

src/connection_string.ts
test/unit/connection_string.test.ts

https://github.com/mongodb/node-mongodb-native/pull/3138 broke options parsing for options that allow arrays of values.  This PR reverts the breaking changes from https://github.com/mongodb/node-mongodb-native/pull/3138, and then fixes read preference tags parsing again.
No.

fix(NODE-4031): options parsing for array options

---

.evergreen/config.yml
.evergreen/config.yml.in
src/connection_string.ts
src/mongo_client.ts
src/operations/connect.ts
src/operations/execute_operation.ts
src/sdam/topology.ts
test/integration/node-specific/feature_flags.test.ts
test/tools/spec-runner/index.js
test/tools/unified-spec-runner/entities.ts
test/unit/assorted/scram_iterations.test.ts
test/unit/connection_string.test.ts

We can now disable the initial ping with a flag. The unified runner and spec runner now disable the initial ping, and have had their "initial ping" handler code removed. 
Necessary drive by fixes:
- SCRAM iteration tests declared to the Topology directly which is something we want to do less of in tests anyway but this resulted in a timeout before fixing the defaulting of the flag. 
- EVG typescript tests were not marked as "test"s so they would appear purple instead of red when they failed
- TS fixes inside UnifiedMongoClient class, should be a type error free file now
For use only in testing, we can disable the fact that connect will send a ping if there are credentials, this will make auth errors surface during the first operation a test performs instead of during entity creation.

test(NODE-4152): make connect auth check configurable

---

src/cmap/commands.ts
test/unit/cmap/commands.test.js

Don't raise an error in the `Response` constructor.
Moves all logic that reads from the message body into the `parse` method to allow for any raised exception to be properly handled in a callback.
No.
NODE-3928

fix(NODE-3928): don't throw error in Response constructor

---

docs/4.2/index.html
docs/4.3/index.html
docs/4.4/index.html
package-lock.json
package.json

chore(NODE-4142): bump bson to 4.6.3 and fix broken link in docs

---

.evergreen/install-dependencies.sh

Upgrading nvm fixes an issue with installing node on windows.

chore: fix windows nvm version issue

---

src/deps.ts

Typings changes for https://github.com/mongodb/libmongocrypt/pull/306

feat(NODE-4136): revise FLE shared library typings for spec changes

---

etc/notes/CHANGES_4.0.0.md

chore(NODE-4171): add timestamp breaking change to 4_0_0 migration notes

---

src/change_stream.ts
src/constants.ts
src/error.ts
src/index.ts
src/utils.ts
test/unit/error.test.ts

In the upcoming change stream work a new type parameter made it difficult to plumb through all the new generic constriants to our floating functions. As all these functions do operate on a parameterized change stream it makes sense to make them private methods that have access to the type cosntraints/variables. 
The result of the executeOperation call is now typed as well, in addition to a small change to isResumable, all unknown errors are not resumeable.
More sensible generic sharing to the helper methods. None of the `private _X` methods should accept a generic of their own they will rely on the class scoped generics now.

refactor(NODE-4059): move free functions into ChangeStream class

---

.evergreen/config.in.yml
.evergreen/config.yml
src/cmap/auth/mongodb_aws.ts
src/error.ts
src/index.ts
test/integration/auth/mongodb_aws.test.js

NODE-4208
- Adding a new subclass of `MongoRunTimeError`: `MongoAWSError` (inspired by the analogous error class for Kerberos)
- Adding a handler for the http request timeout error for AWS requests
- Adding a new environment variable to the EC2 test suite so that the new integration test can run only in the EC2 environment (since the other AWS test suites have credentials already available without the http call)
No
Fixes a bug where the default specified timeout of 10000ms for aws http requests was not being respected.

fix(NODE-4208): add aws http request timeout handler

---

test/readme.md

Updates the test README's load balancer configuration instructions.
The load balancer config can no longer use mlaunch in the test script to work.
None

test: update load balancer configuration instructions

---

test/integration/server-selection/operation_count.test.ts

No.
We don't want to do TODOs for closed Jira tickets in the driver!

chore(NODE-4217): remove todos for won't do jira ticket

---

src/encrypter.ts
src/operations/create_collection.ts
src/operations/drop.ts
test/spec/client-side-encryption/tests/fle2-CreateCollection.json
test/spec/client-side-encryption/tests/fle2-CreateCollection.yml
test/spec/client-side-encryption/tests/noSchema.json
test/spec/client-side-encryption/tests/noSchema.yml
test/tools/spec-runner/index.js

See NODE-4202 / https://github.com/mongodb/specifications/commit/0142955943d91a783fc0314fb41a14e392bd15b6
Collection creation and dropping are extended to account for FLE2 properties according to spec.

feat(NODE-4202): add FLE 2 behavior for create/drop collection

---

src/cursor/find_cursor.ts
test/integration/crud/find_cursor_methods.test.js

See also:
* https://jira.mongodb.org/browse/MONGOSH-1183
* https://jira.mongodb.org/browse/PM-2742

feat(NODE-4185): Allow opting out of disk use on cursor builder

---

src/index.ts
src/operations/create_collection.ts
src/operations/indexes.ts
test/spec/collection-management/clustered-indexes.json
test/spec/collection-management/clustered-indexes.yml

MongoDB 5.3 added support for clustered collections. Clustered collections are collections with a clustered index.
I based the changes in this PR off how timeseries collections work.
Scope: https://docs.google.com/document/d/1r_1BBIlfELnKBz5qAzzLDUB-BJfGrQKTS2TNHXu4DRg/edit#heading=h.b1os3ai9s8t3

feat(NODE-4189): Support clustered collections

---

src/bulk/common.ts
src/operations/insert.ts
test/integration/crud/bulk.test.js

[NODE-3565](https://jira.mongodb.org/browse/NODE-3565)
- Adding a conditional to check if invalid operation is passed to raw, then throwing a more descriptive error.
- Adding int tests to verify the new error is being thrown at the appropriate time
No
The previous error being thrown was not descriptive.

fix(NODE-3565): Error for insertMany with partially empty array is unhelpful

---

src/change_stream.ts
src/cursor/abstract_cursor.ts
test/types/community/cursor.test-d.ts

AbstractCursor#stream also returns `AsyncIterator<TSchema>`
update autogenerated docs maybe
need to carry the type when doing async iteration over stream() result

fix(NODE-4232): stream() also returns generic AsyncIterable

---

test/integration/server-selection/operation_count.test.ts

This PR fixes a flakey test introduced in the operation count work.

test: fix flakey operation count test

---

global.d.ts
src/sessions.ts
src/transactions.ts
test/integration/transactions/transactions.test.ts

The `withTransaction()` function signature implies that `withTransaction()` returns the same value that the user-provided callback returns but that is incorrect.
Reported in https://github.com/Automattic/mongoose/issues/9919
Function signature for `withTransaction()` maintains the T argument but goes unused. Added tests for asserting the expected outcomes.
Fixes the type bug, but also adds documentation to the three possible outcomes of the function.

fix(NODE-4108): improve return type for withTransaction()

---

test/tools/runner/config.ts

CMAP spec tests were validly failing on CI when ran in the versioned api suite
Adds the `apiVersion` to the `MongoClient` when creating a new client from the test config via `newClient()` when `MONGODB_API_VERSION` is in the env. Should cover all cases for futureproofing.
None
Red build.

test: add api version when creating new test client

---

src/change_stream.ts
src/operations/create_collection.ts
test/integration/collection-management/collection_management.spec.test.js
test/spec/change-streams/unified/change-streams-pre_and_post_images.json
test/spec/change-streams/unified/change-streams-pre_and_post_images.yml
test/spec/collection-management/clustered-indexes.json
test/spec/collection-management/clustered-indexes.yml
test/spec/collection-management/createCollection-pre_and_post_images.json
test/spec/collection-management/createCollection-pre_and_post_images.yml
test/spec/collection-management/modifyCollection-pre_and_post_images.json
test/spec/collection-management/modifyCollection-pre_and_post_images.yml

- Adds support for pre/post images in change streams (https://jira.mongodb.org/browse/DRIVERS-1915)
- Adds tests for create collection and modify collection with pre/post image (https://jira.mongodb.org/browse/NODE-4210)
- Includes changes from https://github.com/mongodb/specifications/commit/d1458823bd810014df9da16d3a5354d2269ab865 (this commit is linked in NODE-4210)
No.

feat(NODE-3938): Add support for pre/post images in change streams

---

src/cmap/connection_pool.ts
src/cmap/connection_pool_events.ts
test/integration/connection-monitoring-and-pooling/cmap-node-specs/pool-minPoolSize-population-stats.json
test/integration/connection-monitoring-and-pooling/cmap-node-specs/pool-minPoolSize-replace-removed-connections.json
test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.spec.test.ts
test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.test.ts
test/tools/cmap_spec_runner.ts

NODE-2993
- Connection pool can now attempt to check out up to maxConnecting number of connections in parallel (previously it would only establish the requested connections one at a time)
- ensureMinPoolSize will now only attempt to create one connection at a time so as not to block checkout requests from obtaining connections as quickly as possible (since ensureMinPoolSize always adds the connections to the available pool first, a checkout request would otherwise have to wait to retrieve it from the pool instead of obtaining it immediately; this nonblocking behavior is relied upon by the "threads blocked by maxConnecting check out minPoolSize connections" spec test)
- The ConnectionCreatedEvent is now fired *before* actually establishing the connection, as required by the spec (the …

feat(NODE-2993): implement maxConnecting

---

src/cmap/connection.ts
src/cmap/message_stream.ts
src/sdam/monitor.ts
test/tools/utils.ts
test/unit/cmap/message_stream.test.js
test/unit/sdam/monitor.test.js

Only emits the last message from the message stream's buffer when using the streaming protocol.
The monitor will now tell the connection that it's using the streaming protocol, which in turn will
set the flag on the connection's message stream. When the stream is in this mode, it will only ever
emit the message event with the very last message in the buffer pool. So if there's more data in the
buffer, the stream essentially skips its emit.
None
NODE-4139

feat(NODE-4139): streaming protocol message changes

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
src/encrypter.ts

Allows setting mongodb-client-encryption to an env variable to locate it on the local filesystem.
Needs https://github.com/mongodb/libmongocrypt/pull/342 to work.
Update: changed csfle tests to run on replica sets here (NODE-4236) in order to get the now running tests to pass.
If `MONGODB_CLIENT_ENCRYPTION_OVERRIDE` is present, will attempt to require csfle from that location.
No
NODE-4254

fix(NODE-4254): allow csfle to be dynamically required

---

src/operations/create_collection.ts

Replace instances in code of FLE2 with Queryable Encryption.
2 comments in the code.
None
NODE-4265

chore(NODE-4265): fle2 -> queryable encryption

---

src/cmap/wire_protocol/constants.ts
test/unit/assorted/wire_version.test.js
test/unit/cmap/wire_protocol/constants.test.js

NODE-4229
Bumping maxWireVersion to 17 and max supported server version to 6.0 and updating the corresponding tests.
No
Keeping up with server updates

feat(NODE-4229): bump maxWireVersion to 17

---

src/change_stream.ts
test/integration/change-streams/change_stream.test.ts

As precursor to startSession without connection work I had to fix up change stream tests
Consolidates the initialize logic for iterable mode and event emitter mode. Clarifies clean up routines, makes heavy use of promises, bundling up many async tasks into one entry / one exit procedures.
Need to file TODOs

test: improve change stream tests

---

src/change_stream.ts
test/unit/change_stream.test.ts

- The `resumeOptions` getter on the change stream class copies all of the existing options (including bson options)
- The `resumeOptions` getter applies the `startAfter`, `resumeAfter` and `startAtOperationTime` properties to the resume options according to the spec (outlined [here](https://github.com/mongodb/specifications/blob/master/source/change-streams/change-streams.rst#resume-process))
- Deprecates the no longer used `ResumeOptions` interface
- Removes usages of `Reflect` in the `ResumeOptions` getter so that we have Typescript support when constructing the `ResumeOptions`
No.
This PR is the first step in addressing the change stream resumability issues in the Node driver.

feat(NODE-4081): fix and deprecate change stream resume options

---

.eslintrc.json
src/change_stream.ts
src/cmap/connection.ts
src/cmap/connection_pool.ts
src/sdam/monitor.ts
src/sdam/srv_polling.ts
src/sdam/topology.ts
src/utils.ts
test/integration/change-streams/change_stream.test.ts
test/integration/change-streams/change_streams.prose.test.ts
test/integration/crud/find.test.js
test/integration/crud/misc_cursors.test.js
test/integration/node-specific/cursor_stream.test.js
test/integration/node-specific/examples/change_streams.test.js
test/integration/node-specific/operation_example.test.js
test/integration/objectid.test.js
test/integration/server-selection/server_selection.prose.operation_count.test.ts
test/integration/shared.js
test/tools/mongodb-mock/src/server.js
test/tools/spec-runner/context.js
test/tools/utils.ts
test/unit/assorted/polling_srv_records_for_mongos_discovery.prose.test.ts
test/unit/cmap/connect.test.js
test/unit/cmap/connection.test.ts
test/unit/cmap/connection_pool.test.js
test/unit/error.test.ts
test/unit/sdam/monitor.test.js
test/unit/sdam/topology.test.js
test/unit/timer_sandbox.js
test/unit/utils.test.js

Ensure that the driver always uses the Node.js timers API, rather
than the global one, in case they diverge. This affects Compass,
where the `setTimeout(...).unref()` usage currently results in
uncaught exceptions because `setTimeout()` returns a number in
browsers.
This change adds `import ... from 'timers';` where necessary and
adds a linter rule to prevent regressions. If this is not
an acceptable solution, we can go back to the drawing board,
but this seems like a good solution that doesn’t add too much
overhead when writing driver code.
No
See ticket – `setTimeout().unref()` doesn’t work in Compass renderers

fix(NODE-4281): ensure that the driver always uses Node.js timers

---

src/deps.ts

Adjust the AutoEncryption typings as indicated in the updated spec.
(Changes to libmongocrypt are in https://github.com/mongodb/libmongocrypt/pull/352)

chore(NODE-4285): rename csfle shared library references

---

.evergreen/config.in.yml
.evergreen/config.yml

Skipping TS 4.8 for now, filed NODE-4293 to fix the issues.
Green CI

chore: skip failing TS version

---

.evergreen/run-tests.sh
src/cmap/connection.ts
src/encrypter.ts
test/integration/client-side-encryption/client_side_encryption.spec.test.js
test/spec/client-side-encryption/tests/create-and-createIndexes.json
test/spec/client-side-encryption/tests/create-and-createIndexes.yml
test/spec/client-side-encryption/tests/fle2-CreateCollection.json
test/spec/client-side-encryption/tests/fle2-CreateCollection.yml
test/spec/client-side-encryption/tests/fle2-validatorAndPartialFieldExpression.json
test/spec/client-side-encryption/tests/fle2-validatorAndPartialFieldExpression.yml
test/spec/client-side-encryption/tests/validatorAndPartialFieldExpression.json
test/spec/client-side-encryption/tests/validatorAndPartialFieldExpression.yml
test/tools/spec-runner/index.js

Adds list collections assertions in the create spec tests plus tests for create indexes and collmod.
Spec test sync. https://github.com/mongodb/specifications/commit/f0d133083c3e68c4d3227426d78b4116acf6382e and https://github.com/mongodb/specifications/commit/2fd6b69c9a0ad58d8c246a852fc389617de6e79d
None
NODE-4251/DRIVERS-2309

test(NODE-4251): sync csfle create spec tests

---

global.d.ts
src/change_stream.ts
src/cursor/abstract_cursor.ts
src/cursor/change_stream_cursor.ts
src/index.ts
test/unit/change_stream.test.ts

As a part of NODE-4125, I made a couple of small refactors.  NODE-4125 isn't done, but I broke these changes into a separate PR.  I made 6 distinct changes:
1. added another overload for `.only` describe blocks to our mocha config
2. moved change stream cursor into its own file in the cursors subdirectory
3. added a doc comment to the `next<T>` function, explaining what the `blocking` parameter does
4. moved the `tryNext` function on the change stream to be grouped with the other iterator methods
5. created a custom readable that extends Readable instead of using the Readable constructor method the Node library provides
6. gets rid of a duplicate function that handled unresumable errors in favor of the existing class method
I think point 5 is probably the only change that will cause …

refactor(NODE-4125): misc change stream improvements

---

test/unit/connection_string.test.ts

Change in a unit test so that the error message is tested correctly
No
To include more information in enum option error messages for connection string parsing.
For connection string parsing for the compressors option: Current unit test did not check properly if the correct enum options were provided in the error message, and was giving a false positive.

test(NODE-3218): Consistent error message for connection string parsing

---

test/spec/client-side-encryption/tests/fle2-Compact.json
test/spec/client-side-encryption/tests/fle2-Compact.yml
test/tools/spec-runner/index.js

Syncs FLE2 compact tests.
Syncs the fle2-Compact tests an updates the legacy spec runner to work properly when `encrypted_fields` is provided.
None
NODE-4224

test(NODE-4224): sync fle2 compact tests

---

package-lock.json
package.json

chore: remove accidental dependency

---

src/change_stream.ts
src/cursor/change_stream_cursor.ts
src/sdam/topology.ts
test/integration/change-streams/change_stream.test.ts
test/tools/unified-spec-runner/operations.ts
test/tools/utils.ts

This PR address resumability issues in the iterator-based API for change streams.
As much as I tried to separate the refactor from the code changes, I ended up making a few refactors as a part of this PR.
1. 44635ba30e9dc93559ba1bfe98fcc65ff062e79a makes the cursor property on the change streams always defined (non-optional).  This was primarily to make tests that use the cursor easier to work with.
2. 881dcf2c460a82018b3476262b989c8f24809fb7 breaks apart the error handling for iterator and event emitter modes.  Although this does result in some duplicated code, it did simply each method and allowed the promisifying of iterator-mode resume without modifying event emitter mode resuming.
3. I made each iterator method (tryNext, next and hasNext) internally use async IIFEs.  I did this for …

fix(NODE-4125): change stream resumability

---

test/integration/client-side-encryption/client_side_encryption.prose.test.js

Add the decryption events prose tests for CSFLE.
4 new prose tests have been added to test command monitoring when using CSFLE in various cases. I've copied and pasted the prose tests as comments in the code. The new prose tests language can also be referenced here: https://github.com/mongodb/specifications/commit/f9cbedafe53faffd62f15bcb2e952d1e016934e9
None
NODE-4296

test(NODE-4296): add csfle decryption events prose tests

---

src/deps.ts

Removes the experimental tags for the shared csfle library.
The `extraOptions.cryptSharedLibPath` and `extraOptions.cryptSharedLibRequired` provided as auto encryption options are GA and no longer experimental.
No changes to mongodb-client-encryption.
Update release notes on next release to note this.
NODE-4301

feat(NODE-4301): remove shared lib experimental tags

---

.evergreen/run-tests.sh
test/integration/client-side-encryption/client_side_encryption.prose.test.js
test/integration/shared.js
test/spec/client-side-encryption/etc/data/encryptedFields.json
test/spec/client-side-encryption/etc/data/keys/key1-document.json

Adds explicit encryption prose tests
Adds 5 new prose tests for #12 in the client side encryption spec. https://github.com/mongodb/specifications/blob/7f37c9325b423223edf54d795afed444e6989b98/source/client-side-encryption/tests/README.rst#explicit-encryption
I've also included the spec prose test language in code comments in the test here for easier following.
No
NODE-4227

test(NODE-4227): add explicit encryption prose tests

---

test/integration/collection-management/collection_management.spec.test.js
test/integration/command-monitoring/command_monitoring.spec.test.ts
test/integration/load-balancers/load_balancers.spec.test.js
test/integration/unified-test-format/unified_test_format.spec.test.ts
test/tools/unified-spec-runner/runner.ts
test/tools/unified-spec-runner/schema.ts

This PR enhances the skip test functionality of the unified runner.  Rather than accepting an array of tests to skip, the runner now takes a function that is evaluated to determine whether a test should be skipped.
This PR also updates the existing usages of `runUnifedSuite` that skip tests to use the new function approach.
Finally, some tests relating to auto connect and change stream resumability were unskipped.
Negative.

chore(NODE-4348): enhance skip reason filtering in unified runner

---

src/collection.ts

API documentation calling out that `initializeUnorderedBulkOp` and `initializeOrderedBulkOp` require a connected client.
These APIs rely on information obtained from the hello response from the server. Restructuring the code to run batching logic after a hello has been exchanged would be a significant amount of effort. We defer to a future project to make this possible. 
NODE-4263
Follow up: https://jira.mongodb.org/browse/NODE-4360

docs(NODE-4263): document initialize bulk op function require connection

---

.eslintrc.json
src/change_stream.ts
src/cmap/command_monitoring_events.ts
src/cmap/connect.ts
src/cmap/connection.ts
src/cmap/wire_protocol/compression.ts
src/collection.ts
src/cursor/abstract_cursor.ts
src/deps.ts
src/mongo_client.ts
src/operations/common_functions.ts
src/operations/execute_operation.ts
src/read_preference.ts
src/sessions.ts
src/utils.ts

Adds `@typescript-eslint/recommended-requiring-type-checking` rules which include enforcing promise returning functions are awaited.
Skips the following:
- @typescript-eslint/no-unsafe-member-access
- @typescript-eslint/no-unsafe-argument
- @typescript-eslint/no-unsafe-assignment
- @typescript-eslint/no-unsafe-return
- @typescript-eslint/no-unsafe-call
- @typescript-eslint/restrict-plus-operands
- @typescript-eslint/restrict-template-expressions
I'll file follow up tickets for us to address these.
There are outstanding TODOs that need discussion.
We can use async await internally as long as we pass the result through our callback / maybePromise handling logic. We want this lint rule to help us catch any mistakes where we might forget to await a promise returning funciton.

chore(NODE-4321): add typescript to eslint rules

---

.eslintrc.json
src/mongo_types.ts
src/operations/get_more.ts
src/utils.ts
test/benchmarks/driverBench/common.js
test/integration/server-selection/readpreference.test.js
test/tools/unified-spec-runner/match.ts
test/types/community/client.test-d.ts
test/types/enum.test-d.ts
test/unit/assorted/server_discovery_and_monitoring.spec.test.ts

eslint will now tell us if a code change removes a rule disable usage. a la ts-expect-error behavior
No need to let eslint disables fall out of sync with the code it was referring to below it.

chore: remove unusued eslint directives

---

test/integration/client-side-encryption/driver.test.js

Adds test for NODE-4260
Adds new test but requires https://github.com/mongodb/libmongocrypt/pull/383 to pass.
None
NODE-4260

test(NODE-4260): add test for csfle bulk write error

---

.evergreen/run-custom-csfle-tests.sh
.evergreen/run-tests.sh
test/integration/client-side-encryption/client_side_encryption.prose.test.js
test/integration/client-side-encryption/driver.test.js
test/spec/client-side-encryption/tests/legacy/fle2-Delete.json
test/spec/client-side-encryption/tests/legacy/fle2-Delete.yml
test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-jsonSchema.json
test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-jsonSchema.yml
test/spec/client-side-encryption/tests/legacy/fle2-FindOneAndUpdate.json
test/spec/client-side-encryption/tests/legacy/fle2-FindOneAndUpdate.yml
test/spec/client-side-encryption/tests/legacy/fle2-InsertFind-Indexed.json
test/spec/client-side-encryption/tests/legacy/fle2-InsertFind-Indexed.yml
test/spec/client-side-encryption/tests/legacy/fle2-Update.json
test/spec/client-side-encryption/tests/legacy/fle2-Update.yml

Fixes FLE2 CRUD tests with payload updates.
Syncs the latest tests and pins the checkout of libmongocrypt to 4c3715bbe360a6e87f411d63f5bd1dc237b2f5cb (1.5.0)
None
NODE-4282

test(NODE-4282): sync fle2 payload spec test updates

---

.eslintrc.json
src/cmap/connection.ts
src/cmap/connection_pool.ts
src/sdam/common.ts
src/sdam/monitor.ts
src/sdam/srv_polling.ts
src/sdam/topology.ts
src/utils.ts
test/integration/objectid.test.js
test/unit/sdam/topology.test.js

This change follows on from https://github.com/mongodb/node-mongodb-native/pull/3275
which enforced using Node.js timer methods.
However, it didn't enforce using the Node.js _clear_ methods, which
could fall prey to similar issues.
This change adds linter rules for those clear methods, and fixes the
resulting linter errors.

fix(NODE-4444): use Node.js clear timers

---

src/encrypter.ts
src/utils.ts
test/tools/unified-spec-runner/unified-utils.ts

Move FLE require back into a try catch block.
Webpack needs optional requires to be inside of a try catch.

fix(NODE-4425): webpack optional import of FLE issue

---

package.json
test/integration/auth/mongodb_aws.test.ts

We erroneously changed the aws auth test to use ping instead of count. We need to use a command that requires both authentication and authorization.
Green CI.

test: fix aws auth tests

---

src/mongo_types.ts
test/types/community/collection/filterQuery.test-d.ts
test/types/community/collection/updateX.test-d.ts

Better typing for update & query
```ts
interface User {
pet: {
name: {
first: string;
last: string;
};
};
}
// This works when it shouldn't
const query: mongodb.Filter<User> = { "pet.name": { first: 1 } };
// This doesn't work when it should
const update: mongodb.UpdateFilter<User> = { $set: { "pet.name": { first: "a", last: "b" } } };
```
The second error is a regression. This PR fixes both issues
Tickets:
- https://jira.mongodb.org/browse/NODE-4423
- https://jira.mongodb.org/browse/NODE-4450 (duplicate)

fix(NODE-4423): better type support for nested objects in query & update

---

.evergreen/run-custom-csfle-tests.sh
.evergreen/run-tests.sh
test/integration/client-side-encryption/client_side_encryption.spec.test.ts
test/tools/unified-spec-runner/operations.ts
test/tools/unified-spec-runner/schema.ts
test/tools/unified-spec-runner/unified-utils.ts

https://jira.mongodb.org/browse/NODE-4330
This PR unskips all the key management API tests for the new key management API functions added in https://github.com/mongodb/libmongocrypt/pull/414.  
Before this PR merges, we need to
1. ~~merge https://github.com/mongodb/libmongocrypt/pull/414 into libmongocrypt~~
2. ~~update the supported commit hash in run-custom-csfle-test.sh to the new commit~~
3. ~~release another alpha of mongodb-client-encryption~~
4. ~~update to the newest version of mongodb-client-encryption for the regular tests in CI~~

test(NODE-4469): unskip all key management tests

---

test/spec/server-discovery-and-monitoring/integration/hello-command-error.json
test/spec/server-discovery-and-monitoring/integration/hello-command-error.yml
test/spec/server-discovery-and-monitoring/integration/hello-network-error.json
test/spec/server-discovery-and-monitoring/integration/hello-network-error.yml
test/spec/server-discovery-and-monitoring/integration/hello-timeout.json
test/spec/server-discovery-and-monitoring/integration/hello-timeout.yml

Syncs: https://github.com/mongodb/specifications/pull/1272
NODE-4414

test(NODE-4414): Improve reliability of SDAM heartbeat error spec tests

---

test/spec/initial-dns-seedlist-discovery/replica-set/srvMaxHosts-invalid_integer.json
test/spec/initial-dns-seedlist-discovery/replica-set/srvMaxHosts-invalid_integer.yml
test/spec/initial-dns-seedlist-discovery/replica-set/srvMaxHosts-invalid_type.json
test/spec/initial-dns-seedlist-discovery/replica-set/srvMaxHosts-invalid_type.yml
test/spec/initial-dns-seedlist-discovery/sharded/srvMaxHosts-invalid_integer.json
test/spec/initial-dns-seedlist-discovery/sharded/srvMaxHosts-invalid_integer.yml
test/spec/initial-dns-seedlist-discovery/sharded/srvMaxHosts-invalid_type.json
test/spec/initial-dns-seedlist-discovery/sharded/srvMaxHosts-invalid_type.yml
test/spec/transactions/unified/do-not-retry-read-in-transaction.json
test/spec/transactions/unified/do-not-retry-read-in-transaction.yml

NODE-3812,NODE-4465
- New transactions no retry test
- Removing invalid srvMaxHosts tests
No
Keeping up with spec tests

test(NODE-3812,NODE-4465): transaction and dns seedlist spec test sync

---

test/integration/change-streams/change_streams.spec.test.ts
test/spec/change-streams/unified/change-streams-resume-errorLabels.json
test/spec/change-streams/unified/change-streams-resume-errorLabels.yml

This PR skips `StaleShardVersion` change stream resumibility tests on server versions 6.1.0+.  
In 6.1+ servers, StaleShardVersion is no longer sent as a resumable error (StaleConfig is sent instead, which is also resumable). 
No.

test(NODE-4434): sync skipped StaleShardVersion change stream unifed tests

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-custom-csfle-tests.sh

A new task as been added to the custom dependency tests to test against libmongocrypt master.  The existing task was also renamed to indicate that it tests against a pinned commit, instead of the latest master.

test(NODE-4395): add csfle master && pinned commit tasks to CI

---

src/connection_string.ts
src/mongo_client.ts
test/types/mongodb.test-d.ts

- Added writeConcern to MongoClientOptions
- Added deprecation flags to the top level versions of the options
- Added a type test

feat(NODE-4336): deprecate old write concern options and add missing writeConcern to MongoClientOptions

---

test/integration/client-side-encryption/client_side_encryption.prose.test.js

CSFLE Prose test 13 is implemented, finishing up the key management API work (with the exception of releasing mongodb-client-encryption).
This PR address the following ticket:
- https://jira.mongodb.org/browse/NODE-4331
No.

test(NODE-4331): add prose test 13

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/prepare-crypt-shared-lib.sh
.evergreen/run-custom-csfle-tests.sh
test/readme.md

Downloads the crypt shared lib for the appropriate version and sets its path in the environment.
Adds a new evergreen task that will download the crypt shared lib before running the csfle custom tests. This does not include the changes to the test runner to use it - that is the next subtask.
https://evergreen.mongodb.com/task_log_raw/mongo_node_driver_next_ubuntu1804_custom_dependency_tests_run_custom_csfle_tests_patch_8ecbabcc4dec6c77db4e5ce5ef4a2ca5629c4608_62e12ede2a60ed018c89d3bc_22_07_27_12_26_07/0?type=T#L1437
None.
NODE-4463/NODE-4089

test(NODE-4463): download shared lib in evergreen

---

src/operations/find.ts
test/unit/operations/find.test.ts

The option has been deprecated for MongoDB >=4.4 but should still be available to MongoDB <=4.2
Oplog tailing for MongoDB server <=4.2 can still use this flag in order to have a better performance.
No
The initial query to tail the oplog on huge MongoDB 4.2 servers was taking too long to complete.

fix(NODE-4467): Add back support for `oplogReplay` option as deprecated

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-bson-ext-test.sh
.evergreen/run-tests.sh
test/spec/client-side-encryption/tests/unified/addKeyAltName.json
test/spec/client-side-encryption/tests/unified/addKeyAltName.yml
test/spec/client-side-encryption/tests/unified/createDataKey-kms_providers-invalid.json
test/spec/client-side-encryption/tests/unified/createDataKey-kms_providers-invalid.yml
test/spec/client-side-encryption/tests/unified/getKey.json
test/spec/client-side-encryption/tests/unified/getKey.yml
test/spec/client-side-encryption/tests/unified/getKeyByAltName.json
test/spec/client-side-encryption/tests/unified/getKeyByAltName.yml
test/spec/client-side-encryption/tests/unified/removeKeyAltName.json
test/spec/client-side-encryption/tests/unified/removeKeyAltName.yml
test/spec/client-side-encryption/tests/unified/rewrapManyDataKey.json
test/spec/client-side-encryption/tests/unified/rewrapManyDataKey.yml

- bump fle tests to use https://github.com/mongodb/libmongocrypt/commit/41afd44ca04d246998969c53de4e0f22802b0c8a (2.2.0-alpha.6 release)
- bump bson-ext tests and regular CI tests to use mongodb-client-encryption@2.2.0-alpha.6
- syncs spec tests from [NODE-4487](https://jira.mongodb.org/browse/NODE-4487)
- syncs spec tests from [NODE-4390](https://jira.mongodb.org/browse/NODE-4390)
There will be a follow up PR for https://jira.mongodb.org/browse/NODE-4489.
No.

test(NODE-4487, NODE-4390): sync key management tests && bump fle version in tests

---

test/spec/server-discovery-and-monitoring/integration/hello-command-error.json
test/spec/server-discovery-and-monitoring/integration/hello-command-error.yml
test/spec/server-discovery-and-monitoring/integration/hello-network-error.json
test/spec/server-discovery-and-monitoring/integration/hello-network-error.yml
test/spec/server-discovery-and-monitoring/integration/hello-timeout.json
test/spec/server-discovery-and-monitoring/integration/hello-timeout.yml

[NODE-4480](https://jira.mongodb.org/browse/NODE-4480)
Syncing this test change causes our test runner to leak a 0 timeout socket hanging the process. The test removes two assertions about event counts, possibly the runner isn't correctly awaiting things due to a lack of assertions. `Command error on Monitor check` is the test that would leak the socket. Use TRACE_SOCKETS=true env variable and run the -g filter "SDAM integration spec tests" to reproduce against a 5.0.9 replica_set on linux.
Undo hanging test issue

revert(NODE-4414): Improve reliability of SDAM heartbeat error spec tests

---

test/integration/sessions/sessions.spec.prose.test.ts

Fix a test number for spec prose.
> NOTE original ticket asked to confirm this test only uses one mongos (as in edit the connection string to only specify one host). We already limit to one mongos unless useMultiMongoses is set.
Staying in sync with specs.

test(NODE-4472): fix session spec prose test numbering

---

src/sdam/server.ts
src/sdam/server_description.ts
src/sdam/topology.ts
src/sdam/topology_description.ts
src/utils.ts
test/unit/assorted/server_discovery_and_monitoring.spec.test.ts
test/unit/operations/find.test.ts
test/unit/operations/get_more.test.ts
test/unit/operations/kill_cursors.test.ts
test/unit/sdam/server_description.test.ts
test/unit/utils.test.ts

- Remove servers
- Null out fields on server description instead of omitted keys
- Fixes unix socket issue: https://jira.mongodb.org/browse/NODE-4512
Aligns with spec test, easier assertion against unit specs

fix(NODE-4159,NODE-4512): remove servers with incorrect setName from topology and fix unix socket parsing

---

test/integration/client-side-encryption/client_side_encryption.prose.test.js

Implements csfle prose test 16 - https://jira.mongodb.org/browse/NODE-4489.  This is a regression test for rewrapManyDataKey.
No.

test(NODE-4489): add CSFLE prose test 16

---

.evergreen/run-bson-ext-test.sh
.evergreen/run-tests.sh

This PR bumps our pinned version of mongodb-client-encryption to 2.2.0 in CI.

test(NODE-4525): bump mongodb-client-encryption to 2.2.0 in CI

---

test/unit/operations/get_more.test.ts

test: fix failing unit test

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/prepare-crypt-shared-lib.sh
test/integration/client-side-encryption/client_side_encryption.prose.corpus.test.js
test/integration/client-side-encryption/client_side_encryption.prose.deadlock.js
test/integration/client-side-encryption/client_side_encryption.prose.test.js
test/integration/client-side-encryption/driver.test.ts
test/tools/utils.ts

Uses the shared lib in the csfle prose tests when the environment supports it.
Modifies all csfle prose, corpus, and driver tests to set `extraOptions.sharedCryptLibPath` when CRYPT_SHARED_LIB_PATH is in the environment. Updates the evg config to test csfle against 5.0, rapid, and latest, where CRYPT_SHARED_LIB_PATH will get set currently only with latest and 5.0 and rapid will run against mongocryptd.
None

test(NODE-4422): use shared lib in prose tests

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/run-serverless-tests.sh
test/readme.md
test/tools/runner/config.ts

Updates the serverless tests to use the new `SERVERLESS_URI` set from the drivers tools scripts.
- Sets all relevant testing uris to `SERVERLESS_URI`
- Updates the evergreen project config to use the new Atlas group.
- Fixes the test runner to be able to handle the srv `SERVERLESS_URI` now set (was not srv before)
None
NODE-3735

test(NODE-3735): update to use serverless uri

---

src/sessions.ts
test/tools/unified-spec-runner/entities.ts
test/tools/unified-spec-runner/match.ts
test/tools/unified-spec-runner/operations.ts
test/tools/unified-spec-runner/runner.ts
test/tools/unified-spec-runner/unified-utils.ts
test/unit/sessions.test.js

NODE-4533 for NODE-4325
- Fixed error checking in the unified runner and the discovered non-spec compliant error message for snapshot sessions (we were skipping error checks entirely whenever an expectation contained `isError` or `isClientError`)
- There is a new check for `MongoCryptError` - these aren't standardized in the fle module, so it's a bit awkward, see comment for further discussion
- Fixed a bunch of TS issues in the runner, tried to standardize the null handling as much as possible
- Updated event capturing logic since we'll be adding a new event type in the subsequent work
No
Splitting up groundwork from the sdam-specific unified changes

fix(NODE-4533): session support error message and unified test runner

---

src/index.ts
src/mongo_types.ts
test/types/community/collection/filterQuery.test-d.ts

Fix type for nested objects in query & update added in https://github.com/mongodb/node-mongodb-native/pull/3328
- Support union types (... extends unknown ? ... : never)
- Fail if path is wrong (never vs unknown)
- Support array operators in the middle of a path (number replaced by number | `$${'' | `[${string}]`}` and NestedPathsOfType removed)
No
```ts
const _: MatchKeysAndValues<{ aaa: readonly { bbb: 'ccc' }[] }> = { 'aaa.$.bbb': 'ccc' }; // Error
const _: MatchKeysAndValues<{ aaa: { bbb: { ccc: 'ddd'[] }[] }> = { 'aaa.$.bbb.$[arrayFilter]': 'ddd' }; // Error
```

fix(NODE-4513): type for nested objects in query & update

---

src/operations/create_collection.ts

NODE-4230
- Updating docs reference link for clustered collections
This is a docs change
Consistent permanent link style

docs(NODE-4230): update clustered collection reference link

---

src/mongo_client.ts
test/integration/node-specific/mongo_client.test.ts

This prevents the `endSessions` command from going through server selection when no server would be selected after calling `client.close()`. This could happen in situations where the server has gone down but server selection keeps forcing monitor checks for up to `serverSelectionTimeoutMS` when an immediate return is desired.
- `MongoClient`'s `close()` method now does a quick server selection to get the list of servers that would be returned with a primary preferred read preference. If nothing is returned then calling `endSessions` is skipped.
None
NODE-4429

fix(NODE-4429): select server sync for endSessions during close

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
src/bson.ts
src/index.ts
src/sdam/topology.ts

Exports `BSON` from the library so that it can be used in other modules that depend on `mongodb`, such as `mongodb-client-encryption`.
See https://github.com/mongodb/libmongocrypt/pull/443 for the libmongocrypt changes.
Patch build against this branch from libmongocrypt: https://spruce.mongodb.com/version/62fd246f3627e0758c2439c8/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
- Exports `BSON` from the library.
None
NODE-4516/NODE-4555

fix(NODE-4555): export BSON internally

---

package-lock.json
package.json

bson 4.7.0
bson is nice to have

chore: update bson dependency to 4.7.0

---

test/integration/crud/insert.test.js

We were not correctly manually constructing a UUID in our tests, the Binary constructor does not accept hex strings.
Green trees: 🌲

test: fix incorrect uuid construction

---

test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.spec.test.js

Skips a test that leaks a socket, we'll look into fixing it in a follow up, or replacing it with a unified version of the same test.
Green trees 🌲

test(NODE-4565): skip Network error on Monitor check

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Fixes the CSFLE pinned commit tests.
Updates the pinned commit to latest: c071d5a8d59ddcad40f22887a12bdb374c2f86af
None
NODE-4566

test(NODE-4566): fix csfle pinned commit

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Skipping compression tests on gallium because of .end() hang
see NODE-4575 for followup

test(NODE-4574): skip zstd and snappy on gallium

---

test/integration/server-selection/server_selection.prose.operation_count.test.ts

The server selection operation count latency window test often fails because the observed percentage of requests sent to each mongos is outside the threshold.  Experimenting locally does demonstrate that the percentage approaches 50% to each mongos as the total number of operations increases (which makes sense - as the total time the test runs increases, any ephemeral variations will be averaged away). 
This PR bumps the total number of iterations to a number that when run locally leaves the latency window.  This is purely empirical, and it is possible that the number of iterations is not high enough to reliably run in CI but I believe this should resolve the flakiness of the tests.  I discussed these changes with Patrick and other drivers still see these tests flaking as well.  I propose …

test(NODE-4479): adjust number of iterations of flakey test

---

src/index.ts
src/mongo_types.ts
test/types/community/collection/filterQuery.test-d.ts

Reverts the strict nested union types support.
Reverts https://github.com/mongodb/node-mongodb-native/pull/3349 and comments out the added test with link to original ticket.
Reopens NODE-4513
None
NODE-4583 / NODE-4571

fix(NODE-4583): revert nested union type support

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

This PR updates our CI matrix to only test the rapid release on a standalone server on macos.
No.
Green CI.

test(NODE-4562): reduce macos coverage

---

src/cmap/connect.ts
test/unit/cmap/connect.test.js

We only set `loadBalanced` on the initial hello when it is explicitly provided and set to true.
No.
Spec compliance.
Note that the load balancer tests still fail.  https://jira.mongodb.org/browse/SERVER-69146 has been filed to potentially revert the server changes so that `apiStrict: true` can be used with load balanced mode.  If it turns out the server change is intended behavior, then there will probably be a drivers ticket to skip these tests on load balanced topologies.

fix(NODE-4591): only set loadBalanced on handshake when explicitly set

---

src/sdam/topology.ts
test/integration/server-selection/server_selection.prose.operation_count.test.ts

When we encounter exactly 2 eligible servers in the server selection process, we now shuffle the array of two servers.   This prevents a scenario where, when we receive a sequence of operations and each operation completes before the next (or approximately this scenario), we would select the same server for each request.
No.

fix(NODE-4557): randomize servers when there are only 2 eligible servers 

---

.evergreen/config.in.yml
.evergreen/config.yml

Ensures that when testing AWS auth against EC2 does not accidentally pull the secret key or access key from the written prepare_mongodb_aws.sh script.
Writes an empty file to prepare_mongodb_aws.sh before the EC2 auth task runs.
None
NODE-4585

test(NODE-4585): ensure empty aws env variables

---

test/benchmarks/driverBench/common.js
test/benchmarks/driverBench/index.js
test/benchmarks/mongoBench/suites/bsonBench.js
test/benchmarks/mongoBench/suites/index.js
test/benchmarks/mongoBench/suites/multiBench.js
test/benchmarks/mongoBench/suites/parallelBench.js
test/benchmarks/mongoBench/suites/singleBench.js

This PR adds the parallel benchmarks (defined [here](https://github.com/mongodb/specifications/blob/master/source/benchmarking/benchmarking.rst#parallel)).  In addition, it refactors the benchmark suite to make the runner a bit more readable and organize the code by benchmark suite.
No.

test(NODE-4590): add parallel driver benchmarks

---

src/connection_string.ts
test/unit/assorted/auth.spec.test.ts

Update driver to throw exception when the following conditions are met:
- Using `MONGODB-AWS` auth mechanism
- A `username` is provided
- A `password` is not provided 
Adding check to see if preceding conditions are met when constructing `mongoOptions` object.
Unskip [test](https://github.com/mongodb/specifications/blob/master/source/auth/tests/connection-string.json#L453-L456) that checks this behavior.
No
[NODE-3986](https://jira.mongodb.org/browse/NODE-3986)

fix(NODE-3986): unskip MONGODB-AWS test

---

test/spec/change-streams/unified/change-streams-clusterTime.json
test/spec/change-streams/unified/change-streams-clusterTime.yml
test/spec/change-streams/unified/change-streams-disambiguatedPaths.json
test/spec/change-streams/unified/change-streams-disambiguatedPaths.yml
test/spec/change-streams/unified/change-streams-showExpandedEvents.json
test/spec/change-streams/unified/change-streams-showExpandedEvents.yml

This PR syncs the unified change stream tests to the latest in the specs repo.
There are three drivers tickets covered here.  I broke it out into one commit per drivers ticket:
- 2f263547a04b985b89e2afc52ef3ee50228e8681 covers [NODE-4605](https://jira.mongodb.org/browse/NODE-4605)
- 908ea4781c7424d5a8c8a0174e2f06a7ff0e4e1d covers [NODE-4597](https://jira.mongodb.org/browse/NODE-4597)
- 8bd1eebfaed0258c0ce30e854f6ef831c7d0f85b covers [NODE-4618](https://jira.mongodb.org/browse/NODE-4618)

test(NODE-4605, NODE-4597, NODE-4618): sync latest change stream unified tests

---

src/index.ts
src/mongo_client.ts
src/promise_provider.ts
test/integration/node-specific/custom_promise_library.test.js
test/types/mongodb.test-d.ts

Added the deprecation tag to the API docs for promiseLibrary
async/await in the future

feat(NODE-4519): deprecate promiseLibrary and check for emitted warning

---

src/admin.ts
src/bulk/common.ts
src/change_stream.ts
src/collection.ts
src/cursor/abstract_cursor.ts
src/cursor/aggregation_cursor.ts
src/cursor/find_cursor.ts
src/db.ts
src/gridfs/index.ts
src/gridfs/upload.ts
src/mongo_client.ts
src/sessions.ts
src/utils.ts

* tsdoc indicated deprecations for callbacks
* deprecation will strike through code in editors supporting type info
- N/A Changes are covered by tests
- N/A New TODOs have a related JIRA ticket

feat(NODE-4547): mark all callback APIs as deprecated

---

src/cmap/connection_pool.ts
src/cmap/errors.ts
test/integration/retryable-reads/retryable_reads.spec.prose.test.ts
test/integration/retryable-writes/retryable_writes.spec.prose.test.ts

NODE-3144
- Fixed the ordering of PoolCleared event to happen before the corresponding CheckOutFailed events from waitqueue eviction
- Implemented retryable reads and writes prose tests
- As part of this, I reorganized the existing retryable write prose test so that it would uniformly reset the failPoint with the new added test, but otherwise left it alone
No

fix(NODE-3144): pool clear event ordering and retryability tests

---

src/bulk/common.ts
src/connection_string.ts
src/mongo_client.ts
src/promise_provider.ts
src/sessions.ts
src/utils.ts
test/integration/node-specific/cursor_async_iterator.test.js
test/integration/node-specific/custom_promise_library.test.js
test/types/community/client.test-d.ts
test/unit/mongo_client.test.js

PromiseProvider fix from #3406
The promise provider could have always returned a nullish value, the types were casting away the potential issue. This corrects the issue and allows the PromiseProvider to be unset with `null`

fix(NODE-4639): allow PromiseProvider to be null

---

src/bulk/common.ts
src/operations/update.ts
test/integration/crud/bulk.test.ts

- `FindOperators.update()` and `.updateOne()` use updated TS definitions to allow pipeline-style updates (which are supported by the server and by the actual implementation itself)
- `FindOperators.hint()` is added as an analogue to the `.collation()`, `.arrayHints()` and `.upsert()` methods
- Tests for both of the above are added, modeled on existing tests
I would assume so.
mongosh cannot implement `.hint()` in its own bulk write builder API without one of:
- Modifying driver internals, or
- Implementing the entire bulk builder API itself on top of `collection.bulkWrite()`, or
- This change

feat(NODE-4634): add support for bulk FindOperators.hint()

---

test/benchmarks/mongoBench/benchmark.js
test/benchmarks/mongoBench/runner.js
test/benchmarks/mongoBench/suites/bsonBench.js
test/benchmarks/mongoBench/suites/multiBench.js
test/benchmarks/mongoBench/suites/singleBench.js

Our benchmarks now test the promise-based API instead of the callback based api.
No.
We should benchmark the API we plan to support.

refactor(NODE-4617): use promise apis in benchmarks

---

src/cmap/connection.ts
src/sdam/server_description.ts
src/utils.ts
test/integration/crud/misc_cursors.test.js
test/integration/node-specific/ipv6.test.ts
test/tools/cluster_setup.sh
test/tools/cmap_spec_runner.ts
test/tools/runner/config.ts
test/tools/uri_spec_runner.ts
test/unit/connection_string.test.ts
test/unit/sdam/server_description.test.ts
test/unit/utils.test.ts

NODE-4621
Always include brackets when getting the whole hostAddress string.
- Ensure `Connection` instances have the correct formatted address for ipv6
- HostAddress.toString no longer accepts a flag for disabling IPv6 brackets (they should never have been created without brackets)
- Wrap the error thrown from `new URL` it was very unclear only printing: `TypeError: Invalid URL` prints the input hostname now and attaches the original error as a cause.
- Fixed up a cursor test while debugging it, I can revert, it just happened to demonstrate an issue with bracketing
- fixed type of `this.configuration.options.hostAddresses` to not be nullish
- Added the --ipv6 flag to our mtools script
- cmap spec runner improvement, print the original error stack and name, otherwise its hard to trace
- …

fix(NODE-4621): ipv6 address handling in HostAddress

---

src/bulk/common.ts
src/change_stream.ts
src/gridfs/index.ts
src/gridfs/upload.ts
src/mongo_client.ts
src/promise_provider.ts
src/utils.ts
test/integration/sessions/sessions.spec.prose.test.ts
test/unit/utils.test.ts

- Adds maybeCallback helper with tests
- Changes PromiseProvider to communicate an unset state
- Refactors:
- ChangeStream
- ClientSession
- GridFS

refactor(NODE-4631): change_stream, gridfs to use maybeCallback

---

package-lock.json
package.json

Bumps the nodejs types...
...to fix our lint task.

chore(NODE-4661): bump @types/node version to fix ts next

---

src/cmap/connection.ts
src/operations/aggregate.ts
src/operations/command.ts
src/operations/delete.ts
src/operations/find.ts
src/operations/find_and_modify.ts
src/operations/update.ts
src/sdam/server.ts
src/utils.ts

As a follow up to #3409, this removes all wire version checks which check for a version that is no longer supported by this driver.
Code that wasn't used is being removed.
No
My motivation behind this was to clean up the code, and remove unnecessary checks.

chore(NODE-4641): remove wire version checks for unsupported servers

---

src/cmap/connection_pool.ts
src/cmap/connection_pool_events.ts
src/cmap/errors.ts
src/sdam/server.ts
test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.spec.test.ts
test/tools/cmap_spec_runner.ts
test/unit/cmap/connection_pool.test.js

NODE-4649/NODE-3135
CMAP
- connection pool now saves a reference to the server that it is attached to
- new `serverError` property on the pool allows access to the server description error for the purpose of generating a more descriptive pool cleared error
- per the spec, connection establishment should emit a connection closed event on error, this is now implemented
- min pool size errors are now handled via SDAM error handling (using the new `handleError` server class method)
SDAM
- makeOperationDescription was refactored to pull out SDAM-specific error handling logic (corresponding to `handleError` in the spec) into a class method on the server
- the new server class method `handleError` is as spec compliant as it can be while still handling the load balancer logic alongside the …

fix(NODE-4649): use SDAM handling for errors from min pool size population

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/prepare-shell.sh

CI uses rhel8 instead of ubuntu20 for the majority of tasks. 
Exceptions are
- mongosh tests
- aws auth tests
No.

ci(NODE-4662): remove ubuntu in favor of rhel8

---

src/cmap/connection_pool.ts
src/error.ts
src/sdam/server.ts
test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.spec.test.ts
test/unit/sdam/server.test.ts

NODE-4650/NODE-3135
- Updating SDAM `handleError` logic to handle auth handshake errors [according to the spec](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#error-handling-pseudocode)
- Unskipping the corresponding SDAM auth tests
- New unit tests just for the new portions of the handleError logic
- Injecting a new error `connectionGeneration` property when `createConnection` receives an error so that it can be checked for staleness even in the absence of a connection (which makes this a `feat:`)
No

feat(NODE-4650): handle handshake errors with SDAM

---

test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.prose.test.ts
test/tools/runner/config.ts

NODE-2988
- Adding an SDAM prose test to make sure monitors wait minHeartbeatFrequencyMS between checks
Note: the new test is currently failing, possibly due to work not yet done in: #3404

test(NODE-2988): monitors wait minHeartbeatFrequencyMS between checks

---

src/cmap/connection_pool.ts
test/integration/server-selection/server_selection.prose.operation_count.test.ts
test/tools/cmap_spec_runner.ts
test/unit/cmap/connection_pool.test.js

NODE-3255
- Added `minPoolSizeCheckIntervalMS` option to the connection pool which controls how frequently the `ensureMinPoolSize` runs
- Added a unit test for the option and the default of 100ms
- The corresponding `backgroundThreadIntervalMS` option in the CMAP test runner is now correctly parsed and passed to the test pools
No
Better spec testing

feat(NODE-3255): add minPoolSizeCheckIntervalMS option to connection pool

---

src/sdam/monitor.ts
test/integration/change-streams/change_stream.test.ts
test/integration/change-streams/change_streams.spec.test.ts
test/integration/unified-test-format/unified_test_format.spec.test.ts
test/unit/sdam/monitor.test.ts

The monitor has been refactored to more closely align the spec.  Additionally, this PR also prevents the monitor from re-executing the `fn` while `fn` is currently executing.
The unit tests have been reworked to match the new behavior.  The passing unit tests have the following output (included to help demonstrate the behavior of the monitor):
No.

refactor(NODE-4638): prevent parallel calls to `fn` in the async interval

---

src/transactions.ts
test/types/community/transaction.test-d.ts
test/unit/transactions.test.ts

This commit expands the TransactionOptions type definition to allow values like `'primary'`.
Before, the type definition only allowed passing an instance of the `ReadPreference` class. This differs from documented and common usage. We expand the type definition from `ReadPreference` to `ReadPreferenceLike`.
Updating this type annotation will reduce confusion for Typescipt users of the library.
No, this makes the types match the existing documentation more closely.  For instance, in https://www.mongodb.com/docs/drivers/node/current/fundamentals/transactions/#transaction-settings, this API is documented as accepting a string: 
> const transactionOptions = {
>   readPreference: 'primary',
>   readConcern: { level: 'local' },
>   writeConcern: { w: 'majority' },
>   maxCommitTimeMS: 1000
> }; …

fix(NODE-4186): accept ReadPreferenceLike in TransactionOptions type

---

src/sdam/monitor.ts
test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.spec.test.ts
test/unit/sdam/monitor.test.ts

Prevents the Monitor.wake() method from proceeding if the monitor is already in a monitoring state.  This PR also unskips the two remaining SDAM tests, as well as removes the socket leak checks in the sdam unified runner.
No.

fix(NODE-4608): prevent parallel monitor checks

---

src/operations/indexes.ts
test/types/community/createIndex.test-d.ts

Add 'hashed' to IndexDirection.
Should be auto generated [here](https://mongodb.github.io/node-mongodb-native/4.10/modules.html#IndexDirection)
Type system is currently not working for hashed index.

feat(NODE-3651): add hashed index type

---

test/spec/change-streams/unified/change-streams-clusterTime.json
test/spec/change-streams/unified/change-streams-clusterTime.yml
test/spec/change-streams/unified/change-streams-showExpandedEvents.json
test/spec/change-streams/unified/change-streams-showExpandedEvents.yml
test/spec/client-side-encryption/tests/legacy/maxWireVersion.json
test/spec/client-side-encryption/tests/legacy/maxWireVersion.yml

Small spec sync addressing both NODE-4628 and NODE-4640.
No.

test(NODE-4628, NODE-4640): sync fle and change stream spec tests

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-bson-ext-test.sh
.evergreen/run-tests.sh

Bumps mongodb-client-encryption in the driver CI to 2.3.0.

ci: bump mongodb-client-encryption version

---

src/cmap/connection_pool.ts

https://jira.mongodb.org/browse/NODE-4094
The connection pool now tracks checked out connections instead of only keeping track of the number of checked out connections.
No.
https://jira.mongodb.org/browse/NODE-4094

refactor(NODE-4689): track checked out connections

---

src/cursor/abstract_cursor.ts

This undocumented behavior is surprising. Adding a note here may help future users.

docs: Note special case in `AbstractCursor.forEach()` iterator

---

src/mongo_types.ts
test/types/basic_schema.test-d.ts
test/types/community/collection/recursive-types.test-d.ts
test/types/community/collection/updateX.test-d.ts
test/types/community/slow-model.test-d.ts
test/types/union_schema.test-d.ts

Adds a type check to limit recursion to 8 levels of depth. Mutually recursive types are now accepted and stop getting type checking / hinting after a certain depth.
Mutually recursive types can be useful for modeling data

feat(NODE-3875): support recursive schema types

---

src/cursor/abstract_cursor.ts
test/integration/change-streams/change_stream.test.ts

Fixes change stream retryability on 4.4 servers and lower when performing a failover.
This is the "quick and dirty" fix that just avoids pushing a `null` to the readable cursor stream before calling `destroy` on the stream when the error contains the message "interrupted at shutdown".
Existing spec tests cover the more specific error - see: https://github.com/mongodb/node-mongodb-native/blob/main/test/spec/retryable-writes/legacy/insertOne-serverErrors.yml#L468
Note: see https://github.com/mongodb/node-mongodb-native/pull/3438 for what a start of a refactor away from checking for this error message and creating separate streams for the change stream cursor and the others would look like. However it seems the "operation was interrupted" message affects change streams as well so I'll leave …

fix(NODE-4475): make interrupted message more specific

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/install-dependencies.sh
package-lock.json
package.json
src/cmap/auth/mongodb_aws.ts
src/deps.ts
test/integration/auth/mongodb_aws.test.ts

Uses the AWS-SDK for finding credentials when present in dependencies, otherwise uses the internal implementation.
- Adds @aws-sdk/credential-providers as an optional dependency.
- Uses the SDK when installed to find credentials from the environment when missing.
Patch build with AWS tests for with and without the optional dependencies: 
https://spruce.mongodb.com/version/634d68f92fbabe2d0a6b964f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Can make a note to users that they can install the SDK to have it be used.
NODE-4721

feat(NODE-4721): add aws-sdk as optional dependency

---

src/change_stream.ts

docs(NODE-4554): remove experimental tag from disambiguatedPaths

---

src/collection.ts
src/deps.ts
src/error.ts
src/mongo_client.ts
src/sdam/topology.ts

Docs
Consistency across documentation

docs(NODE-4724): update fle docs to use "in use encryption" terminology

---

src/cmap/connection_pool.ts
src/cmap/connection_pool_events.ts
test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.spec.test.ts
test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.spec.test.ts
test/spec/connection-monitoring-and-pooling/pool-clear-interrupt-immediately.json
test/spec/connection-monitoring-and-pooling/pool-clear-interrupt-immediately.yml
test/spec/connection-monitoring-and-pooling/pool-clear-interrupting-pending-connections.json
test/spec/connection-monitoring-and-pooling/pool-clear-interrupting-pending-connections.yml
test/spec/connection-monitoring-and-pooling/pool-clear-schedule-run-interruptInUseConnections-false.json
test/spec/connection-monitoring-and-pooling/pool-clear-schedule-run-interruptInUseConnections-false.yml
test/spec/server-discovery-and-monitoring/unified/interruptInUse-pool-clear.json
test/spec/server-discovery-and-monitoring/unified/interruptInUse-pool-clear.yml
test/spec/unified-test-format/invalid/expectedCmapEvent-poolClearedEvent-interruptInUseConnections-type.json
test/spec/unified-test-format/invalid/expectedCmapEvent-poolClearedEvent-interruptInUseConnections-type.yml
test/tools/cmap_spec_runner.ts
test/tools/unified-spec-runner/match.ts
test/tools/unified-spec-runner/schema.ts

This PR does the following:
- syncs new unified and cmap unit tests from [this](https://github.com/mongodb/specifications/commit/23bd4db8fcfc1dbd5d5c123f936134913720e85b) spec change
- updates the cmap runner to support passing `interruptInUseConnections` to `pool.clear()`
- updates the unified runner to support `interruptInUseConnections`
- Updates the PoolClearedEvent to support `interruptInUseConnections` (necessary for the tests)
No.

refactor(NODE-4690): update cmap and test runners to support interruptInUseConnections

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/prepare-shell.sh

Re-enables the combined coverage tasks.
Re-enables the tasks and switches to RHEL 8. 
https://mciuploads.s3.amazonaws.com/mongo-node-driver/6fb87e41e6300129503722d6232fcaaf6a556019/6351390d57e85a401615adba/coverage/index.html
None
NODE-3897

test(NODE-3897): re-enable combined coverage

---

package-lock.json
package.json
src/cmap/connection_pool.ts
src/cmap/message_stream.ts
src/cursor/abstract_cursor.ts
src/index.ts
src/sdam/topology.ts
src/sessions.ts
src/utils.ts
test/action/dependency.test.ts
test/benchmarks/unitBench/list.bench.js
test/integration/crud/find_cursor_methods.test.js
test/unit/sessions.test.js
test/unit/utils.test.ts

Anywhere we used arrays or an external dependency I've migrated us to our own linked list implementation.
In v4 the cursor implementation was changed to shift documents from the front of a list which has a negative impact of moving every item in the list up by one index. I considered tracking an offset on the cursor, but after wrestling with a number of tests that reveled the many locations the index would need to be incremented and decremented to correctly track the next document, it seemed worth using a data structure fitting the job.
I offer our own implementation of linked list which is relatively simple to follow and for us to make future adjustments to if needed. It is circularly linked with an always defined sentinel head node to remove the need for null checks on next/prev. I've …

perf(NODE-4727): Improve performance of buffering and cursors

---

src/cursor/abstract_cursor.ts
test/integration/node-specific/abstract_cursor.test.ts

This PR allows mapping to falsey values in cursors.
No.

fix(NODE-4609): allow mapping to falsey non-null values in cursors

---

src/cmap/connection.ts
src/index.ts

Removes the internal, unused `QueryOptions` definition and export
No.
Code clean up.

refactor(NODE-4754): remove unused QueryOptions export

---

src/change_stream.ts
test/integration/change-streams/change_stream.test.ts
test/integration/change-streams/change_streams.spec.test.ts
test/integration/unified-test-format/unified_test_format.spec.test.ts

Change streams should loop until a document is produced, so that in the case of a successful resume, a subsequent resumable error is treated as its own resumable error.
No.
Correct change stream resume behavior.

fix(NODE-4735): fix change stream consecutive resumabilty

---

src/change_stream.ts
src/cursor/abstract_cursor.ts
test/integration/change-streams/change_stream.test.ts
test/types/change_stream.test-d.ts

Adds the `asyncIterator` symbol to the ChangeStream class.
Yes.
Currently, Change streams support manual promise-based iteration using `next`, `hasNext` and `tryNext`.  Making the ChangeStream an async iterable allows for idiomatic use in for-await loops.

feat(NODE-4683): make ChangeStream an async iterable

---

src/gridfs/download.ts
test/integration/gridfs/gridfs_stream.test.js

Documentation for the `start` and `end` options on GridFS downloads.
Addtionally a test that covers the expected behavior has been modernized / cleaned up a bit.
`end` is a non-inclusive offset, so the documentation should clearly state that.

docs(NODE-4775): improve documentation on gridfs start and end options

---

src/bulk/common.ts

Deprecates `BulkWriteResult`'s `result` and `getLastOp`.
Deprecates `BulkWriteResult`'s `result` and `getLastOp`.
None
NODE-4733

feat(NODE-4733): deprecate result and getLastOp

---

src/collection.ts
test/types/community/collection/findX.test-d.ts

Deprecates the `ModifyResult` type.
- Deprecates the `ModifyResult` type.
- Adds commented out type tests to use later when returning the actual result document.
None
NODE-4681

feat(NODE-4681): deprecate modify result

---

src/admin.ts
src/collection.ts
src/cursor/aggregation_cursor.ts
src/cursor/find_cursor.ts
src/db.ts
src/mongo_client.ts
src/sessions.ts

This PR simply moves all deprecated function overloads to the bottom of their signatures so that the overloads that should be used come up first and are preferred by TS
No, they were already documented in the PR that introduced the deprecations
When using TS's built-in types such as ReturnType or others, TS will usually grab the first overload of the function. Along with that, if you ever had an error in some of your function's arguments, the overload would often fallback to the callback one since, in the presence of an error, TS fins the first overload that matches the amount of parameters passed, causing your function's return type to be `void`. Also by doing this it will make it easier to remove all of these overloads when the time comes for that, and it will also make the diff look …

docs(NODE-4798): move deprecated overloads to the bottom

---

src/logger.ts

Deprecate the existing logger to be removed in the next major version.
No.
NODE-3974 proposes a new logger and since this one is unused and will be replaced it should be deprecated and eventually removed.
- [] Changes are covered by tests

feat(NODE-4809): deprecate the existing logger

---

src/change_stream.ts

NODE-4757
Deprecating the unused PipeOptions public export
No
Clean up public API

feat(NODE-4757): deprecate unused PipeOptions

---

src/operations/create_collection.ts

NODE-4755
Updated docs for `autoIndexId` and removed references to a min required version of `3.4` or lower since we don't support connecting to servers `< 3.6`.
No
Clarity

docs(NODE-4755): clarify deprecation docs for autoIndexId

---

src/cmap/connection.ts
test/tools/utils.ts
test/unit/cmap/connection.test.ts
test/unit/cmap/message_stream.test.js

In the case where streaming hello responses are skipped in the driver, the last hello that is processed will get ignored by the connection's `onMessage` handler because the `responseTo` field of the hello does not match the original `requestId`
This was the least invasive change I could think of doing without reworking the monitoring connection to not depend on its internal queue. That is the basis of not just matching the request and responses but all the callback execution and error handling also is closely coupled to the queue.
This change basically knows that when an operation description is not found in the queue for the `responseTo` field and it is a monitoring connection, that hellos have been skipped and there will be one operation description in the queue for the original hello …

fix(NODE-4783): handle orphaned operation descriptions

---

package-lock.json
test/integration/retryable-reads/retryable_reads.spec.test.js
test/spec/retryable-reads/unified/handshakeError.json
test/spec/retryable-writes/unified/handshakeError.json
test/tools/unified-spec-runner/operations.ts

NODE-4790
- Sync retryable read and write spec tests to latest
- Skip tests for APIs our driver does not implement
- Implement `findOne` operation in the unified test runner
No

test(NODE-4790): retryable handshake errors spec sync

---

src/cmap/auth/mongodb_aws.ts
src/deps.ts

This PR refactors the import for the aws module to be imported lazily, on demand.
No.
We don't want to import aws code when aws is not configured by the user.

fix(NODE-4830): lazily import aws module

---

src/cmap/connection.ts
test/unit/cmap/connection.test.ts

When no operation description is in the monitoring connection's queue map and a message comes in the application would error _"TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))"._
The iterator `next()` call when nothing is in the map will return `{ value: undefined, done: true }` - so we change the existence check to look at the actual value.
No
NODE-4831

fix(NODE-4831): check map value is not undefined

---

etc/check-remote.sh
etc/docs/build.ts

Adds support for remotes that were cloned with https instead of ssh in our pre-docs generation check.

chore(no-story): allow clones that use https in docs pre-generation check

---

src/sessions.ts
test/spec/sessions/implicit-sessions-default-causal-consistency.json
test/spec/sessions/implicit-sessions-default-causal-consistency.yml
test/unit/sessions.test.js

NODE-4447
- Disable causal consistency by default in implicit sessions to avoid clashing with read concern settings
- Sync spec tests
- New unit tests around the functionality
No
Fixes bug described in DRIVERS-2369 (retrying operations when read concern is `linearizable` or `available`)

fix(NODE-4447): disable causal consistency in implicit sessions

---

.github/workflows/dependencies.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

ci(NODE-4872): add permissions to dependency check workflow

---

test/types/schema_helpers.test-d.ts

NODE-4498
Adding tests to make sure document types returned from methods on a collection using an `OptionalId`-wrapped schema with a defined `_id` are still assignable to the original schema.
No
Ensure user types continue to work as expected when using the `OptionalId` helper wrapper

test(NODE-4498): ts tests for OptionalId wrapping schemas with _id

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/run-kms-servers.sh
test/readme.md
test/spec/client-side-encryption/tests/README.rst

Update to latest drivers evergreen tools scripts.
Test failures on latest related to: https://jira.mongodb.org/browse/DRIVERS-2490
- Replaces usages of [csfle/activate_venv.sh](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/a3a17f1185643135a6b24f318bf0ce1e58fdea94/.evergreen/csfle/activate_venv.sh) with [csfle/activate-kmstlsvenv.sh](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/a3a17f1185643135a6b24f318bf0ce1e58fdea94/.evergreen/csfle/activate-kmstlsvenv.sh).
- Replaces usages of [auth_aws/activate_venv.sh](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/a3a17f1185643135a6b24f318bf0ce1e58fdea94/.evergreen/auth_aws/activate_venv.sh) with [auth_aws/activate-authawsvenv.sh](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/a3a17f1185643135 …

test(NODE-4800): update build env scripts

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-kms-servers.sh
test/integration/client-side-encryption/client_side_encryption.prose.corpus.test.js
test/integration/client-side-encryption/client_side_encryption.prose.deadlock.js
test/integration/client-side-encryption/client_side_encryption.prose.test.js
test/integration/client-side-encryption/client_side_encryption.spec.test.ts
test/integration/client-side-encryption/driver.test.ts
test/integration/server-selection/server_selection.prose.operation_count.test.ts
test/manual/atlas-data-lake-testing/atlas_data_lake_testing.prose.js
test/manual/atlas-data-lake-testing/atlas_data_lake_testing.spec.js
test/manual/socks5.test.ts
test/tools/runner/hooks/configuration.js

- socks5 tests now run on node18
- adl tests now run on node18
- csfle tests have been fixed on node18
- the pinned version of libmongocrypt has been bumped in our CI
- failing tasks on node18 now run in CI
Most tests are made to pass by either setting the family to 4 directly on the mongo client, or by setting the default dns resolution order.

ci(NODE-4881): adjust tests to pass on Node18

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
etc/notes/CHANGES_5.0.0.md
package-lock.json
package.json

Updates the minimum supported Node version to 14.20.1.
- Removes Node 12 from CI
- Updates the engine requirement to >=14.20.1
- Updates the migration guide.
Compatibility matrix needs to be updated.
NODE-4436

feat(NODE-4436)!: update minimum supported node version

---

etc/notes/CHANGES_5.0.0.md
package-lock.json
package.json
test/action/dependency.test.ts

Makes `@aws-sdk/credentials-provider` an optional peer dependency.
- Makes `@aws-sdk/credentials-provider` a peer dependency with optional metadata.
- Adds the sdk as a dev dependency
- Updates the dependency check Github action.
Updates to migration doc.
NODE-4898

feat(NODE-4898)!: aws credential providers now optional peerDependency

---

etc/notes/CHANGES_5.0.0.md
src/cursor/abstract_cursor.ts
test/integration/node-specific/cursor_async_iterator.test.js

Ensures cursor is closed when exiting the async generator.
Adds a finally clause in the async generator to close the cursor (if it's not already closed). This handles early exits from `for await of...` loops. A new integration test also is added to check this scenario.
None
NODE-4598

feat(NODE-4598)!: close cursor on early loop break

---

test/manual/socks5.test.ts

Fix Socks5 flaky tests
- Updates the single connection URI to use read preference primary preferred to avoid the "not primary and secondaryOk=false" errors.
None
NODE-4580

test(NODE-4580): use primary preferred in socks test

---

etc/notes/CHANGES_5.0.0.md
src/cursor/abstract_cursor.ts
src/index.ts

Removes `CursorCloseOptions`.
- Removes the `CursorCloseOptions` and updates the `close()` method to no longer take options.
None
NODE-3489

feat(NODE-3489)!: remove cursor close options

---

package.json
src/collection.ts
src/deps.ts
src/encrypter.ts
src/sdam/topology.ts
test/action/dependency.test.ts

mongodb-client-encryption is now an optional peer dependency with a support version range of `^2.3.0`.
Yes, we need to document our support matrix.  

feat(NODE-4751)!: drop support for client encryption < 2.3.0

---

etc/notes/CHANGES_5.0.0.md
package-lock.json
package.json

[NODE-4959](https://jira.mongodb.org/browse/NODE-4959)
We decided to use the caret notation instead of .x.x notation in the non-required deps spike
Consistency

chore(NODE-4959): use caret notation for snappy peer dependency

---

etc/notes/CHANGES_5.0.0.md
src/bulk/common.ts
test/integration/retryable-writes/retryable_writes.spec.test.ts
test/spec/client-side-encryption/tests/unified/rewrapManyDataKey.json
test/spec/client-side-encryption/tests/unified/rewrapManyDataKey.yml
test/tools/unified-spec-runner/operations.ts

Makes the internal `BulkResult` on the `BulkWriteResult` private.
- Marks the `BulkResult` interface as internal.
- Makes the `result` property of the `BulkWriteResult` private and non-enumerable.
- Makes all properties of the `BulkWriteResult` per the crud spec definition actual properties instead of getters.
- Removes `toJSON()`.
- DRYs up the generation of the inserted/upserted id maps.
- Eliminates `insertedIds` from the result enumerable in unified tests.
mongosh CI failures fix in this PR: https://github.com/mongodb-js/mongosh/pull/1386
None
NODE-4034/NODE-4393/NODE-4973

feat(NODE-4034)!: make internal bulk result private

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-custom-csfle-tests.sh

Removes usage of `find_cmake` script and updates to latest fle sha1.
This fixes the CSFLE custom CI tasks.
No
NODE-4985

test(NODE-4985): update csfle build scripts

---

package-lock.json
package.json
test/mongodb.ts
test/unit/assorted/client.test.js
test/unit/cursor/abstract_cursor.test.ts
test/unit/mongodb-legacy.test.ts
test/unit/tools/mongodb-legacy.test.ts

We use the mongodb-legacy package to continue supporting callback style tests

test(NODE-4919): import mongodb-legacy in tests

---

etc/notes/CHANGES_5.0.0.md
src/cursor/abstract_cursor.ts

Change the return type of the `AbstractCursor`'s `asyncIterator` implementation to `AsyncGenerator`
Yes. Added note in upgrade guide to mention type change.
Narrowing the Typescript types for better developer experience.

feat(NODE-4767): Change abstract cursor return type

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Bumps pinned commit for FLE
Need promise style tests

chore(NODE-4993): update fle hash to pull in promise tests

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-custom-csfle-tests.sh
.evergreen/run-kms-servers.sh
test/integration/client-side-encryption/client_side_encryption.prose.corpus.test.js
test/integration/client-side-encryption/client_side_encryption.prose.deadlock.js
test/integration/client-side-encryption/client_side_encryption.prose.test.js
test/integration/client-side-encryption/client_side_encryption.spec.test.ts
test/integration/client-side-encryption/driver.test.ts
test/integration/server-selection/server_selection.prose.operation_count.test.ts
test/manual/atlas-data-lake-testing/atlas_data_lake_testing.prose.js
test/manual/atlas-data-lake-testing/atlas_data_lake_testing.spec.js
test/manual/socks5.test.ts
test/tools/runner/hooks/configuration.js

Collection of fixes needed for 4x CI.
A more exhaustive CI run is here - https://spruce.mongodb.com/version/63cef18c3e8e860af2ccf52f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC.  Some tests still fail but with usual flaky test failures, not with CI configuration issues.

ci: pull in misc CI fixes for the 4x branch

---

src/db.ts
src/gridfs/download.ts
src/gridfs/index.ts
src/logger.ts
src/mongo_client.ts

Deprecating methods and options that are being removed in the driver v5.
Deprecating the following methods
Deprecating the following options
No, documentation is in the tsdoc comments
Getting rid of old logger cleanly to make way for spec-compliant logger.

feat(NODE-4992): Deprecate methods and options that reference legacy logger

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-socks5-tests.sh

* Changes the proxy host addresses to be IPv4 to avoid node 18 dns issue
* Splits socks5 driver only run from socks5 csfle run
Green ci

fix(NODE-4998): use ipv4 in socks5 tests for node 18

---

README.md
etc/notes/CHANGES_5.0.0.md

- References to callbacks have been removed from the driver readme.
- Migration examples have been added to the migration guide for callbacks

docs(NODE-4916, NODE-4523): update readme and upgrade guide with callback removal information

---

.eslintrc.json
tsconfig.json

- tsconfig "target" set to es2020
- eslintrc ecmaVersion set to es2020
Align output syntax with ts syntax.

feat(NODE-5016)!: compile ts with target es2020

---

package-lock.json
package.json

chore(NODE-4983): bump BSON to v5.0.0

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-kms-servers.sh

Just use the python in the path once the env is set.
Calls to python are just the main runtime name.

test(NODE-5022): skip socks5-csfle tests on windows

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/krb5.conf
.evergreen/run-kerberos-tests.sh

Re-enables the Kerberos auth tests on Node 18 and latest.
RHEL 8.0 forces a cipher suite for libkrb5 of rc4-hmac which is both legacy and deprecated, and Node 18 dropped support for it. We've generated a new drivers keytab that forces aes256-cts and aes128-cts and use it specifically in all tests now.
None

test(NODE-4894): re-enable kerberos tests on 18

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/install-dependencies.sh

Remove from npm settings that are no longer supported (and unused)

ci(NODE-5032): fix windows node 18.14.0 npm version issue

---

test/integration/client-side-encryption/client_side_encryption.prose.test.js

Fix the CSFLE handshake error test.
- Check for both the old and new handshake error messages in the prose test.
None
NODE-5033

test(NODE-5033): fix handshake error message check

---

.evergreen/run-tests.sh
src/cmap/connect.ts
src/cmap/connection.ts
src/cmap/connection_pool.ts
src/sdam/server.ts
src/sdam/topology.ts
test/integration/crud/misc_cursors.test.js
test/integration/node-specific/topology.test.js
test/unit/assorted/polling_srv_records_for_mongos_discovery.prose.test.ts
test/unit/assorted/server_selection_spec_helper.js
test/unit/cmap/connection.test.ts
test/unit/error.test.ts
test/unit/sdam/monitor.test.ts
test/unit/sdam/topology.test.js

This reverts commit 8338bae933c777dee4e7e49dbcf52c4fd7047528.

fix(NODE-5027): revert "ensure that MessageStream is destroyed when connections are destroyed"

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
package-lock.json
package.json

Adds testing for AssumeRoleWithIdentity into CI.
No.

feat(NODE-3445): add support for AssumeRoleWithWebIdentity in aws authentication

---

src/cmap/connect.ts
src/cmap/connection.ts
src/cmap/connection_pool.ts
src/sdam/server.ts
src/sdam/topology.ts
test/integration/crud/misc_cursors.test.js
test/integration/node-specific/topology.test.js
test/unit/assorted/polling_srv_records_for_mongos_discovery.prose.test.ts
test/unit/assorted/server_selection_spec_helper.js
test/unit/error.test.ts
test/unit/sdam/monitor.test.ts
test/unit/sdam/topology.test.js

Applies all refactor changes from https://github.com/mongodb/node-mongodb-native/pull/3482.  Specifically, this PR makes the `DestroyOptions` interface required.
No.

refactor(NODE-5063): make DestroyOptions required on connection.destroy

---

src/cmap/connection.ts
test/integration/crud/misc_cursors.test.js
test/unit/cmap/connection.test.ts

This PR primarily does three things:
- ensures that the message stream is always destroyed and ensure that the socket is always destroyed
- consolidate the connection clean up logic into a single function that is called from each point where the connection is cleaned out
- improves the unit tests to properly assert on the state of the connection after _cleanup has been called. Additionally, the unit tests now in for synchronous versus asynchronous behavior for the various error and clean up scenarios.
Example unit test output:
```
new Connection()
✔ should support fire-and-forget messages
✔ should destroy streams which time out (55ms)
✔ should throw a network error with kBeforeHandshake set to false on timeout after handshake (56ms)
✔ should throw a network error with kBeforeHandshake set …
```

fix(NODE-5064): consolidate connection cleanup logic and ensure socket is always closed

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-gcp-kms-tests.sh
.evergreen/setup-gcp-instance.sh
.evergreen/setup-gcp-testing.sh
src/deps.ts
test/integration/client-side-encryption/client_side_encryption.prose.17.on_demand_gcp.test.ts
test/tools/runner/filters/client_encryption_filter.js
test/types/encryption.test-d.ts

- Add `test-gcpkms-task` that uploads the driver to a GCP instance and runs success test
- Add `test-gcpkms-fail-task` that runs locally on EVG and tests for failure
- Add `{accessToken:string}` types to `azure` and `gcp` credential types
- Add `{}` empty credential types to `aws` and `gcp`
- Debugging print for when FLE is required to run but fails to import
Support GCP KMS auto credential fetching.

feat(NODE-5050): support GCP automatic credential fetch for CSFLE

---

test/spec/client-side-encryption/tests/legacy/fle2-CreateCollection.json
test/spec/client-side-encryption/tests/legacy/fle2-CreateCollection.yml
test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.json
test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.yml

test(NODE-5092): fix fle2 collection names in legacy fle2 tests

---

src/cmap/command_monitoring_events.ts
test/tools/unified-spec-runner/entities.ts
test/tools/unified-spec-runner/schema.ts

Introduces `observeSensitiveCommands` to the unified spec runner.
- Adds the `observeSensitiveCommands` option to the client entity.
- Adds the sensitive commands to the ignored event list.
None
NODE-5091

test(NODE-5091): introduce observeSensitiveCommands

---

test/spec/initial-dns-seedlist-discovery/replica-set/dbname-with-commas-escaped.json
test/spec/initial-dns-seedlist-discovery/replica-set/dbname-with-commas-escaped.yml
test/spec/initial-dns-seedlist-discovery/replica-set/dbname-with-commas.json
test/spec/initial-dns-seedlist-discovery/replica-set/dbname-with-commas.yml

NODE-3359/DRIVERS-1777
- Sync initial dns seedlist discovery spec tests for db names with commas
No

test(NODE-3359): add spec tests for db names with commas

---

.evergreen/install-dependencies.sh

Keeping 5.x in sync with other repos install scripts

ci(NODE-5099): add aarch64 condition to sync with other repos

---

.evergreen/install-dependencies.sh

Added Curl flags
- compressed - should fetch compressed data
- location - will follow redirects
- continue-at - will resume interrupted downloads

ci(NODE-5110): update curl flags

---

etc/clean_definition_files.cjs
package-lock.json
package.json

Remove rimraf as a dependency and implement a script on node std lib APIs that remove the definition files and maps from our `lib` directory.
- one less dep
- globbing stopped working

chore(NODE-5128): add script to clean dts and dts.map files

---

test/integration/client-side-encryption/client_side_encryption.prose.22.range_explicit_encryption.test.ts

Documents are inserted sequentially because bulk inserts are not supported for queryable encryption.

test(NODE-5147): fix broken range index test

---

test/integration/client-side-encryption/client_side_encryption.prose.22.range_explicit_encryption.test.ts

Backport of range index test fix.

test(NODE-5149): fix broken range index test

---

.evergreen/run-serverless-tests.sh

The serverless run script just needs to source the PATH fixes to run the right node version that has already been downloaded.

test(NODE-5113): fix serverless tests source setup

---

package-lock.json
package.json

Update BSON to v5.1.0.
We typically pin to latest BSON before each driver release to ensure a consistent expirence.

chore: update BSON to v5.2.0

---

package-lock.json
package.json

Update BSON to v4.7.2
Pulls in BSON bug fixes so that the next 4.x version of the driver will pull in the fixes as well.

chore: update BSON to v4.7.2

---

src/bulk/common.ts
test/integration/client-side-encryption/client_side_encryption.prose.test.js
test/integration/crud/bulk.test.ts
test/integration/crud/crud_api.test.ts
test/integration/node-specific/operation_examples.test.ts

Deprecates duplicate bulk write methods.
- Deprecates all the "n..." duplicate getters
- Deprecates select duplicate getters starting with "get".
- Updates tests to use the non-deprecated bulk properties.
None
NODE-4791

feat(NODE-4791): deprecate duplicate bulk methods

---

src/cursor/abstract_cursor.ts

Deprecates `AbstractCursor.forEach()`
Deprecates the method in favour of `for await...of`.
None
NODE-4774

feat(NODE-4774): deprecate cursor forEach

---

src/admin.ts
src/db.ts
src/operations/add_user.ts

Deprecates the addUser helper.
- Deprecates the addUser helper along with the associated options.
None
NODE-4795

feat(NODE-4795): deprecate addUser helper

---

src/cmap/auth/auth_provider.ts
src/cmap/connect.ts
src/connection_string.ts
src/mongo_client.ts
src/utils.ts
test/integration/connection-monitoring-and-pooling/connection.test.ts
test/integration/node-specific/topology.test.js
test/tools/cmap_spec_runner.ts
test/unit/cmap/handshake/client_metadata.test.ts
test/unit/sdam/topology.test.js

fix(NODE-5161): metadata duplication in handshake

---

.evergreen/config.in.yml
.evergreen/config.yml

- Reload expansions before deleting Azure resources
Verified with this patch: https://spruce.mongodb.com/version/64345805850e61555185df30
No.
This is an improvement to the `testazurekms_task_group` added as part of DRIVERS-2411. https://github.com/mongodb/mongo-c-driver/pull/1234 explains this improvement.
- ~~[ ] Changes are covered by tests~~ N/A. Only modifies Evergreen config.
- ~~[ ] New TODOs have a related JIRA ticket~~ N/A. No new TODOs were added.

test(NODE-5183): Clean up Azure resources on task failure

---

src/collection.ts
src/operations/update.ts
test/types/community/collection/updateX.test-d.ts

`UpdateResult` is now generic over a collection schema type.  `UpdateResult.upsertedId` has two changes: it can now be null, and the type is inferred from the collection schema.  
`Collection.update*` methods now return an `UpdateResult` that is generic over the collection's schema.

fix(NODE-5171): allow `upsertedId` to be null in `UpdateResult`

---

src/cmap/handshake/client_metadata.ts
test/unit/cmap/handshake/client_metadata.test.ts

Changes platform metadata based on globals in the driver's runtime environement.
Node.js compatibility in Deno and Bun have made it possible to run the driver, it is useful to denote the difference between the runtimes in the platform information.

feat(NODE-5188): add alternative runtime detection to client metadata

---

src/connection_string.ts
src/sdam/srv_polling.ts
src/utils.ts
test/unit/utils.test.ts

fix(NODE-5200): relax SRV record validation to account for a dot suffix

---

src/cmap/auth/auth_provider.ts
src/cmap/connect.ts
src/cmap/connection.ts
src/cmap/handshake/client_metadata.ts
src/connection_string.ts
src/index.ts
src/mongo_client.ts
src/sdam/topology.ts
src/utils.ts
test/integration/connection-monitoring-and-pooling/connection.test.ts
test/integration/mongodb-handshake/mongodb-handshake.prose.test.ts
test/integration/mongodb-handshake/mongodb-handshake.test.ts
test/integration/node-specific/topology.test.js
test/tools/cmap_spec_runner.ts
test/unit/cmap/handshake/client_metadata.test.ts
test/unit/sdam/topology.test.js

feat(NODE-5159): add FaaS env information to client metadata

---

src/operations/find.ts

Logic to support `Binary` objects as filter predicates has been removed from the `find` operation.
No.

chore(NODE-5133): remove broken filter as binary from find operation

---

src/mongo_logger.ts
test/unit/mongo_logger.test.ts

Adds the `maybeTruncate` helper and calls it in the `defaultLogTransform` helper function to produce spec-compliant logs.

feat(NODE-4815): stringify and truncate BSON documents in log messages

---

src/change_stream.ts
test/types/change_stream.test-d.ts

Update [ChangeStream.tryNext()](https://github.com/mongodb/node-mongodb-native/blob/d6bd1d1602c213e5c46a702163351d1865cdc727/src/change_stream.ts#L703) return type to be consistent with [ChangeStream.next()](https://github.com/mongodb/node-mongodb-native/blob/d6bd1d1602c213e5c46a702163351d1865cdc727/src/change_stream.ts#L674).
The underlying AbstractCursor has the [same return type](https://github.com/mongodb/node-mongodb-native/blob/d6bd1d1602c213e5c46a702163351d1865cdc727/src/cursor/abstract_cursor.ts#L375-L386) for both.
If [these API docs](https://mongodb.github.io/node-mongodb-native/5.3/classes/ChangeStream.html#tryNext) aren't auto-generated, then yes.
Avoiding having to cast when using ChangeStream.tryNext().

fix(NODE-5213): `ChangeStream.tryNext()` should return TChange type

---

test/spec/retryable-writes/README.rst
test/spec/retryable-writes/unified/handshakeError.yml
test/spec/retryable-writes/unified/insertOne-noWritesPerformedError.json
test/spec/retryable-writes/unified/insertOne-noWritesPerformedError.yml

Catches up some missed spec tests in this sync

test(NODE-3733): sync remaining unified tests

---

src/deps.ts

QE equality API is marked stable in anticipation of 7.0.
Yes.

docs(NODE-5280): mark QE equality stable

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/install-dependencies.sh
.evergreen/run-azure-kms-tests.sh
.evergreen/run-custom-csfle-tests.sh
.evergreen/run-gcp-kms-tests.sh
.evergreen/run-serverless-tests.sh
.evergreen/run-tests.sh

test(NODE-5180): bump mongodb-client-encryption pinned commits to 2.8.0 release 

---

src/mongo_client.ts

Updates the TLS comments in `MongoClient` to note the spec compliant options, that others will be deprecated and removed, and fixed the type comments on the existing options.
NODE-4778

docs(NODE-4778): update tls option notes

---

src/operations/create_collection.ts

The `strict` option was removed in driver 4.x but the Typescript was not updated.  This PR removes the `strict` option from the `CreateCollectionOptions` type.

fix(NODE-5249): remove strict flag from create collection options

---

.evergreen/ci_matrix_constants.js
.evergreen/config.yml

Adds 7.0 servers to our CI matrix.  

test(NODE-5299): add 7.0 server to CI 

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-custom-csfle-tests.sh
.evergreen/run-serverless-tests.sh
.evergreen/run-tests.sh
global.d.ts
src/cmap/handshake/client_metadata.ts
src/error.ts
test/integration/mongodb-handshake/mongodb-handshake.prose.test.ts
test/integration/node-specific/errors.ts
test/tools/runner/filters/node_version_filter.js
test/unit/cmap/handshake/client_metadata.test.ts

Backports https://github.com/mongodb/node-mongodb-native/pull/3663 and https://github.com/mongodb/node-mongodb-native/pull/3682.
Also updates CI scripts to pull in mongodb-client-encryption@2.8.0.

fix(NODE-5262, NODE-5311): batch backport

---

test/integration/client-side-encryption/client_side_encryption.prose.test.js

Adds prose test #2 for RewrapManyDataKey.
- Adds the second prose test and asserts that it raises an error.
- Bindings throw a type error with the message "expected UTF-8 provider" - no bindings changes needed.
None
NODE-4708 / DRIVERS-2441

test(NODE-4708): add rewrapmanydatakey prose test 2

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-tests.sh

*Summary*
Adding new CI variants to run CSFLE tests with mongocryptd instead of crypt_shared, which we already had coverage for.
- script in "run tests" now conditionally executes `.evergreen/prepare-crypt-shared-lib.sh`
- script in "run tests" now sets the `TEST_NPM_SCRIPT` env variable
- Added new tasks that only run the csfle integration suite on relevant server versions and topologies using mongocryptd
No

ci(NODE-4698): test csfle with mongocryptd

---

.evergreen/ci_matrix_constants.js
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

- vs2019 -> vsCurrent
- Gathered all the hosts into constants, with the intention to make a quick reference of which hosts we depend on
vsCurrent is a more recent OS and is better maintained

ci(NODE-5312): change windows hosts to vsCurrent

---

.evergreen/ci_matrix_constants.js
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

- vs2019 -> vsCurrent
- Gathered all the hosts into constants, with the intention to make a quick reference of which hosts we depend on
#3687
vsCurrent is a more recent OS and is better maintained

ci(NODE-5313): change windows hosts to vsCurrent

---

src/sdam/server.ts
test/integration/server-selection/operation_count.test.ts

Fixes operation count flaky test.
Wraps the increment/decrement of the server's operation count in 2 methods, that then can be spied on to assert the number of times each was called.
None
NODE-5265

test(NODE-5265): fix flaky operation count test

---

src/mongo_client.ts
test/integration/node-specific/mongo_client.test.ts

Backports the mongo client connect log fix from https://github.com/mongodb/node-mongodb-native/pull/3596.
No.

fix(NODE-5316): prevent parallel topology creation in MongoClient.connect

---

.github/scripts/nightly.mjs
.github/workflows/release-nightly.yml

ci(NODE-5328): change format of nightly versions

---

.github/scripts/nightly.mjs
.github/workflows/release-nightly.yml

Tested locally:
```
version:       5.6.0-dev.20230602.sha.357472cd1            
filename:      mongodb-5.6.0-dev.20230602.sha.357472cd1.tgz
```
month is fixed

chore(NODE-5336): finalize nightly release time

---

CONTRIBUTING.md

Update dead mtools link in CONTRIBUTING.md
No
Remove dead link

chore: update mtools link

---

package-lock.json
package.json
src/cmap/auth/gssapi.ts
src/cmap/wire_protocol/compression.ts
src/deps.ts
test/action/dependency.test.ts

Adds zstd and kerberos to peer dependencies.
Sets @mongodb-js/zstd and kerberos in the peer dependencies to their latest versions and sets them as optional.
None
NODE-5008
- [] Changes are covered by tests

feat(NODE-5008): add zstd and kerberos to peer deps

---

.github/workflows/release-alpha.yml

Adds a workflow_dispatch, so we can test the actual implementation of the alpha release process.

chore(NODE-5344): add alpha skeleton for testing

---

.evergreen/config.yml
.evergreen/generate_mongosh_tasks.js

ci(NODE-5341): remove browser repl from mongosh CI

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/install-dependencies.sh

- Updates the distro used for perf testing to the dedicated rhel90-dbx-perf-large
- Updates the node version for perf testing to a pinned 18.6.0
- Updates the server version for perf testing to a pinned 6.0.6
No
Consistent build for perf testing

ci: use perf distro and pinned server and node versions for testing

---

.github/workflows/release.yml

chore(NODE-5347): add release workflow skeleton

---

.evergreen/activate-kms-venv.sh
.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/run-kmip-server.sh
.evergreen/run-kms-servers.sh

CI was getting frequent errors "KMS Request Failed" due to the KMIP server not being started by the time the tests that needed it ran. This was a common happening across all drivers, and while each driver addressed it in its own manner the common solution was that the KMIP server needed to be started in its own task.
- Splits the startup of the KMIP and KMS HTTP servers in 2 separate subprocess tasks that run in the background.
- Splits out the activation of the kms virtual env into its own subprocess task that does not run in the background, to ensure all the python requirements are fulfilled synchronously.
None
NODE-5198

test(NODE-5198): fix kms request failure

---

.evergreen/config.in.yml
.evergreen/config.yml

ci(Node 5335): clean up instance profile from instance after CI runs

---

etc/docs/build.ts

Bump typedoc to 0.24.8 to support TS 5.
Bumps typedoc to 0.24.8
None
NODE-5346

fix(NODE-5346): update typedoc version

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/prepare-shell.sh

Updates the aws auth lambda handler test to use the new drivers-evergreen-tools setup for AWS authentication.
No.

ci(NODE-5322): fix lambda handler aws test

---

lib/core/auth/scram.js

Prevents an error when `saslprep` is not a function.

fix(NODE-5355): prevent error when saslprep is not a function

---

.github/pull_request_template.md
.github/scripts/highlights.mjs
HISTORY.md

Make relase-notes action and PR template format the highlights prettier.
No
Pretty release docs

chore: update release note generation formatting

---

etc/check-remote.sh

Restoring the check-remote script that turned out to be used in our docs build.
No
Fix the docs build

chore: put check-remote script back to fix docs build

---

src/operations/find_and_modify.ts

Fixes the docs around the `includeResultMetadata` option.
Updates the docs on the options.
None
NODE-5368
A new flag, `includeResultMetadata` has been added to `Collection.findOneAnd*` helpers.  This flag defaults to true.  When disabled, the collection helpers only return the modified document.  For example:
```typescript
const deletedDocument = collection.findOneAndDelete({ _id: <id> }, { includeResultMetadata: false });
// deletedDocument contains the deleted document from the server, not a `ModifyResult`
```

docs(NODE-5368): fix includeResultMetadata docs

---

etc/expand-tasks.mjs

This script parses the evergreen config and will print all the commands that get executed in CI for that task.  This is useful when you need to answer the question: "What happens in CI for a particular task?"

chore(no-story): add script to display commands for a given evergreen task

---

src/collection.ts
src/cursor/list_search_indexes_cursor.ts
src/operations/search_indexes/create.ts

The search index API is marked public. 
Also, @lerouxb noticed that the definition for `SearchIndexModel` was incorrect, although the code path (and our unified tests) do assert on the correct value at runtime.  This PR fixes the type.
Yes, docsp ticket.
This PR adds support for managing search indexes (creating, updating, deleting and listing indexes).  The new methods are available on the `Collection` class.
```typescript
const indexes = await collection.listSearchIndexes().toArray(); // produces an array of search indexes
await collection.createSearchIndex({ name: 'my-index', definition: < index definition > } ); 
await collection.updateSearchIndex('my-index', < new definition >);
await collection.dropSearchIndex('my-index');
```
- Example: `feat(NODE-1234)!: rewriting everything in …

feat(NODE-5319): mark search index api public

---

src/connection_string.ts
src/mongo_client.ts

Deprecates duplicate SSL options in favour of spec compliant TLS options.
Deprecates:
- sslCA
- sslCRL
- sslCert
- sslKey
- sslPass
- sslValidate
- tlsCertificateFile
None
NODE-5287

feat(NODE-5287): deprecate ssl options

---

src/change_stream.ts
src/index.ts
test/integration/change-streams/change_streams.prose.test.ts

Adds support for change stream split events.
- Adds the new `ChangeStreamSplitEvent` type.
- Adds the `splitEvent` to the change stream common document type.
- Add the new prose test to test the event splitting. (see https://github.com/mongodb/specifications/tree/master/source/change-streams/tests#prose-tests #19)
None
NODE-5243
When change stream documents exceed the max BSON size limit of 16MB, they can be split into multiple fragments in order to not error when sending events over the wire. In order to enable this functionality, the collection must be created with `changeStreamPreAndPostImages` enabled and the change stream itself must include an `$changeStreamSplitLargeEvent` aggregation stage. This feature requires a minimum server version of 7.0.0.
Example:
```typescript
await …
```

feat(NODE-5243): add change stream split event

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/prepare-shell.sh

Switches the deployed AWS Lambda tests to use task groups for more consistent setup and teardown.
- Removes the one-shot lambda test.
- Updates the Evergreen config to use task groups with a setup and teardown script provided in drivers tools. (https://github.com/mongodb-labs/drivers-evergreen-tools/pull/325)
- Spec changes: https://github.com/mongodb/specifications/pull/1438
None
NODE-5361/DRIVERS-2657 and not losing money on orphaned Atlas clusters.

ci(NODE-5361): use task groups for lambda

---

.github/actions/setup/action.yml
.github/scripts/highlights.mjs
.github/scripts/pr_list.mjs
.github/scripts/release_notes.mjs
.github/scripts/util.mjs

Backport release scripts.
No
The release_notes action will need the scripts local to the 4.x branch in order to run properly
- [/] Ran `npm run check:lint` script
- [/] Changes are covered by tests
- [/] New TODOs have a related JIRA ticket

chore(NODE-5382): backport release automation scripts

---

.github/workflows/release-4.x.yml

- Copied the release from main workflow
- Changed the branch trigger to 4.x
- Changed default-branch to 4.x
- added npm tag "4x"
No
Automagic releases for 4.x
- [/] Ran `npm run check:lint` script
- [/] Changes are covered by tests
- [/] New TODOs have a related JIRA ticket

chore(NODE-5382): add 4.x release workflow

---

src/gridfs/upload.ts
src/operations/aggregate.ts
src/operations/command.ts
src/sessions.ts
src/write_concern.ts
test/integration/crud/find_and_modify.test.ts
test/integration/node-specific/mongo_client.test.ts
test/integration/transactions/transactions.spec.test.js
test/integration/uri-options/uri.test.js
test/unit/write_concern.test.ts

Deprecates old write concern options.
- Deprecates `wtimeout`, `j`, and `fsync` options.
- Adds new `WriteConcern.apply()` method to add a write concern to a command.
- Updates instances of adding write concern to commands to use the new apply method.
None
NODE-5274
`wtimeout`, `j`, and `fsync` options have been deprecated, please use `wtimeoutMS` and `journal` instead.

feat(NODE-5274): deprecate write concern options

---

package-lock.json
package.json

Updates BSON to latest 5.4.0
Keeps BSON up to date with next driver release
Take a look at the `bson` package's release notes!
- https://github.com/mongodb/js-bson/releases/tag/v5.4.0

feat(NODE-5407): update bson to 5.4.0

---

src/index.ts
src/operations/add_user.ts
src/operations/aggregate.ts
src/operations/command.ts
src/operations/count.ts
src/operations/create_collection.ts
src/operations/delete.ts
src/operations/distinct.ts
src/operations/drop.ts
src/operations/estimated_document_count.ts
src/operations/eval.ts
src/operations/find.ts
src/operations/find_and_modify.ts
src/operations/indexes.ts
src/operations/insert.ts
src/operations/list_collections.ts
src/operations/list_databases.ts
src/operations/profiling_level.ts
src/operations/remove_user.ts
src/operations/run_command.ts
src/operations/set_profiling_level.ts
src/operations/stats.ts
src/operations/update.ts
src/operations/validate_collection.ts
src/sdam/server.ts
test/integration/crud/explain.test.ts
test/unit/operations/abstract_command.test.ts

refactored CommandOperation class to use async
modified all calls to CommandOperation to call CommandCallbackOperation instead
new class CommandCallbackOperation
operations now subclass CommandCallbackOperation
new tests
refactoring operations layer to use async/await

refactor(NODE-5360): refactor CommandOperation to use async

---

.evergreen/ci_matrix_constants.js
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/install-dependencies.sh
package.json
test/integration/node-specific/errors.test.ts
tsconfig.json

- Dropping testing & support for Node.js 14
- Update engine field to >=16.20.1
- Update tsconfig target & lib to es2021
Update to the compat table will follow the release of v6
Removing support for EOL node versions helps us keep our tooling and testing up to date and modern. 
The minimum supported Node.js  version is now v16.20.1. We strive to keep our minimum supported Node.js version in sync with the runtime's [release cadence](https://nodejs.dev/en/about/releases/) to keep up with the latest security updates and modern language features.

feat(NODE-5415)!: bump minimum Node.js version to v16.20.1

---

src/bulk/common.ts
src/operations/aggregate.ts
src/operations/find_and_modify.ts
src/operations/insert.ts

- remove duplicate BulkWriteResult accessors
- Add defaultValue documentation to BulkOptions
- Remove mention of non-supported server version on `bypassDocumentValidation` option.
API docs will update in next release
Removal of duplicate APIs so there is a single source of truth.
The following deprecated properties have been removed as they duplicated the functionality provided by the common driver spec compliant properties. The list indicates what properties provide the correct migration:
- `BulkWriteResult.nInserted` -> `BulkWriteResult.insertedCount`
- `BulkWriteResult.nUpserted` -> `BulkWriteResult.upsertedCount`
- `BulkWriteResult.nMatched` -> `BulkWriteResult.matchedCount`
- `BulkWriteResult.nModified` -> `BulkWriteResult.modifiedCount`
- `BulkWriteResult.nRemoved` -> …

feat(NODE-5186)!: remove duplicate BulkWriteResult accessors

---

.github/workflows/release-4.x.yml
.github/workflows/release.yml

Adds id-token permission for releasing

chore(NODE-5433): add id-token permission to release workflow

---

test/integration/node-specific/examples/change_streams.test.js

The Server documentation has a ticket (DOCSP-29813) to improve the code example naming, which is generated from this test file.
The corresponding documentation ticket mentioned above tracks these changes.
There was a discussion in NODE-2307 about confusion related to how to use change streams. Updating this example was an action item from that discussion that is intended to help relieve some of that confusion.

docs(NODE-5438): Improve naming in code example for documentation

---

src/operations/add_user.ts
src/operations/create_collection.ts
src/operations/drop.ts
src/operations/is_capped.ts
src/operations/options_operation.ts
src/operations/profiling_level.ts
src/operations/remove_user.ts
src/operations/rename.ts
src/operations/set_profiling_level.ts
src/operations/stats.ts
src/operations/validate_collection.ts

admin operations were converted from callback to async/await format
executeCallback changed to execute and now returns a promise
because of inheritance from AbstractCallbackOperation, there is also an implementation of executeCallback
No
further converting the driver from callbacks to async/await

refactor(NODE-5437): admin operations to use async syntax

---

package-lock.json
src/cmap/connection_pool_events.ts
test/integration/connection-monitoring-and-pooling/connection_pool.test.ts
test/types/connection_pool_events.test-d.ts
test/unit/cmap/connection_pool_events.test.ts

- Remove unneeded fields from `ConnectionPoolCraetedEvent.options`
- Made `ConnectionPoolCreatedEvent.options` field required
The `options` field of `ConnectionPoolCreatedEvent` now has the following shape:
```ts
{
maxPoolSize: number,
minPoolSize: number,
maxConnecting: number,
maxIdleTimeMS: number,
waitQueueTimeoutMS: number
}
```

fix(NODE-5228)!: remove unneeded fields from ConnectionPoolCreatedEvent.options

---

.github/workflows/release-4.x.yml
.github/workflows/release-alpha.yml
.github/workflows/release-nightly.yml
.github/workflows/release.yml

Move permissions, make release work again
No

chore(NODE-5474): move id-token permission to workflow

---

src/operations/search_indexes/create.ts
src/operations/search_indexes/drop.ts
src/operations/search_indexes/update.ts

search index operations now use async/await syntax
each search index operation inherits from AbstractOperation and calls server.commandAsync
None
further converting the driver to use async syntax

refactor(NODE-5480): search index operations to use async syntax

---

test/action/dependency.test.ts

- use alpha version instead of major for check:dependencies test
No.
Prevent inbox spam 

chore: pin dependencies check mongodb-client-encryption test to install alpha

---

package-lock.json
package.json
src/client-side-encryption/stateMachine.js
src/cmap/connect.ts
src/deps.ts
test/action/dependency.test.ts

- Add getSocks method to deps
- update dependencies test for socks, and general imports
No
See highlight
The driver uses the `socks` dependency to connect to `mongod` or `mongos` through a [SOCKS5 proxy](https://en.wikipedia.org/wiki/SOCKS).  `socks` used to be a required dependency of the driver and was installed automatically.  Now, `socks` is a `peerDependency` that must be installed to enable `socks` proxy support. 

feat(NODE-5409)!: allow socks to be installed optionally

---

src/mongo_client.ts
src/sessions.ts
test/integration/sessions/sessions.test.ts
test/integration/transactions/transactions.test.ts
test/tools/unified-spec-runner/operations.ts
test/types/sessions.test-d.ts

- `withSession` & `withTransaction` return the value returned by the provided functions
Yes, API docs have been updated. Look for docs changes needed on the ticket
See highlight.
The `await client.withSession(async session => {})` now returns the value that the provided function returns. Previously, this function returned `void` this is a feature to align with the following breaking change. 
The `await session.withTransaction(async () => {})` method now returns the value that the provided function returns. Previously, this function returned the server command response which is subject to change depending on the server version or type the driver is connected to. The return value got in the way of writing robust, reliable, consistent code no matter the backing database supporting the …

feat(NODE-2014)!: return executor result from withSession and withTransaction

---

src/sessions.ts
test/integration/transactions/transactions.test.ts
test/tools/unified-spec-runner/operations.ts

- commit & abort transaction properly return void
- added a regression test
The typescript has been updated.
See notes
Each of these methods erroneously returned server command results that can be different depending on server version or type the driver is connected to. These methods return a promise that if resolved means the command (aborting or commiting) sucessfully completed and rejects otherwise. Viewing command responses is possible through the [command monitoring APIs](https://www.mongodb.com/docs/drivers/node/upcoming/fundamentals/monitoring/command-monitoring/) on the MongoClient.

feat(NODE-4961)!: remove command result from commit and abort transaction APIs

---

src/client-side-encryption/client_encryption.ts
src/collection.ts
src/operations/find_and_modify.ts
test/integration/crud/crud_api.test.ts
test/integration/crud/explain.test.ts
test/integration/crud/find.test.js
test/integration/crud/find_and_modify.test.ts
test/integration/crud/insert.test.js
test/integration/node-specific/client_encryption.test.ts
test/integration/node-specific/operation_examples.test.ts
test/tools/unified-spec-runner/operations.ts
test/types/community/collection/findX.test-d.ts
test/types/community/transaction.test-d.ts
test/types/schema_helpers.test-d.ts

- `includeResultsMetadata` is now set to false by default for `findAndX` family of methods
- Updated uses of `findAndX` methods to set `includeResultMetadata` as appropriate
- NODE-3568
- spec compliance
Previously, the default return type of this family of methods was a `ModifyResult` containing the found document and additional metadata. Now by default, they will return the found document or `null`.
```ts
// This has the same behaviour as providing `{ includeResultMetadata: false }` in the pre v6 driver
await collection.findOneAndUpdate(
{ hello: 'world' },
{ $set: { hello: 'WORLD' } });
// > { _id: new ObjectId("64c4204517f785be30795c92"), hello: 'world' }
// This has the same behaviour as providing no options in the pre v6 driver
await collection.findOneAndUpdate(
{ hello: 'world' }, …
```

feat(NODE-3568)!: ensure includeResultsMetadata is false by default

---

.evergreen/generate_evergreen_tasks.js
.evergreen/run-kerberos-tests.sh

Updates kerberos dependency to ^2.0.1
The optional peer dependency has already changed, this updates the test script to install it instead of the beta. There were no specific tests targeting kerberos 1.x and the filter in the evergreen generation script was removed even though it was no longer actually doing anything.
None
NODE-5490
This was done in https://github.com/mongodb/node-mongodb-native/pull/3691/commits/5fcdf93df573739904f405177413fb327a5015d6 (https://github.com/mongodb/node-mongodb-native/pull/3691)

feat(NODE-5490)!: bump kerberos compatibility to ^2.0.1

---

.evergreen/run-kerberos-tests.sh
package-lock.json
package.json

Changes kerberos dependency to `^1.0.0 || ^2.0.0`
Changes kerberos dependency back to `^1.0.0 || ^2.0.0` to reintroduce 1.x support.
None
NODE-5489
Moves the kerberos dependency back to `^1.0.0 || ^2.0.0` to indicate support for both 1.x and 2.x. Support for 1.x is removed in 6.0.

fix(NODE-5489): set kerberos compatibility to ^1.0.0 || ^2.0.0

---

package-lock.json
package.json

Change `@aws-sdk/credential-providers` version to 3.188.0 since this is the version that will get pulled in when users work with the driver in AWS Lambda
No
NODE-5412
This release lowers the version of the `@aws-sdk/credential-providers` peer dependency to 3.188.0 as this is the version that will get pulled in when using the driver in AWS lambda environments in the Node 18 runtime.

fix(NODE-5412): drop aws sdk version to match node18 runtime

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
package-lock.json
package.json
test/tools/runner/filters/client_encryption_filter.js
test/tools/runner/hooks/configuration.js

To prepare for the 6.0 release and the compatabilty matrix between mongodb-client-encryption and the driver, I added a task to our CI that tests the latest driver changes against mongodb-client-encryption@6.0.0.  This task runs for all regular CI runs as a part of the custom csfle tests.
I also pulled in the latest alpha of mongodb-client-encryption for all CI runs except the new variant.
To confirm that the new task was running against the correct version of `mongodb-client-encryption`, I added the version of mongodb-client-encryption used (if it's available) to the printout before mocha CI runs.  This affects all CI runs but I believe this is a useful improvement.  Here is an example: https://parsley.mongodb.com/evergreen/mongo_node_driver_next_rhel80_large_Node20_test_4.4_sharded_cluste …

ci(NODE-5424): add CI testing for FLE 6.0 with driver latest

---

.github/workflows/release-5.x.yml

Adds a 5.x release automation
No
- Merge robot PR === Release 5.x

chore(NODE-5428): add 5.x release automation

---

docs/4.10/classes/ClientSession.html
docs/4.11/classes/ClientSession.html
docs/4.12/classes/ClientSession.html
docs/4.13/classes/ClientSession.html
docs/4.14/classes/ClientSession.html
docs/4.15/classes/ClientSession.html
docs/4.16/classes/ClientSession.html
docs/4.7/classes/ClientSession.html
docs/4.8/classes/ClientSession.html
docs/4.9/classes/ClientSession.html
docs/5.0/classes/ClientSession.html
docs/5.1/classes/ClientSession.html
docs/5.2/classes/ClientSession.html
docs/5.3/classes/ClientSession.html
docs/5.4/classes/ClientSession.html
docs/5.5/classes/ClientSession.html
docs/5.6/classes/ClientSession.html
docs/5.7/classes/ClientSession.html
docs/Next/classes/ClientSession.html
src/sessions.ts

Previous link (https://www.mongodb.com/developer/quickstart/node-transactions/) returns a 404.
Based on the last valid [web archive](https://web.archive.org/web/20220516091725/https://www.mongodb.com/developer/quickstart/node-transactions/) of this page it appears this [MongoDB blog post](https://www.mongodb.com/blog/post/quick-start-nodejs--mongodb--how-to-implement-transactions) contains the same content.

docs(NODE-5535): fix link to Transactions quickstart 

---

README.md

NODE-5523
Added table with version compat info for add-on packages
This is documentation
Clarity about add-on compatibility
- [N/A] Ran `npm run check:lint` script

docs(NODE-5523): add component support matrix to readme

---

src/connection_string.ts
test/unit/mongo_client.test.js

This PR prevents the driver from emitting a deprecation warning when `tlsCertificateKeyFile` is specified and `tlsCertificateFile` is not.
No.
Because of internal options handling, a deprecation was emitted for `tlsCertificateFile` when using `tlsCertificateKeyFile`. That has been corrected.

fix(NODE-5495): do not emit deprecation warning when tlsCertificateKeyFile is specified and tlsCertificateFile is not

---

src/gridfs/download.ts
src/gridfs/upload.ts
test/integration/gridfs/gridfs.spec.test.js
test/integration/gridfs/gridfs_stream.test.js
test/tools/unified-spec-runner/operations.ts

- Remove overrides of stream methods
- Add overrides of _X stream methods that control the underlying implmentations
- Remove manual event emitting
- Ensure callback is always invoked asynchronously (nextTick)
- TBD
Node.js Streams are supposed to be implemented with the _X methods, the write & end functions are maintained by Node.js, the _ methods define the implementation of a stream.
Our implementation of a writeable stream for GridFSBucketWriteStream mistakenly overrode the `write()` and `end()` methods, as well as, manually emitted `'close'`, `'drain'`, `'finish'` events. Per Node.js documentation, these methods and events are intended for the Node.js stream implementation to provide, and an author of a stream implementation is supposed to override `_write`, `_final`, and allow …

fix(NODE-4788)!: use implementer Writable methods for GridFSBucketWriteStream 

---

etc/docs/template/layouts/index.html
etc/docs/template/layouts/partials/mongodbUniversity.html

M101JS no longer exists. Updated templates to link to new courses for Node.js developers
- fixed links
- moved MDB University section to below the _Quickstart_ (from below the _Releases_ list)

docs(NODE-5540): Fix MDB University links in GH pages

---

src/cmap/connection_pool_events.ts
src/operations/operation.ts
test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.test.ts

- Omit credentials from ConnectionPoolCreatedEvent if they exist
No
In order to avoid mistakenly printing credentials the `ConnectionPoolCreatedEvent` will replace the credentials option with an empty object. The credentials are still accessble via MongoClient options: `client.options.credentials`.

fix(NODE-5536): remove credentials from ConnectionPoolCreatedEvent options

---

package-lock.json
package.json
src/deps.ts

`@mongodb-js/saslprep` has replaced `saslprep` as the optional dependency our driver users on for SCRAM-SHA-256 authentication.
Until v6, the driver included the `saslprep` package as an optional dependency for SCRAM-SHA-256 authentication.  `saslprep` breaks when bundled with webpack because it attempted to read a file relative to the package location and consequently the driver would throw errors when using SCRAM-SHA-256 if it were bundled.
The driver now depends on `mongodb-js/saslprep`, a fork of `saslprep` that can be bundled with webpack because it includes the necessary saslprep data in memory upon loading. This will be installed by default but will only be used if SCRAM-SHA-256 authentication is used.  

feat(NODE-5398): use mongodb-js/saslprep instead of saslprep

---

package-lock.json
package.json
src/deps.ts

`@mongodb-js/saslprep` has replaced `saslprep` as the optional dependency our driver users on for SCRAM-SHA-256 authentication.
All existing passing tests are passing.  The failures for FLE are unrelated (they also are failing on `5.x`).
Until this release, the driver included the `saslprep` package as an optional dependency for SCRAM-SHA-256 authentication.  `saslprep` breaks when bundled with webpack because it attempted to read a file relative to the package location and consequently the driver would throw errors when using SCRAM-SHA-256 if it were bundled.
The driver now depends on `mongodb-js/saslprep`, a fork of `saslprep` that can be bundled with webpack because it includes the necessary saslprep data in memory upon loading. This will be installed by default but will only be used …

feat(NODE-5399): use mongodb-js/saslprep instead of saslprep

---

.github/scripts/highlights.mjs
.github/scripts/pr_list.mjs
.github/workflows/release-4.x.yml
.github/workflows/release_notes.yml

- sync scripts
4.x needs a copy of the release_notes workflow in order to manually dispatch from the release PR's branch.

chore: update release automation scripts 4.x

---

.github/scripts/highlights.mjs
.github/scripts/pr_list.mjs
.github/workflows/release-4.x.yml
.github/workflows/release-5.x.yml
.github/workflows/release-alpha.yml
.github/workflows/release-nightly.yml
package-lock.json
package.json

chore: update release automation scripts 5.x

---

package-lock.json
package.json

`@aws-sdk/credential-providers` has been lowered to `^3.188.0` to align with AWS Lambda's version.
`zstd` has been lowered to `1.0.0`. 
No.
The Node18 runtime on AWS Lambda comes with version `@aws-sdk/credential-providers@3.188.0` installed.  Our peer dependency version of 3.201.0 caused installation issues for users who wanted to use the driver with aws authentication on Lambda.

feat(NODE-5465,NODE-5538): lower `@aws-sdk/credential-providers` version to 3.188.0 and `zstd` to `^1.0.0`

---

src/cmap/command_monitoring_events.ts

Docs fixup for CommandStartedEvent

docs: fix cutoff sentence on CommandStartedEvent

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/run-tls-tests.sh
src/connection_string.ts
src/mongo_client.ts
test/manual/tls_support.test.ts
test/unit/connection_string.test.ts
test/unit/mongo_client.test.js

Adds the ability to provide a CRL file as an option in the connection string or client options.
- Adds a new option, `tlsCRLFile`, that takes a string as a path to the crl.pem.
- Refactors a bit of TLS testing variable names.
Yes, TLS options should be updated.
NODE-5549/NODE-5566
For users wanting to provide a TLS client revokation list as a filename and not a `Buffer`, a new option `tlsCRLFile` has been added and can be provided in either the connection string or as a `MongoClient` option.
```ts
new MongoClient('mongodb://localhost:27017/db?tls=true&tlsCRLFile=path/to/crl.pem'); // option in connection string.
new MongoClient('mongodb://localhost:27017/db', { tls: true, tlsCRLFile: 'path/to/crl.pem' }) // option in client options.
```
- Example: `feat(NODE-1234)!: rewriting everything …

feat(NODE-5566): add ability to provide CRL file via tlsCRLFile

---

src/connection_string.ts
src/mongo_client.ts

Adds a note on the new 6.0 `tlsCRLFile` option to SSL docs.
Doc changes and deprecation message.
None
NODE-5562

docs(NODE-5562): update upcoming crl option changes

---

src/deps.ts

Require @mongodb-js/saslprep not saslprep
Fixes the saslprep import.
None
NODE-5572
Fixes the import of saslprep to be the correct `@mongodb-js/saslprep` library.

fix(NODE-5572): fix saslprep import

---

src/deps.ts

Require @mongodb-js/saslprep not saslprep
Fixes the saslprep import.
None
NODE-5573
Fixes the import of saslprep to be the correct `@mongodb-js/saslprep` library.

fix(NODE-5573): fix saslprep import

---

package-lock.json
package.json
src/cmap/auth/scram.ts
test/action/dependency.test.ts
test/integration/crud/insert.test.js
test/integration/crud/pk_factory.test.js
test/tools/common.js
test/tools/utils.ts
test/types/community/collection/filterQuery.test-d.ts
test/unit/client-side-encryption/auto_encrypter.test.ts
test/unit/index.test.ts
test/unit/sessions.test.js

- Update bson to alpha.1
- Pull in mongodb-legacy main branch
No.
Test the nearly ready stuff!

chore(NODE-5581): pull in bson alpha.1 and mongodb-legacy main

---

src/sessions.ts
test/types/community/transaction.test-d.ts

- Fixed `withTransaction` return type
- Updated test to check `withTransaction` return type
- No
- Fixing NODE-2014 implementation (#3783)
N/A

fix(NODE-5592): fix withTransaction return type

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-socks5-tests.sh
.evergreen/run-unit-tests.sh
package-lock.json
package.json
test/action/dependency.test.ts

- bumping mongodb-client-encryption and bson to v6
- Remove manual mongodb-client-encryption installs in CI config and scripts
- Remove `test-latest-driver-mongodb-client-encryption-6.0.0` CI task
- Remove manual mongodb-client-encryption installs in test files
No.
https://github.com/mongodb/js-bson/releases/tag/v6.0.0
https://github.com/mongodb/libmongocrypt/releases/tag/node-v6.0.0

feat(NODE-5584)!: adopt bson v6 and mongodb-client-encryption v6

---

package-lock.json
package.json

- instead of a git branch we can use the released v6 legacy driver
- Some day we will remove our callback tests.... not today

chore(NODE-5585): use mongodb-legacy 6 for tests

---

src/cmap/auth/mongodb_aws.ts
src/deps.ts
test/integration/auth/mongodb_aws.test.ts

- Same as #3831
When using [IAM AssumeRoleWithWebIdentity](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html) AWS authentication the driver uses the [@aws-sdk/credential-providers](https://github.com/aws/aws-sdk-js-v3) package to contact the Security Token Service API for temporary credentials. AWS recommends using Regional AWS STS endpoints instead of the global endpoint to reduce latency, build-in redundancy, and increase session token validity. Unfortunately, environment variables `AWS_STS_REGIONAL_ENDPOINTS` and `AWS_REGION` do not directly control the region the SDK's STS client contacts for credentials. 
The driver now has added support for detecting these variables and setting the appropriate options when calling the SDK's API: …

fix(NODE-5550): set AWS region from environment variable for STSClient

---

src/cursor/abstract_cursor.ts
src/cursor/find_cursor.ts

- Modified the isDead condition (moved it to a getter)
- If the cursorId is zero, if it has been closed or has been killed, it's "dead"
- if kId is nullish, it has not been initialized yet, a not-even-started-yet cursor is not dead
- `(this[kId]?.isZero() ?? false) || this[kClosed] || this[kKilled];`
No
In a previous release, 5.7.0, we refactored cursor internals from callbacks to async/await. In particular, the `next` function that powers cursors was written with callbacks and would recursively call itself depending on the cursor type. For `ChangeStreams`, this function would call itself if there were no new changes to return to the user. After converting that code to async/await each recursive call created a new promise that saved the current async context. This would slowly build up …

fix(NODE-5587): recursive calls to next cause memory leak

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

- Accidental removal of coverage in https://github.com/mongodb/node-mongodb-native/pull/3845 reverted here.
- The latest driver must remain compatible with v6.0.0 of mongodb-client-encryption the task reintroduced here specifically pins to that version and runs our test suite.

ci(NODE-5424): test driver latest, client-encryption 6.0.0 in CI

---

package.json
test/atlas/drivers_atlas_testing.test.ts
test/tools/reporter/mongodb_reporter.js
test/tools/runner/config.ts
test/tools/runner/hooks/configuration.js
test/tools/unified-spec-runner/astrolabe_results_writer.ts
test/tools/unified-spec-runner/entities.ts
test/tools/unified-spec-runner/entity_event_registry.ts
test/tools/unified-spec-runner/operations.ts
test/tools/unified-spec-runner/runner.ts
test/tools/unified-spec-runner/schema.ts
test/unit/tools/unified_spec_runner/entity_event_registry.test.ts

This PR makes the necessary changes in the driver for it to be able to be tested by Astrolabe.
- Adds a new task `test:drivers-atlas-testing` to run the unified test runner against the Astrolabe tests.
- Updates the test runner config to use the URI provided by Astrolabe when present in the environment.
- Creates an astrolabe results write to write the spec defined events.json and results.json
- Updates the entities map to handle new new entites for `iterations`, `successes`, `events`, `failures`, and `errors`.
- Creates a registry to handle mapping events between the unified client and the entities map.
- Adds a new unified operation `loop`, as defined per the [Unified Test Format spec](https://github.com/mongodb/specifications/blob/master/source/unified-test-format/unified-test-format.rs …

test(NODE-3049): drivers atlas testing

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/generate_mongosh_tasks.js
.evergreen/install-dependencies.sh

Fixes Node 16 failures with npm 10.
- Installs npm@9 when on Node 16 or lower.
None
NODE-5606

test(NODE-5606): use npm 9 on eol node versions

---

test/integration/crud/aggregation.test.ts
test/integration/crud/explain.test.ts

Failing aggregate + explain tests are skipped on latest servers.

chore(no-story): skip failing aggregate explain tests

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/generate_mongosh_tasks.js
.evergreen/install-dependencies.sh

Fixes Node 16 failures with npm 10 on 5.x branch.
- Installs npm@9 when on Node 16 or lower.
None
NOE-5619

test(NODE-5619): use npm 9 on eol node versions

---

src/cursor/abstract_cursor.ts
src/cursor/aggregation_cursor.ts
src/cursor/change_stream_cursor.ts
src/cursor/find_cursor.ts
src/cursor/list_collections_cursor.ts
src/cursor/list_indexes_cursor.ts
src/cursor/run_command_cursor.ts
test/integration/change-streams/change_stream.test.ts
test/integration/change-streams/change_streams.prose.test.ts
test/integration/crud/explain.test.ts
test/tools/unified-spec-runner/operations.ts

refactored cursor internals to use async-await syntax instead of callbacks
getMore, _initialize, cleanupCursor, and [kInit] now use async-await syntax
all classes that inherit from AbstractCursor now use async-await
None
further converting the driver to async-await

refactor(NODE-5379): cursor internals to use async-await

---

package-lock.json
package.json

Bump bson dependency version to 5.5 to make use of [new `Decimal128` behaviour](https://github.com/mongodb/js-bson/releases/tag/v5.5.0).
Just release notes
NODE-5564
In this release, we have adopted the changes made to `Decimal128` in [bson version 5.5](https://github.com/mongodb/js-bson/releases/tag/v5.5.0). The `Decimal128` constructor and `fromString()` methods now throw when detecting a loss of precision (more than 34 significant digits). We also expose a new `fromStringWithRounding()` method which restores the previous rounding behaviour.
See the [bson v5.5.0 release notes](https://github.com/mongodb/js-bson/releases/tag/v5.5.0) for more information.

feat(NODE-5564): bump bson version to ^5.5.0

---

package-lock.json
package.json

Bump bson dependency version to 6.1.0 to expose new `Decimal128.fromStringWithRounding()` method.
Release notes
NODE-5634
In this release, we have adopted the changes made to Decimal128 in [bson version 6.1.0](https://github.com/mongodb/js-bson/releases/tag/v6.1.0). We have added a new `fromStringWithRounding()` method which exposes the previously available inexact rounding behaviour.
See the [bson v6.1.0 release notes](https://github.com/mongodb/js-bson/releases/tag/v6.1.0) for more information.

feat(NODE-5634): bump bson version to ^6.1.0

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

- Move all usages of `vars` to expansions
- set `add_expansions_to_env: true`
- formatting
**Note to reviewer** it is easier to follow changes per commit to skip over misc formatting fixes
No
Avoiding use of var removes the risk of breakages when evergreen removes the behavior where vars persist across functions

ci(NODE-5652): move vars to expansions

---

.evergreen/ci_matrix_constants.js
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
test/unit/assorted/polling_srv_records_for_mongos_discovery.prose.test.ts
test/unit/connection_string.spec.test.ts
test/unit/sdam/monitor.test.ts
test/unit/sdam/topology.test.js

We now unit test against Node18 and Node20 in CI.  The changes are set up so that when a new LTS node version is added, we will automatically start testing against it.
I also did a small cleanup and converted the `lint` variant in CI to use evergreen tags, not hard-coded task names.
The failing tests on Node18 and Node20 are skipped and NODE-5666 was filed to fix them.
No.

ci(NODE-5615): unit test on Node18 and Node20

---

.evergreen/ci_matrix_constants.js
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
test/unit/assorted/polling_srv_records_for_mongos_discovery.prose.test.ts
test/unit/connection_string.spec.test.ts
test/unit/sdam/monitor.test.ts
test/unit/sdam/topology.test.js

We now unit test on all supported Node versions.  Backports https://github.com/mongodb/node-mongodb-native/pull/3879.

ci(NODE-5664): unit test on all supported Node versions

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-bson-ext-test.sh
.evergreen/run-serverless-tests.sh
.evergreen/run-tests.sh
test/integration/client-side-encryption/client_side_encryption.prose.test.js

- 4.x only has custom dependency tests against the pinned commit
- FLE prose test 14 has been fixed, with the same fix from https://github.com/mongodb/node-mongodb-native/pull/3833/files
Unrelated to NODE-5667 - this PR also incorporates changes from https://jira.mongodb.org/browse/NODE-5632.  Notably, it
- sets the pinned commit to the mongodb-client-encryption@2.9.1 release commit
- specifies version 2.x of mongodb-client-encryption for driver 4.x CI

ci(NODE-5667): remove custom dep tests against master and fix prose test 14

---

test/integration/crud/aggregation.test.ts
test/integration/crud/explain.test.ts

Fixes explain tests to be able to handle SBE and non SBE explain results.
Looks for specific strings the JSON stringified version of the explain results. Not that SBE results do not contain an "allPlansExecution" or "executionStats" fields so those assertions were removed.
None
NODE-5617

test(NODE-5704): fix explain tests

---

test/integration/crud/aggregation.test.ts
test/integration/crud/explain.test.ts

Fixes explain tests to be able to handle SBE and non SBE explain results. (5.x backport)
Looks for specific strings the JSON stringified version of the explain results. Not that SBE results do not contain an "allPlansExecution" or "executionStats" fields so those assertions were removed.
None
NODE-5705

test(NODE-5705): fix failing explain tests

---

src/cmap/connection_pool.ts
src/index.ts
src/sdam/topology.ts
src/utils.ts
test/unit/utils.test.ts

- A custom abort controller, `TimeoutController`, has been added that aborts its signal after a specified timeout
- Server selection and connection checkout have been refactored to use the `TimeoutController` instead of managing timeouts
No.

refactor(NODE-5675): refactor server selection and connection checkout to use abort signals for timeout management 

---

src/sdam/events.ts
src/sdam/monitor.ts

Adds an `awaited` field to server heartbeat events.
- Adds the `awaited` field and sets it to true when using the streaming protocol.
- Tests will come as part of NODE-5197
None
Need the field to pass tests coming in NODE-5197
```typescript
const client = new MongoClient(process.env.MONGODB_URI);
client.on('serverHeartbeatStarted', (event) => {
console.log(event.awaited);
});
client.on('serverHeartbeatSucceeded', (event) => {
console.log(event.awaited);
});
client.on('serverHeartbeatFailed', (event) => {
console.log(event.awaited);
});
```

feat(NODE-5613): add `awaited` field to SDAM heartbeat events

---

src/collection.ts
test/integration/crud/crud_api.test.ts

I found this potential issue while troubleshooting https://github.com/Automattic/mongoose/issues/13829. Running the following Mongoose script:
```
import v8 from 'node:v8';
import mongoose from 'mongoose';
await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
const testSchema = new mongoose.Schema(
{
data: String,
createdAt: { type: Date, default: Date.now },
},
{
timeseries: {
timeField: 'createdAt'
},
expireAfterSeconds: 60 * 60 * 24 * 7
}
);
const TestModel = mongoose.model('Test', testSchema);
await TestModel.deleteMany({});
const docs = [];
for (let i = 0; i < 1000; ++i) {
docs.push({ data: '0'.repeat(1024 * 2 * 10) });
}
await TestModel.create(docs);
console.log('Created docs');
let start = Date.now();
let count = 0;
await TestModel.deleteMany({});
const docs = [];
for …
```

fix(NODE-5691): make findOne() close implicit session to avoid memory leak

---

src/collection.ts
test/integration/crud/crud_api.test.ts

A forward port of #3889
No
Ensures the cursor created for findOne is always cleaned up
When running a findOne against a time series collection due to the way the server returns the resulting cursor information the driver left the implicit session for the cursor un-ended. Now the cursor will always be cleaned up regardless of the outcome of the find operation.

fix(NODE-5706): make findOne() close implicit session to avoid memory leak

---

package-lock.json
package.json

- Pulls in bson ^6.2.0 
No.
See below.
BSON now prints in full color! :rainbow: :rocket: 
See our release notes for [BSON 6.2.0 here](https://github.com/mongodb/js-bson/releases/tag/v6.2.0) for more examples!

feat: update bson to 6.2.0

---

src/gridfs/download.ts
src/gridfs/upload.ts

Deprecate unused GridFS fields.
Deprecates `contentType` and `aliases` options.
None
[NODE-5590](https://jira.mongodb.org/browse/NODE-5590)
The GridFS `contentType` and `aliases` options are deprecated. According to [the GridFS spec](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst), applications wishing to store `contentType` and `aliases` should add a corresponding field to the `metadata` document instead.

feat(NODE-5590): deprecate GridFS fields

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Updates the AWS ECS task definition ARN to run on Ubuntu 20.
- Creates a new Evergreen environment variable for the new ARN
- Updates AWS tests to run on Ubuntu 20 and use the new ARN.
None
NODE-5707

test(NODE-5707): update aws ecs task definition

---

package-lock.json
package.json
test/action/dependency.test.ts

This includes a solution for the deprecation warning in NODE-5709 by bumping whatwg-url. The major version bump is only because the new Node.js version minimum supported by that whatwg-url version is Node.js 16.

fix(NODE-5709): bump mongodb-connection-string-url to 3.0.0

---

.evergreen/ci_matrix_constants.js
.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Updates the driver to use the new tools data lake test scripts so we don't occasionally fail when the DL team makes breaking changes to their configs. They now own the drivers config on the image and will update them when they make breaking changes.
- Updates our evergreen config to use the new `pull-mongohouse-image.sh` and `run-mongohouse-image.sh` scripts.
- Moves Data Lake tests to an Ubuntu 22 variant as these will not work on RHEL8
None
DRIVERS-2543

test(NODE-5732): update data lake test scripts

---

test/integration/crud/crud_api.test.ts

Remove at usage
No
Fix node 14

test(NODE-5733): remove `at()` usage

---

src/cmap/errors.ts
src/error.ts
src/sessions.ts
test/integration/retryable-writes/non-server-retryable_writes.test.ts

Use the `MongoErrorLabel.PoolRequstedRetry` label instead of misused `MongoErrorLabel.RetryableWriteError` for non-server errors according to [spec](https://github.com/mongodb/specifications/blob/master/source/retryable-writes/retryable-writes.rst).
- The `PoolClearedError` constructor adds the new `MongoErrorLabel.PoolRequstedRetry` label instead of misused `MongoErrorLabel.RetryableWriteError`.
- The `isRetryableWriteError` function checks if PoolRequstedRetry or RetryableWriteError is set to determine if `retryOperation` is required.
None
[NODE-4863](https://jira.mongodb.org/browse/NODE-4863)

fix(NODE-4863): do not use RetryableWriteError for non-server errors

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Updates the AWS ECS task definition ARN to run on Ubuntu 20.
- Creates a new Evergreen environment variable for the new ARN
- Updates AWS tests to run on Ubuntu 20 and use the new ARN.
None
NODE-5737

test(NODE-5737): update aws ecs task definition

---

.evergreen/ci_matrix_constants.js
.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Updates the driver to use the new tools data lake test scripts so we don't occasionally fail when the DL team makes breaking changes to their configs. They now own the drivers config on the image and will update them when they make breaking changes.
https://spruce.mongodb.com/task/mongo_node_driver_ubuntu2204_test_atlas_data_lake_test_atlas_data_lake_patch_3934465ef4dbc37d8f3942d8ffba5905ed0d509a_654d4a2a2a60ed5a5a28e98e_23_11_09_21_07_55?execution=0&sortBy=STATUS&sortDir=ASC
- Updates our evergreen config to use the new `pull-mongohouse-image.sh` and `run-mongohouse-image.sh` scripts.
- Moves Data Lake tests to an Ubuntu 22 variant as these will not work on RHEL8
None
NODE-5738

test(NODE-5738): update data lake test scripts

---

.evergreen/ci_matrix_constants.js
.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Updates the driver to use the new tools data lake test scripts so we don't occasionally fail when the DL team makes breaking changes to their configs. They now own the drivers config on the image and will update them when they make breaking changes.
- Updates our evergreen config to use the new `pull-mongohouse-image.sh` and `run-mongohouse-image.sh` scripts.
- Moves Data Lake tests to an Ubuntu 22 variant as these will not work on RHEL8
None
NODE-5739

test(NODE-5739): update data lake test scripts

---

src/sdam/monitor.ts
src/sdam/server.ts
test/integration/connection-monitoring-and-pooling/rtt_pinger.test.ts
test/unit/sdam/topology.test.js

- Adds serverApi and helloOk logic to RTTPinger
- Calls destory on connection when an error is recv-ed
- Replaced symbol properties with string properties
No
Fixes a connection leak when serverApi is enabled.
When enabling serverApi the driver's RTT mesurment logic (used to determine the closest node) still sent the legacy hello command "isMaster" causing the server to return an error. Unfortunately, the error handling logic did not correctly destroy the socket which would cause a leak.
Both sending the correct hello command and the error handling connection clean up logic are fixed in this change.

fix(NODE-5750): RTTPinger always sends legacy hello

---

src/sdam/monitor.ts
src/sdam/server.ts
test/integration/connection-monitoring-and-pooling/rtt_pinger.test.ts
test/unit/sdam/topology.test.js

- Adds serverApi and helloOk logic to RTTPinger
- Calls destory on connection when an error is recv-ed
- Replaced symbol properties with string properties
No
Fixes a connection leak when serverApi is enabled.
When enabling serverApi the driver's RTT mesurment logic (used to determine the closest node) still sent the legacy hello command "isMaster" causing the server to return an error. Unfortunately, the error handling logic did not correctly destroy the socket which would cause a leak.
Both sending the correct hello command and the error handling connection clean up logic are fixed in this change.

fix(NODE-5751): RTTPinger always sends legacy hello

---

.github/workflows/release_notes.yml

GH_TOKEN must be GITHUB_TOKEN
No
To give gh access to the api call

chore: fix env var name in release_notes

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Doesn't actually skip the Azure OIDC tests but removes them from the matrix as the failures are in the setup from the drivers tools scripts.
Removes the variant from the matrix with a todo.
None
NODE-5761

test(NODE-5761): skip azure oidc tests

---

src/cmap/commands.ts
src/cmap/connection.ts
src/sdam/monitor.ts

Some minor refactors to the monitoring class 
No
To pull them out of the "feature" work of adding streaming support to the new monitoring class.

refactor(NODE-5778): change kConnection to connection, split polling and streaming functions, define exhaustCommand

---

src/error.ts
test/spec/retryable-reads/unified/exceededTimeLimit.json
test/spec/retryable-reads/unified/exceededTimeLimit.yml

- Add ExceededTimeLimit to RETRYABLE_READ_ERROR_CODES
- Sync spec tests: https://github.com/mongodb/specifications/commit/5786a46a59cdfeebab36edf6672cdf6f23dd636c
Previously ExceededTimeLimit related only to retryable writes errors. Now it belongs both to RETRYABLE_WRITE_ERROR_CODES and RETRYABLE_READ_ERROR_CODES arrays.
None
[NODE-5717](https://jira.mongodb.org/browse/NODE-5717)

feat(NODE-5717): make ExceededTimeLimit retryable reads error

---

test/spec/index-management/README.rst
test/spec/index-management/createSearchIndex.json
test/spec/index-management/createSearchIndex.yml
test/spec/index-management/createSearchIndexes.json
test/spec/index-management/createSearchIndexes.yml
test/spec/index-management/dropSearchIndex.json
test/spec/index-management/dropSearchIndex.yml
test/spec/index-management/listSearchIndexes.json
test/spec/index-management/listSearchIndexes.yml
test/spec/index-management/updateSearchIndex.json
test/spec/index-management/updateSearchIndex.yml

- Syncs test changes from https://github.com/mongodb/specifications/pull/1485
No
Correct the substring match for error messages about search index support.

test(NODE-5799): search index management operations fail with a different error message

---

src/bulk/common.ts
src/collection.ts
src/mongo_types.ts
test/types/community/collection/bulkWrite.test-d.ts
test/types/community/collection/updateX.test-d.ts

Backporting https://github.com/mongodb/node-mongodb-native/pull/3953 to 5x.
We update types to fix the error with $addToSet in bulkWrite.
None
[NODE-5647](https://jira.mongodb.org/browse/NODE-5647)
[NODE-4664](https://jira.mongodb.org/browse/NODE-4664)
Extending collection interfaces from `Document`/`any` type or specifying fields of `any` type doesn't cause a type error anymore.

fix(NODE-5790): type error with $addToSet in bulkWrite

---

src/bulk/common.ts
src/operations/execute_operation.ts
src/sessions.ts
src/utils.ts
test/unit/utils.test.ts

- Move .then/.catch chain into callers
- Remove maybeCallback
- Improve docs over executeOperation
No.
This change is effectively a no-op, but it removes the overloads advertized by executeOperation that are no longer used making future changes to executeOperation easier to make.

refactor(NODE-5809): remove executeOperation callback overload and maybeCallback

---

test/manual/tls_support.test.ts

- Skip flaky windows URL settings TLS test
Tracking the fix at NODE-5803

chore(NODE-5842): skip windows tls url settings failure

---

test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.prose.test.ts
test/unit/sdam/server_discovery_and_monitoring.prose.test.ts

Implement spec test added in DRIVERS-2677
No
NODE-5724

test(NODE-5724): heartbeat started is emitted before socket is connected

---

src/connection_string.ts
src/mongo_client.ts
test/tools/unified-spec-runner/operations.ts

Implements unified test runner changes for the CSOT unified tests to run.
Implements the following operations:
- `listDatabaseNames`
- `listCollectionNames`
- `count`
- `listIndexNames`
- `dropIndexes`
- `drop`
Updates `find` to work on both a collection or gridfs bucket.
Patch for enabled CSOT unified tests on all topologies: https://spruce.mongodb.com/version/65a7fe30e3c33167dda24b5d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
None
NODE-5823

test(NODE-5823): CSOT unified runner changes

---

src/operations/execute_operation.ts
src/sdam/server_selection.ts
src/sdam/topology.ts
test/integration/server-selection/server_selection.prose.sharded_retryable_reads.test.ts
test/integration/server-selection/server_selection.prose.sharded_retryable_writes.test.ts
test/unit/sdam/server_selection.test.ts

When retrying reads and writes on a sharded cluster, will attempt the retry on a different mongos if multiple mongoses are present.
- `executeOperation` now keeps track of the previously selected server.
- Server selection will now attempt to exclude the previous server when the topology is sharded and multiple mongoses are present.
- Adds unit tests for server selection and prose tests for retryable reads and writes.
None
NODE-3470

feat(NODE-3470): retry selects another mongos

---

src/mongo_logger.ts
src/sdam/server_selection.ts
src/utils.ts
test/unit/mongo_logger.test.ts

Look at changes commit by commit to easily separate async and sync changes
This ticket is a subtask of [NODE-4816](https://jira.mongodb.org/browse/NODE-4816) (Add Error Handling to the Logger).
Essentially, these changes ensure that the logger does not crash the user's application at runtime, at any point after options are parsed.
Add support for runtime error handling (ensure no constructors for loggers throw unless given type errors, log.write, stringifyWithMaxLen, defaultLogTransform).
Add async support for log.write function
See all unit tests defined under runtime error handling in [Kickoff Document](https://docs.google.com/document/d/1gDJ9vpVdH7BalRxEvzC_UZz-gIYOLSTU7HTqSoa18FA/edit#heading=h.7t9v3ahij9a1), and under mongodbLogPath stream handling (since some of this must be done at …

feat(NODE-4848): Add runtime error handling to logging

---

src/mongo_logger.ts
test/integration/command-logging-and-monitoring/command_logging_and_monitoring.prose.test.ts
test/unit/mongo_logger.test.ts

Support truncation of multibyte codepoints through `stringifyWithMaxLen` into well-formed strings. (round down to the nearest codepoint).
- Add codepoint check before truncation
- If maxDocLength = 1, and maxDocLength--, return ' '
- Un-skipped prose test #3 for command logging
- No longer wrap lone strings in an extra quotation while stringifying for logger (makes stringification confusing to read and is unnecessary) 
No
Prose test #3 command logging (see kickoff)

fix(NODE-5839): support for multibyte code-points in stringifyWithMaxLen

---

src/cmap/auth/scram.ts
test/unit/assorted/scram_iterations.test.ts

Ensure that we don't strip padded "=" from saslStart responses that are passed to saslContinue.
We replace the existing parsing using `split` that kills trailing “=”s with `regex` parsing that preserves trailing “=”s.
None
[NODE-5609](https://jira.mongodb.org/browse/NODE-5609)
The authentication was rejected by the saslContinue command from mongosh due to missing "=" padding from the client. We fixed the way we parse payload to preserve trailing "="s.

fix(NODE-5609): node driver omits base64 padding in sasl-continue command

---

src/cmap/connect.ts
src/cmap/connection_pool.ts
src/error.ts
src/sdam/monitor.ts
src/utils.ts
test/integration/connection-monitoring-and-pooling/connection.test.ts
test/tools/runner/hooks/configuration.js
test/unit/cmap/connect.test.ts
test/unit/cmap/connection.test.ts
test/unit/sdam/monitor.test.ts

- Refactor connect to be async
- Rename and refactor makeConnection -> makeSocket
- Add makeConnection function
- Refactor monitor to record start time after socket is created, before handshake
- socket failures set heartbeat failed duration to -1 
- Refactor tests using callback style connect
- Test duration does not include socket creation by artificially delaying it
The duration field of hb started and failed should match the definition in the spec.
The ServerHeartbeatSucceeded and ServerHeartbeatFailed event have a duration property that represents the time it took to perform the `hello` handshake with MongoDB. The Monitor responsible for issuing heartbeats mistakenly included the time it took to create the socket in this field, which inflates the value with the time it takes to …

fix(NODE-5840): heartbeat duration includes socket creation

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Updates the Evergreen configurations to add expansions to the environment due to recent Evergreen config changes.
Cherry-picks https://github.com/mongodb/node-mongodb-native/commit/33933ba119df7a50ae48517c374de83ea2d19abf into the 6.0 branch and fixes all the merge conflicts and makes necessary npm version adjustments.
The base issue here was that the `AUTH` environment variable was getting improperly defaulted to "noauth" in the Evergreen runs when authentication was required and mongo orchestration had set up the clusters with auth enabled and auth URIs.
The failure for authentication (NODE-5856) on the POC unified spec tests for retryable reads was 3.6 replica set specific. Those tests are now passing shown here: https://spruce.mongodb.com/task/node_mongodb_native_6.0_rhel80_large_node_ …

ci(NODE-5856): move vars to expansions

---

test/integration/transactions/transactions.spec.test.js

Skip transaction unpin tests related to a build failure. 
Skip relevant tests. 
No.
Build failure described in NODE-5852

test(NODE-5852): Skip transaction unpin spec tests

---

package-lock.json
package.json

Upgrade next driver version to the latest BSON release
No.
New BSON new me
BSON 6.3.0 introduces an optimization to parsing basic latin (ASCII) strings under 20 bytes. This can have a big impact on the time it takes to parse BSON keys. 
Check out the release notes here: [BSON short basic latin string parsing performance improved! 🐎 ](https://github.com/mongodb/js-bson/releases/tag/v6.3.0)

feat(NODE-5885): upgrade BSON to `^6.3.0`

---

etc/notes/editor.md

- Add new extensions to our editor setup reccomendation
No.
De-opt node proved very useful in finding perf issues.

chore: update recommended editor extensions

---

src/cursor/abstract_cursor.ts
test/integration/node-specific/abstract_cursor.test.ts

Right now, any query error when using cursor `stream()` with `transform` option leads to an uncatchable error. Consider the following script: the following script throws an uncaught "Sort exceeded memory limit" even though there's an `on('error')` handler.
```javascript
const mongodb = require('mongodb');
const { Transform } = require('stream');
async function run() { 
const client = await mongodb.MongoClient.connect('mongodb://localhost:27017/test');
const numDocs = 10000;
const db = client.db();
const count = await db.collection('tests').countDocuments();
if (count < numDocs) {
const numToCreate = numDocs - count;
console.log(`begin creating ${numToCreate} docs`);
for (let i = 0; i < iterations; i++) {
await db.collection('tests').insertOne({ studentId: ('' + i).repeat(5000) }); …
```

fix(NODE-5901): propagate errors to transformed stream in cursor

---

src/mongo_logger.ts
src/sdam/topology.ts
test/unit/sdam/server_selection.test.ts

Add feature flagging to server selection logging, so that event instances are only created when `willLog` returns `true` for the logging configuration.
Upon comparing the perf results of NODE-5818's changes to the commit before server selection logging was merged ([b93d405](https://evergreen.mongodb.com/task/mongo_node_driver_next_performance_tests_run_spec_benchmark_tests_node_18_server_6.0_b93d405275c3a8ce6b1eba0af335ffb2a309e34e_24_01_03_17_07_24), there are no significant regressions through this commit. 
Both commits were rerun at the same time to ensure no ci changes influence the results.
Here is the [Spreadsheet Link](https://docs.google.com/spreadsheets/d/1L_tlp-n5-tUFVuSAQrmIdC0aqMNvFsPLKqV8my-ACE8/edit#gid=0).
Same as above.
No.
Before: (Due to server selection logging merge …

fix(NODE-5818): Add feature flagging to server selection logging

---

test/spec/retryable-writes/unified/bulkWrite-serverErrors.json
test/spec/retryable-writes/unified/bulkWrite-serverErrors.yml
test/spec/retryable-writes/unified/insertOne-serverErrors.json
test/spec/retryable-writes/unified/insertOne-serverErrors.yml
test/spec/unified-test-format/valid-pass/poc-retryable-writes.json
test/spec/unified-test-format/valid-pass/poc-retryable-writes.yml
test/tools/unified-spec-runner/unified-utils.ts

NODE-5797/DRIVERS-2799
* Synced the following tests to latest compatible with DRIVERS-2799; the resulting files include changes from DRIVERS-2609, DRIVERS-2799, and DRIVERS-2802:
* retryable-writes/unified/insertOne-serverErrors
* spec@5fc23f4 (DRIVERS-2802)
* retryable-writes/unified/bulkWrite-serverErrors
* latest spec
* unified-test-format/valid-pass/poc-retryable-writes
* latest spec
* *Note: The NODE tickets corresponding to DRIVERS-2609 and DRIVERS-2802 were updated to reflect that the above tests have already been updated.*
* Cleaned up `skipReason` logic to provide a more accurate message when skipping tests:
* Topology now takes precedence over server version (i.e., if neither the topology nor the server requirements are met, the skip will be attributed to the topology mismatch …

test(NODE-5938): sync retryable writes spec tests

---

src/operations/find_and_modify.ts

The previous version of the documentation (5.x) also had the lines that are removed in this commit. However, after testing and verifying, the default behavior is as-if the property "includeResultMetadata" was set to false.
The change is documentation 
Incorrect documentation 

docs(NODE-5933): remove find-and-modify warning about defaults

---

test/spec/connection-string/invalid-uris.json
test/spec/connection-string/invalid-uris.yml
test/spec/connection-string/valid-options.json
test/spec/connection-string/valid-options.yml
test/spec/connection-string/valid-unix_socket-absolute.json
test/spec/connection-string/valid-unix_socket-absolute.yml
test/spec/connection-string/valid-unix_socket-relative.json
test/spec/connection-string/valid-unix_socket-relative.yml
test/spec/connection-string/valid-warnings.json
test/spec/connection-string/valid-warnings.yml
test/unit/connection_string.spec.test.ts

Syncs connection string spec tests to latest.
- Syncs the connection string spec tests to the most recent in the specifications repo.
- Note the DRIVERS ticket only mentions 2 tests, but I figured to see if going to latest on all would pass and the other changes did. This then covers NODE-5753 as well
- Unskipped NODE-3919 test as it passes now, and that ticket was already closed.
None
NODE-5643/NODE-5753/DRIVERS-2679/DRIVERS-2770

test(NODE-5643): sync connection string spec tests

---

src/cmap/auth/mongodb_aws.ts
src/cmap/auth/scram.ts
src/utils.ts

Move promisifying of `randomBytes` to utils.ts to make it module-scoped function and to reuse everywhere else.
None
Technical debt leftover from [NODE-5616](https://jira.mongodb.org/browse/NODE-5616)

refactor(NODE-5953): move promisifying of randomBytes to utils

---

src/cmap/connect.ts
test/unit/mongo_client.test.js

We don't need to pass `authProviders` to `prepareHandshakeDocument()`, because it can read `ConnectionOptions` from `AuthContext`.
None
[NODE-5964](https://jira.mongodb.org/browse/NODE-5964)

refactor(NODE-5964): clean up prepareHandshakeDocument

---

package-lock.json
package.json

https://github.com/mongodb/node-mongodb-native/commit/eb5e2ab762548571102d35d2ea7b516039a8aa71 accidentally included TS@5.3.3 in the package-lock file.  This was allowed because our version specification for Typescript was ^5.0.0.  
This had the unintended side-effect of breaking our API docs.
I specified in the package.json that TS must be a 5.0.x version for now, which fixes doc generation as well.

chore(NODE-5972): specify TS 5.0 in package.json and package-lock 

---

src/cmap/auth/auth_provider.ts
src/cmap/auth/mongodb_aws.ts
src/cmap/auth/scram.ts
src/cmap/connect.ts
src/cmap/connection.ts
src/cmap/connection_pool.ts
src/index.ts
src/mongo_client.ts
src/mongo_client_auth_providers.ts
src/utils.ts
test/integration/auth/mongodb_aws.test.ts
test/unit/cmap/connect.test.ts
test/unit/cmap/connection.test.ts
test/unit/cmap/connection_pool.test.js
test/unit/index.test.ts
test/unit/mongo_client.test.js

Instead of creating a new AWS provider for each authentication, we cache the AWS credentials provider per client.
Backporting [NODE-5616](https://jira.mongodb.org/browse/NODE-5616) to 5.x.
None
[NODE-5940](https://jira.mongodb.org/browse/NODE-5940)
Instead of creating a new AWS provider for each authentication, we cache the AWS credentials provider per client to prevent overwhelming the auth endpoint and ensure that cached credentials are not shared with other clients.

feat(NODE-5940): cache the AWS credentials provider in the MONGODB-AWS auth logic

---

package-lock.json
package.json

Upgrading to the latest BSON
No.
New BSON new me
BSON has had a number of performance increases in the last two releases (6.3.0 and 6.4.0). Small basic latin (ASCII) only strings, small memory allocations (ObjectId and Decimal128) and numeric parsing operations (int32, doubles, and longs) have all had optimizations applied to them. 
For details check out the release notes here: [BSON 6.3.0](https://github.com/mongodb/js-bson/releases/tag/v6.3.0) and [BSON 6.4.0](https://github.com/mongodb/js-bson/releases/tag/v6.4.0) :racehorse:

feat(NODE-5978): upgrade BSON to ^6.4.0

---

src/connection_string.ts

Just a small thing I noticed while looking at the driver code, this is a quick win to improve connection establishment performance.
When connecting using a convenient SRV connection string (`mongodb+srv://`) hostnames are obtained from an SRV dns lookup and some configuration options are obtained from a TXT dns query. Those DNS operations are now performed in parallel to reduce first-time connection latency.

perf(NODE-5986): parallelize SRV/TXT resolution

---

test/integration/auth/mongodb_aws.test.ts

Without this fix, if AWS_SESSION_TOKEN does not exist, afterEach would set it to "undefined".
Reset AWS_SESSION_TOKEN only when `awsSessionToken != null`.
None
[NODE-5992](https://jira.mongodb.org/browse/NODE-5992)

test(NODE-5992): fix env var restoration in tests

---

src/cmap/auth/mongodb_aws.ts
test/integration/auth/mongodb_aws.test.ts

Backport optional AWS session token [fix](https://github.com/mongodb/node-mongodb-native/pull/4002).
Do not throw the `MongoMissingCredentialsError('Could not obtain temporary MONGODB-AWS credentials')` exception when the AWS token is missing.
None
[NODE-5945](https://jira.mongodb.org/browse/NODE-5945)
Users may provide an `AWS_SESSION_TOKEN` as a client option or AWS configuration in addition to a username and password. But if the token is not provided, the driver won't throw an exception and let AWS SDK handle the request.

fix(NODE-5945): make AWS session token optional

---

src/mongo_logger.ts
test/unit/connection_string.test.ts
test/unit/mongo_client.test.js
test/unit/mongo_logger.test.ts

Added newline to create stdio logger.
Updated stdio logging tests to expect newline.
No.
To ensure all stdio logs are not just on one line.

chore(NODE-5903): add newline to stdio logging

---

src/cmap/connect.ts

When enabled, `rejectUnauthorized` configures Node's TLS API to reject / error when its unable to verify the certificates of the server.  This is enabled by default.  When the option is enabled and Node is unabled to verify the certificates of the server, an error event is emitted.  In our connect logic, this means the `connect` promise rejects.
Prior to https://github.com/mongodb/node-mongodb-native/pull/3973, the code removed in this PR was in the connect handler (called on successful TLS connection).  This was dead code because we will never receive an error that is triggered by `rejectUnauthorized` and successfully connect.  When https://github.com/mongodb/node-mongodb-native/pull/3973 refactored `connect()` to be async, we moved this logic into the `catch` block instead of the `try` …

fix(NODE-5985): throw Nodejs' certificate expired error when TLS fails to connect instead of `CERT_HAS_EXPIRED`

---

test/integration/transactions-convenient-api/transactions-convenient-api.spec.test.ts
test/tools/unified-spec-runner/entities.ts
test/tools/unified-spec-runner/operations.ts
test/tools/unified-spec-runner/runner.ts

Gossip the cluster time in the unified test runner.
- Pings the server on the util client to get the current cluster time.
- Sets the cluster time on all sessions that get created in the entities map.
None
NODE-5962/DRIVERS-2816

test(NODE-5962): gossip cluster time in utr

---

package-lock.json
package.json

Upgrades our version of saslprep to 1.1.5 (latest).
No.

chore(NODE-5997): update saslprep to 1.1.5

---

src/cmap/connection.ts
src/cmap/wire_protocol/on_data.ts
src/utils.ts
test/integration/connection-monitoring-and-pooling/connection.test.ts
test/integration/node-specific/resource_clean_up.test.ts

- Remove promise wrapping of signal
- Make writing async based on whether or not write returns true
- Remove signal
The Connection class stored a promise that would reject when the signal was aborted. This caused a leak that would create new promises unbounded. I've removed the promise wrapping opting for a simpler implementation that only makes writing async if there was buffering. If there was buffering we wait for the drain event and use try/finally to make sure we clean up event listeners.
The Connection class has recently been refactored to operate on our socket operations using promises. An oversight how we made async network operations interruptible made new promises for every operation. We've simplified the approach and corrected the leak.
- Example: `feat(NODE-1234)!: rewriting …

fix(NODE-5993): memory leak in the `Connection` class

---

src/error.ts
src/sdam/server.ts
src/sdam/topology_description.ts
test/integration/collection-management/collection_management.spec.test.js
test/integration/crud/crud.spec.test.js
test/spec/collection-management/modifyCollection-errorResponse.json
test/spec/collection-management/modifyCollection-errorResponse.yml
test/spec/crud/unified/aggregate-merge-errorResponse.json
test/spec/crud/unified/aggregate-merge-errorResponse.yml
test/spec/crud/unified/bulkWrite-errorResponse.json
test/spec/crud/unified/bulkWrite-errorResponse.yml
test/spec/crud/unified/deleteOne-errorResponse.json
test/spec/crud/unified/deleteOne-errorResponse.yml
test/spec/crud/unified/findOneAndUpdate-errorResponse.json
test/spec/crud/unified/findOneAndUpdate-errorResponse.yml
test/spec/crud/unified/insertOne-errorResponse.json
test/spec/crud/unified/insertOne-errorResponse.yml
test/spec/crud/unified/updateOne-errorResponse.json
test/spec/crud/unified/updateOne-errorResponse.yml
test/spec/unified-test-format/invalid/expectedError-errorResponse-type.json
test/spec/unified-test-format/invalid/expectedError-errorResponse-type.yml
test/spec/unified-test-format/valid-pass/expectedError-errorResponse.json
test/spec/unified-test-format/valid-pass/expectedError-errorResponse.yml
test/tools/unified-spec-runner/match.ts
test/tools/unified-spec-runner/schema.ts
test/unit/error.test.ts

Provide access to raw results doc in MongoServerError.
See release highlight.
Yes, API docs. 
Provide support for all values returned by server error.
The `MongoServerError.errorResponse` property now contains the raw error document returned by the server.

feat(NODE-5988): Provide access to raw results doc after MongoServerError

---

test/integration/load-balancers/load_balancers.spec.test.js

Unskips one load balancer test that was part of the two described in DRIVERS-2812. The other was already running and passing.
- Unskips the last of the two load balancer tests described in the drivers ticket.
None
DRIVERS-2812

test(DRIVERS-2812): sdam load balancer tests in serverless

---

test/integration/transactions/transactions.spec.test.js

Skip transaction unpin `TransientTransactionError` tests on the 5.x branch, so that the build failures do not clutter the CI.
Skip relevant tests on 5.x
No.
Build failure described in NODE-5852
For 5.x, we are skipping all versions (not just latest like on 6.x) to clear CI.

test(NODE-5862): skip transaction unpin TransientTransactionErrors spec tests

---

src/cmap/connect.ts
src/cmap/connection.ts
src/cmap/handshake/client_metadata.ts
src/connection_string.ts
src/mongo_client.ts
src/sdam/topology.ts
test/integration/connection-monitoring-and-pooling/connection.test.ts
test/tools/cmap_spec_runner.ts
test/unit/cmap/connect.test.ts
test/unit/cmap/connection_pool.test.js

**Note:** This PR's description and changes are  almost identical to the one on the 6.x branch (NODE-5968).
Track user usage of containers on 5.x branch.
When kubernetes is in `process.env`, we add a  `{orchestrator: 'kubernetes'}` field to the `client.env` field of the handshake document (if this does not make the document exceed 512 bytes).
When '/.dockerenv' exists, we add a  `{runtime: 'docker'}` field to the `client.env` field of the handshake document (if this does not make the document exceed 512 bytes).
Note: We do not unit test docker, but I tested our logic for detecting docker on an EVG Host, ran Docker and detection succeeds for both root and non-root user cases.
No, non-user facing change. 
Product wants to track user usage of docker and kubernetes.
The Node.js driver now …

feat(NODE-5967): container and Kubernetes awareness in client metadata

---

test/integration/client-side-encryption/client_side_encryption.prose.06.corpus.test.ts
test/integration/client-side-encryption/client_side_encryption.prose.test.js

Converts the FLE corpus #6 tests to typescript, refactors to use async-await and a few other fixes.  Notably, this PR adds a write concern to all createCollection & insertMany operations in the tests, which _seems_ to have resolved the flakiness of the tests.

test(NODE-5969): convert CSFLE corpus test #6 to TS, async/await and add write concerns to all CRUD operations

---

src/cmap/connection.ts
src/cmap/connection_pool.ts
src/cmap/stream_description.ts
src/sdam/server.ts

refactor(no-story): don't store directConnection on the connection pool and stream description

---

test/integration/crud/crud.spec.test.js
test/tools/unified-spec-runner/operations.ts

Add `modifyCollection` helper to UTR.
UTR can now support operation `modifyCollection`.
No.
To unskip crud spec test. 

test(NODE-6011): Add modifyCollection helper to UTR

---

package-lock.json
package.json

- Bumps BSON to ^6.5.0
No.
- Keeping BSON upgraded for fixes and feats

feat(NODE-6020): upgrade BSON to ^6.5.0

---

src/sessions.ts

Add API docs to `withTransaction` function to aid users with error handling in the case that the command passed into the transaction fails, and the transaction goes into an infinite loop.
Descriptive API doc with error handling steps is added to `withTransaction`
Yes, I've added "Docs Changes Needed" to the ticket description, asking the docs team to update this [page](https://www.mongodb.com/docs/drivers/node/current/fundamentals/transactions/#convenient-transaction-api).
Help users with error handling after this infinite loop case was discovered.
The `withTransaction` function API docs now contain more information on how to avoid an application entering an infinite loop in the event that a failed command aborts the transaction and causes the transaction to be retried.
- Example: …

docs(NODE-5721): thrown error expectations in withTransaction

---

.evergreen/ci_matrix_constants.js
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
src/sessions.ts
test/integration/transactions/transactions.spec.test.ts

- Unskip TXN tests now that we've updated the unified spec tests
- Unskip TXN tests on LB
- Move session clearing of connection after checkIn
Also resolves: NODE-5931
- Testing TXN

test(NODE-5855): unskip transaction tests

---

.eslintrc.json
package-lock.json
package.json
test/atlas/drivers_atlas_testing.test.ts
test/integration/client-side-encryption/client_side_encryption.prose.22.range_explicit_encryption.test.ts
test/integration/crud/abstract_operation.test.ts
test/integration/node-specific/bson-options/use_bigint_64.test.ts
test/unit/cmap/connect.test.ts
test/unit/commands.test.ts
test/unit/mongo_logger.test.ts
test/unit/sdam/server_selection.test.ts

- Added an eslint rule for checking mocha describe blocks for async functions
- Run fix to remove current accidental usages
- Use metadata to skip range tests
No.
- Async functions in context/describe blocks are incorrect usage of the test framework. We suspect this lead to a problem with mocha exiting silently on latest sharded clusters, that is no longer happening after this change.

chore(NODE-6037): use metadata for skip logic and remove async from context block

---

src/operations/indexes.ts
test/integration/index_management.test.ts

`createIndex` and `createIndexes` now support specifying an index version with the `version` option.
One note is that `createIndexes()` requires that users specify the `version` as a part of their index specification - a `version` provided as a part of the options is ignored.  This behavior is consistent with other index options provided to `createIndexes`.
(release highlight left empty since `v` is an undocumented feature, no need for it to appear in our release notes)

fix(NODE-5971): attach `v` to createIndexes command when `version` is specified

---

src/mongo_types.ts
test/integration/crud/find_and_modify.test.ts
test/types/community/collection/updateX.test-d.ts
test/types/helper_types.test-d.ts

When a field with boolean value `true`, is passed into `$currentDate`, it will no longer throw an TS error.
Example:
```
$currentData: {
lastModified: true
} // no longer throws a TS error
```
No. 
The motivation is that the Node Driver should not output unnecessary errors to users. 
Example:
```typescript
const collection = new Collection(); // collection with no schema
collection.update(
$currentData: {
lastModified: true
} // no longer throws a TS error
);
```

fix(NODE-3681): Typescript error in Collection.findOneAndModify UpdateFilter $currentDate

---

src/cmap/auth/aws_temporary_credentials.ts
src/cmap/auth/mongodb_aws.ts
src/error.ts
test/integration/auth/mongodb_aws.test.ts
test/mongodb.ts

In order to share AWS credential fetching logic with CSFLE, ([NODE-5917](https://jira.mongodb.org/browse/NODE-5917)), the AWS temporary credential fetching logic has been extracted from the `MongoDBAWS` auth provider into a new `AWSTemporaryCredentialProvider` abstraction.  This is purely a refactor, and all existing tests are passing.

refactor(NODE-6040): extract aws temporary credential acquisition logic into a standalone module

---

src/change_stream.ts

- Update change stream links
No.
- Make change stream documentation links more specific to change event types

docs(NODE-4295): ensure all change stream events have links to their documentation

---

test/integration/client-side-encryption/client_side_encryption.prose.test.js
test/integration/client-side-encryption/client_side_encryption.spec.test.ts
test/integration/command-logging-and-monitoring/command_logging_and_monitoring.spec.test.ts
test/integration/command-logging-and-monitoring/command_monitoring.test.ts
test/integration/crud/aggregation.test.ts
test/integration/crud/explain.test.ts
test/integration/load-balancers/load_balancers.spec.test.ts
test/integration/node-specific/client_encryption.test.ts
test/integration/node-specific/crypto_callbacks.test.ts
test/integration/unified-test-format/unified_test_format.spec.test.ts
test/tools/unified-spec-runner/runner.ts
test/types/client-side-encryption.test-d.ts
test/unit/connection_string.test.ts

While auditing the existing skipped tests, I found a couple of quick fixes.  This PR unskips some tests that not longer fail, removes some unnecessary skip reason assignment, and removes some unnecessary TODO comments.

test(NODE-5898): small fixes and unskips of test TODOs

---

test/integration/crud/bulk.test.ts

chore: skip bulkWrite with w:0 test failing on `latest`

---

src/client-side-encryption/providers/aws.ts
test/integration/auth/mongodb_aws.test.ts
test/integration/crud/bulk.test.ts
test/unit/assorted/polling_srv_records_for_mongos_discovery.prose.test.ts
test/unit/client-side-encryption/providers/credentialsProvider.test.ts
test/unit/connection_string.spec.test.ts
test/unit/sdam/monitor.test.ts
test/unit/sdam/topology.test.ts

- AWS KMS credentials are now fetched using the same logic as AWS authentication (the AWSSDKTemporaryCredentialProvider). 
- Only expected keys (`sessionToken`,`accessKeyId`, `secretAccessKey`) are returned to libmongocrypt after fetching kms credentials
I also fixed some unit test skipping logic on Node18+, which previously only skipped on Node 18 and 20.  Now it skips on Node18+.
This PR includes changes from https://github.com/mongodb/node-mongodb-native/pull/4064 to get a greener CI.
Nope.
In addition to letting users provide KMS credentials manually, client-side encryption supports fetching AWS KMS credentials on-demand using the AWS SDK.  However, AWS credential mechanisms that returned access keys with expiration timestamps caused the driver to throw an error.
The driver will no …

fix(NODE-6051): only provide expected allowed keys to libmongocrypt after fetching aws kms credentials

---

src/sdam/common.ts
test/types/sessions.test-d.ts

- Correct typescript for signature property on ClusterTime interface
No.. well yes, these are docs changes!
The `ClusterTime` interface incorrectly reported the `signature` field as required, [the server may omit it](https://github.com/10gen/mongo/blob/a6ede4e300909230b3ec9cc47ea71a9abedde65b/src/mongo/db/vector_clock.idl#L47-L58), so the typescript has been updated to reflect reality. 

fix(NODE-6066): signature can be optional at runtime

---

src/cmap/auth/gssapi.ts
src/cmap/connection.ts
src/cmap/wire_protocol/compression.ts
src/deps.ts
src/encrypter.ts
src/error.ts

`MongoMissingDependencyError` now includes two required properties: 
- `dependencyName` - the name of the missing dependency
- `cause` - the error thrown when attempting to `require` the missing dependency.
`MongoMissingDependencyError`s now include a `cause` and a `dependencyName` field, which can be used to programmatically determine which package is missing and why the driver failed to load it.

feat(NODE-5762): include `cause` and package name for all `MongoMissingDependencyError`s

---

src/bson.ts
src/cmap/auth/gssapi.ts
src/cmap/commands.ts
src/cmap/connect.ts
src/cmap/connection.ts
src/cmap/wire_protocol/compression.ts
src/cmap/wire_protocol/on_demand/document.ts
src/cmap/wire_protocol/responses.ts
src/index.ts
src/sessions.ts
test/integration/connection-monitoring-and-pooling/connection.test.ts
test/integration/node-specific/bson-options/raw.test.ts
test/integration/node-specific/bson-options/utf8_validation.test.ts
test/mongodb.ts
test/types/connection.test-d.ts
test/unit/cmap/commands.test.js
test/unit/cmap/wire_protocol/on_demand/document.test.ts
test/unit/cmap/wire_protocol/responses.test.ts
test/unit/commands.test.ts

- Fixes and closes: [NODE-3946](https://jira.mongodb.org/browse/NODE-3946)
- Moves BSON parsing to OnDemandDocument
- Adds a subclass that provides getters for common command response properties
No
- In service of future improvements and optimizations
- Typesafe responses

refactor(NODE-6056): implement MongoDBResponse class

---

src/sdam/topology_description.ts
test/integration/node-specific/errors.test.ts
test/integration/server-discovery-and-monitoring/topology_description.test.ts

This is basically entirely invisible to users.  However, the TopologyDescription is a field on `MongoServerSelectionError`s, so if a user is calling JSON.stringify on their errors, they will now see the `servers` field in the output instead of an empty object.
No.
The `TopologyDescription` class is exposed by the driver in server selection errors and topology monitoring events to provide insight into the driver's current representation of the server's topology and to aid in debugging.  However, the TopologyDescription uses `Map`s internally, which get serialized to `{}` when JSON stringified.  We recommend using Node's `util.inspect()` helper to print topology descriptions because `inspect` properly handles all JS types and all types we use in the driver.  However, if JSON must be used, …

fix(NODE-5530): make topology descriptions JSON stringifiable 

---

src/collection.ts
src/db.ts
src/index.ts
src/operations/indexes.ts
test/types/indexes_test-d.ts

Update the return type of `Collection.prototype.indexes` and `Collection.prototype.indexInformation` to an array of indexes with full properties when the `full` option is true and to a Record of \<index name\> - \<keys and direction\> when the full option is false.
No.
The old types were incorrect in regards to the `full` option and were very wide. This will avoid making some type mistakes when using these methods.
`Collection.indexInformation()`, `Collection.indexes()` and `Db.indexInformation()` are helpers that return index information for a given collection or database.  These helpers take an option, `full`, that configures whether the return value contains full index descriptions or a compact summary:
```typescript
collection.indexes({ full: true });   // returns an array of index …
```

fix(NODE-6029): update types for collection listing indexes

---

test/spec/connection-monitoring-and-pooling/cmap-format/pool-checkout-maxConnecting-is-enforced.json
test/spec/connection-monitoring-and-pooling/cmap-format/pool-checkout-maxConnecting-is-enforced.yml

test(NODE-6077): fix flaky maxConnecting is enforced CMAP test

---

src/operations/execute_operation.ts
src/sessions.ts
src/utils.ts
test/integration/transactions/transactions.spec.test.ts
test/tools/unified-spec-runner/entities.ts

Within a transaction, readPreferences != 'primary' are not supported, and our error logic must support that to comply with spec. An error should only be thrown in these circumstances when a read operation is being executed. 
In a transaction, when a user provides a readPreference != 'primary' and then tries to perform a command that involves a read, the Node Driver will now throw a 
Yes, update [Transactions Node.js Manual](https://www.mongodb.com/docs/drivers/node/current/fundamentals/transactions/) to reflect desired readPreference inputs.
See Release Highlights
The following error will now only be thrown  when a user provides a `ReadPreferenceMode` other than `primary` and then tries to perform a command that involves a read:
```javascript
new MongoTransactionError('Read preference in …
```

fix(NODE-5925): driver throws error when non-read operation in a transaction has a ReadPreferenceMode other than 'primary'

---

test/integration/connections-survive-step-down/connections_survive_step_down.prose.test.ts

- Update connections survive stepdown tests to check CMAP events
No.
These tests started failing in https://github.com/mongodb/node-mongodb-native/pull/4062 debugging them proved difficult and they need to be updated anyway. 

test(NODE-3903): update connections survive stepdown tests to check CMAP events

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/setup-gcp-instance.sh
.evergreen/setup-gcp-testing.sh

Fixes the GCP KMS test suite.
Updates the evergreen config to use the new setup and teardown scripts and pull env variables from the secrets manager.
None
NODE-6096

test(NODE-6096): fix gcp kms tests

---

src/cursor/aggregation_cursor.ts
test/integration/crud/aggregation.test.ts

add a general stage method to the aggregation pipeline builder
This feature would allow arbitrary aggregation stages to be used builder style with the aggregation cursor, simplifying the syntax needed to use the stages otherwise. Currently only the most common stages have explicit APIs available for chaining and adding an explicit API for every possible aggregation stage would not be maintainable.
This change will also help making progress in other aggregation pipeline typification features, as the aggregation pipeline builder can be used for both stages which have explicit builder helpers and those which do not.
When creating an aggregation pipeline cursor, a new generic method `addStage()` has been added in the fluid API for users to add stages in a general manner.
```ts
const documents …
```

feat(NODE-3639): add a general stage to the aggregation pipeline builder

---

src/operations/search_indexes/create.ts
test/manual/search-index-management.prose.test.ts
test/spec/index-management/createSearchIndex.json
test/spec/index-management/createSearchIndex.yml
test/spec/index-management/createSearchIndexes.json
test/spec/index-management/createSearchIndexes.yml

Add support for the `type` field in `SearchIndexDescription`.  Also syncs the unified search index tests and adds two new search index prose tests, as added in https://jira.mongodb.org/browse/DRIVERS-2768.
It is now possible to specify the type of a search index when creating a search index:
```typescript
const indexName = await collection.createSearchIndex({
name: 'my-vector-search-index',
// new! specifies that a `vectorSearch` index is created
type: 'vectorSearch',
definition: {
mappings: { dynamic: false }
}
});
```

feat(NODE-5919): support new `type` option in create search index helpers

---

src/timeout.ts

- Make TimeoutError construction lazy
No

perf(NODE-6127): move error construction into setTimeout callback

---

test/unit/connection_string.spec.test.ts

Unskip following tests [invalid port (zero) with hostname](https://github.com/mongodb/specifications/blob/b88f80027812f6833252ab5990a099d4d8d6b5f9/source/connection-string/tests/invalid-uris.yml) and [invalid port (zero) with IP literal.](https://github.com/mongodb/specifications/blob/b88f80027812f6833252ab5990a099d4d8d6b5f9/source/connection-string/tests/invalid-uris.yml) on Node 20+
Unskipping 2 uri tests that failed on Node 18.17 and some Node 20 back in September 2023, the issue has gone away now.
No.
Issue has gone away.

test(NODE-5610): unskip uri invalid port (zero) with hostname/IP literal tests on Node 20+

---

src/client-side-encryption/auto_encrypter.ts
src/client-side-encryption/state_machine.ts
src/cmap/connection.ts
src/cmap/wire_protocol/on_demand/document.ts
src/cmap/wire_protocol/responses.ts
src/cursor/abstract_cursor.ts
src/cursor/find_cursor.ts
src/cursor/run_command_cursor.ts
src/index.ts
src/operations/execute_operation.ts
src/operations/find.ts
src/operations/get_more.ts
src/sdam/server.ts
src/utils.ts
test/integration/client-side-encryption/driver.test.ts
test/integration/crud/abstract_operation.test.ts
test/unit/assorted/collations.test.js
test/unit/assorted/sessions_collection.test.js
test/unit/cmap/wire_protocol/on_demand/document.test.ts
test/unit/cmap/wire_protocol/responses.test.ts
test/unit/operations/find.test.ts
test/unit/utils.test.ts

- Implement a `CursorResponse` subclass of MongoDBResponse
- Implements logic to abstract List vs CursorResponse handling
- Make FindCursors use CursorResponse
TBD. Is this something we want to apply to all cursors? Should we progressively migrate to this?
An attempt at increasing performance. A sucessful decoupling of driver BSON and user BSON settings.
Only for FindCursor, BSON documents from the current batch are now parsed on each iteration. 
One clear improvement is that any cursor that is closed before exhaustion will take significantly less run time.

refactor(NODE-6057): implement CursorResponse for lazy document parsing

---

src/cursor/find_cursor.ts
src/operations/find.ts

Undo CursorResponse temporarily to improve performance.

refactor(NODE-6146): put cursor response back under a flag

---

src/timeout.ts
test/unit/timeout.test.ts

When the `MongoClient` is first starting up (`client.connect()`) monitoring connections begin the process of discovering servers to make them selectable. The [`ref()`-ed](https://nodejs.org/docs/latest/api/timers.html#timeoutref) `serverSelectionTimeoutMS` timer keeps Node.js' event loop running as the monitoring connections are created. In the last release we inadvertently [`unref()`-ed](https://nodejs.org/docs/latest/api/timers.html#timeoutunref) this initial timer which would allow Node.js to close before the monitors could create connections. 

fix(NODE-6151): MongoClient connect does not keep Node.js running

---

.evergreen/ci_matrix_constants.js
.evergreen/config.yml

- add server 8.0 to evergreen
Yes, compat table
8.0 coverage

ci(NODE-6162): add server 8.0 to evergreen

---

src/sdam/monitor.ts
test/integration/server-discovery-and-monitoring/server_discover_and_monitoring.test.ts

No
NODE-6171
Starting in version [6.6.0](https://github.com/mongodb/node-mongodb-native/commit/0e3d6ead735ed067bd044c8d0c9c307d970f1986#), when using the `stream` server monitoring mode, heartbeats were incorrectly timed as having a duration of 0, leading to server selection viewing each server as equally desirable for selection.

fix(NODE-6171): RTT set to zero when serverMonitoringMode=stream

---

src/sessions.ts

Add inline documentation detailing that Promise.all and other concurrency mechanisms should not be used to parallelize transaction operations
No
NODE-6192

docs(NODE-6192): clarify that operations should not be parallelized in transactions

---

src/sessions.ts

Add inline documentation detailing that Promise.all and other concurrency mechanisms should not be used to parallelize transaction operations
No
NODE-6191

docs(NODE-6191): clarify that operations should not be parallelized in transactions

---

src/client-side-encryption/client_encryption.ts
src/index.ts

The original KMIP implementation added runtime support for KMIP data key options, but did not add TS support.  This PR adds support for the keyId and endpoint options, with delegated to be added in [NODE-5853](https://jira.mongodb.org/browse/NODE-5853).
Demonstration of the options working as expected: https://github.com/mongodb/node-mongodb-native/blob/db00ac46847563f7d32beb1dd4ecbf18531fd15e/test/integration/client-side-encryption/client_side_encryption.prose.test.js#L1011
No.
Typescript accuracy.

fix(NODE-6085): add TS support for KMIP data key options

---

global.d.ts
package-lock.json
package.json
test/tools/runner/filters/client_encryption_filter.ts

going forward, we'll have FLE tests that make use of newer libmongocrypt features. We haven't had this issue in the past, because we've always tested with latest mongodb-client-encryption, but now that we ensure compatibility between mongodb-client-encryption@6.0.0 and latest driver, we'll need to start skipping tests on versions of our bindings that don't support the features under test.

chore: use new mongodb-client-encryption and update filter to support versions

---

src/cursor/abstract_cursor.ts
src/cursor/aggregation_cursor.ts
src/cursor/find_cursor.ts
src/sessions.ts
test/integration/change-streams/change_stream.test.ts
test/integration/change-streams/change_streams.prose.test.ts
test/integration/crud/misc_cursors.test.js
test/integration/node-specific/abstract_cursor.test.ts
test/integration/node-specific/cursor_async_iterator.test.js
test/tools/unified-spec-runner/operations.ts

- Move `next` into cursor and rename to fetchBatch
- Remove transform and blocking flags
- tryNext/next now call fetchBatch as appropriate to get the same behavior the flags provided
- move cleanupCursor logic to cleanup()
No
The `next` floating function owned too many details of the implementation of each cursor API, tryNext and next now do a small amount more lifting and we have a fetchBatch method that is focused on obtaining the next batch either with the init command or with a getMore.

refactor(NODE-6201): cursor to use fetchBatch when current batch is empty

---

src/cursor/abstract_cursor.ts
src/cursor/aggregation_cursor.ts
src/cursor/change_stream_cursor.ts
src/cursor/find_cursor.ts
src/sessions.ts
test/integration/change-streams/change_stream.test.ts
test/integration/crud/maxTimeMS.test.ts

- `AbstractCursor`
- Removed all symbol properties in favor of equivalently named strings.
- Changed "options" to cursorOptions, no need for the getter indirection
- Added `is` in front of booleans that have getters
- `FindCursor`
- kFilter -> cursorFilter since there is a "filter" method
- builtOptions -> findOptions, I think the naming came from TS translation days, it is true that the options are built from all the helpers (if one uses those) but in the end they are options for find
- `AggregationCursor`
- pipline is a public readonly property which is equivalent to the getter that fetched the symbol property before
- `ChangeStreamCursor`
- No symbol properties here, but the "options" property shared the same name as AbstractCursor's "options" until I changed it to "cursorOptions". 
- …

refactor: replace symbol properties in cursor classes

---

etc/notes/releasing.md

- Add documentation for our release process
No
Moving release documentation to a more discoverable location

docs(NODE-6193): add releasing documentation

---

etc/docs/build.ts
etc/docs/template/data/releases.toml
etc/docs/template/layouts/partials/releases.html
etc/docs/template/static/s/css/frontpage.css
etc/docs/utils.ts

- Fixed: The drop down arrow was not displaying correctly next to "Legacy Versions"
- Fixed: The Legacy versions section didn't accurately list which versions were out of support
- Added a notice about legacy driver versions.
No
Nicer docs landing page

docs: update legacy drivers section and fix drop down

---

.github/workflows/codeql.yml
.github/workflows/release-5.x.yml
.github/workflows/release.yml

Sarif reports are generated and upload to s3 upon release.
Our sbom.json file is also uploaded with releases.
Example upload to s3 from main: 

chore(NODE-6212): generate sarif reports in releases and upload sbom lite to s3 [skip-ci]

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/run-atlas-tests.sh
test/manual/atlas_connectivity.test.ts

Atlas connectivity test URIs are now obtained from aws secrets manager.

ci(NODE-6203): fix atlas connectivity tests

---

test/integration/client-side-encryption/client_side_encryption.spec.test.ts
test/spec/client-side-encryption/tests/legacy/timeoutMS.json
test/spec/client-side-encryption/tests/legacy/timeoutMS.yml

chore(NODE-5974): sync CSOT tests

---

.github/actions/compress_sign_and_upload/action.yml
.github/workflows/release-5.x.yml
.github/workflows/release.yml

Authorized publisher reports and compliance reports are generated during the main and 5.x releases.
Example successful CI run: https://github.com/mongodb/node-mongodb-native/actions/workflows/release.yml
Here's an example authorized publisher report:
```
Product: node-mongodb-native
Version: 
Releaser: Bailey Pearson
Build Source: GitHub Actions
Build Number: 9600830984
Filename: mongodb-6.7.0.tgz
Shasum: 41d7f96711c3b309201b850162e484c08f[79](https://github.com/mongodb/node-mongodb-native/actions/runs/9600830984/job/26478024665#step:7:81)cb008b96ebdfc177ecae0f43edb0
Filename: mongodb-6.7.0.tgz.sig
Shasum: fea5d7a0ae385b7186faac73f49732a89d14d3[80](https://github.com/mongodb/node-mongodb-native/actions/runs/9600830984/job/26478024665#step:7:82)b5e83d507fb74675ca7b7023
```
Here's an …

chore(NODE-6118): generate authorized publisher report and compliance report

---

src/client-side-encryption/providers/index.ts
test/types/client-side-encryption.test-d.ts

This aligns the types with actual behavior as well as the shell's expected set of supported types.
Accurate TS
A `local` KMS provider at runtime accepted a `BSON` `Binary` instance but the Typescript inaccurately only permitted `Buffer` and `string`. 

fix(NODE-6241): allow `Binary` as local KMS provider key

---

src/cursor/abstract_cursor.ts
test/integration/change-streams/change_stream.test.ts
test/integration/node-specific/abstract_cursor.test.ts
test/integration/node-specific/cursor_async_iterator.test.js

Fix a change in behavior to close introduced in a recent cursor refactor. The expectation was that close became true when no more documents remain locally.
Yes, API docs updated.
The closed flag is used to determine if there are docs remaing in mongosh
The cursor has a few properties that represent the current state from the perspective of the driver and server. This PR corrects an issue that never made it to a release but we would like to take the opportunity to re-highlight what each of these properties mean.
- `cursor.closed` - `cursor.close()` has been called, and there are no more documents stored in the cursor.
- `cursor.killed` - `cursor.close()` was called while the cursor still had a non-zero id, and the driver sent a killCursors command to free server-side resources
- `cursor.id …

fix(NODE-6242): close becomes true after calling close when documents still remain

---

README.md

Updates the release integrity section with links to the GPG key and npm note.
README.md
None
NODE-6234

docs(NODE-6234): update release integrity section

---

src/client-side-encryption/mongocryptd_manager.ts
test/unit/client-side-encryption/mongocryptd_manager.test.ts
tsconfig.json

To prevent prototype pollution gadget, added a check to ensure that 'mongocryptSpawnPath' and 'mongocryptSpawnArgs' properties exist in 'extraOptions' object before assigning them to 'this.spawnPath' and 'this.spawnArgs', which are passed to 'spawn' function in line 53. 
HackerOne report: https://hackerone.com/bugs?subject=user&report_id=2522466
We have added some defensive programming to the options that specify spawn path and spawn arguments for `mongocryptd` due to the sensitivity of the system resource they control, namely, launching a process. Now, `mongocryptdSpawnPath` and `mongocryptdSpawnArgs` **must** be [own properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn) of `autoEncryption.extraOptions`. This makes it more difficult …

feat(NODE-6225): add property ownership check before referencing `mongocryptdSpawnPath` and `mongocryptdSpawnArgs`

---

.mocharc.json
test/mocha_mongodb.json
test/tools/runner/chai_addons.ts
test/tools/runner/hooks/configuration.ts
test/tools/runner/hooks/leak_checker.ts
test/tools/runner/hooks/unhandled_checker.ts

- commonjs exports can be replaced with ES syntax.
- No
Proper TS conversion

chore: convert mocha hooks cjs exports to esm exports

---

test/benchmarks/mongoBench/suites/multiBench.js

Add perf benchmark for `AbstractCursor.toArray`
New perf benchmark.
None.
To test perf optimizations in NODE-5906 (Optimize toArray).

test: add toArray perf benchmark

---

src/bulk/common.ts

The length property was declared on the `BulkOperationBase` interface in the `@types/mongodb` package. With version 4.0, installing `@types/mongodb` is no longer required. However, the declarations generated in the `mongodb` package don't have the `length` property.
The `BulkOperationBase` type now has a `length` property. This was the behaviour when using `@types/mongodb`.
No
See [this discussion](https://www.mongodb.com/community/forums/t/how-to-check-if-bulkop-is-empty-or-not/287055/4) in the Community Forums.
The `length` getter for these classes was defined manually using `Object.defineProperty` which hid it from typescript. Thanks to @sis0k0 we now have the getter defined on the class, which is functionally the same, but a greatly improved DX when working with types. 🎉  
- Example: …

fix(NODE-6259): replace dynamically assigned length property with a static getter

---

README.md

This PR adds a readme change primarily so that we have a PR for which to add release highlights.  We must communicate to users at least a minor version ahead of dropping support for a server version.
Support for 3.6 servers is deprecated and will be removed in a future version.

feat(NODE-6278): deprecate 3.6 servers

---

test/integration/unified-test-format/unified_test_format.spec.test.ts
test/spec/unified-test-format/valid-fail/entity-findCursor-malformed.json
test/spec/unified-test-format/valid-fail/entity-findCursor-malformed.yml
test/spec/unified-test-format/valid-fail/entity-findCursor.json
test/spec/unified-test-format/valid-fail/entity-findCursor.yml
test/spec/unified-test-format/valid-fail/ignoreResultAndError-malformed.json
test/spec/unified-test-format/valid-fail/ignoreResultAndError-malformed.yml
test/spec/unified-test-format/valid-fail/ignoreResultAndError.yml
test/spec/unified-test-format/valid-fail/operation-unsupported.json
test/spec/unified-test-format/valid-fail/operation-unsupported.yml
test/tools/unified-spec-runner/entities.ts
test/tools/unified-spec-runner/entity_event_registry.ts
test/tools/unified-spec-runner/operations.ts
test/tools/unified-spec-runner/runner.ts
test/tools/unified-spec-runner/unified-utils.ts
test/unit/tools/unifed-utils.test.ts

Enables the unifed test format's valid-fail tests and fixes all failures.
- Syncs the valid-fail tests in the specs directory to latest.
- Adds the necessary validation in the unified runner to pass the tests
None
NODE-6098

test(NODE-6098): enable unified valid fail tests

---

src/bulk/common.ts
src/error.ts
src/index.ts
test/unit/error.test.ts
test/unit/index.test.ts
test/unit/mongo_client.test.ts

Preserve top level error code MongoWriteConcernError
Ensure that MongoWriteConcernError is correctly formed such that the original top-level code is preserved
- If no top-level code exists, MongoWriteConcernError.code should be set to the nested code
- If a top-level code is passed into the constructor, it shouldn't be changed or overwritten by the nested writeConcernError.code
No
Bug fix
`MongoWriteConcernError` is now correctly formed such that the original top-level code is preserved
- If no top-level code exists, `MongoWriteConcernError.code` should be set to `MongoWriteConcernError.result.writeConcernError.code`
- If a top-level code is passed into the constructor, it shouldn't be changed or overwritten by the nested `writeConcernError.code`
- Example: `feat(NODE-1234)!: rewriting …

fix(NODE-6276): preserve top level error code MongoWriteConcernError

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-custom-csfle-tests.sh

- Pulls bindings from our new repo
- Remove rapid and latest, replace with 6.0 and (after slack convo) 7.0
No
Maintain support for driver 6.0.0+ with latest bindings version
We no longer need to support `rangePreview` so I left out testing on 7.0

chore(NODE-6167): fix server matrix and test against new binding location

---

src/cmap/connection.ts
src/cmap/wire_protocol/responses.ts
test/integration/client-side-operations-timeout/node_csot.test.ts

- When the server returns a max time error we turn it into a client side timeout error.
Not for this PR. General CSOT documentation should cover the cases where a timeout error is encountered
When CSOT is enabled the goal is to provide a consistent mechanism for timing out operations. Ususally a client side timeout should expire before a server is able to, but depending on the variance in RTT calculation it is possible for the maxTimeMS setting that is sent to the server to be shorter than what remains on the client side. In this case, if we get a server timeout we want to throw the same error that would normally occur in CSOT circumstances.

feat(NODE-6312): add error transformation for server timeouts

---

test/integration/unified-test-format/unified_test_format.test.ts
test/tools/unified-spec-runner/operations.ts
test/tools/unified-spec-runner/schema.ts

- Propagate errors from callback to withTransaction as the specifications say to
No
It is needed to test withTransaction correctly.

test(NODE-6318): utf runner withTransaction callback propagates errors from operations

---

src/sessions.ts

- expirementing with simpilifying Txn logic
CSOT requires errors to be handled differently and the recursion and nesting of the existing implementation, which is mainly callback inspired, was difficult to adapt.

refactor(NODE-6335): remove recursion from transaction APIs

---

src/cmap/commands.ts
test/unit/cmap/commands.test.ts

Implements OP_MSG type 1 sections for document sequences.
- Adds a `DocumentSequence` object that can be added to commands internally to leverage type 1 sections.
- Updates `OpMsgRequest` to properly handle document sequences in commands.
- Adds unit tests on `OpMsgRequest#toBin` 
None
NODE-6325

refactor(NODE-6325): implement document sequence support

---

test/integration/client-side-encryption/client_side_encryption.prose.06.corpus.test.ts
test/integration/client-side-encryption/client_side_encryption.prose.12.deadlock.test.ts
test/integration/client-side-encryption/client_side_encryption.prose.14.decryption_events.test.ts
test/integration/client-side-encryption/client_side_encryption.prose.21.automatic_data_encryption_keys.test.ts
test/integration/client-side-encryption/client_side_encryption.prose.22.range_explicit_encryption.test.ts
test/integration/client-side-encryption/client_side_encryption.prose.test.js
test/integration/client-side-encryption/client_side_encryption.spec.test.ts
test/integration/client-side-encryption/driver.test.ts
test/manual/socks5.test.ts
test/tools/runner/hooks/configuration.ts

Now that [NODE-5754](https://jira.mongodb.org/browse/NODE-5754) is implemented, the driver connects to both ipv4 and ipv6 hosts without additional configuration. This makes installNodeDNSWorkaroundHooks, added when Node18 changed the default DNS resolution order, unnecessary.
This PR removes installNodeDNSWorkaroundHooks.

chore(NODE-6341): remove node18+ dns resolution order hooks

---

test/integration/client-side-encryption/client_side_encryption.prose.23.range_encryption_defaults.test.ts
test/integration/client-side-encryption/driver.test.ts

The merged commit on main wasn't included in #4202, this finishes the removal
No
CI 💥  -> CI ✅

chore(NODE-6341): followup fix remove node18+ dns resolution order hooks

---

src/operations/client_bulk_write/command_builder.ts
src/operations/client_bulk_write/common.ts
test/mongodb.ts
test/unit/operations/client_bulk_write/command_builder.test.ts

Creates the new client bulk write model types and options as well as the builders for the bulk write command.
- Creates the new client bulk write model types.
- Creates a client bulk write command builder that delegates to the various model builders to build the operations.
- Ensures the `ops` field of the bulk write command is a document sequence
- Ensures the `nsInfo` field of the bulk write command is a unique document sequence.
- Adds a bunch-o-unit-tests
None. docs changes will come on the last ticket of the epic as well as the release highlights.
NODE-6327

feat(NODE-6327): new client bulk write types and builders

---

test/integration/client-side-encryption/client_side_encryption.prose.test.js

Remove skip on node versions greater than 19
No
More coverage

test(NODE-6343): unskip Case 4: KMIP should fail with no TLS

---

.github/workflows/release-6.8.yml

- Add a workflow for releasing from 6.8
No
Automated releases from 6.8

chore: add a 6.8 release process workflow

---

test/integration/server-discovery-and-monitoring/server_discover_and_monitoring.test.ts

This test is flaky on macos.  
The assertion removed isn't related to the test description and isn't necessary for the correctness of the test.

test(NODE-6317): remove flaky unnecessary assertion

---

.evergreen/install-mongodb-client-encryption.sh
src/cmap/wire_protocol/on_demand/document.ts
src/cmap/wire_protocol/responses.ts
test/integration/node-specific/bson-options/utf8_validation.test.ts
test/unit/cmap/wire_protocol/responses.test.ts

This PR ensures that any BSON utf8 validation options are provided to the deserializer when deserializing cursors.
Since on-demand BSON, cursors are deserialized on-demand.  Documents are pulled out of the cursor using `MongoDBResponse.get()`, which returns an unparsed on-demand document.  We then deserialize it using `toObject()`.
However, although `MongoDBResponse` correctly applies BSON utf8 options to its deserialization logic, the on-demand document does not.  This results in documents retrieved from a cursor being deserialized without the utf8 validation options.

fix(NODE-6355): respect utf8 validation options when iterating cursors

---

test/integration/server-discovery-and-monitoring/server_discover_and_monitoring.test.ts

Renaming test and reworking assertion removed in #4212 
No
Testing correctness

test(NODE-6317): fix test assertions and naming

---

.eslintrc.json
src/bson.ts
src/cmap/connection.ts
src/cmap/wire_protocol/on_demand/document.ts
src/cmap/wire_protocol/responses.ts
src/cursor/abstract_cursor.ts
src/cursor/aggregation_cursor.ts
src/cursor/find_cursor.ts
src/index.ts
test/integration/change-streams/change_stream.test.ts
test/integration/node-specific/bson-options/utf8_validation.test.ts
test/integration/server-selection/server_selection.prose.operation_count.test.ts
test/unit/cmap/wire_protocol/responses.test.ts
test/unit/mongo_logger.test.ts

Cursors now respect `enableUtf8Validation`.
CI won't run on 6.8 - patch build here: https://spruce.mongodb.com/version/66db46990ef9890007c0f2cb/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Performance comparison with the 6.8 commit: https://performance-analyzer.server-tig.prod.corp.mongodb.com/perf-analyzer-viz/?comparison_id=66db3c2adbc39a02ac0aef75
Starting in v6.8.0 we inadvertently removed the ability to disable UTF-8 validation when deserializing BSON. Validation is normally a good thing, but it was always meant to be configurable and the recent Node.js runtime issues (v22.7.0) make this option indispensable for avoiding errors from mistakenly generated invalid UTF-8 bytes.

fix(NODE-6355): respect utf8 validation options when iterating cursors (6.8)

---

.github/workflows/build_docs.yml
.github/workflows/release-5.x.yml
.github/workflows/release-6.8.yml
.github/workflows/release.yml

- Added quotes to all the branch names I could find.
- Only necessary when branch name is numeric but if we put it everywhere when we copy pasta we will be less likely to omit it
No
Correctness

chore: quote branch names to avoid numeric conversion

---

package-lock.json
package.json
src/cmap/connection.ts
src/cmap/wire_protocol/on_data.ts
src/collection.ts
src/db.ts
src/error.ts
src/operations/execute_operation.ts
src/sessions.ts
src/timeout.ts
src/transactions.ts
src/utils.ts
test/integration/client-side-operations-timeout/client_side_operations_timeout.prose.test.ts
test/integration/client-side-operations-timeout/client_side_operations_timeout.spec.test.ts
test/integration/client-side-operations-timeout/node_csot.test.ts
test/spec/client-side-operations-timeout/sessions-inherit-timeoutMS.json
test/spec/client-side-operations-timeout/sessions-inherit-timeoutMS.yml
test/spec/client-side-operations-timeout/sessions-override-operation-timeoutMS.json
test/spec/client-side-operations-timeout/sessions-override-operation-timeoutMS.yml
test/spec/client-side-operations-timeout/sessions-override-timeoutMS.json
test/spec/client-side-operations-timeout/sessions-override-timeoutMS.yml
test/tools/unified-spec-runner/entities.ts
test/tools/unified-spec-runner/match.ts
test/tools/unified-spec-runner/operations.ts

- CSOT support for session APIs
- abort/commit Transaction
- endSession
- withTransaction
- Despite the diff I only: 
- indented the logic into a try/finally block
- the timeoutContext is always cleared when withTxn is done
- the old timeout mechanism is short-circuited away if we have a timeoutContext defined
- API docs updated.
- Some external fixes to timeout handling:
- Do not synchronously throw from getters that return promises (timeouts) so .then chaining works as expected
- Move TimeoutError conversion out of onData into readMany so that the stack trace is preserved
- update mongodb-legacy version to pull in options passing fix
- Moved duration into timeout error for debugging, it should always be equal to timeoutMS but it is useful when it is not. If we don't like this, we can …

feat(NODE-6313): add CSOT support to sessions and transactions

---

src/cmap/connect.ts
src/connection_string.ts
src/mongo_client.ts

~~Will leave this in draft until the upstream Node.js PR is merged.~~
Refs: https://github.com/nodejs/node/pull/54790
This option is now exposed through the MongoClient constructor's options parameter and controls the [`X509_V_FLAG_PARTIAL_CHAIN`](https://docs.openssl.org/master/man3/X509_VERIFY_PARAM_set_flags/#verification-flags) OpenSSL flag.

feat(NODE-6365): pass through `allowPartialTrustChain` TLS flag

---

src/bson.ts
src/cmap/connection.ts
src/cmap/wire_protocol/on_demand/document.ts
src/cmap/wire_protocol/responses.ts
src/cursor/abstract_cursor.ts
src/cursor/aggregation_cursor.ts
src/cursor/find_cursor.ts
src/index.ts
test/integration/node-specific/bson-options/utf8_validation.test.ts
test/unit/cmap/wire_protocol/responses.test.ts

Forward-port of https://github.com/mongodb/node-mongodb-native/pull/4220.
Starting in v6.8.0 we inadvertently removed the ability to disable UTF-8 validation when deserializing BSON. Validation is normally a good thing, but it was always meant to be configurable and the [recent Node.js runtime issues (v22.7.0)](https://github.com/nodejs/node/issues/54543) make this option indispensable for avoiding errors from mistakenly generated invalid UTF-8 bytes.

fix(NODE-6362): cache cursor deserialization options across deserialize calls

---

test/benchmarks/mongoBench/suites/singleBench.js

- We check what returning a document "costs" to compare against our APIs
- Because it _should_ never change this would indicate if something external has changed

test(NODE-6323): add performance no-op baseline test

---

src/cursor/abstract_cursor.ts
test/integration/crud/find_cursor_methods.test.js

No
Fixing mixed use of `cursor.next` and `for await (const doc of cursor)`.
In 6.8.0, we inadvertently prevented the use of `cursor.next()` along with using `for await` syntax to iterate cursors. This use-case has now been restored.

fix(NODE-6367):  enable mixed use of iteration APIs

---

src/cursor/abstract_cursor.ts
test/integration/crud/find_cursor_methods.test.js

No
Fixing mixed use of `cursor.next` and `for await (const doc of cursor)`.
In 6.8.0, we inadvertently prevented the use of cursor.next() along with using for await syntax to iterate cursors. If your code made use of the following pattern and the call to cursor.next retrieved all your documents in the first batch, then the for-await loop would never be entered. This issue is now fixed.
```ts
const firstDoc = await cursor.next();
for await (const doc of cursor) {
// process doc
// ...
}
```

fix(NODE-6367): enable mixed use of iteration APIs 

---

etc/notes/errors.md
src/error.ts
test/unit/error.test.ts

- Fix error inheritance
No
Runtime errors indicate surprising outcomes, running out of time may be surprising but it is the intended outcome of an API that is given a deadline. 

fix(NODE-6374): MongoOperationTimeoutError inherits MongoRuntimeError

---

test/integration/client-side-operations-timeout/node_csot.test.ts

Remove empty context blocks that unintentionally skipped tests that should have been running
No
Test coverage

test: remove empty skipped context blocks

---

src/sdam/server_description.ts
test/integration/server-discovery-and-monitoring/server_description.test.ts

Add iscryptd to serverDescription
No
Need to be able to identify mongocryptd instances

feat(NODE-5844): add iscryptd to ServerDescription

---

src/operations/client_bulk_write/client_bulk_write.ts

Add timeoutContext to ClientBulkWriteOperation.execute and pass through
No
Fixing a typescript error in ClientBulkWriteOperation.execute.

chore: allow clientBulkWrite to use TimeoutContext

---

.evergreen/prepare-shell.sh

- print the commit used for tools
No
for debugging what version of tools used

chore: print drivers evergreen tools commit

---

src/cmap/connection.ts
test/unit/cmap/connection.test.ts

The message stream is paused when we're not reading from it, so we do not miss `data` events.
When performing large and many write operations, the driver will likely encounter buffering at the socket layer. The logic that waited until buffered writes were complete would mistakenly drop `'data'` (reading from the socket), causing the driver to hang indefinitely or until a socket timeout. Using pausing and resuming mechanisms exposed by Node streams we have eliminated the possibility for data events to go unhandled. 
Shout out to @hunkydoryrepair for debugging and finding this issue!

fix(NODE-6394): pause message stream when not listening for events

---

test/spec/crud/unified/aggregate-write-readPreference.json
test/spec/crud/unified/aggregate-write-readPreference.yml
test/spec/crud/unified/db-aggregate-write-readPreference.json
test/spec/crud/unified/db-aggregate-write-readPreference.yml

NODE-6184 / DRIVERS-2914
Syncing crud/db-aggregate-write-readPreference and crud/aggregate-write-readPreference spec tests to latest spec (DRIVERS-2914).
N/A
Keeping up with spec test changes, avoiding potential race condition.

test(NODE-6184): sync CRUD spec tests

---

src/bulk/common.ts
test/integration/client-side-operations-timeout/client_side_operations_timeout.prose.test.ts
test/integration/client-side-operations-timeout/client_side_operations_timeout.spec.test.ts
test/tools/unified-spec-runner/match.ts

- Adds CSOT support to bulkWrite
No
CSOT for all operations

feat(NODE-6274): add CSOT support to bulkWrite

---

src/cmap/connection.ts
src/cursor/abstract_cursor.ts
src/index.ts
src/operations/find.ts
src/timeout.ts
test/integration/client-side-operations-timeout/node_csot.test.ts
test/integration/crud/find_cursor_methods.test.js
test/integration/node-specific/abstract_cursor.test.ts
test/integration/server-selection/server_selection.prose.operation_count.test.ts
test/tools/utils.ts

The abstract cursor now accepts an external timeout.  This lets operations which create cursors share their timeout contexts with the abstract cursor.  This required a handful of changes:
1. this can only be used in CURSOR_LIFETIME, since ITERATION mutates the timeout context after each operation
2. killcursors now refreshes the timeout context without mutating it using the new `refreshed` method
I also removed some usages of `isCSOTEnabled()` by adding a `maxTimeMS` property to the TimeoutContext.  We can iterate on this and remove `omitMaxTimeMS` too if we want by making cursors conditionally return `null` when they should not set maxTimeMS, but I considered this out of scope for this PR.

refactor(NODE-6411): AbstractCursor accepts an external timeout context

---

src/bulk/common.ts
src/bulk/unordered.ts
test/integration/crud/crud_api.test.ts

- Refactor executeCommands to use async/await
No
Stack traces, debugging

refactor(NODE-6398): bulkWrite internals to use async/await

---

src/change_stream.ts
test/integration/change-streams/change_stream.test.ts
test/integration/change-streams/change_streams.prose.test.ts

* `changeStream` iteration methods now throw when the `aggregate` command that establishes the change stream on the server side fails
Before this fix, when change streams would fail to establish a cursor on the server, the driver would infinitely attempt to resume the change stream. Now, when the aggregate to establish the change stream fails, the driver will throw an error and clos the change stream.

fix(NODE-6418): change stream resumes infinitely after failed aggregates

---

src/operations/aggregate.ts
src/operations/find.ts
test/types/community/collection/findX.test-d.ts

`collection.find({}, { explain: ... })` and `collection/db.aggregate({}, { explain: ... })` are deprecated.
Specifying explain for cursors in the operation's options is deprecated in favor of the `.explain()` methods on cursors:
```typescript
collection.find({}, { explain: true })
// -> collection.find({}).explain()
collection.aggregate([], { explain: true })
// -> collection.aggregate([]).explain()
db.find([], { explain: true })
// -> db.find([]).explain()
```

feat(NODE-6419): deprecate explain options API for find and aggregate

---

src/cmap/connection.ts
test/integration/client-side-operations-timeout/client_side_operations_timeout.spec.test.ts
test/integration/client-side-operations-timeout/node_csot.test.ts

- Close a connection that has been timed out
No
If the connection is not closed it will go back into the pool and a subsequent operation will read the reply to the previous operation

fix(NODE-6412): read stale response from previously timed out connection

---

src/cmap/connection.ts
src/cmap/wire_protocol/on_data.ts
src/cursor/abstract_cursor.ts
src/cursor/client_bulk_write_cursor.ts
src/operations/client_bulk_write/executor.ts
src/sdam/server.ts
src/timeout.ts
src/utils.ts
test/integration/client-side-operations-timeout/client_side_operations_timeout.prose.test.ts
test/integration/client-side-operations-timeout/node_csot.test.ts
test/integration/collection-management/collection_db_management.test.ts
test/integration/crud/client_bulk_write.test.ts
test/tools/runner/config.ts
test/tools/utils.ts

This PR adds support for CSOT to the client bulk write API.

feat(NODE-6403): Add CSOT support to client bulk write

---

src/operations/client_bulk_write/executor.ts
test/integration/crud/crud.prose.test.ts
test/spec/command-logging-and-monitoring/monitoring/unacknowledged-client-bulkWrite.json
test/spec/command-logging-and-monitoring/monitoring/unacknowledged-client-bulkWrite.yml
test/spec/crud/unified/client-bulkWrite-errors.json
test/spec/crud/unified/client-bulkWrite-errors.yml

Updates client bulk write to change the way it handles unacknowledged writes.
- Error is thrown when w:0 and ordered is true.
- Error is thrown when w:0 and verbose results are requested.
- Syncs unified tests to latest.
- Adds a new prose test for batching unacknowledged writes.
None
NODE-6409/DRIVERS-2993
https://github.com/mongodb/specifications/pull/1670

feat(NODE-6409): new errors for unacknowledged bulk writes

---

.evergreen/run-resource-management-feature-integration.sh
test/integration/client-side-operations-timeout/client_side_operations_timeout.prose.test.ts
test/integration/client-side-operations-timeout/node_csot.test.ts
test/integration/crud/client_bulk_write.test.ts
test/integration/node-specific/abstract_cursor.test.ts
test/tools/utils.ts

I've noticed a number of flaky CSOT tests.  This PR attempts to fix the flakiness.

chore: fix a few flaky CSOT tests

---

src/sessions.ts
test/integration/transactions/transactions.test.ts

Ensure that `commitTransaction` only overrides the write concern when the `commitTransaction` call is retried (both with builtin retry mechanism and user-initiated retry).
No
Needed by NODE-3914
Prior to this change, `ClientSession.commitTransaction()` would always override any previously configured `writeConcern` on the initial attempt. This overriding behaviour now only applies to internal and user-initiated retries of `ClientSession.commitTransaction()` for a given transaction.

fix(NODE-6436): only force majority write concern on commitTransaction retry

---

.eslintrc.json
src/beta.ts
src/bson.ts
src/cmap/auth/mongodb_oidc.ts
src/cmap/auth/mongodb_oidc/callback_workflow.ts
src/cmap/auth/mongodb_oidc/command_builders.ts
src/cmap/auth/mongodb_oidc/human_callback_workflow.ts
src/cmap/auth/mongodb_oidc/machine_workflow.ts
src/cmap/connection.ts
src/cmap/wire_protocol/on_demand/document.ts
src/cmap/wire_protocol/responses.ts
src/cursor/client_bulk_write_cursor.ts
src/mongo_types.ts
src/operations/search_indexes/create.ts
src/operations/search_indexes/drop.ts
src/operations/search_indexes/update.ts

chore: add lint rule to prevent import from `bson` in driver src

---

src/index.ts
src/mongo_client.ts
src/operations/client_bulk_write/command_builder.ts
src/operations/client_bulk_write/common.ts
src/operations/client_bulk_write/executor.ts
src/operations/client_bulk_write/results_merger.ts
test/integration/crud/crud.prose.test.ts
test/types/client_bulk_write.test-d.ts
test/unit/operations/client_bulk_write/results_merger.test.ts

- Adds namespace to schema mapping type
- Adds tests/examples to our tsd tests
- Some important choices:
- We should default only where needed ("near the top"), the Models now require an input schema, Document can be used when none is needed. 
- `ClientBulkWriteModel` is exported on its own and is _not_ an array type. We can offer this seperate from the client API so annotations can be used to get this string to schema behavior (but I would advocate for putting it directly into the API)
Yes, I think the API doc on client.bulkWrite should explain how to use the TS a bit. I started in the TS doc for `ClientBulkWriteModel` 
We mostly use "inline" models to demo the API, however, this TS change does not cause friction in wrapping this API, it does have some considerations though, if you make …

feat(NODE-6350): add typescript support to client bulkWrite API

---

package-lock.json
package.json
src/cursor/aggregation_cursor.ts
src/cursor/find_cursor.ts
src/explain.ts
src/index.ts
src/operations/command.ts
src/operations/find.ts
src/utils.ts
test/integration/crud/explain.test.ts
test/tools/runner/config.ts
test/tools/utils.ts
test/unit/explain.test.ts
test/unit/index.test.ts

Explain helpers now support timeoutMS.
Explain helpers support timeoutMS:
```typescript
await collection.deleteMany({}, { timeoutMS: 1_000, explain: true });
await collection.find().explain(
{ verbosity: 'queryPlanner' },
{ timeoutMS: 1_000 }
)
```
> [!NOTE] 
> Providing a `maxTimeMS` value with a `timeoutMS` value will throw errors.

feat(NODE-6421): add support for timeoutMS to explain helpers

---

src/operations/client_bulk_write/executor.ts

- fix bson import lint
No
bson importing from the one file in the driver controls all usages of BSON APIs.

chore: fix bson import lint

---

src/mongo_client.ts
src/timeout.ts
test/integration/node-specific/auto_connect.test.ts

Added docs
New docs for docs? interesting idea
Auto connect or plain connect performs file system access, DNS lookup, monitor creation, mongocryptd launching, and more! each one of these steps has its own mechanism for cancellation that is not considered by the CSOT spec. Alternatively we considered ignoring cancelling those operations and simply racing with a timeout, however, the impact could be squashing important errors. 
Auto connect needs a future rework to better align with the drivers "always connected" perspective, for now, its best to explicitly connect if there's concern that the connecting operation won't complete in a globally set timeoutMS value.
Nothing specific to auto-connect, any client options: `socketTimeoutMS`, `waitQueueTimeoutMS`, `serverSelectionTimeoutMS`, …

docs(NODE-6223): timeoutMS does not govern auto-connect

---

.evergreen/run-resource-management-feature-integration.sh

chore: fix resource management tests

---

src/change_stream.ts
src/cmap/connection.ts
src/cursor/abstract_cursor.ts
src/cursor/change_stream_cursor.ts
test/integration/client-side-operations-timeout/client_side_operations_timeout.prose.test.ts
test/integration/client-side-operations-timeout/client_side_operations_timeout.spec.test.ts
test/integration/client-side-operations-timeout/node_csot.test.ts
test/integration/client-side-operations-timeout/unified-csot-node-specs/change-streams.json
test/integration/client-side-operations-timeout/unified-csot-node-specs/tailable-awaitData.json
test/integration/node-specific/abstract_cursor.test.ts

* Added support for CSOT to change stream iterator mode methods (`ChangeStream.next()`, `ChangeStream.hasNext()`, `ChangeStream.tryNext()`)
* Added support for CSOT to change stream emitter mode
* Change streams will now emit an error event with a `MongoOperationTimeoutError` when the internal cursor iteration times out
* Close socket when a command times out (temporary change while #4273 is in progress)
* Unskip and fix change stream prose test
* Unskip change stream tests
* Add integration tests to verify that CSOT behviour for ChangeStream emitter mode
Yes, punted to NODE-5688
NODE-6387

feat(NODE-6387): Add CSOT support to change streams

---

test/spec/client-side-encryption/tests/legacy/fle2v2-Rangev2-Compact.json
test/spec/client-side-encryption/tests/legacy/fle2v2-Rangev2-Compact.yml

Unskip rangev2 compact tests on serverless.

test(NODE-6388): unskip rangev2 compact tests on serverless

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Remove serverless proxy build variants as Serverless gRPC Proxy is being sunset..
Remove serverless proxy build variants. Revert changes from the [NODE-5731 PR](https://github.com/mongodb/node-mongodb-native/pull/4003/files#diff-2bc841e86ce96b7b422ae203fd8315d0b2a461956cecbe0e096420656fc3fb12).
No, test only change.
DRIVERS-2939.

test(NODE-6266): Remove serverless proxy incremental rollout tests

---

test/spec/connection-monitoring-and-pooling/cmap-format/README.md
test/spec/connection-monitoring-and-pooling/cmap-format/pool-checkin-make-available.json
test/spec/connection-monitoring-and-pooling/cmap-format/pool-checkin-make-available.yml
test/spec/connection-monitoring-and-pooling/cmap-format/pool-checkout-connection.json
test/spec/connection-monitoring-and-pooling/cmap-format/pool-checkout-connection.yml
test/spec/connection-monitoring-and-pooling/cmap-format/pool-checkout-error-closed.json
test/spec/connection-monitoring-and-pooling/cmap-format/pool-checkout-error-closed.yml
test/spec/connection-monitoring-and-pooling/cmap-format/pool-checkout-maxConnecting-timeout.json
test/spec/connection-monitoring-and-pooling/cmap-format/pool-checkout-maxConnecting-timeout.yml
test/spec/connection-monitoring-and-pooling/cmap-format/pool-clear-clears-waitqueue.json
test/spec/connection-monitoring-and-pooling/cmap-format/pool-clear-clears-waitqueue.yml
test/spec/connection-monitoring-and-pooling/cmap-format/pool-clear-interrupting-pending-connections.json
test/spec/connection-monitoring-and-pooling/cmap-format/pool-clear-interrupting-pending-connections.yml
test/spec/connection-monitoring-and-pooling/cmap-format/pool-clear-ready.json
test/spec/connection-monitoring-and-pooling/cmap-format/pool-clear-ready.yml
test/spec/connection-monitoring-and-pooling/cmap-format/pool-ready.json
test/spec/connection-monitoring-and-pooling/cmap-format/pool-ready.yml
test/spec/connection-monitoring-and-pooling/cmap-format/wait-queue-timeout.json
test/spec/connection-monitoring-and-pooling/cmap-format/wait-queue-timeout.yml
test/tools/cmap_spec_runner.ts

Not a P3 spec fest ticket, but I noticed all our CMAP tests were out-of-date during other spec-fest work.  

test(NODE-6110): sync `duration` property on CMAP events tests

---

src/client-side-encryption/state_machine.ts
src/operations/list_collections.ts
test/integration/client-side-encryption/driver.test.ts
test/integration/crud/client_bulk_write.test.ts
test/tools/utils.ts
test/unit/client-side-encryption/state_machine.test.ts

Instead of using the remainingTimeMS as the value for `timeoutMS` when running cursor operations in the state machine, we provide a CursorTimeoutContext that wraps the original timeout.

fix(NODE-6454): use timeoutcontext for state machine execute() cursor options

---

src/collection.ts
src/db.ts
src/mongo_client.ts

Add API docs for change streams

docs(NODE-6457): Document CSOT change stream behaviour

---

src/client-side-encryption/client_encryption.ts

docs(NODE-6458): document CSOT for explicit encryption

---

src/collection.ts
src/cursor/abstract_cursor.ts
src/cursor/run_command_cursor.ts
src/db.ts
src/error.ts
src/gridfs/index.ts
src/index.ts
src/mongo_client.ts
src/operations/indexes.ts
src/operations/operation.ts
src/operations/run_command.ts
src/sessions.ts
test/integration/client-side-operations-timeout/node_csot.test.ts
test/unit/index.test.ts

* Add API docs to `timeoutMS` and `timeoutMode` options
* Add API docs to `CursorTimeoutMode`
* Make `timeoutMS` and `timeoutMode` public

docs(NODE-6456): document CSOT pt 1

---

test/integration/client-side-operations-timeout/client_side_operations_timeout.spec.test.ts
test/spec/client-side-operations-timeout/runCursorCommand.json
test/spec/client-side-operations-timeout/runCursorCommand.yml
test/tools/unified-spec-runner/operations.ts

test(NODE-6493): sync runCursorCommand fixes

---

etc/notes/errors.md
src/change_stream.ts
src/connection_string.ts
src/cursor/abstract_cursor.ts
src/cursor/run_command_cursor.ts
src/error.ts
src/mongo_client.ts
src/operations/aggregate.ts
src/operations/command.ts
src/operations/count.ts
src/operations/estimated_document_count.ts
src/sdam/server.ts
src/sdam/topology.ts
src/timeout.ts
src/transactions.ts
src/write_concern.ts
test/benchmarks/driverBench/common.js
test/integration/client-side-operations-timeout/client_side_operations_timeout.prose.test.ts
test/integration/client-side-operations-timeout/client_side_operations_timeout.spec.test.ts
test/spec/client-side-operations-timeout/runCursorCommand.json
test/spec/client-side-operations-timeout/runCursorCommand.yml
test/types/mongodb.test-d.ts
test/types/write_concern.test-d.ts
test/unit/explain.test.ts
test/unit/timeout.test.ts

- Includes test sync from: https://jira.mongodb.org/browse/NODE-6493
Remaining cleanups for CSOT branch

chore(NODE-6493): CSOT clean ups and sync runCursorCommand test

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/run-oidc-prose-tests.sh
.evergreen/run-oidc-tests-k8s.sh
package.json
src/cmap/auth/mongo_credentials.ts
src/cmap/auth/mongodb_oidc.ts
src/cmap/auth/mongodb_oidc/k8s_machine_workflow.ts
test/integration/auth/mongodb_oidc_k8s.prose.07.test.ts
test/spec/auth/legacy/connection-string.json
test/spec/auth/legacy/connection-string.yml

Implements Kubernetes support for MONGODB-OIDC
- Adds support for AKS, EKS, GKE
- Adds evergreen task groups for both environments to run prose tests.
- Creates the new K8s machine workflow.
Yes in the manual.
DRIVERS-2882
https://github.com/mongodb/specifications/pull/1622
For k8s environments running in Amazon's EKS (Elastic Kubernetes Service), Google's GKE (Google Kubernetes Engine), or Azure's AKS (Azure Kubernetes Service) simply provide an `ENVIRONMENT` auth mechanism property in the URI or `MongoClient` options of "k8s".
Example:
```ts
const client = new MongoClient('mongodb://host:port/?authMechanism=MONGODB-OIDC&authMechanismProperties=ENVIRONMENT:k8s');
```

feat(NODE-6069): OIDC k8s machine workflow

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/run-benchmarks.sh
test/benchmarks/driverBench/common.js
test/benchmarks/driverBench/index.js
test/benchmarks/mongoBench/runner.js

- Add new benchmark tasks for CSOT
- set to 0, which means no timeouts are made
- set to 120,000 ms so nothing actually times out but we are making timers
No
More perf data!

chore(NODE-6459): compare CSOT performance

---

src/gridfs/upload.ts
test/integration/client-side-operations-timeout/client_side_operations_timeout.prose.test.ts

Pass `timeoutMS` as an option, not a field in the filter predicate, to deleteMany() when aborting a gridfs upload stream.
Also, I reworked the flaky CSOT test reported in https://jira.mongodb.org/browse/NODE-6522.  I'm not sure what caused the flakiness, but now it every time on macos now (ex run of 1000 iterations: https://spruce.mongodb.com/version/672cfbacdc76ef0007d99ed6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).

fix(NODE-6523): deleteMany in gridfs passes timeoutMS to predicate, not options

---

src/sessions.ts
test/benchmarks/driverBench/index.js

- Making various performance improvements to the hot paths of the driver
No
Regain performance
TBD...

perf(NODE-6525): remove setPrototype and defineProperty from hot path

---

.evergreen/run-azure-kms-mock-server.sh
.evergreen/run-socks5-tests.sh

Follow up to #4322
No
Use scripts from drivers-evergreen-tools instead of using the system python package manager.

chore(NODE-6502) Address two other usages of system python

---

src/cmap/connection.ts
src/cmap/connection_pool.ts
src/cursor/abstract_cursor.ts
src/timeout.ts

refactor(NODE-6524): consolidate socket timeout calculation

---

test/spec/load-balancers/transactions.json
test/spec/load-balancers/transactions.yml

Syncs unified tests for the latest unpinning test.
Sync of the load balancer unified tests.
None
NODE-5722

test(NODE-5722): unpin on endSessions test

---

.evergreen/run-typescript.sh
README.md

Set target to es2021 to avoid errors related to supporting JS syntax below our lowest supported node version.
Yes, added to the readme

chore(NODE-6488): specify target=es2021 for ts compilation tests

---

.evergreen/config.in.yml
.evergreen/config.yml

Adds a post task to kill mongo orchestration
Updates evergreen config to always attempt to stop mongo-orchestration in a post task.
None
NODE-6405

test(NODE-6405): stop mongo orchestration in post task

---

package-lock.json
package.json
test/benchmarks/driverBench/index.js
test/benchmarks/mongoBench/suites/parallelBench.js

Bump BSON to 6.10.0
No
Make vector APIs available in next release

feat(NODE-6551): update bson to 6.10.0

---

package-lock.json
package.json

Updates prod dependencies
Updates the prod dependencies to latest semver compatible versions.
None
NODE-6426

chore(NODE-6426): update prod dependencies

---

.github/dependabot.yml

Adds dependabot config to update Github Actions.
Adds dependabot config to update Github Actions.
None
NODE-6565

chore(NODE-6565): add dependabot for github actions

---

test/benchmarks/mongoBench/suites/singleBench.js

- Fix the inaccurate command document size
No
When we changed to hello from the legacy hello the size wasn't updated. We left it as is to preserve our performance history but with our recent reset, we should update this now

chore: fix runCommand bench hello size

---

test/spec/connection-monitoring-and-pooling/cmap-format/pool-checkout-returned-connection-maxConnecting.json
test/spec/connection-monitoring-and-pooling/cmap-format/pool-checkout-returned-connection-maxConnecting.yml

test(NODE-6527): sync pool-checkout-returned-connection-maxConnecting tests

---

test/spec/transactions-convenient-api/unified/commit-retry.json
test/spec/transactions-convenient-api/unified/commit-retry.yml
test/spec/transactions-convenient-api/unified/commit-writeconcernerror.json
test/spec/transactions-convenient-api/unified/commit-writeconcernerror.yml
test/spec/transactions/unified/retryable-commit.json
test/spec/transactions/unified/retryable-commit.yml

Syncs tests from https://jira.mongodb.org/browse/DRIVERS-3022.

test(NODE-6532): unskip transactions tests on serverless

---

.evergreen/install-dependencies.sh
src/cmap/connect.ts
test/benchmarks/driverBench/index.js

- SOCKS errors should be wrapped in our network error type
- Improve error messages for socket errors
No
While fixing NODE-6552 the error message changes helped with debugging and caught the error convert bug in a driveby
If the driver encounters an error while connecting to a socks5 proxy, the driver wraps the socks5 error in a MongoNetworkError.  In some circumstances, this resulted in the driver wrapping MongoNetworkErrors inside MongoNetworkErrors. 
The driver no longer double wraps errors in MongoNetworkErrors.

fix(NODE-6602): only wrap errors from SOCKS in network errors

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
README.md
package-lock.json
package.json
test/tools/runner/hooks/configuration.ts
test/unit/cmap/wire_protocol/compression.test.ts

The new [@mongodb-js/zstd@2.0](https://github.com/mongodb-js/zstd/releases/tag/v2.0.0) release can now be used with the driver for zstd compression.

feat(NODE-6593): add support for zstd@2.x

---

src/error.ts
src/index.ts
src/sdam/server_description.ts
src/sdam/topology_description.ts
test/spec/server-discovery-and-monitoring/rs/new_primary.json
test/spec/server-discovery-and-monitoring/rs/new_primary_new_electionid.json
test/spec/server-discovery-and-monitoring/rs/new_primary_new_electionid.yml
test/spec/server-discovery-and-monitoring/rs/new_primary_new_setversion.json
test/spec/server-discovery-and-monitoring/rs/new_primary_new_setversion.yml
test/spec/server-discovery-and-monitoring/rs/null_election_id-pre-6.0.json
test/spec/server-discovery-and-monitoring/rs/primary_disconnect_electionid.json
test/spec/server-discovery-and-monitoring/rs/primary_disconnect_electionid.yml
test/spec/server-discovery-and-monitoring/rs/primary_disconnect_setversion.json
test/spec/server-discovery-and-monitoring/rs/primary_disconnect_setversion.yml
test/spec/server-discovery-and-monitoring/rs/setversion_greaterthan_max_without_electionid.json
test/spec/server-discovery-and-monitoring/rs/setversion_greaterthan_max_without_electionid.yml
test/spec/server-discovery-and-monitoring/rs/setversion_without_electionid-pre-6.0.json
test/spec/server-discovery-and-monitoring/rs/setversion_without_electionid-pre-6.0.yml
test/spec/server-discovery-and-monitoring/rs/use_setversion_without_electionid-pre-6.0.json
test/spec/server-discovery-and-monitoring/rs/use_setversion_without_electionid-pre-6.0.yml
test/spec/server-discovery-and-monitoring/rs/use_setversion_without_electionid.json
test/spec/server-discovery-and-monitoring/rs/use_setversion_without_electionid.yml
test/unit/assorted/server_discovery_and_monitoring.spec.test.ts
test/unit/index.test.ts

* Added `MongoStalePrimaryError`
* Updated sdam unit test runner
* Updated spec tests from draft changes in DRIVERS-2972
We now attach an error to the newly created ServerDescription object when marking a primary as stale. This helps with debugging SDAM issues when monitoring SDAM events.

feat(NODE-6605):  add error message when invalidating primary

---

src/collection.ts

Add docs in from drivers ticket.
See above
Only API docs
DRIVERS-2728
The API documentation for `Collection.countDocuments` now documents [restrictions](https://www.mongodb.com/docs/manual/reference/operator/aggregation/match/#restrictions) for filters in the countDocuments API that result from the API using aggregation pipeline.

docs(NODE-6483): Add documentation for countDocuments $match operator

---

.evergreen/config.in.yml
.evergreen/config.yml

 ci(NODE-6609): add command monitoring perf test task

---

src/bulk/common.ts
src/change_stream.ts
src/cmap/connection_pool.ts
src/encrypter.ts
src/error.ts
src/mongo_client.ts
src/operations/operation.ts
src/sdam/monitor.ts
src/sdam/server.ts
src/sdam/topology.ts
src/sessions.ts
test/integration/change-streams/change_stream.test.ts
test/integration/connection-monitoring-and-pooling/connection.test.ts
test/integration/crud/misc_cursors.test.js
test/tools/utils.ts
test/unit/cmap/connection.test.ts
test/unit/error.test.ts
test/unit/mongo_client.test.ts
test/unit/sdam/topology.test.ts
test/unit/sessions.test.ts

Similar to: https://github.com/mongodb/node-mongodb-native/pull/4133
- Remove all symbol class properties in favor of private and internal marked string properties
No
Symbol class properties were introduced to the driver before we adopted typescript and API-extractor to clearly indicate the accessibility of driver APIs. The symbol properties provided implied privacy, making properties non-trivial to access. Today we have the power of typescript private/protected and API-extractor's type deletion feature for APIs marked internal. With these tools, we can remove symbol properties in favor of appropriately marked string properties. This makes debugging internals easier by making inspection and assertion far more simple.

refactor(NODE-4144): remove all symbol properties

---

.evergreen/ci_matrix_constants.js
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/install-dependencies.sh

- Add pins for npm 10 whereever we use node 18
No
NPM 11 drops support for node 18

chore(NODE-6622): pin npm version for node 18 to 10

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

* We are temporarily disabling variants that run on Node latest (currently v23.6.0) due to an issue with installing C++ addons.
* Move resource management tests to run on Node 22

ci(NODE-6641): disable Node latest tasks

---

src/cmap/auth/mongodb_aws.ts

`MONGODB-AWS` authentication mechanism should follow SASL [spec](https://github.com/mongodb/specifications/blob/master/source/auth/auth.md#sasl-mechanisms). Current implementation ignores the `conversationId` sent by the server and uses a hardcoded integer for all `saslContinue` messages across all conversations.
Changing the hardcoded integer for `conversationId` to utilize the one that gets returned in the `saslStart` response.
No. This change brings the implementation to spec.
This is a bug. MONGODB-AWS authentication failed on database emulating MongoDB.
Fixes SASL implementation for MONGODB-AWS to use conversationId returned by the server instead of hardcoded integer.

fix(NODE-6407): use conversationId returned by the server instead of hardcoded integer in SASL implementation for MONGODB-AWS.

---

test/integration/node-specific/resource_clean_up.test.ts
test/integration/node-specific/resource_tracking_script_builder.ts
test/tools/fixtures/heap_resource_script.in.js

- Throws the error to the before hook if an error occurs
- use the correct script name
- use SCRIPT_NAME_STRING instead of NAME_STRING
No
Calling the this.test.error(error) function was ending the test run early without error.   Running all the tests would be a nice-to-have. 🙂
Fixing issue introduced in #4355.

chore(NODE-6664): use correct script_name and replacement substring

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/install-dependencies.sh
.evergreen/prepare-shell.sh

Used the npm setting in based on the environment from drivers tools.
Removes the npm version setting backup from the install script.
None
NODE-6637

chore(NODE-6637): remove drivers tools env setting

---

src/cmap/command_monitoring_events.ts
src/utils.ts
test/integration/command-logging-and-monitoring/command_monitoring.test.ts

* Remove deep copy from `extractCommand` and `extractReply` helpers
No
Improving performance of command monitoring
Eliminated unnecessary deep copies of command and reply objects when command monitoring is enabled, leading to up to 

perf(NODE-6452): Optimize CommandStartedEvent and CommandSucceededEvent constructors

---

src/connection_string.ts
src/mongo_client.ts
test/integration/initial-dns-seedlist-discovery/dns_seedlist.test.ts

- When the dns.TIMEOUT error is detected when resolving SRV and TXT the driver will try those look ups again.
Yes API updated
In some environments (possibly FAAS?) it has been observed that DNS look ups can fail transiently. The driver can attempt to mitigate these with a retry.
To mitigate the potentially transient DNS timeout error, the driver now catches and retries the DNS lookups upon resolving a `mongodb+srv://` style connection string. 

feat(NODE-6451): retry SRV and TXT lookup for DNS timeout errors

---

src/cursor/abstract_cursor.ts
src/mongo_client.ts
test/integration/crud/find_cursor_methods.test.js
test/integration/crud/misc_cursors.test.js
test/integration/node-specific/abort_signal.test.ts
test/integration/node-specific/abstract_cursor.test.ts
test/integration/node-specific/mongo_client.test.ts

- MongoClient's close cursors created from them upon close
- Yes. will do.
In an effort to make MongoClient.close more effective and align with other existing close semantics in the ecosystem our close method is being improved to ensure the client when closed cleans up any resources it was responsible for creating. This allows users to rely on the paradigm that a closed client is no longer performing operations, which is currently not true and is likely surprising.
Previously, cursors could somewhat live beyond the client they came from. What this meant was depending on timing you would learn of the client's (and by proxy, the cursor's) demise via an assertion that the associated session had expired. This only occurred if your cursor needed to use the session, which only happens when it …

feat(NODE-6633): MongoClient.close closes active cursors

---

test/spec/command-logging-and-monitoring/logging/command.json
test/spec/command-logging-and-monitoring/logging/command.yml
test/spec/command-logging-and-monitoring/monitoring/find.json
test/spec/command-logging-and-monitoring/monitoring/find.yml
test/spec/command-logging-and-monitoring/monitoring/unacknowledgedBulkWrite.json
test/spec/command-logging-and-monitoring/monitoring/unacknowledgedBulkWrite.yml
test/spec/command-logging-and-monitoring/monitoring/writeConcernError.json
test/spec/command-logging-and-monitoring/monitoring/writeConcernError.yml

Sync new spec tests
No
NODE-4955/DRIVERS-2525
Additionally syncs:
- https://jira.mongodb.org/browse/NODE-5808
- https://jira.mongodb.org/browse/NODE-5055
- https://jira.mongodb.org/browse/DRIVERS-2644 (just a schema version fix, no lang ticket)
- 

test(NODE-4955): sync unacknowledged write spec tests

---

src/cmap/auth/mongodb_oidc.ts
test/integration/auth/mongodb_oidc.prose.test.ts

Changes OIDC not to skip reauthentication when the initial auth happened via speculative authentication.
- Fixes the reauth case.
- Adds the new prose test.
None
https://jira.mongodb.org/browse/DRIVERS-2960
When using MONGODB-OIDC authentication and the initial handshake contained speculative authentication, the driver would not properly reauthenticate when the server would raise 391 errors. This is now fixed.

fix(NODE-6340): OIDC reauth uses caches speculative auth result

---

src/mongo_client.ts
test/integration/node-specific/mongo_client.test.ts
test/unit/mongo_client.test.ts

Previously, concurrent calls to `client.close()` would throw an error. 
This PR introduces a locking mechanism on `client.close()`. The 
No.
User submitted bug: NODE-5225
In the past, concurrent calls to `MongoClient.close()` had poorly defined behavior depending on the exact timing of the second (or more) calls to close().  In some cases, this could also throw errors.
With these changes, MongoClient.close() can be called concurrently safely and always return the same promise.
> [!NOTE]
> This is intended as a correctness fix - we don't recommend calling MongoClient.close() concurrently if it can be avoided.

fix(NODE-5225): concurrent MongoClient.close() calls each attempt to close the client

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/run-deployed-azure-kms-tests.sh
.evergreen/run-deployed-gcp-kms-tests.sh
.evergreen/run-serverless-tests.sh
.evergreen/setup-serverless.sh
test/readme.md
test/tools/runner/config.ts

Serverless tests use AWS secrets manager to fetch credentials to set up the cluster.  These tests don't use secretes manager to fetch FLE credentials (https://jira.mongodb.org/browse/NODE-6685).
GCP and Azure KMS e2e tests also use secrets manager.
I also updated the testing readme with instructions on how to use secrets manager and how to run these tests locally.
No.

ci(NODE-6682, NODE-6684): deployed KMS tests and serverless tests use secrets manager

---

.evergreen/config.in.yml
.evergreen/config.yml
test/readme.md

Deployed atlas clusters now use Secrets Manager.

ci(NODE-6686): deployed Atlas cluster tests use secrets manager

---

.github/CODEOWNERS

Add CODEOWNERS file
N/A
Auto-assign team to PRs
- [N/A] Ran `npm run check:lint` script

chore: Add CODEOWNERS file [skip-ci]

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/run-kerberos-tests.sh
.gitignore
test/manual/kerberos.test.ts
test/readme.md

Kerberos tests use secrets manager.

ci(NODE-6694): kerberos tests use secrets manager

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
test/benchmarks/driver_bench/readme.md
test/benchmarks/driver_bench/src/driver.mts
test/benchmarks/driver_bench/src/suites/multi_bench/aggregate_a_million_documents_and_to_array.mts
test/benchmarks/driver_bench/src/suites/multi_bench/aggregate_a_million_tweets_and_to_array.mts
test/benchmarks/driver_bench/src/suites/multi_bench/find_many_and_to_array.mts
test/benchmarks/driver_bench/src/suites/multi_bench/grid_fs_download.mts
test/benchmarks/driver_bench/src/suites/multi_bench/grid_fs_upload.mts
test/benchmarks/driver_bench/src/suites/multi_bench/large_doc_bulk_insert.mts

Move to the new isolated and warm up bench system

chore(NODE-6720): migrate multibench tests

---

test/benchmarks/driver_bench/src/driver.mts
test/benchmarks/driver_bench/src/runner.mts
test/benchmarks/driver_bench/src/suites/multi_bench/aggregate_a_million_documents_and_to_array.mts
test/benchmarks/driver_bench/src/suites/multi_bench/aggregate_a_million_tweets_and_to_array.mts
test/benchmarks/driver_bench/src/suites/multi_bench/find_many_and_empty_cursor.mts
test/benchmarks/driver_bench/src/suites/multi_bench/find_many_and_to_array.mts
test/benchmarks/driver_bench/src/suites/multi_bench/grid_fs_download.mts
test/benchmarks/driver_bench/src/suites/multi_bench/grid_fs_upload.mts
test/benchmarks/driver_bench/src/suites/multi_bench/large_doc_bulk_insert.mts
test/benchmarks/driver_bench/src/suites/multi_bench/small_doc_bulk_insert.mts
test/benchmarks/driver_bench/src/suites/single_bench/find_one.mts
test/benchmarks/driver_bench/src/suites/single_bench/large_doc_insert_one.mts
test/benchmarks/driver_bench/src/suites/single_bench/ping.mts
test/benchmarks/driver_bench/src/suites/single_bench/run_command.mts
test/benchmarks/driver_bench/src/suites/single_bench/small_doc_insert_one.mts

Migrate the single bench to the new format

chore(NODE-6721): migrate singlebench tests

---

src/error.ts
src/sdam/topology_description.ts
test/spec/server-discovery-and-monitoring/rs/new_primary.json
test/spec/server-discovery-and-monitoring/rs/new_primary.yml
test/spec/server-discovery-and-monitoring/rs/new_primary_new_electionid.json
test/spec/server-discovery-and-monitoring/rs/new_primary_new_electionid.yml
test/spec/server-discovery-and-monitoring/rs/new_primary_new_setversion.json
test/spec/server-discovery-and-monitoring/rs/new_primary_new_setversion.yml
test/spec/server-discovery-and-monitoring/rs/primary_disconnect_electionid.json
test/spec/server-discovery-and-monitoring/rs/primary_disconnect_electionid.yml
test/spec/server-discovery-and-monitoring/rs/primary_disconnect_setversion.json
test/spec/server-discovery-and-monitoring/rs/primary_disconnect_setversion.yml
test/spec/server-discovery-and-monitoring/rs/setversion_greaterthan_max_without_electionid.json
test/spec/server-discovery-and-monitoring/rs/setversion_greaterthan_max_without_electionid.yml
test/spec/server-discovery-and-monitoring/rs/setversion_without_electionid-pre-6.0.json
test/spec/server-discovery-and-monitoring/rs/setversion_without_electionid-pre-6.0.yml
test/spec/server-discovery-and-monitoring/rs/use_setversion_without_electionid-pre-6.0.json
test/spec/server-discovery-and-monitoring/rs/use_setversion_without_electionid-pre-6.0.yml
test/unit/assorted/server_discovery_and_monitoring.test.ts

Update error messages added to `ServerDescription` objects to more accurately reflect Topology state when Primaries step down.
None
NODE-6613, DRIVERS-2972

fix(NODE-6613): Update error messages when primaries go stale

---

test/benchmarks/driver_bench/src/suites/single_bench/primes.mts

- add a cpu benchmark for scale

chore(NODE-6733): add a cpu benchmark

---

test/benchmarks/driver_bench/src/driver.mts
test/benchmarks/driver_bench/src/main.mts
test/benchmarks/driver_bench/src/runner.mts
test/benchmarks/driver_bench/src/suites/single_bench/primes.mts

We need to keep reporting the composite scores. Remove reporting count

chore(NODE-6724): report composite benchmark scores

---

.evergreen/config.in.yml
.evergreen/config.yml

Renaming the ARN we use for secrets manager so the name more accurately describes what the secret is.  We use the same ARN for all secrets, not just OIDC.

ci: rename secrets manager ARN

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Skip serverless tests
No
Blocked on getParameter and fail points not working.

ci: skip serverless tests

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Skip a test that fails to setup currently
No
https://jira.mongodb.org/browse/NODE-6750

chore: skip azure oidc login setup failure

---

.evergreen/run-kerberos-tests.sh
package-lock.json
package.json
test/manual/x509_auth.test.ts

Let the lock file update to pull in the prebuild with the N-API parse fix

ci: pull in fixed prebuild version and add kerberos to dev dependencies

---

test/integration/auth/auth.prose.test.ts

Skips the failing SCRAM test.
Skips the failing test with TODO.
None
NODE-6751

test(NODE-6751): skip flaky scram test

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Adds a tag to the perf variant so we can filter it out of PRs (and coverage)

chore: add tag to performance variant

---

.evergreen/config.in.yml
.evergreen/config.yml

Atlas clusters have a 23-character unique prefix requirement.  The search index tests hard-code in a prefix that is 23 characters long, so if two search index runs execute concurrently, one will fail.
This PR shortens the prefix to prevent this issue.

ci(NODE-6749): make Atlas cluster prefix < 23 characters long

---

src/utils.ts
test/integration/read-write-concern/write_concern.test.ts
test/unit/utils.test.ts

That PR should fix case of loosing write-concern options while using `timeoutMS` option.
`WriteConcern.fromOptions` static method accepts 3 options formats:
* `WriteConcernOptions` object
* `WriteConcern` instance
* `W` type
But in case of using `timeoutMS` options, utils function `resolveOptions` calls ([link to code](https://github.com/mongodb/node-mongodb-native/blob/main/src/utils.ts#L533)) `WriteConcern.fromOptions` with options, which looks like `WriteConcern` instance, but there is no instance and more look like `WriteConcernSettings` type:
```ts
writeConcern = WriteConcern.fromOptions({
...writeConcern,
wtimeout: undefined,
wtimeoutMS: undefined
});
```
So that call return `undefined` as "parsing failed" and command losses write-concern context.
I changed options format to be …

fix(NODE-6763): pass WriteConcernOptions instead on WriteConcernSettings

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/install-dependencies.sh
.evergreen/prepare-shell.sh

Reverts changes in tools for finding python3 that broken the AWS ECS tests. Companion PR: https://github.com/mongodb-labs/drivers-evergreen-tools/pull/602
Moves the forced python3 find into our install dependencies script only when testing functionality with a native module.
None
NODE-6745
https://github.com/mongodb-labs/drivers-evergreen-tools/pull/602

test(NODE-6745): only find python when installing native

---

package-lock.json

The lockfile got out of sync with the package.json, so `npm ci` failed in the `check dependencies` Github action.

ci(NODE-6768): regenerate lockfile

---

package-lock.json
package.json

Update BSON version requirement
No
Pull in BSON fixes
This forces fixes made in [6.10.3](https://github.com/mongodb/js-bson/releases/tag/v6.10.3) and [6.10.2](https://github.com/mongodb/js-bson/releases/tag/v6.10.2) to be pulled into the driver.

fix(NODE-6777): update BSON to 6.10.3

---

src/collection.ts
test/integration/crud/find_and_modify.test.ts
test/types/community/collection/findX.test-d.ts

In https://github.com/mongodb/node-mongodb-native/pull/3953, the aggregation pipeline signature was added for `updateOne` and `updateMany`, but this was missed for `findOneAndUpdate`
Documentation is included.
The documentation was missing from the node.js driver. The initial motivation is that the downstream mongoose type also need to be updated to allow aggregation pipelines in `findOneAndUpdate`, but for consistency, these types should be updated first, or at least have this update ready while updating the mongoose types.
https://jira.mongodb.org/browse/NODE-6765

docs(NODE-6765): sync types for findOneAndUpdate

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Disables serverless testing.
Comment out the serverless variant in CI.
None
NODE-6766

test(NODE-6766): skip serverless tests

---

src/mongo_logger.ts

Switch from util/types to ./utils for isUint8Array
No
Bundlers need to add a target module for util/types for a method we already implement ourselves. No reason to cause that friction.
Some users of bundlers for next.js and our very own mongosh noticed a new import from "util/types" that would need to be supported in environments that don't have that module. We already have an internal implementation of `isUint8Array` so we do not need to add an import for "util/types".

fix(NODE-6792): use driver version of isUint8Array

---

package-lock.json
package.json

Undo peer compat change in last release
No
Peer compatiblity shouldn't change in a minor/patch release
In v6.13.1 we inadvertantly raised the version compatibility of `@aws-sdk/credential-providers`, that change has been reverted.

fix(NODE-6794): revert `@aws-sdk/credential-providers` peer compatibility change

---

src/cmap/auth/mongodb_oidc/machine_workflow.ts
test/unit/cmap/auth/mongodb_oidc/gcp_machine_workflow.test.ts

When using OIDC authentication when there is more than one connection in the pool, connections that were created after the first connection would have no access token set on them until after the first reauthentication attempt. This was due to the fact that the first connection that was created retrieved the token and put it in the cache, and all following connections weren't setting their access token properly from the cache if it existed.
- Changes the machine workflow to properly set a token from the cache on the connection if the connection's token is undefined.
- Adds a unit test.
None
HELP-70195
This was due to a bug in setting the properly cached access token on the connection.

fix(NODE-6801): set token on connection from cache

---

test/integration/client-side-encryption/client_side_encryption.prose.17.on_demand_gcp.test.ts
test/integration/client-side-encryption/client_side_encryption.prose.19.on_demand_azure.test.ts

The deployed KMS tests were skipped because KMS credentials were not present in the environment when the tests ran on Azure or GCP.  
This PR fixes the tests to ensure that they run.

ci(NODE-6791): make deployed KMS tests run again

---

test/benchmarks/driver_bench/src/driver.mts

test(NODE-6807): move benchmark tags into correct place

---

etc/notes/releasing.md

docs(NODE-6840): add docs covering minor version backports

---

test/integration/change-streams/change_stream.test.ts

- remove callback based test
The test flaked but it isn't the correct coverage for our API. The promises test covers the same concept

chore(NODE-6846): remove legacy callback change stream test

---

global.d.ts
test/integration/change-streams/change_stream.test.ts
test/integration/change-streams/change_streams.prose.test.ts
test/tools/runner/plugins/deferred.js

- Add validation to defer to prevent incorrect usages
- Use async/await to get stack traces
- remove incorrect usages
The defer usages were passed a promise instead of a functiont that creates a promise. 

chore(NODE-6844): modernize defer and remove incorrect usages

---

test/integration/retryable-reads/retryable_reads.spec.test.ts
test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.prose.test.ts

https://spruce.mongodb.com/version/mongo_node_driver_next_4e18803c074231ec9fc3ace8f966e2c49d9874bb_75c01e57abc470e785838d3c6dd0a8c0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

ci: skip flaky tests in retryable reads and sdam suites

---

test/integration/client-side-encryption/client_side_encryption.prose.test.js
test/integration/client-side-encryption/client_side_encryption.spec.test.ts

https://spruce.mongodb.com/version/67d36239b34f3e000734c09c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

ci: skip flaky tests in FLE test suite

---

test/integration/node-specific/abort_signal.test.ts

https://spruce.mongodb.com/version/67d450f10f5a9c0007908420/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

ci: skip flaky test in abort signal test suite

---

test/integration/client-side-operations-timeout/client_side_operations_timeout.spec.test.ts

skip
https://spruce.mongodb.com/task/mongo_node_driver_next_rhel80_large_node_latest_test_4.4_sharded_cluster_91d235221cc42a49bcfa85e428f83d8e6ba258d0_75c01e57abc470e785838d3c6dd0a8c0_25_03_18_15_22_09/logs?execution=0&sortBy=STATUS&sortDir=ASC
Will unskip in: NODE-6867

ci: skip flaky test in CSOT test suite

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/perf-send.sh
test/benchmarks/driver_bench/src/main.mts

NODE-6870
normalized_throughput didn't have the tags from the original metric
Tags are needed to add metrics to a context

chore(NODE-6870): add tags to normalized_throughput

---

test/benchmarks/driver_bench/src/driver.mts
test/benchmarks/driver_bench/src/main.mts
test/benchmarks/driver_bench/src/runner.mts
test/benchmarks/driver_bench/src/suites/node_specific/cpu_baseline.mts

NODE-6871
Tagging the composite scores accurately and making sure we don't miss tags in the future.

chore(NODE-6871): make tags required and add tags to composite scores

---

test/spec/load-balancers/non-lb-connection-establishment.json
test/spec/load-balancers/non-lb-connection-establishment.yml

Unskip lb test on latest
spec: https://github.com/mongodb/specifications/commit/f04df7d667e20fa7f9ae067e6951662c68da85b6
NODE-6802
_update:_ This test runs on non-lb hosts
https://parsley.mongodb.com/evergreen/mongo_node_driver_next_rhel8_no_auth_tests_test_latest_server_noauth_patch_5ce0a4ec855fd1d609fbb17f85b014e5b0fa8157_67e1c3fbf504270007ffbd67_25_03_24_20_43_41/0/task?bookmarks=0,11408&shareLine=7718
No
spec compat

test(NODE-6802): unskip operations against non-load balanced clusters fail if URI contains loadBalanced=true on latest

---

test/spec/server-discovery-and-monitoring/rs/secondary_ipv6_literal.json
test/spec/server-discovery-and-monitoring/rs/secondary_ipv6_literal.yml

Sync tests from https://github.com/mongodb/specifications/commit/fc495d5a58479a6527d7950c0d4be57f0f8869c4
NODE-6835
No
spec compat

test(NODE-6835): IPv6 literal in SDAM

---

test/manual/x509_auth.test.ts

ci: skip flaky x509 authentication test

---

test/integration/change-streams/change_streams.prose.test.ts

test(NODE-5466): update MongoDB version requirement for changeStreamSplitLargeEvent prose tests

---

test/csfle-kms-providers.ts
test/integration/client-side-encryption/client_side_encryption.prose.10.kms_tls.test.ts
test/integration/client-side-encryption/client_side_encryption.prose.test.js

Add KMS TLS test: NODE-3151
No
Spec test for specific error messages

test(NODE-3151): add KMS TLS tests for client-side encryption

---

test/spec/crud/unified/estimatedDocumentCount.json
test/spec/crud/unified/estimatedDocumentCount.yml
test/spec/retryable-reads/unified/estimatedDocumentCount.json
test/spec/retryable-reads/unified/estimatedDocumentCount.yml
test/spec/unified-test-format/valid-pass/expectedError-isClientError.json
test/spec/unified-test-format/valid-pass/expectedError-isClientError.yml

test(NODE-6500): sync UTR isClientError asserts true for network errors tests

---

test/spec/change-streams/unified/change-streams-disambiguatedPaths.json
test/spec/change-streams/unified/change-streams-disambiguatedPaths.yml
test/spec/change-streams/unified/change-streams.json
test/spec/change-streams/unified/change-streams.yml

test(NODE-6885): sync new change stream disambiguated path changes

---

.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
test/manual/x509_auth.test.ts

Fixes the flaky x509 test.
Change tests to run against a standalone instead of sharded cluster.
None
NODE-6834

test(NODE-6834): fix flaky x509 test

---

src/change_stream.ts

docs(NODE-6888): update API docs for disambiguatedPaths on 8.2.0+ servers

---

.evergreen/config.in.yml
.evergreen/config.yml

Performance uploads to the same place as coverage and coverage downloads everything

chore: fix coverage downloading perf results

---

.evergreen/ci_matrix_constants.js
.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/perf_send.mjs
.evergreen/run-lint-checks.sh

chore(NODE-6890): add AWS variables to env from expansions

---

test/integration/client-side-operations-timeout/client_side_operations_timeout.spec.test.ts
test/tools/runner/flaky.ts

Unskip the flaky CSOT double timeout test.
- Unskip the flaky test
- Add the test to the flaky logging list.
None
NODE-6867

test(NODE-6867): unskip csot double timeout test

---

test/tools/runner/flaky.ts

Unskip flaky SDAM prose test.
- Unskip the flaky test
- Add the test to the flaky logging list.
None
NODE-5206

test(NODE-5206): add logging to flaky SDAM test

---

test/integration/client-side-operations-timeout/client_side_operations_timeout.spec.test.ts
test/tools/runner/flaky.ts

Unskip the flaky CSOT legacy single timeout test.
- Unskip the flaky test
- Add the test to the flaky logging list.
None
NODE-6863

test(NODE-6863): unskip flaky csot legacy timeout spec test

---

test/integration/client-side-operations-timeout/client_side_operations_timeout.spec.test.ts
test/tools/runner/flaky.ts

Unskips the flaky CSOT spec test for timeoutMS overriding socketTimeoutMS
- Unskip the flaky test
- Add the test to the flaky logging list.
None
NODE-6862

 test(NODE-6862): unskip flaky csot spec test 

---

test/tools/unified-spec-runner/operations.ts

- quick search and replace fix for return -> return await
- Add names to our operation functions
BEFORE:
```
at async executeOperation (src/operations/execute_operation.ts:115:12)
at async Collection.insertMany (src/collection.ts:307:12)
at async executeOperationAndCheck (test/tools/unified-spec-runner/operations.ts:1030:14)
```
AFTER:
```
at async executeOperation (src/operations/execute_operation.ts:115:12)
at async Collection.insertMany (src/collection.ts:307:12)
at async insertMany (test/tools/unified-spec-runner/operations.ts:411:10)
at async executeOperationAndCheck (test/tools/unified-spec-runner/operations.ts:1039:14)
```

chore: use return await syntax in UTR to jump to throwing operation

---

README.md

Driver support for 4.0 is deprecated.
> [!IMPORTANT]
> Node driver support for server 4.0 will be removed in an upcoming minor release. Reference: [MongoDB Software Lifecycle Schedules](https://www.mongodb.com/legal/support-policy/lifecycles).

feat(NODE-6515): deprecate driver support for server 4.0

---

src/bulk/common.ts
src/collection.ts
src/operations/client_bulk_write/command_builder.ts
src/operations/client_bulk_write/common.ts
src/operations/update.ts
src/sort.ts
test/integration/crud/client_bulk_write.test.ts
test/integration/crud/crud_api.test.ts
test/spec/crud/unified/bulkWrite-replaceOne-sort.json
test/spec/crud/unified/bulkWrite-replaceOne-sort.yml
test/spec/crud/unified/bulkWrite-updateOne-sort.json
test/spec/crud/unified/bulkWrite-updateOne-sort.yml
test/spec/crud/unified/client-bulkWrite-replaceOne-sort.json
test/spec/crud/unified/client-bulkWrite-replaceOne-sort.yml
test/spec/crud/unified/client-bulkWrite-updateOne-sort.json
test/spec/crud/unified/client-bulkWrite-updateOne-sort.yml
test/spec/crud/unified/replaceOne-sort.json
test/spec/crud/unified/replaceOne-sort.yml
test/spec/crud/unified/updateOne-sort.json
test/spec/crud/unified/updateOne-sort.yml
test/types/sort.test-d.ts

- Adds support for sort on updateOne and replaceOne operations
- client bulkWrite and collection bulkWrite versions of these operations support it as well
No
The server now supports a sort on these operations, so we do too!
The updateOne and replaceOne operations in each of the ways they can be performed support a sort option starting in MongoDB 8.0. The driver now supports the sort option the same way it does for find or findOneAndModify-style commands:
```js
const sort = { fieldName: -1 };
collection.updateOne({}, {}, { sort });
collection.replaceOne({}, {}, { sort }); 
collection.bulkWrite([ { updateOne: { filter: {}, update: {}, sort } } ]);
client.bulkWrite([
{ name: 'updateOne', namespace: 'db.test', filter: {}, update: {}, sort },
{ name: 'replaceOne', namespace: 'db.test', filter: …
```

feat(NODE-6290): add sort support to updateOne and replaceOne

---

src/cmap/connect.ts
src/connection_string.ts
src/mongo_client.ts
test/integration/node-specific/mongo_client.test.ts
test/manual/tls_support.test.ts

Brings back the `keepAliveInitialDelay` option.
- Adds `keepAliveInitialDelay` as an option to pass to the socket.
- Removed the explicit calls to `setKeepAlive` and `setNoDelay`
- Defaults now to 120 seconds instead of 300
Yes, driver docs.
NODE-6245
When not present will default to 120 seconds. The option value must be specified in milliseconds.
```typescript
import { MongoClient } from 'mongodb';
const client = new MongoClient(process.env.MONGODB_URI, { keepAliveInitialDelay: 100000 });
```

feat(NODE-6245): add keepAliveInitialDelay config

---

test/integration/client-side-encryption/client_side_encryption.prose.test.js
test/tools/runner/flaky.ts

Skip the consistently failing FLE AWS bad URI test.
- Skip the test
- Add to the flaky list for logging later.
None
NODE-6927

test(NODE-6927): skip failing aws uri test

---

test/integration/mongodb-handshake/mongodb-handshake.prose.test.ts

test(NODE-6288): test that container and FAAS env information are both included  in handshake 

---

test/integration/node-specific/resource_clean_up.test.ts
test/tools/runner/flaky.ts

test: add logging for gcp flaky test

---

package-lock.json
package.json
src/client-side-encryption/auto_encrypter.ts
src/client-side-encryption/client_encryption.ts
test/integration/client-side-encryption/client_side_encryption.spec.test.ts
test/spec/client-side-encryption/tests/legacy/keyCache.json
test/spec/client-side-encryption/tests/legacy/keyCache.yml
test/spec/client-side-encryption/tests/unified/keyCache.json
test/spec/client-side-encryption/tests/unified/keyCache.yml
test/tools/unified-spec-runner/schema.ts
test/tools/unified-spec-runner/unified-utils.ts

Adds support to configure the DEK cache expiration time.
- Adds the option `keyTimeoutMS` to both client encryption and auto encryption options.
None
Default value is 60000. Requires using mongodb-client-encryption >= 6.4.0
For `ClientEncryption`:
```ts
import { MongoClient, ClientEncryption } from 'mongodb';
const client = new MongoClient(process.env.MONGODB_URI);
const clientEncryption = new ClientEncryption(client, { keyExpirationMS: 100000, kmsProviders: ... });
```
For auto encryption:
```ts
import { MongoClient, ClientEncryption } from 'mongodb';
const client = new MongoClient(process.env.MONGODB_URI, {
autoEncryption: {
keyExpirationMS: 100000,
kmsProviders: ...
}
});
```

feat(NODE-6952): support configuring DEK cache expiration

---

README.md

Updated README.md to add mention of semantic versioning.
Only the README.md file. 
No
Addresses [DRIVERS-3105](https://jira.mongodb.org/browse/DRIVERS-3105).

feat(DRIVERS-3105): Update README.md

---

src/cursor/abstract_cursor.ts
src/cursor/run_command_cursor.ts
test/integration/crud/misc_cursors.test.js
test/integration/node-specific/abstract_cursor.test.ts
test/unit/cursor/abstract_cursor.test.ts
test/unit/cursor/aggregation_cursor.test.ts

When no explicit session is provided to a cursor, we now instantiate an implicit session when initializing the cursor, instead of in the cursor's constructor.
In previous versions, sessions were eagerly allocated whenever a cursor was created, regardless of whether or not a cursor was actually iterated (and the session was actually needed).  Some driver APIs (`FindCursor.count()`, `AggregationCursor.explain()` and `FindCursor.explain()`) don't actually iterate the cursor they are executed on.  This can lead to client sessions being created and never being cleaned up.
With this update, sessions are not allocated until the cursor is iterated.

fix(NODE-4845): allocate sessions lazily in cursors

---

src/cmap/connection_pool.ts
src/cmap/handshake/client_metadata.ts
src/connection_string.ts
src/mongo_client.ts
test/integration/connection-monitoring-and-pooling/connection.test.ts
test/integration/mongodb-handshake/mongodb-handshake.prose.test.ts
test/integration/mongodb-handshake/mongodb-handshake.spec.test.ts
test/spec/connection-monitoring-and-pooling/cmap-format/pool-create-min-size-error.json
test/spec/mongodb-handshake/metadata-not-propagated.json
test/spec/mongodb-handshake/metadata-not-propagated.yml
test/tools/cmap_spec_runner.ts
test/tools/unified-spec-runner/operations.ts
test/unit/cmap/handshake/client_metadata.test.ts
test/unit/sdam/topology.test.ts

Allows appending driver info for the client metadata after a mongo client has been constructed.
- Adds `appendMetadata` to `MongoClient`
- Adds the ability for certain metadata to be modified on the client instance.
- Allows for appending metadata multiple times for the handshake.
- Syncs unified tests allowing for new functionality.
- Updates prose handshake tests.
Manual docs.
NODE-7009
Driver information such as name, version, and platform are allowed:
```ts
import { MongoClient } from 'mongodb';
const client = new MongoClient(process.env.MONGODB_URI);
client.appendMetadata({ name: 'my library', version: '1.0', platform: 'NodeJS' });
```

feat(NODE-7009): add client metadata on demand

---

src/operations/command.ts

`CommandOptions.noResponse` is deprecated.
> [!CAUTION]
> `noResponse` is not intended for use outside of `MongoClient.close()`.  Do not use this option.
The Node driver has historically supported an option, `noResponse`, that is used internally when a MongoClient is closed.  This option was accidentally public.  This option will be removed in an upcoming major release.

feat(NODE-7053): deprecate noResponse option

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js

Unskips the LDAP and Kerberos tests.
- Unskips the tests
- Adds assume secret manager role to the runs.
None
NODE-6944

test(NODE-6944): unskip ldap and kerberos tests

---

src/client-side-encryption/state_machine.ts
test/integration/client-side-encryption/client_side_encryption.prose.test.ts
test/integration/client-side-encryption/driver.test.ts
test/tsconfig.json

Allows users to pass a `secureContext` option to the TLS options in client encryption and auto encryption.
- Allows a `secureContext` option to the `tlsOptions:<provider>` option in `autoEncryption` options on the `MongoClient` or the options for `ClientEncryption`.
- Adds tests that ensure a `secureContext` option takes precedence over the driver tls* options, that the tls* options aren't attempted to be read from the file, and that it works end-to-end.
Yes, update the MongoDB manual to show the precedence of the options.
NODE-4179
This can be provided in the `tlsOptions` option both both objects.
```ts
import * as tls from 'tls';
import { ClientEncryption, MongoClient } from 'mongodb';
const caFile = await fs.readFile(process.env.CSFLE_TLS_CA_FILE);
const certFile = await …
```

feat(NODE-4179): allow secureContext in KMS TLS options

---

src/collection.ts
src/db.ts
src/operations/create_collection.ts
src/operations/drop.ts
test/integration/collection-management/collection_db_management.test.ts

This PR moves esc and esoc create/drop support out of operation's `execute()` method.

refactor(NODE-7060): move QE collection creation/deletion out of operations classes

---

src/cmap/connection.ts
src/cursor/aggregation_cursor.ts
src/cursor/explainable_cursor.ts
src/cursor/find_cursor.ts
src/explain.ts
src/index.ts
src/operations/aggregate.ts
src/operations/command.ts
src/operations/execute_operation.ts
src/operations/operation.ts
src/sdam/server.ts
test/unit/operations/aggregate.test.js

I broke this PR out of https://github.com/mongodb/node-mongodb-native/pull/4609 because it got kinda large.
This PR refactors AggregateOperation to subclass ModernizedOperation.  Along the way, I encountered issues with `omitReadPreference` - an option which is used by the server class to remove a read preference from a command.  To make this work with the existing design, the `buildOptions` method would need to start taking a reference to the connection to determine the maxWireVersion when attaching this option.
I didn't like this approach and this option is only used for the AggregateOperation when there is a write stage and we are using wire version <9, so I refactored to remove this option.  
After removing `omitReadPreference`, it became clear we no longer needed `trySecondaryWrite`, …

refactor(NODE-7089): make AggregateOperation subclass ModernizedOperation

---

src/operations/create_collection.ts
src/operations/drop.ts
src/operations/list_databases.ts
src/operations/rename.ts
src/operations/validate_collection.ts
test/integration/node-specific/bson-options/use_bigint_64.test.ts
test/integration/node-specific/validate_collection.test.ts

This PR refactors db/collection management APIs to use ModernizedOperation.

refactor(NODE-7085): refactor db collection management APIs to use modernized operation

---

src/cmap/wire_protocol/responses.ts
src/operations/indexes.ts
src/operations/search_indexes/create.ts
src/operations/search_indexes/update.ts

Refactors index related operations to use the modernized operations.
Refactor index operations.
None
NODE-7083

refactor(NODE-7083): index operations to modernized operation

---

package-lock.json

tar-fs provides filesystem bindings for tar-stream. Versions prior to 3.0.9, 2.1.3, and 1.16.5 have an issue where an extract can write outside the specified dir with a specific tarball. This has been patched in versions 3.0.9, 2.1.3, and 1.16.5. As a workaround, use the ignore option to ignore non files/directories.

deps(NODE-7106): pin tar-fs@2.1.3 in lockfile

---

.evergreen/install-mongodb-client-encryption.sh
global.d.ts
package-lock.json
package.json
src/client-side-encryption/client_encryption.ts
src/index.ts
test/integration/client-side-encryption/client_side_encryption.prose.27.text_queries.test.ts
test/integration/client-side-encryption/client_side_encryption.spec.test.ts
test/spec/client-side-encryption/etc/data/encryptedFields-prefix-suffix.json
test/spec/client-side-encryption/etc/data/encryptedFields-substring.json
test/spec/client-side-encryption/tests/unified/QE-Text-cleanupStructuredEncryptionData.json
test/spec/client-side-encryption/tests/unified/QE-Text-cleanupStructuredEncryptionData.yml
test/spec/client-side-encryption/tests/unified/QE-Text-compactStructuredEncryptionData.json
test/spec/client-side-encryption/tests/unified/QE-Text-compactStructuredEncryptionData.yml
test/spec/client-side-encryption/tests/unified/QE-Text-prefixPreview.json
test/spec/client-side-encryption/tests/unified/QE-Text-prefixPreview.yml
test/spec/client-side-encryption/tests/unified/QE-Text-substringPreview.json
test/spec/client-side-encryption/tests/unified/QE-Text-substringPreview.yml
test/spec/client-side-encryption/tests/unified/QE-Text-suffixPreview.json
test/spec/client-side-encryption/tests/unified/QE-Text-suffixPreview.yml
test/spec/unified-test-format/invalid/runOnRequirement-csfle-minLibmongocryptVersion-pattern.json
test/spec/unified-test-format/invalid/runOnRequirement-csfle-minLibmongocryptVersion-pattern.yml
test/spec/unified-test-format/invalid/runOnRequirement-csfle-minLibmongocryptVersion-type.json
test/spec/unified-test-format/invalid/runOnRequirement-csfle-minLibmongocryptVersion-type.yml
test/tools/runner/filters/client_encryption_filter.ts
test/tools/runner/filters/libmongocrypt_version_filter.ts
test/tools/runner/hooks/configuration.ts
test/tools/unified-spec-runner/schema.ts
test/tools/unified-spec-runner/unified-utils.ts

Adds support for text queries for QE encrypted fields.  Incorporates changes from:
- https://github.com/mongodb/specifications/pull/1823 (auto encryption)
- https://github.com/mongodb/specifications/pull/1824 (explicit encryption)
Note that the failing tests on `latest` servers will be fixed by https://github.com/mongodb/specifications/pull/1827.

feat(NODE-7059, NODE-7008): add support for text queries for QE string fields

---

test/integration/change-streams/change_stream.test.ts
test/integration/client-side-encryption/driver.test.ts
test/integration/client-side-operations-timeout/client_side_operations_timeout.prose.test.ts
test/integration/client-side-operations-timeout/node_csot.test.ts
test/integration/collection-management/collection.test.ts
test/integration/connections-survive-step-down/connections_survive_step_down.prose.test.ts
test/integration/crud/crud_api.test.ts
test/integration/crud/explain.test.ts
test/integration/index_management.test.ts
test/integration/node-specific/abstract_cursor.test.ts
test/integration/server-selection/operation_count.test.ts
test/integration/transactions/transactions.test.ts
test/tools/cmap_spec_runner.ts
test/tools/utils.ts

This PR fixes the flaky test mentioned in the ticket.  Additionally, because we are now creating the `maxTimeNeverTimeOut` in multiple tests, I updated the `FailCommand` interface to support `maxTimeNeverTimeOut` (a `failCommand` is a subset of `failPoint).

chore(NODE-7123): fix flaky CSOT test

---

test/integration/crud/crud.spec.test.ts
test/spec/crud/unified/bulkWrite-updateMany-pipeline.json
test/spec/crud/unified/bulkWrite-updateMany-pipeline.yml
test/spec/crud/unified/bulkWrite-updateOne-pipeline.json
test/spec/crud/unified/bulkWrite-updateOne-pipeline.yml
test/spec/crud/unified/bypassDocumentValidation.json
test/spec/crud/unified/bypassDocumentValidation.yml
test/spec/crud/unified/client-bulkWrite-partialResults.json
test/spec/crud/unified/client-bulkWrite-partialResults.yml
test/spec/crud/unified/create-null-ids.json
test/spec/crud/unified/create-null-ids.yml
test/spec/crud/unified/findOneAndUpdate-pipeline.json
test/spec/crud/unified/findOneAndUpdate-pipeline.yml
test/spec/crud/unified/insertOne-dots_and_dollars.yml
test/spec/crud/unified/updateMany-pipeline.json
test/spec/crud/unified/updateMany-pipeline.yml
test/spec/crud/unified/updateOne-pipeline.json
test/spec/crud/unified/updateOne-pipeline.yml

This PR syncs all CRUD unified tests to latest and skips any tests for features we have not implemented.

test(NODE-7129): sync CRUD spec tests to latest

---

etc/docs/utils.ts

Updates import of `yargs` in our documentation tooling to work with `yargs@11`.  Docs build locally for me:
```
bailey.pearson:node-mongodb-native (fix-yargs) % npm run build:docs -- --yes   
> mongodb@6.19.0 build:docs
> ./etc/docs/build.ts --yes
[ 'Installing dependencies...' ]
[ 'Building docs for current branch' ]
[ 'Generating new static site...' ]
[ 'Successfully generated api documentation and updated the doc site.' ]
```

chore: fix yargs import in docs build

---

src/operations/delete.ts
src/operations/find_and_modify.ts
src/operations/update.ts
test/integration/crud/crud.spec.test.ts

With these changes, the driver only throws errors when an unacknowledged write is used with a hint when the server does not support `hint`.  This occurs in the following scenarios:
- update commands: **never** (this is supported 4.2+, 4.2 is our minimum supported server version)
- findAndModify and delete commands: 4.4+
The driver no longer throws errors when `hint` is provided to unacknowledged writes for delete, update and findOneModify commands in the following circumstances:
- No error is thrown for update commands.
- No errors are thrown for delete and findAndModify commands on servers >=4.4.

feat(NODE-7134): allow hint with unacknowledged writes for delete, update and findAndModify commands

---

src/operations/command.ts
src/operations/indexes.ts

refactor(NODE-7148): make rawData internal

---

src/operations/command.ts

Deprecate option `retryWrites` in `CommandOperationOptions`.
`CommandOperationOptions.retryWrites` is deprecated. This per‑command option has no effect; the Node.js driver only honors `retryWrites` when configured at the client level (MongoClient options) or via the connection string. Do not use this option on individual commands. There is no runtime behavior change because it was already ignored, but it will be removed in an upcoming major release and may cause type or build errors in code that references it. To control retryable writes, set `retryWrites` in MongoClient options or include `retryWrites=true|false` in the connection string.

feat(NODE-7157): deprecate `retryWrites` in `CommandOperationOptions`

---

src/cmap/handshake/client_metadata.ts
src/connection_string.ts
src/mongo_client.ts
test/integration/connection-monitoring-and-pooling/connection.test.ts
test/integration/mongodb-handshake/mongodb-handshake.prose.test.ts
test/tools/runner/filters/api_version_filter.ts
test/tools/runner/hooks/configuration.ts
test/unit/cmap/handshake/client_metadata.test.ts
test/unit/sdam/topology.test.ts

This PR is a POC implementation for https://github.com/mongodb/specifications/pull/1833. 
Additionally, while working on the implementation, I decided to simplify the handshake metadata logic by using `MongoClient.appendMetadata()` to append the driverInfo provided to the MongoClient, if any was provided.  

fix(NODE-7138): prevent duplicate metadata from being appended to handshake metadata

---

.evergreen/config.in.yml
.evergreen/config.yml
.evergreen/generate_evergreen_tasks.js
.evergreen/prepare-mongodb-aws-ecs-auth.sh
.evergreen/setup-mongodb-aws-auth-tests.sh
src/cmap/auth/aws_temporary_credentials.ts
src/cmap/auth/mongodb_aws.ts
test/integration/auth/mongodb_aws.test.ts
test/integration/client-side-encryption/client_side_encryption.prose.26.custom_aws_credential_providers.test.ts

Requires @aws-sdk/credential-providers in order to perform AWS authentication.
- Removes our implementation of AWS credential fetching.
- Updates AWS tests.
NODE-6988
Previous versions of the driver contained two implementations for AWS authentication and could run the risk of the custom driver implementation not supporting all AWS authentication features as well as not being correct when AWS makes changes. Using the official AWS SDK in all cases alleviates these issues.
```bash
npm install @aws-sdk/credential-providers
```

feat(NODE-6988)!: require aws sdk for aws auth

---

test/integration/connection-monitoring-and-pooling/connection.test.ts

This PR migrates the integration tests for `connection-monitoring-and-pooling`. The changes include:
- Replacing callbacks with `async/await` for one test.
- Import directly from the `src` folder.
To simplify the review process, this PR is split into several commits:
- The first commit converts callbacks to async/await.
- Other commits contains the remaining refactoring changes (imports).
This work is part of a larger, ongoing initiative to convert all tests to use `async/await`, with the ultimate goal of removing the legacy driver wrapper.

test(NODE-7182): migrate `integration/connection-monitoring-and-pooling` tests

---

test/readme.md

docs: invoke `bash` directly in test readme bash commands

---

test/integration/server-selection/readpreference.test.ts

This PR migrates the integration tests for `server-selection/readpreference`. The changes include:
- Commenting out or skipping ineffective tests (follow-up [NODE-7219](https://jira.mongodb.org/browse/NODE-7219) has been created)
- Import directly from the `src` folder, convert .js file test into .ts
- Refactor callback into async/await
Please note that 6 first tests are ineffective now:
- first 3 because of missing `command` method on the `Topology` class
- next 3 because the same types we check with Typescript
I do not want to make a decision on them in this PR, and instead follow-up ticket NODE-7219 has been created.
The `Hedged Reads` are deprecated in MongoDB Server version 8.0, so it probably makes sense to limit tests with `requires: [mongodb<8.0]` (also listed in the ticket).
This …

test(NODE-7185): migrate `integration/server-selection/readpreference` test

---

src/cmap/errors.ts
src/error.ts
test/integration/retryable-writes/non-server-retryable_writes.test.ts

Fixes the typo in the error name.
Renames the error
NODE-6334
The `PoolClearedError` thrown in cases where the connection pool was cleared now fixes the typo in the error label.

feat(NODE-6334)!: rename PoolRequstedRetry to PoolRequestedRetry

---

etc/notes/releasing.md

docs: add instructions for prereleases to the release guide

---

test/integration/crud/document_validation.test.ts

This PR migrates the integration tests for `crud/document_validation`. The changes include:
- Convert file in typescript
- Refactor callbacks to async/await
- Direct import from the `src` folder
To simplify the review process there is a separate commit for .js -> .ts conversion.
This work is part of a larger, ongoing initiative to convert all tests to use `async/await`, with the ultimate goal of removing the legacy driver wrapper.

test(NODE-7191): migrate `integration/crud/document_validation` tests

---

src/operations/aggregate.ts
test/integration/crud/aggregation.test.ts
test/unit/operations/aggregate.test.ts

Driver no longer throws on an aggregation when write concern and explain are provided. Server will now error.
Removes the check in the driver and updates tests.
NODE-4184
This will now throw a `MongoServerError`

feat(NODE-4184)!: don't throw on aggregate with write concern and explain
